README.md, bitcoin/contrib/test.sh
CI change only, can this merge without 2 acks?
The recent 1.0.108 `syn` update violated our MSRV, pin `syn` in the CI script.
=> Pin syn dependency for MSRV toolchain

bitcoin/src/crypto/sighash.rs, bitcoin/src/hash_types.rs, bitcoin/src/taproot.rs, hashes/embedded/src/main.rs, hashes/extended_tests/schemars/src/main.rs, hashes/src/lib.rs, hashes/src/sha256t.rs, hashes/src/util.rs
The API guidelines say macro input should be evocative of the output.
`hash_newtype` didn't have this property.
This change makes it look exactly like the resulting struct, `$len`
parameter was removed since it's not needed, reversing is controlled
using an attribute. The macro is also better documented and ready to be
extended in the future.
The tagged SHA256 newtype is not yet modified because it has a more
complicated input parameters.
Closes #1648
=> Make `hash_newtype` evocative of the output

bitcoin/src/blockdata/transaction.rs
The updated implementation accepts borrowed values and now it is convenient to use with slices.
closes #1669
=> Accept borrowed values in InputWeightPrediction::new()

bitcoin/src/blockdata/fee_rate.rs, bitcoin/src/blockdata/locktime/absolute.rs, bitcoin/src/blockdata/locktime/relative.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/blockdata/weight.rs, bitcoin/src/parse.rs
Currently we implement string parsing for height/time from the `absolute` module but not the `relative` module.
Improve the macros used to implement string parsing and use the new versions to implement string parsing for the height and time types in `relative`.
Done while reviewing data structures in relation to `serde`.
=> Improve string parsing

bitcoin/src/network/mod.rs
Writing `network::Magic` is more natural and less annoying than `network::constants::Magic`, so this change reexports it.
Closes #1667
=> Reexport `Magic`

bitcoin/src/network/constants.rs
I assume the old docs are a copy-paste error, strings are not involved when this error is encountered.
=> Fix docs for UnknownMagic to be accurate

hashes/src/util.rs
Removed unused macro and improved documentation to address review of #1659 - see commits. I also added a note about recursion.
=> `hash_newtype` cleanup

bitcoin/examples/taproot-psbt.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/crypto/key.rs, bitcoin/src/crypto/mod.rs, bitcoin/src/lib.rs, bitcoin/src/taproot.rs, bitcoin/tests/serde.rs
We created the `crypto` crate as a container for cryptography modules with the idea that it may be split out into a separate crate. There is no reason for users of the lib to know about this module. Also, we have two `taproot` modules, one in `crypto` and one at the crate root, this makes for un-ergonomic usage of the lib.
Improve the public API by doing:
- Make the `crypto` module private (`pub(crate)`).
- Re-export `crypto::taproot::Signature` (and `Error`) from `crate::taproot`
Fix: #1668
=> Improve the public API

bitcoin/src/address.rs
Fixes: #1677
In `bitcoin/src/address.rs`, a new field `address` is added to the enum variant `Error::NetworkValidation`. Also, the implementation of `Display` trait for `Error` is updated to print the `address` field.
However, to print the `address` through `Display`, either the reference is needed or `Address` and `Payload` both need to derive the `Copy` trait. Since I am little new to both the rust-bitcoin codebase and rust itself, I am confused about choosing between the two and have moved with the first one. Would appreciate any feedback on this.
=> Include address in Error::NetworkValidation

bitcoin/Cargo.toml, hashes/CHANGELOG.md, hashes/Cargo.toml
It was a little tricky to bump the version number because of https://github.com/rust-bitcoin/rust-bitcoin/issues/1553. There are a couple other things I considered trying, which maybe we'll do for future releases, but I believe this works for now.
Maybe should wait for #1111.
=> release bitcoin_hashes 0.12

bitcoin/src/pow.rs
Closes #1703 
This adds a conversion function to U256 to get an f64. We use the method shown in the following blog post.
https://blog.m-ou.se/floats/
Target::MAX was converted to a f64 and set as a const that is verified in a unit test.
The code is rather confusing, so I took a crack at explaining it in my comments as well. Please let me know if you want it cleaned up some more.
=> Add a method to `pow::Target` for returning difficulty as an f64.

bitcoin/Cargo.toml, hashes/Cargo.toml, internals/CHANGELOG.md, internals/Cargo.toml
=> update internals CHANGELOG for release

bitcoin/build.rs, bitcoin/src/blockdata/script/mod.rs, bitcoin/src/consensus/encode.rs, bitcoin/src/lib.rs
Hi! I'm still a beginner with both Rust and cross-compilation, so please take the rest with a few grains of salt!
I'm setting up a project targeting `riscv32i-unknown-none-elf`, which seems not to support atomic types. Even with `--no-default-features` and `no-std`, I would get this error:
```
error[E0432]: unresolved import `alloc::sync`
--> rust-bitcoin/bitcoin/src/blockdata/script/mod.rs:52:12
|
52 | use alloc::sync::Arc;
|            ^^^^ could not find `sync` in `alloc`
error[E0432]: unresolved import `alloc::sync`
--> rust-bitcoin/bitcoin/src/lib.rs:163:114
|
163 |     pub use alloc::{string::{String, ToString}, vec::Vec, boxed::Box, borrow::{Borrow, Cow, ToOwned}, slice, rc, sync};
| …
```
=> Avoid usage of atomic types if not supported by the target arch

README.md
Building this crate requires the `std` and/or `no-std` features be enabled. This PR documents this build constraint in the README ~~and gives an error is anyone tries to build without enabling one or both of these features~~.
See discussion in rust-bitcoin/rust-miniscript#533.
=> Add README docs for proper use of std and no-std features

bitcoin/src/pow.rs
See: https://github.com/rust-bitcoin/rust-bitcoin/pull/1707#issuecomment-1464052971
=> Swap out `Work::log2` implementation for `U256::to_f64`

bitcoin/src/blockdata/transaction.rs, bitcoin/src/consensus/encode.rs, bitcoin/src/internal_macros.rs
**Notes for reviewers:**
This is something that I want to use in my code and hopefully reasonably easy to review, so if this can get into 0.30 that'd be really nice. No hard feelings if it doesn't.
I tried to put extra effort into making review easier by:
* intentionally "mis-formatting" the first commit so diff is smaller and easy to understand - see individual commits.
* copying patterns from non-const fn to const fn so it's obviously correct (includes same variable names)
* not bothering with the array trick in `VarInt::len` and simply accepting the limitation of Rust 1.46+ (I use 1.48 BTW).
**Description**
Some smart contracts or simplified wallets statically know the sizes of
transactions or inputs. The possible approaches to handling them so far
were re-computing the values (and …
=> Support weight prediction in `const` context

README.md, bitcoin/Cargo.toml, bitcoin/contrib/test.sh
Also remove the spurious dev-dependency copy of rust-secp, which should've been updated to remove the "recovery" feature in https://www.github.com/rust-bitcoin/rust-bitcoin/pull/545 and then been removed entirely in https://www.github.com/rust-bitcoin/rust-bitcoin/pull/1387
=> update rust-secp to 0.27.0

bitcoin/src/amount.rs
I was looking to maintain compatibility easily with core tests, and many of the tests use [cent](https://github.com/bitcoin/bitcoin/blob/40e1c4d4024b8ad35f2511b2e10bf80c5531dfde/src/test/util/setup_common.h#L74) denominations.  It would be nice to be able to use cent as a denomination in rust-bitcoin as well.
=> Add CentiBitcoin to denominations

bitcoin/src/lib.rs
(Merge candidate only after release of 0.30.0)
We no longer have a "hashbrown" feature, the feature gated `pub extern crate hashbrown` should have been removed when we removed the feature.
=> Remove extern crate hashbrown

bitcoin/CHANGELOG.md, bitcoin/Cargo.toml
Add changelog notes and bump the version number to v0.30.0.
- https://github.com/rust-bitcoin/rust-secp256k1/pull/590
- ~https://github.com/rust-bitcoin/rust-bitcoin/pull/1696~
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1695
-  https://github.com/rust-bitcoin/rust-bitcoin/pull/1111
- #1710 
- #1705 
- #1713 
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1721
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1720
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1719
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1717  
- ~Set the date in the blog post to match the date 0.30 is released~
=> Release tracking PR - v0.30.0

bitcoin/Cargo.toml
We moved to a submodule and didn't fix the readme path in the `bitcoin` manifest.
=> bitcoin: Fix path to the readme

bitcoin/src/blockdata/block.rs
We just merged a patch to enable formatting in CI but commit: `05fdead2 Feature: Add difficulty_float method for block::Header.` must have slipped in.
Run the formatter.
=> Run cargo +nightly rustfmt

.github/workflows/fuzz.yml, .github/workflows/rust.yml
Closes #1726 
This will prevent duplicate CI runs when merging an internal branch into master.
You can opt-in to a non-master branch CI by using the prefix given.
=> CI: Prevent duplicate CI runs

bitcoin/src/blockdata/weight.rs
The FeeRate module defaults to sats per `kwu` so when doing fee calculations, it would be convenient to easily convert weight to the same units.
=> Add kilo weight unit conversion

.github/workflows/rust.yml, README.md, bitcoin/build.rs, bitcoin/contrib/test.sh, bitcoin/src/amount.rs, bitcoin/src/blockdata/script/push_bytes.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/consensus/encode.rs, bitcoin/src/consensus/serde.rs, bitcoin/src/internal_macros.rs, hashes/README.md, internals/src/hex/buf_encoder.rs
Just patch 2, patch 1 is #1728  
From the commit log of patch 2
Bump MSRV to 1.48.1
As per discussion [0] bump our MSRV for all crates in `rust-bitcoin`
repo to 1.48.1 [1].
[0] https://github.com/rust-bitcoin/rust-bitcoin/discussions/1329
[1] https://blog.rust-lang.org/2020/11/19/Rust-1.48.html
=> Bump MSRV to 1.48.0

.github/workflows/release.yml
Will set this to "allow failure" since I think it'll fail during large parts of development, but this will be useful to avoid last-minute problems with releases.
=> ci: do dry-run releases in CI

bitcoin/src/blockdata/constants.rs
This improves readability of converting `BlockHash` into `ChainHash`. It's useful in e.g. Electrum protocol which sends `BlockHash` (serialized backward).
Closes #1751
=> Add `ChainHash::from_genesis_block_hash`

README.md
The changelog was moved in[1], but the link to it in README.md wasn't updated.  I don't see any other outdated links to it in this project via a quick git grep.
---Not your usual Harding
[1] https://github.com/rust-bitcoin/rust-bitcoin/pull/1284/commits/bae64e156ee21d7dd2fae12b77674d330419ed0d
=> [Docs] Update internal project link to changelog

hashes/src/internal_macros.rs, hashes/src/ripemd160.rs
Closes #1756
I added tests to one of the Hash types, let me know if this seems reasonable as a test and I'll add it for all the other Hash types.
=> Feature (hashes): Add from_bytes_ref and from_bytes_mut to all Hash types

README.md
In #1759 we fixed the link to the bitcoin changelog, we can go one step further and add links for each of the crates.
=> Add per crate release notes link

bitcoin/src/address.rs, bitcoin/src/sign_message.rs
Closes #1755 
In this PR the `as_unchecked` is added to the Address struct, which returns a reference to the same address but with the type Address<NetworkUnchecked>.  Similarly, the `assume_checked_ref` is added to Address<NetworkUnchecked>, which returns a reference to the same address but with the type Address.
=> unsafe address type conversions

hashes/src/sha512.rs
For all the other hash types we use derive, by way of the `hash_type!` macro, unless I'm missing something we can do the same for `sha512::Hash`.
=> hashes: Derive traits on the sha512::Hash type

.github/workflows/release.yml, contrib/release.sh
Currently we run the release jobs for all PRs, this leads to red CI runs any time we have unreleased changes in one crate used by another i.e., basically days after a release comes out.
Add a `release.sh` script that has more smarts to try and figure out if the patch series currently ontop of tip of mater contains changes that imply its a release PR. To do so we check for changes to the version field in the manifest of each crate.
=> CI: Only run release job for release PRs

contrib/release.sh
The intention here is that we can use the deprecation tag
`#[deprecated(since = "NEXT_RELEASE")]` and fill in the version number
at release time.
Not sure if there is a good place to mention this somewhere in developer docs. I looked into CONTRIBUTING.md but didn't really found a suitable section for this.
=> ci: Check for remaining NEXT_RELEASE in the release script

bitcoin/src/network/message_blockdata.rs
I'm not positive we won't ever had inv items that are not `sha256d::Hash`, though. I would expect them to stay like that, but we never know.
Would accept that as a reasonable objection against this helper.
=> Add Inventory::network_hash() method

README.md, bitcoin/contrib/test.sh, hashes/Cargo.toml, hashes/README.md, hashes/contrib/test.sh, hashes/extended_tests/schemars/Cargo.toml, hashes/extended_tests/schemars/README.md, hashes/src/lib.rs, hashes/src/sha256t.rs
This has grown due to now including pinning work also done in https://github.com/rust-bitcoin/rust-bitcoin/pull/1736, I decided to do this because the PRs conflict and doing it all here saves accidentally getting out of sync. And  https://github.com/rust-bitcoin/rust-bitcoin/pull/1764 requires this PR.
- Patch 1 is unchanged
- Patch 2 now fixes pinning in bitcoin and hashes CI scripts and in the docs of both as well as the manifest stuff relating to `schemars` - phew.
Fix: #1687
=> Remove `schemars` pin from manifest

hashes/extended_tests/schemars/README.md
We no longer need to pin `syn`; remove stale docs.
This is a follow up to #1696
=> extended_tests: Remove stale docs

bitcoin/src/blockdata/block.rs, bitcoin/src/blockdata/transaction.rs, contrib/release.sh
Alternative to https://github.com/rust-bitcoin/rust-bitcoin/pull/1795.
Keep the old method as deprecated and add doc alias. Also change internal usage of the method.
=> transaction: Rename is_coin_base to is_coinbase

bitcoin/src/blockdata/transaction.rs, bitcoin/src/consensus/encode.rs
Fix some types in Transaction.rs and encode.rs
=> Spelling and typo fixes

bitcoin/embedded/src/main.rs, hashes/embedded/src/main.rs
Seems we no longer need an explicit error handler, remove it.
I did not grok the reason (long thread link below) but just removed it and checked that the embedded crates still ran correctly.
https://github.com/rust-lang/rust/issues/51540
Fix: #1813
=> embedded: Remove error handler

bitcoin/src/blockdata/constants.rs, bitcoin/src/blockdata/weight.rs, bitcoin/src/merkle_tree/block.rs
deprecate constants::MAX_BLOCK_WEIGHT and constants::MIN_TRANSACTION_WEIGHT to nicely redirect users to the constants in the Weight type
=> Move weight constants in the `Weight` type

bitcoin/src/network/constants.rs
The new module provides serde functions to convert from/to Bitcoin Core network variants.
Fixes #1799
=> Adds as_core_arg serde module to network

.github/workflows/fuzz.yml, fuzz/Cargo.toml, fuzz/README.md, fuzz/generate-files.sh, hashes/src/lib.rs, hashes/src/ripemd160.rs, hashes/src/sha1.rs, hashes/src/sha256.rs, hashes/src/sha512.rs, hashes/src/siphash24.rs, hashes/src/util.rs
A custom `cfg` flag can be turned on or off by the user. Our current use of `cfg(fuzzing)` is impossible to turn off when using honggfuzz, which makes it impossible to fuzz without the broken crypto. This causes trouble for some downstream crates and also makes it hard for us to fuzz our own library.
Companion to rust-secp PR (TODO open this) which does effectively the same thing.
Fixes #1587.
=> fuzz: replace `cfg(fuzzing)` weth `cfg(bitcoin-hashes-fuzz)`.

bitcoin/src/address.rs
With the new rewrite of Address, `serde::Serialize` is only implemented on `Address<bitcoin::address::NetworkChecked>` and `Address<bitcoin::address::NetworkUnchecked>`. But the compiler has no way of knowing that that are all the possible versions of `Address`, so the generic `Address<impl bitcoin::address::NetworkValidation>` doesn't implement `serde::Serialize`.
=> Implement serde::Serialize for Address

bitcoin/src/pow.rs
Once `U256` was made private, we lost the ability to check whether a valid difficulty transition was made in the chain, since `Target` doesn't expose any operations. We only choose to expose `Shl<u32>` and `Shr<u32>` such that we can compute the min and max target thresholds allowed for a difficulty transition.
This is something we realized was missing after bumping to `rust-bitcoin v0.30.0` in `rust-lightning`, specifically for our `lightning-block-sync` crate. It may also be worth having a helper in `rust-bitcoin` that checks a header properly builds upon the previous, but that can be left for future work.
=> Expose valid (min, max) difficulty transition thresholds

bitcoin/src/lib.rs, hashes/src/lib.rs
A new version of rust nightly is causing a test failure for external crates that are not documented.  This is currently causing a failure on my branch here: https://github.com/rust-bitcoin/rust-bitcoin/pull/1838
As a side note, it feels like this should be locked to a specific version of nightly in the CI tests and then updated as a choir instead of having it create a new problem in a branch that's not related.
=> docs: Add doc comments for external crates

bitcoin/src/blockdata/script/owned.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/crypto/sighash.rs, bitcoin/src/psbt/mod.rs
Create an associated constant `const TxOut::NULL` for consensus signing code and remove the default trait.  Note I tried to deprecate the `default()` fn instead of just removing it but it doesn't seem to be possible.  Also because `TxOut::NULL` is `const`, `ScriptBuf::new()` needed to be changed to `const fn`.
=> Move and rename TxOut default trait to a const called NULL

.github/workflows/fuzz.yml, fuzz/generate-files.sh
I think our CI failures started with #1821 when we added an extra `run:` line to `fuzz.yml` without prefixing it with `-`.
Fix the syntax to use a multi-line `run` instead.
=> ci: fix -run syntax

bitcoin/src/amount.rs
Numbers with only zeros after decimal points are valid if they are also
multiples of `10^precision` (e.g. 1000 for msats). These were
artificially disallowed as "too precise" which was at least misleading.
This change allows parsing such numbers.
And yes, I know this is not perfectly efficient (unless the compiler figures out some magic opts) but so isn't the rest of the code. TBH this parsing code drives me crazy and I'd love to rewrite it to be more efficient and readable.
=> Allow parsing sub-sat denominations with decimal points 

bitcoin/src/address.rs
The spec RFC3986 specifies the scheme is case insensitive and we were uppercasing to optimize QR code representation.
Unfortunately, common platform such as Android seems to fail to recognize uppercase schema, so for compatibility reason we use lowercase.
close #1843
=> make bip21 schema lowercase

bitcoin/src/address.rs
This slipped in and is breaking builds.
=> Fix formatting

bitcoin/src/blockdata/transaction.rs
These constants had an error that they had `script_size` set to 0 which
was incorrect because it's not length of the script but serialized size.
Rather than just bumping the value this uses the `from_slice` method
which is less error-prone.
Closes https://github.com/rust-bitcoin/rust-bitcoin/issues/1834
=> Fix associated constants of `InputWeightPrediction`

bitcoin/src/blockdata/fee_rate.rs
Add a checked version of fee_rate * weight.  While I like the trait version of just being able to multiply `feerate * weight`, it's not really very useful imo since a large input feerate could cause an overflow.  Instead of changing the trait in https://github.com/rust-bitcoin/rust-bitcoin/pull/1849 (not idiomatic enough I guess) I added a `checked_weight_mul` method to `FeeRate`.
=> Add a checked version of weight mul fee_rate

bitcoin/src/blockdata/script/tests.rs
The `ScriptBuf` type can be serialized using it's `to_bytes` function. Do not use the `psbt::Serialize` trait to do so in test code.
No logic changes, since the impl of `psbt::Serialize` for `ScriptBuf` just calls `to_bytes`.
=> tests: Use script hash functions

Cargo-minimal.lock, Cargo-recent.lock, SECURITY.md, bitcoin/Cargo.toml, contrib/release.sh, hashes/Cargo.toml, internals/Cargo.toml
Since we now have control over the name on crates.io.
=> rename bitcoin-private to bitcoin-internals

bitcoin/embedded/README.md
Our embedded crate includes instructions to source a shell script that sets the `RUSTFLAGS` env var. Having the env var set like this in ones environment breaks linkage when trying to do "regular" builds.
Document how to clean up.
=> embedded: Document how to clean up linker flags

bitcoin/src/blockdata/script/push_bytes.rs
These build cfg options are not features, fix broken usage. And remove stale docsrs attribute while we are at it. Bad rust-bitcoin devs.
Found while reviewing #1870
=> Fix conditional configuration options usage

bitcoin/src/psbt/mod.rs
No idea why this re-export is here, the `Prevouts` type is not even used in the `psbt` module.
Remove the re-export of `crate::sighash::Prevouts` from `pstb`.
Fix: #1869
=> psbt: Remove reexport of Prevouts

bitcoin/src/address.rs, bitcoin/src/blockdata/script/mod.rs, bitcoin/src/consensus/encode.rs, bitcoin/src/crypto/key.rs, bitcoin/src/psbt/error.rs, bitcoin/src/sign_message.rs
Give people access to the error type conversion docs, its no harm and it may be useful when the compiler does not give enough information.
Done based on discussion here: https://github.com/rust-bitcoin/rust-bitcoin/pull/1846#discussion_r1209583520
=> Remove doc(hidden) from error conversion functions

bitcoin/src/taproot.rs
The `as_script_map` is a getter not a conversion function (to/into/as), as such it should not include the prefix `as_`.
Deprecate `as_script_map` in favour of `script_map`.
=> Rename `TaprootSpendInfo::as_script_map` to `script_map`

bitcoin/src/blockdata/opcodes.rs, bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/script/tests.rs
Planning to also add methods for the various parts of Transaction etc. to eventually allow for easier sigops calculation.
Bare multisig is making a comeback, which is causing a large amount of transactions' effective vSizes (for fee calculation) to be dependent on the sigop count.
This is a first step at making those transactions easier to estimate fees for / template blocks for etc.
=> [script] Add method get_sigop_count

bitcoin/src/crypto/taproot.rs, bitcoin/src/psbt/error.rs, bitcoin/src/psbt/serialize.rs, bitcoin/src/taproot.rs
First three patches are preparatory cleanup, last patch renames `crypto::taproot::Error` to `SigFromSliceError`. See commit log for justification of the `Sig` prefix.
Done as part of the great error cleanup.
=> Improve `crytpo::taproot` error type

bitcoin/src/network/constants.rs
I think the NONE/empty service flags are a reasonable default value, no?
=> network: Implement Default on ServiceFlags

bitcoin/src/blockdata/transaction.rs
Fix: #1850 
Removed "*Important: only available in Rust 1.46+*" on the file  transaction.rs from lines 1288 and 1407 respectively.
=> Removed only available in 1.46.0 line

bitcoin/src/lib.rs
Fix: #1867
Docs claim this library is pure rust but it depends on libsecp256k1 (and optionally libbitcoinconsensus)
So, I changed the lib.rs file accordingly.
=> This library is not solely dependent on Rust

bitcoin/examples/taproot-psbt.rs, bitcoin/src/amount.rs
Followup PR from https://github.com/rust-bitcoin/rust-bitcoin/pull/1811
Added a `const` associated function `from_int_btc()` for Amount.  `panic()` in const context is only available after 1.57+ so a work around is provided.
=> Add from_int_btc method to Amount

hashes/README.md
We do not use travis in our CI pipeline anymore, remove the stale badge.
=> hashes: Remove stale status badge

bitcoin/src/pow.rs
Add the `mutate` attribute to mutate `mul_u64`. Add non-doc comments listing the two false positives. These are identical but we list them twice so when devs grep for `mutagen false pos` the same number of lines for each function is displayed as is displayed by the `mutagen` run. This coding false positives thing is also introduced in PR #1655.
=> Mutate mul_u64 with mutagen

hashes/contrib/test.sh
We never enable the `DO_ALLOC_TESTS` variable, and hence never test the "alloc" feature in `hashes`.
Remove the `DO_ALLOC_TESTS` variable and add "alloc" to the `FEATURES` array.
=> ci: Remove stal DO_ALLOC_TESTS variable

bitcoin/contrib/test.sh
MSRV build breaks because of edition _2021_ not 2018.
=> Fix incorrect comment in ci script

hashes/src/sha512.rs, hashes/src/sha512_256.rs
Recently we made the hash engine fields pub crate so that `sha512_256` could construct a hash engine with different constants. We can make the code slightly cleaner by adding a pub crate constructor and making the fields private again.
Idea from Kixunil:
https://github.com/rust-bitcoin/rust-bitcoin/pull/1413#pullrequestreview-1197207593
This is a follow up to #1413, cc kcalvinalvin as the author of that one.
=> Make sha512::HashEngine fields private

bitcoin/src/crypto/key.rs
Expose signature verification functionality for ECDSA signatures on the `PublicKey` type.
We should have an identical function on `XOnlyPublicKey` but this will have to be done in `secp2561`: https://github.com/rust-bitcoin/rust-secp256k1/pull/618
Idea from Kixunil: https://github.com/rust-bitcoin/rust-bitcoin/pull/1744#issuecomment-1534200841
=> Add a verify function to PublicKey

bitcoin/examples/sighash.rs
So far computed sighashes and verified signatures for:
- P2WPKH
- P2MS 2of3
- P2SH 2of2 multisig
- P2SH 2of3 multisig
- P2WSH 2of2 multisig.
TODOs:
- Add P2TR script-path multisig and key-path examples
- Are there mutisig transactions where flags are different for diff signatures within an input?
- Maybe switch to  segwit_signature_hash()?
- Consider also verifying script hash if we go for full P2(W)SH transactions verifications?
=> Added examples for signature verification

bitcoin/src/blockdata/transaction.rs
Followup from https://github.com/rust-bitcoin/rust-bitcoin/pull/1835.  Call `predict_weight` from `weight` instead of `scaled_size()` https://github.com/rust-bitcoin/rust-bitcoin/pull/1835#issuecomment-1543687210.  I think we could also deprecate `scaled_size()` and `strippedsize()` in a future refactor.
=> Refactor transaction weight

Cargo-minimal.lock, Cargo-recent.lock
1.0.56 does not compile on Rust nightly anymore.
=> update proc-macro to 1.0.56 to 1.0.63

bitcoin/contrib/test.sh, hashes/contrib/test.sh
Recent release of `serde_json` depends on `serde` 1.0.66 but we pin to 1.0.56
Pin `serde_json` for MSRV build to v1.0.99
=> CI: Pin serde_json for MSRV build

bitcoin/src/address.rs, bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/script/mod.rs, bitcoin/src/blockdata/script/owned.rs, bitcoin/src/blockdata/script/witness_program.rs, bitcoin/src/blockdata/script/witness_version.rs, bitcoin/src/lib.rs, bitcoin/src/psbt/mod.rs
This is done as part of an ongoing effort to improve the `address` module and `Address` type.
- Patch 1: Move `WitnessVersion` and `WitnessProgram` to their own modules within `script` - this is code move only except for the variant changes to the `address::Error` enum (see note below on `rustfmt` acting up).
- Patch 2: Improves documentation on the `WitnessProgram`
- 
There are a bunch of formatting changes that shouldn't be in here, I stashed and re-ran the formatter a bunch of times but for some reason `rustfmt` wouldn't change `address` as it is but after I patched it `rustfmt` made a bunch of changes.
=> Move witness types to the script module

bitcoin/src/blockdata/witness.rs
The current derived debug implementation on `Witness` prints the content field as an array of integers. We can do better than this by manually implementing `Debug`.
With this applied `Witness` is printed as follows: (first line is `{:?}` and the next is `{:#?}`):
Using `{:?}`:
```
Witness: { indices: 3, indices_start: 8, witnesses: [[0x00], [0x02, 0x03], [0x04, 0x05]] }
```
Using `{:#?}`:
```
Witness: {
indices: 3,
indices_start: 8,
witnesses: [
[0x00],
[0x02, 0x03],
[0x04, 0x05],
],
}
```
=> Manually implement Debug on Witness

bitcoin/src/blockdata/transaction.rs
Currently the test `hex` macro is only available when the `test` compiler configuration option is set but we are using it in benches code, this works for use because `cargo bench` sets `test` for the current crate, however it breaks downstream crates.
Fix: #1830
=> Use hex_lit::hex in benches

bitcoin/src/bip32.rs, hashes/src/serde_macros.rs, internals/src/parse.rs
Somehow when we started using `doc_auto_cfg` we forgot to remove a bunch of docsrs attributes.
=> Remove docsrs attributes

bitcoin/CHANGELOG.md, bitcoin/Cargo.toml, bitcoin/src/blockdata/transaction.rs
Needed to unstick https://github.com/rust-bitcoin/rust-miniscript/pull/482
=> Backport #1941 to 0.30.x and release new patch version

Cargo-minimal.lock, Cargo-recent.lock, bitcoin/Cargo.toml, hashes/Cargo.toml, internals/CHANGELOG.md, internals/Cargo.toml
In preparation for release bump the version and add a changelog entry. Includes updating the dependency in `bitcoin` and `hashes`.
=> internals: Bump version to 0.2.0

bitcoin/src/lib.rs, bitcoin/src/psbt/macros.rs, bitcoin/src/psbt/map/global.rs, bitcoin/src/psbt/mod.rs, bitcoin/src/psbt/serialize.rs, fuzz/fuzz_targets/bitcoin/deserialize_psbt.rs
Last release we added a type alias for `Psbt`, now lets just rename the type and be done with it.
Includes re-export at the crate root because `bitcoin::Psbt` is clear and obvious.
=> Rename PartiallySignedTransaction to Psbt

bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/script/tests.rs, bitcoin/src/crypto/sighash.rs
The `empty` constructor is mis-named for the following reasons:
- Non-uniform with `ScriptBuf::new`
- Non-standard with respect to stdlib which uses `Path::new` and `PathBuf::new` (on which we based the `Scritp`/`ScriptBuf`)
Rename the function to `new`, put it at the top of the impl block while we are at it.
=> Rename `Script::empty` to `Script::new`

bitcoin/src/blockdata/witness.rs
The previous code seems to have been rebased/iterated on too many times, and had room for significant simplification. By inlining the indentation logic we can eliminate 40 LOC and also clean up the output by removing trailing spaces.
Fixes #1937 
It is not good form to add unit tests for debug output but you can test this locally with the patch
```
diff --git a/bitcoin/src/blockdata/witness.rs b/bitcoin/src/blockdata/witness.rs
index d0b7408c..a2c38af0 100644
--- a/bitcoin/src/blockdata/witness.rs
+++ b/bitcoin/src/blockdata/witness.rs
@@ -619,6 +619,9 @@ mod test {
"304402207c800d698f4b0298c5aac830b822f011bb02df41eb114ade9a6702f364d5e39c0220366900d2a60cab903e77ef7dd415d46509b1f78ac78906e3296f495aa1b1b54101")
];
assert_eq!(witness.to_vec(), expected_witness);
+
+ …
```
=> witness: clean up Debug implementation

bitcoin/src/bip32.rs
This is useful to pass the keypath to other libraries which expect it to be represented with a list of u32 ints.
Fixes #1944
=> bitcoin/bip32: add DerivationPath::to_u32_vec

bitcoin/src/psbt/error.rs, bitcoin/src/psbt/mod.rs
Recently we changed the inner type of this variant and the name became stale because it is caused by a from slice constructor not from parsing.
=> Rename `HashParse` error variant to `InvalidHash`

bitcoin/Cargo.toml, bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/script/builder.rs, bitcoin/src/blockdata/script/mod.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/consensus/mod.rs, bitcoin/src/consensus/validation.rs
Pull all the code that depends on `bitcoinconsensus` out into a separate module `consensus::validation`.
While we are at it clean up the error returns by making functions return error types specific to their needs instead of general error types. We still need the std error hack to implement `std::error::Error` if `bitcoinconsensus` feature is on but not `bitcoinconsensus-std`.
This is a re-spin of work done by @stevenroose in https://github.com/rust-bitcoin/rust-bitcoin/pull/330, things that are different:
- Use specific error types for script vs transaction error instead of a single general error
- Did improvements to docs including linking to docsrs for `bitcoinconsensus` type.
=> Separate out bitcoinconsensus validation code 

bitcoin/examples/handshake.rs, bitcoin/src/consensus/encode.rs, bitcoin/src/network/message.rs
This PR removes the need to serialize the inner NetworkMessage in the RawNetworkMessage encoding, thus saving memory and reducing allocations.
To achieve this payload_len and checksum are kept in the RawNetworkMessage and checksum kept in CheckedData, to preserve invariants fields of the struct are made non-public.
=> Avoid vector allocation in `RawNetworkMessage` encoding

bitcoin/src/blockdata/transaction.rs
As we gear up for the v0.31.0 release we can fill in the NEXT-RELEASE placeholders.
=> Fill in deprecated since NEXT-RELEASE placeholder

CONTRIBUTING.md
I have managed to burn out or bore our reviewers/maintainers. Getting two acks is becoming increasingly difficult. I've pestered everyone to the limit that I feel socially comfortable doing so, and as such, am requesting a carve out to the 2-ACK before merge rule.
The primary justification is that I feel we should have a bit more of BDFL and a bit less total consensus if we are to push forwards.
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1925
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1854
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1862
=> policy: Add refactor carve out

bitcoin/src/blockdata/transaction.rs, bitcoin/src/crypto/ecdsa.rs, bitcoin/src/crypto/key.rs, bitcoin/src/crypto/sighash.rs, bitcoin/src/crypto/taproot.rs, bitcoin/src/psbt/map/input.rs, bitcoin/src/psbt/serialize.rs
EDIT: The commit hashes below are stale but the text is valid still.
In an effort to "perfect" our error handling, overhaul the error handling in the `crypto` module. 
The aim is to do a small chunk so we can bikeshed on it then I can apply the learnings to the rest of the codebase.
Its all pretty trivial except:
- commit `4c180277 Put NonStandardSighashTypeError inside ecdsa::Error variant`
- comimt `5a196535 Add InvalidSighashTypeError`
- commit `05772ade Use defensive documentation`
Particularly the last one might be incorrect/controversial.
Also, please take the time to check the overall state of error code in the `crypto` module on this branch in case there is anything else we want to do.
Thanks
=> crypto: Overhaul the errors

bitcoin/src/psbt/map/input.rs, hashes/src/util.rs
Two minor patches to fix up docs links. These were originally done as part of #1880 but are unrelated so pushing them up separately.
=> Fix links in docs

bitcoin/src/blockdata/transaction.rs
Add a constant for the max transaction weight.  Similar to [max block weight](https://github.com/yancyribbens/rust-bitcoin/blob/1b009b809ba2f282d88153cc32e390f1bbd4773c/bitcoin/src/blockdata/weight.rs#L35).  This value is pulled from core  [here](https://github.com/bitcoin/bitcoin/blob/44b05bf3fef2468783dcebf651654fdd30717e7e/src/policy/policy.h#L27)
=> Add max standard tx weight constant to transaction

contrib/test.sh
Add a test for pinned version with current MSRV.  I'm not sure how to test this in CI before opening this PR (will probably fail).
=> Add CI test for pinned versions using 1.48

bitcoin/src/blockdata/opcodes.rs, bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/script/builder.rs, bitcoin/src/blockdata/script/instruction.rs, bitcoin/src/blockdata/script/mod.rs, bitcoin/src/blockdata/script/owned.rs, bitcoin/src/blockdata/script/witness_version.rs
I may be missing something about the `All` type but it seems it can be re-named to `Opcode` with no loss of clarity.
The first few patches do some other clean ups, the last patch is the meat and potatoes.
=> Rename `opcodes::All` to `Opcode`

bitcoin/src/merkle_tree/block.rs
Just came across this and felt like doing this.
=> Eliminate a heap allocation from PartialMerkleTree encoding & decoding

hashes/src/sha256.rs
This is my first time dabbling into architecture specific code and simd. The algorithm is a word to word translation of the C code from  https://github.com/noloader/SHA-Intrinsics/blob/4899efc81d1af159c1fd955936c673139f35aea9/sha256-x86.c .
Some benchmarks:
With simd
```
test sha256::benches::sha256_10                   ... bench:          11 ns/iter (+/- 0) = 909 MB/s
test sha256::benches::sha256_1k                   ... bench:         712 ns/iter (+/- 2) = 1438 MB/s
test sha256::benches::sha256_64k                  ... bench:      45,597 ns/iter (+/- 189) = 1437 MB/s
```
Without simd
```
test sha256::benches::sha256_10                   ... bench:          47 ns/iter (+/- 0) = 212 MB/s
test sha256::benches::sha256_1k                   ... bench:       4,243 ns/iter (+/- 17) = 241 MB/s …
```
=> Add simd sha256 intrinsics for x86 machines

clippy.toml, hashes/Cargo.toml, hashes/src/ripemd160.rs, hashes/src/sha256.rs, hashes/src/sha512.rs
When enabled this feature swaps the hash implementation of sha512, sha256 and ripemd160 for a smaller (but also slower) one.
On embedded processors (Cortex-M4) it can lead to up to a 52% size reduction, from around 37KiB for just the `process_block` methods of the three hash functions to 17.8KiB.
The following numbers were collected on `aarch64-unknown-linux-gnu` with `cargo 1.72.0-nightly`.
```
RUSTFLAGS='--cfg=bench -C opt-level=z' cargo bench
```
```
test hash160::benches::hash160_10                 ... bench:          33 ns/iter (+/- 1) = 303 MB/s
test hash160::benches::hash160_1k                 ... bench:       2,953 ns/iter (+/- 187) = 346 MB/s
test hash160::benches::hash160_64k                ... bench:     188,480 ns/iter (+/- 11,595) = 347 MB/s
test hmac::benches::hmac_sha256_10 …
```
=> Introduce the `small-hash` feature for `bitcoin_hashes`

bitcoin/src/blockdata/transaction.rs
Add a base weight const to TxIn.  I also used this const in strippedsize() and scaledsize().  As a different PR, I think strippedsize and scaledsize could return Weight instead of usize.  Also added a small commit to re-arrange commit messages.
=> Add txin base weight

bitcoin/examples/sighash.rs, bitcoin/src/crypto/sighash.rs, bitcoin/src/psbt/mod.rs
The word "segwit" refers to segwit v0 and taproot but these functions are version specific. Add `v0` into the function names.
This is similar to #1994, both based on recent post of mine to bitcoin dev mailing list.
=> Improve segwit signature hash API

bitcoin/examples/sighash.rs, bitcoin/examples/taproot-psbt.rs, bitcoin/src/crypto/sighash.rs, bitcoin/src/psbt/mod.rs, bitcoin/src/sign_message.rs
The `ThirtyTwoByteHash` trait is defined in `secp256k1` and used in `hashes` as well as `bitcoin`. This means that we must use the same version of `hashes` in both `bitcoin` and `secp256k1`. This makes doing release difficult.
Remove usage of `ThirtyTwoByteHash` and use `Message::from_slice`. Include TODO above each usage because as soon as we release the new version of secp we can use the new `Message::from_digest`.
This is step backwards as far as type safety goes and it makes the code more ugly as well because it uses `expect` but thems the breaks.
For context see #1985
=> Remove usage of ThirtyTwoByteHash

contrib/update-lock-files.sh
Every time one of the dependencies is explicitly changed we have to update the minimal/recent lock files. Add a script to do so.
=> Add a script for updating lock files

Cargo-minimal.lock, Cargo-recent.lock, bitcoin/Cargo.toml, bitcoin/contrib/test.sh, hashes/CHANGELOG.md, hashes/Cargo.toml
In preparation for `hashes` release, bump the version. Depend on new version in `rust-bitcoin`.
Note the `bitcoin-private` addition to the lock files is because we temporarily have two `bitcoin_hashes` dependencies and the secp one (v.0.12.0) depends on `bitcoin-private`.
=> hashes: Release `v0.13.0`

bitcoin/src/lib.rs
During the 0.30.0 release we removed the re-exports of hash types. This upset some folk and since the aim of our re-exports is not exactly clean as well as the fact that the public API surface is not yet fixed just re-export all the hash types at the crate root again.
This is #1792 but does not use a wildcard and also grabs the other hashes that we recently moved.
=> Export all hash types

bitcoin/src/blockdata/witness.rs
When we introduce a custom `Debug` implementation for the `Witness` we introduced a bug that causes code to panic if the witness contains an empty instruction.
The bug can be verified by putting patch 2 first or by running `cargo run --example sighash` on master.
=> Fix witness display bug

contrib/test.sh
More crates broke our MSRV by using edition 2021 without doing a major release, pin them in the CI script.
Other open PRs need this to get past CI.
=> CI: Fx pinning

README.md, justfile
Introduce usage of `just` by adding a basic `justfile`.
If this goes in we can add various script invocations to it plus other useful things that often get red CI runs (eg, checking no-std).
=> Introduce a basic justfile

bitcoin/src/blockdata/witness.rs
Recently we "if" guarded subtraction manually using `> 0`, we can better convey the meaning by using `checked_sub` and pattern match on the option.
=> Improve witness display

bitcoin/src/blockdata/block.rs, bitcoin/src/blockdata/transaction.rs
Use Weight type for `base_size` in Transaction.  Also a small re-factor to remove `test_` and `_tests` from the testname for transaction tests.
=> Use weight for block size function

.github/dependabot.yml
Fixes #2051.
This does not touch Rust code or Cargo workflows.
It creates a dependabot update only restricted to `"github-actions"`.
We are using outdated `actions/checkout`, `actions/cache` (`v2` in some and `v3` in others were the must up-to-date is `v4`).
For the `dtolnay/rust-toolchain@1.48.0` in
https://github.com/rust-bitcoin/rust-bitcoin/blob/f8d7bcfce2b301870b1df23e6f508e8dd7942d10/.github/workflows/rust.yml#L77
it would not touch it only if there is a `1.48.X` increase in `X`.
For the `actions-rs/toolchain@v1` in https://github.com/rust-bitcoin/rust-bitcoin/blob/f8d7bcfce2b301870b1df23e6f508e8dd7942d10/.github/workflows/fuzz.yml#L50 it will only update if we have `actions-rs/toolchain@vX` increase in `X`.
**And to stress that again, it will ⚠️ create PRs and we would need to …
=> CI: Add `dependabot.yml`

bitcoin/src/bip152.rs, bitcoin/src/consensus/encode.rs, bitcoin/src/p2p/address.rs
One encodes to a writer and decodes from a reader, most of the time in the consensus `Encodable`/`Decodable` traits we use generic `R`/`W` and variable `r`/`w` but there are other places that use other characters.
While touching these lines note also that there are a bunch of unneeded `mut`s, I'm not sure why since usually between the compiler and the linter `mut` is handled correctly.
Make implementations of `Encodable` and `Decodable` uniform by:
- Use R/W and r/w for trait and variable name
- Remove unneeded mut
(This is split out of #1891 to assist review.)
=> Make Encodable/Decodable usage uniform

bitcoin/src/address.rs, bitcoin/src/blockdata/script/witness_version.rs
Done as part of the push to have small specific errors instead of large general ones.
Split the `witness_version::Error` up into small specific errors.
The first two patches are preparatory clean up.
=> Split witness version errors up

.github/workflows/rust.yml
- sets `dtolnay/rust-toolchain` to `stable`
- delegates the `toolchain` to `1.48.0` as GitHub action input
This will make the rust-toolchain to always run in the `stable` branch with the toolchain version being handled in the action. It will appease dependabot and we can change at any time the `toolchain` action input.
Discussed in https://github.com/rust-bitcoin/rust-bitcoin/pull/2055
=> fix(CI): `rust-toolchain` stable

bitcoin/src/psbt/mod.rs
=> Fix: IndexOutOfBoundsError Display impl has values in wrong order

hashes/CHANGELOG.md
We accidentally mentioned an error change twice, remove the entry without the PR link.
=> hashes: Remove duplicate entry

bitcoin/src/crypto/sighash.rs
Recently we deprecated the `segwit_signature_hash` function but during development the deprecation notice got stale.
Fix deprecation notice to use the actual function names.
=> Fix deprecation notice

CONTRIBUTING.md
In an effort to reduce review burden add so strict rules defining 3 times where we think it is acceptable for code to be merged with a single ACK. Feels a bit like we only just added the refactor carve-out and now we are adding more carve-outs, so whats next? We should take these rules seriously, if we are to be taken seriously.
```
We reserve the right to merge PRs with a single ACK [0], at any time, if they match
any of the following conditions:
1. PR only touches CI i.e, only changes any of the `test.sh` scripts and/or
stuff in `.github/workflows`.
2. Non-content changing documentation fixes i.e., grammar/typos, spelling, full
stops, capital letters. Any change with more substance must still get two
ACKs.
3. Code moves that do not change the API i.e., moving error types to a submodule …
```
=> Add one ACK carve-out

bitcoin/src/blockdata/script/instruction.rs, bitcoin/src/blockdata/script/mod.rs, bitcoin/src/blockdata/script/tests.rs
This new method on `Instruction` will allow for interpreting the Instruction as a script number (i32)
=> Feature: Instruction can read the script number

bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/script/tests.rs
When implementing some tests for the Transaction PR, I noticed that there were coinbase transactions that would pass Bitcoin Core parsing and fail my code.
It turns out that the Script parsing for sigops calls `break`  to exit the loop and returns the current n value whenever there is an EarlyEndOfScript error.
See this comment: https://github.com/rust-bitcoin/rust-bitcoin/pull/2073#issuecomment-1722403687 for some links to the relevant source.
=> Bugfix: Script::count_sigops should not return a Result

bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/script/tests.rs
A new `is_multisig` helper method to classify bare multisig output scripts.
The form of a valid multisig script is:
- Pushnum `M`
- &lt;N&gt; pubkeys
- Pushnum `N`
- `OP_CHECKMULTISIG`
`N` must equal the number of pushed pubkeys, and `M` must be less than or equal to `N`.
I've tested this against the RPC output of Core at the block level, checking that the total number of multisig outputs matches.
```
Block 350338, 89 multisig
Block 350340, 29 multisig
Block 350341, 4 multisig
Block 350343, 579 multisig
Block 350344, 48 multisig
Block 350346, 11 multisig
Block 350347, 404 multisig
Block 350350, 127 multisig
Block 350351, 1 multisig
Block 350353, 40 multisig
Block 350356, 13 multisig
Block 350357, 2 multisig
Block 350358, 1 multisig
```
=> Script helper to classify bare multisig

bitcoin/src/lib.rs
We recently rename `opcodes::All` to `Opcode` but did not re-export it from the crate root. Since it now has a nice clear name we can do so.
Found while hacking up the `rust-bitcoincore-rpc` dependency upgrade for upcoming release `bitcoin v0.31.0`.
=> Re-export Opcode

bitcoin/src/blockdata/script/owned.rs, bitcoin/src/blockdata/script/tests.rs
`T` is a generic that implements`AsRef<PushBytes>`, it should not be a reference. This is inline with other usages of `AsRef<PushBytes>` for example in `Builder::push_slice`.
Found while working on #2003
=> Remove unnecessary reference

bitcoin/examples/ecdsa-psbt.rs, bitcoin/examples/sighash.rs, bitcoin/examples/taproot-psbt.rs, bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/script/owned.rs, bitcoin/src/blockdata/script/tests.rs, bitcoin/src/psbt/mod.rs
A P2TR output does not need to be clarified with version 1, it is implicit. As with p2wpkh/p2wsh and version 0.
Remove redundant version identifiers from function names, deprecating the originals.
=> Remove redundant segwit version from function names

CONTRIBUTING.md
One "carves out" something, not "carve output" - woops.
=> Use correct terminology: carve out

bitcoin/src/blockdata/locktime/absolute.rs
Fixes https://github.com/rust-bitcoin/rust-bitcoin/issues/2011.
This PR aims to make the "pretty print" of `absolute::LockTime` prettier by printing `X blocks` and `X seconds` for `Blocks` and `Seconds` respectively instead of the default Enum printing.
=> Fixes #2011: Customize Debug implementation of `absolute::LockTime`

Cargo-minimal.lock, Cargo-recent.lock, bitcoin/Cargo.toml, bitcoin/src/address/error.rs, bitcoin/src/address/mod.rs, bitcoin/src/blockdata/script/witness_version.rs
Depend on the newly released version of `bech32`, BOOM!
=> Use newly released bech32 API

bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/transaction.rs
I copied over the sigop counting logic from Bitcoin Core, but I made a few adjustments.
1. I removed 2 consensus flags that checked for P2SH and SegWit activation. This code assumes both are activated. If we were to include that, what would be a good way to go about it? (ie. If I run this method on a transaction from the 1000th block and it just so happened to have a P2SH-like input, Bitcoin Core wouldn't accidentally count those sigops because the consensus flag will stop them from running the P2SH logic. Same goes for SegWit)
3. Since there's no guarantee that we have an index from which we can get the prevout scripts, I made it into a generic closure that looks up the prevout script for us. If the caller doesn't provide it, We can only count sigops directly in the scriptSig and …
=> Feature: Count sigops for Transaction

bitcoin/examples/ecdsa-psbt.rs, bitcoin/examples/taproot-psbt.rs, bitcoin/src/bip152.rs, bitcoin/src/blockdata/constants.rs, bitcoin/src/blockdata/fee_rate.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/crypto/sighash.rs, bitcoin/src/psbt/mod.rs, bitcoin/tests/psbt.rs, bitcoin/tests/serde.rs
BIP-68 activated a fair while ago (circa 2019) and since then only transaction versions 1 and 2 have been considered standard.
Currently in our `Transaction` struct we use an `i32`, this means users can construct a non-standard transaction if they do not first look up what the value should be. We can help folk out here by abstracting over the version number.
Add transaction::Version data type that simply provides two consts `ONE` and `TWO`.
Add a `Default` impl on `Version` that returns `Version::TWO`.
In tests that used version 0, instead use `Version::default` because the test obviously does not care.
=> Add transaction::Version data type

bitcoin/src/blockdata/witness.rs
In order to create the witness to spend p2wpkh output one must create a `Witness` that includes the signature and the pubkey, we should have a function for this.
The PR originally added a `push_p2wphk` method, this is now instead a constrcutor `Witness:p2wpkh` (after review discussion below).
- Patch 1 changes `push_bitcoin_signature` to take an `ecdsa::Sigtnture` instead of an `ecdsa::SerializedSignature`
- Patch 2 takes a `secp256k1::PublicKey` removing the need for an error path (discussed below).
=> Add `Witness::p2wpkh` constructor

bitcoin/src/amount.rs, bitcoin/src/blockdata/block.rs, bitcoin/src/blockdata/locktime/absolute.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/blockdata/witness.rs, bitcoin/src/consensus/encode.rs, bitcoin/src/psbt/serialize.rs, fuzz/fuzz_targets/bitcoin/deserialize_transaction.rs
Audit and re-write the weight/size API for `Block` and `Transaction`. First two patches are trivial, patch 3 contains justification and explanation for this work, copied here:
```
Recently we introduced a bug in the weight/size code, while
investigating I found that our `Transaction`/`Block` weight/size APIs
were in a total mess because:
- The docs were stale
- The concept of weight (weight units) and size (bytes) were mixed up
I audited all the API functions, read some bips (141, 144) and re-wrote
the API with the following goals:
- Use terminology from the bips
- Use abstractions that mirror the bips where possible
```
Please note, this PR introduces panics if a sciptPubkey overflows the calculation `weight = spk.size() * 4`.
Fix #2049
=> Re-write the weight/size API

Cargo-minimal.lock, Cargo-recent.lock, hashes/Cargo.toml
`hashes` no longer depends on `internals`.
EDIT: If anyone saw that, I'm a total wombat, clearly cannot remove `core2` dependency.
=> hashes: Remove unnecessary dependencies

.github/workflows/gh-release.yml
Creates a `gh-release.yml` that runs on every new tag using the [`ncipollo/release-action`](https://github.com/ncipollo/release-action), which is one of the recommended actions after [GitHub's official `actions/create-release`](https://github.com/actions/create-release) was archived.
The idea is to just have a release with the source code, no binary (although if wanted I can add that as well).
A little bit of context: tcharding told me yesterday at TABConf that he copied manually all commits titles to the release notes somewhere (I think in crates.io?).
This is an easy way to do it, just copy from the GitHub release.
Finally, it is also positive to generate Releases from Tags since this increases the exposure of the repo (GitHub is highly social) while also signaling maturity.
Here's an …
=> CI: add an automated github releases on new tags

bitcoin/examples/ecdsa-psbt.rs, bitcoin/examples/taproot-psbt.rs, bitcoin/src/blockdata/fee_rate.rs, bitcoin/src/psbt/macros.rs, bitcoin/src/psbt/mod.rs, bitcoin/tests/psbt.rs
Closes #2061
These new methods on Psbt will add checks for high fees by default. The threshold for "high fees" is currently set to 25000 sat/vbyte, which is about 20x higher than the highest next block fees seen on the "Mempool" website.
The primary goal of this change is to prevent users of the library from accidentally sending absurd amounts of fees.
(ie. Recently in September 2023 there was a transaction that sent an absurd amount of fees and made news in the Bitcoin world. Luckily the mining pool gave it back, but some might not be so lucky.)
There are variants of the method that allow for users to set their own "absurd" threshold using a `FeeRate` value. And there is a method that performs no checks, and the method name is alarming enough to draw attention in a review, so at least …
=> Feature: Psbt fee checks

Cargo-minimal.lock, Cargo-recent.lock, contrib/test.sh, hashes/Cargo.toml, hashes/contrib/test.sh
We only test WASM in CI using a stable toolchain however because we have a target specific dev-dependencies section the wasm deps get pulled in during MSRV builds - this breaks the MSRV build.
Instead of including WASM dev-dependencies in the manifest we can dynamically modify the manifest when running the WASM tests. We do this already to add the `crate-type` section so this is not really that surprising to see in the CI script.
Doing so allows us to stop pinning the transitive `syn` dependency also which is included in the dependency graph because of `wasm-bingen-test`.
Originally part of #2093
=> Add wasm dev-deps using CI script

bitcoin/src/base58.rs, bitcoin/src/bip158.rs, bitcoin/src/bip32.rs, bitcoin/src/blockdata/block.rs, bitcoin/src/blockdata/constants.rs, bitcoin/src/blockdata/fee_rate.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/blockdata/witness.rs, bitcoin/src/crypto/sighash.rs, bitcoin/src/internal_macros.rs, bitcoin/src/merkle_tree/block.rs, bitcoin/src/p2p/address.rs, bitcoin/src/p2p/message.rs, bitcoin/src/p2p/message_blockdata.rs, bitcoin/src/p2p/message_network.rs, bitcoin/src/psbt/mod.rs, bitcoin/src/taproot.rs
We have this macro in `hex-conservative` now, remove the version here.
This patch does not change the public API and only touches test code.
=> Remove private hex test macro

.github/workflows/fuzz.yml
To avoid YAML automatic parsing of inputs as floats, e.g. [`1.60` being parsed as `1.6`](https://github.com/rust-bitcoin/rust-bitcoin/pull/2109#issuecomment-1751392327), it is best to future-proof the `toolchain` input in CI fuzz testing as a string.
=> ci: fuzz test YAML toolchain future-proof

Cargo-minimal.lock, Cargo-recent.lock, bitcoin/Cargo.toml, bitcoin/src/address/error.rs, bitcoin/src/address/mod.rs
Update the `bech32` dependency to use the newly release beta version.
The main fix here is silent, a bug fix in `bech32` that was being hit by our fuzzing suite.
=> Update bech32 dependency

.github/workflows/fuzz.yml, fuzz/Cargo.toml, fuzz/fuzz-util.sh, fuzz/generate-files.sh
1. Changes the toolchain fom `actions-rs/toolchain` to `dtolnay/rust-toolchain`.
Closes #2113.
1. Changes the CI runner from `ubuntu-20.04` to `ubuntu-latest`.
Related #2114.
1. Updates the `fuzz/generate-files.sh` to match `.github/workflows/fuzz.yml`.
Closes #2115.
=> ci(fuzz): replace toolchain and runner

Cargo-minimal.lock, Cargo-recent.lock, bitcoin/Cargo.toml, bitcoin/examples/sighash.rs, bitcoin/examples/taproot-psbt.rs, bitcoin/src/bip32.rs, bitcoin/src/crypto/key.rs, bitcoin/src/crypto/sighash.rs, bitcoin/src/crypto/taproot.rs, bitcoin/src/psbt/mod.rs, bitcoin/src/sign_message.rs
Upgrade the `secp256k1` dependency to the newly released `v0.28.0`.
FTR this includes two simple changes:
- Use `Message::from_digest_slice` instead of `Message::from_slice`.
- Use `secp256k1::Keypair` instead of `secp256k1::KeyPair`.
But to stay in line with the keypair change we deprecate and rename the tweaked alias.
=> Upgrade secp dependency

bitcoin/src/consensus/params.rs, bitcoin/src/pow.rs
The `Params::pow_limit` field is currently a `Work` type, this is incorrect. The proof of work limit is the highest _target_ not the lowest work (even though these have a relationship).
Note that we use the highest _attainable_ target, this differs from Bitcoin Core and the reasoning is already documented in the code.
Add new consts and document where they came from as well as how they differ to Core.
Use the new consts in the various network specific `Params` types.
Fix: #2106
=> Use `Target` as type for `pow_limit`

Cargo-minimal.lock, Cargo-recent.lock, bitcoin/Cargo.toml, contrib/test.sh, fuzz/Cargo.toml, fuzz/generate-files.sh
Lets go!
As discussed in #2099 we are going to do RC releases for this release. This PR is for the first one, as such it does not include changelog entries, we are going to try out using the new github action to create those.
=> Tracking PR for release `v0.31.0-rc1`

bitcoin/src/blockdata/block.rs
I think it makes sense for a block header to have the block hash shown in the debug print.
=> Implement manual fmt::Debug for BlockHeader to include block hash

Cargo-minimal.lock, Cargo-recent.lock, bitcoin/CHANGELOG.md, bitcoin/Cargo.toml, fuzz/Cargo.toml, fuzz/generate-files.sh, justfile
Prepare for the v0.31.0-rc2 release.
- Add changlog entries
- Add a `just update-lock-files` command
- Bump the version ready for next RC release
=> Tracking PR for `v0.31.0-rc2` release

bitcoin/tests/psbt.rs
Remove the macro hex_psbt and replace with a function.  Using track_caller to accurately report the test name and line number during a panic is used in place of a macro.
This is a refactor commit to the test suit.
=> Replace helper macro with helper function

.github/workflows/rust.yml, .github/workflows/rustfmt.yml, CONTRIBUTING.md
- Removes nightly `rustfmt` checks from CI and `CONTRIBUTING.md`. Superseds #2127
- Adds automated nightly `rustfmt` PR creations manual and every Sunday 00:00 UTC. Closes #2128. Closes #1712.
The new `.github/workflows/rustfmt.yml` action does the following:
1. Checkouts the repo
1. Install the nightly Rust toolchain with `rustfmt` component
1. Run `cargo +nightly fmt` which format all the codebase with the nightly Rust toolchain writing the changes
1. Add the current date in `YYYY-MM-DD` format as an GH action ENV var
1. If changes are detected, create a PR with the following details:
- Title: Automated nightly rustfmt (`DATE`)
- Body: Automated nightly `rustfmt` changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
- Commit message: `DATE` …
=> ci: automated nightly rustfmt scheduled/manual PRs

bitcoin/src/lib.rs, hashes/src/lib.rs, internals/src/lib.rs
This lint forces you to write semantically different code that is in most cases inferior, just to save you 5 characters.
The reason why the code is inferior is because it doesn't do error conversion so it would break when either of the two function signatures changes while in the original code using the `?` operator, nothing would break if the inner error can be converted into the outer error.
=> Add clippy exceptions for needless_question_mark lint

contrib/test.sh
=> Fix a small typo in 'contrib/test.sh'

bitcoin/CHANGELOG.md
In the changelog, there is a wrong link to #2006.
Additionally, a link and description for #2020 are missing.
This PR addresses these minor issues.
=> Add a missing link to #2006 in 'bitcoin/CHANGELOG.md'

Cargo-minimal.lock, Cargo-recent.lock, bitcoin/Cargo.toml, fuzz/Cargo.toml, fuzz/generate-files.sh
In preparation for release of v0.31.0 bump the version number.
The changelog is already up to date because we have done two RC releases.
=> bitcoin: Tracking PR for release `v0.31.0` 

bitcoin/build.rs, internals/build.rs
Previously, each unique compiler cfg attribute that appeared in the codebase was hard coded and emitted to stdout at compile time.  This meant keeping the file up to date as different compiler cfg attributes changed.  It's inconsequential to emit a compiler version that's not used, so this change just emits all possibilities to reduce the maintenance burden of the build script.
Note that there is a bit of diff noise in one of the `build.rs` since I simply did a copy of one to the other to make them uniform.
=> Create uniform build script

hashes/src/sha512_256.rs
Make the `sha512_256` module use similar code layout to the other hash modules by putting the call to `hash_type` at the top followed by the `from_engine` function.
Code move only, no other changes.
=> Move `sha512_256` code

hashes/src/sha512.rs
This PR does not introduce any logic changes.
- Patch 1 is a code move.
- Patch 2 uses the `hash_type!` macro to define the `sha512::Hash` type.
=> Use macro to define `sha512::Hash`

bitcoin/src/amount.rs, bitcoin/src/blockdata/block.rs, bitcoin/src/blockdata/constants.rs, bitcoin/src/blockdata/locktime/absolute.rs, bitcoin/src/blockdata/locktime/relative.rs, bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/script/owned.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/blockdata/witness.rs, bitcoin/src/consensus/encode.rs, bitcoin/src/crypto/key.rs, bitcoin/src/crypto/sighash.rs, bitcoin/src/pow.rs, bitcoin/src/taproot.rs
We only deprecate for a single release.
Remove all code deprecated since `v0.31.0`.
=> Remove code deprecated since `v0.31.0`

bitcoin/src/address/mod.rs
The `AddressEncoding` and `Payload` types are implementation details and should never have been public.    Make them private.
Fix: #1908
=> Make `Payload` and `AddressEncoding` private

bitcoin/src/bip32.rs
Not sure what happened here but our release job didn't catch this? We should have updated this to "since = 0.31.0" before release. Since we only deprecate for one release lets go ahead and remove this.
=> Remove deprecated since NEXT-RELEASE

bitcoin/src/blockdata/block.rs, bitcoin/src/pow.rs
The difficulty is a ratio of the max and current targets, since the max is network specific the difficulty calculation is also network specific.
We already have network specific maximum target constants, use them when calculating the difficulty.
Patch 1 is a trival docs improvement to `block::Header::difficulty`.
=> Use network when calculating difficulty

bitcoin/src/blockdata/fee_rate.rs
Fixes a bug in https://github.com/rust-bitcoin/rust-bitcoin/pull/1864. The `FeeRate::checked_mul_by_weight` and by extension the `FeeRate::fee_wu` methods were returning fee amounts scaled up by a factor of 1000, since the internal representation in `FeeRate` is sats per 1000 weight units. 
This PR fixes `checked_mul_by_weight` and its unit tests by scaling the output of these methods down by 1000, so that `X sat/vbyte * Y vbytes = X * Y sats`, instead of `X * Y * 1000 sats` as before.
This code would pass without panic before this PR.
```rust
let weight = Weight::from_vb(3).unwrap();
let rate = FeeRate::from_sat_per_vb(3).unwrap();
assert_eq!(weight * rate, Amount::from_sat(9));
assert_eq!(rate.checked_mul_by_weight(weight), Some(Amount::from_sat(9000)));
```
```rust
let weight = …
```
=> fix: FeeRate::checked_mul_by_weight should scale output down by 1000

bitcoin/src/address/error.rs, bitcoin/src/address/mod.rs, bitcoin/src/blockdata/block.rs, bitcoin/src/blockdata/mod.rs, bitcoin/src/blockdata/script/mod.rs, bitcoin/src/blockdata/script/push_bytes.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/consensus/mod.rs, bitcoin/src/crypto/key.rs, bitcoin/src/crypto/taproot.rs, bitcoin/src/error.rs, bitcoin/src/hash_types.rs, bitcoin/src/lib.rs, bitcoin/src/merkle_tree/mod.rs, bitcoin/src/p2p/mod.rs, bitcoin/src/psbt/map/mod.rs, bitcoin/src/psbt/mod.rs, bitcoin/src/sign_message.rs, bitcoin/src/taproot.rs
Improve the public exports in two ways:
1. Inline re-exports into the docs of the module that re-exports them.
2. Separate public and private use statements
Recently we discussed a way to separate the public and private import statements to make the code more clear and prevent `rustfmt` joining them all together.
Separate public exports using a code block and `#[rustfmt::skip]`. Has the nice advantage of reducing the number of `#[doc(inline)]` attributes also.
1. Modules first, as they are part of the project's structure.
2. Private imports
3. Public re-exports (using `rustfmt::skip` to prevent merge)
Use the format
```rust
mod xyz;
mod abc;
use ...;
pub use {
...,
};
```
This patch introduces changes to the rendered HTML docs.
=> Improve public re-exports

bitcoin/src/blockdata/transaction.rs
Adds input weight prediction constant and `ground_p2pkh_*` methods, mirroring those for `P2WPKH`. This seemed to be missing.
=> add input weight predictions for p2pkh outputs

CONTRIBUTING.md, bitcoin/src/blockdata/script/borrowed.rs
Fixes #2193 (first commit)
Second commit fixes broken link in `CONTRIBUTING.md`
=> Script documentation weirdness and typos

bitcoin/CHANGELOG.md, bitcoin/Cargo.toml, bitcoin/src/pow.rs
Patch one backports #1820, I believe this is all that is needed for LDK to be able to upgrade to `rust-bitcoin v0.30`.
Context:
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1820
- https://github.com/lightningdevkit/rust-lightning/issues/2124
Patch 2 adds a changelog entry and bumps the minor version.
=> Backport #1820 and bump minor version 0.30.2

bitcoin/src/consensus/params.rs, bitcoin/src/network.rs
Writing `network.params()` is less annoying than `Params::network()`, so this adds it. Making it return a static could also improve performance.
Didn't do `Params` -> `Network` conversions because of #2173
=> Add `params` method to `Network`

bitcoin/src/blockdata/weight.rs
This function is can be used to construct a Weight type from_vb in const context.  Note I don't think it's possible to test the panic case since it's a compile time error work around currently to panic.
=> Add from_vb_const function

Cargo-minimal.lock, Cargo-recent.lock, bitcoin/Cargo.toml, bitcoin/src/consensus/serde.rs, contrib/test.sh, hashes/Cargo.toml, hashes/src/hash160.rs, hashes/src/hmac.rs, hashes/src/internal_macros.rs, hashes/src/ripemd160.rs, hashes/src/sha1.rs, hashes/src/sha256.rs, hashes/src/sha256d.rs, hashes/src/sha256t.rs, hashes/src/sha512.rs, hashes/src/sha512_256.rs, hashes/src/siphash24.rs, hashes/src/util.rs
Done while investigating removal of `serde_derive` dependency.
- Patch 1: Do trivial dev-dep removal
- Patch 2: Manually implement `JsonSchema` and remove default dependencies from "schemars" dependency (transitively depends on `serde_derive`)
=> Manually implement `JsonSchema`

bitcoin/src/blockdata/transaction.rs
The `P2WPKH_MAX` constant assumed DER signatures in the witness have a max length of 73. In practice, their maximum length is 72, because [BIP62](https://github.com/bitcoin/bips/blob/master/bip-0062.mediawiki) forbids nodes from relaying transactions which contain non-canonical ECDSA signatures (i.e. TX sigs must have an $s$ value of less than $\frac{n}{2}$). 
This means $s$ is never encoded with a leading zero byte, and the signature as a whole never exceeds 72 bytes in total encoded length. The `ground_p2wpkh` function was already correct; only the constant needed to be corrected.
Technically 73 bytes *is* the upper limit for signatures, as nothing forbids miners from including such non-standard transaction signatures in blocks, but for the purposes of fee estimation and input weight …
=> Fix InputWeightPrediction::P2WPKH_MAX constant DER sig length

bitcoin/src/pow.rs
=> Implement LowerHex and UpperHex for CompactTarget

bitcoin/src/hash_types.rs
Fixes https://github.com/rust-bitcoin/rust-bitcoin/issues/2220.
Also adds the equivalent conversion trait from `Wtxid` -> `WitnessMerkleNode`.
=> add conversions from TXIDs to merkle nodes

bitcoin/Cargo.toml, bitcoin/src/amount.rs, bitcoin/src/bip158.rs, bitcoin/src/bip32.rs, bitcoin/src/blockdata/block.rs, bitcoin/src/blockdata/locktime/absolute.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/blockdata/witness.rs, bitcoin/src/consensus/encode.rs, bitcoin/src/consensus/serde.rs, bitcoin/src/lib.rs, bitcoin/src/merkle_tree/block.rs, bitcoin/src/merkle_tree/mod.rs, bitcoin/src/p2p/address.rs, bitcoin/src/p2p/message.rs, bitcoin/src/p2p/message_bloom.rs, bitcoin/src/pow.rs, bitcoin/src/psbt/map/global.rs, bitcoin/src/psbt/raw.rs, hashes/embedded/src/main.rs, hashes/src/impls.rs, io/src/lib.rs, io/src/macros.rs
Its not immediately obvious why we nest the whole `io` code in an `io` submodule within `lib.rs`. As far as I can tell we can inline it and re-export from `rust-bitcoin` same as we do for our other dependencies.
This change would effect other users of the crate but since the `io` crate is unreleased this effects no-one except us.
After doing this it might be because `crate::io::Foo` looks good when near `std::io::Foo`?
=> Inline io module in the io crate root

contrib/release.sh
There is an ecosystem-wide solution to our custom usage of `NEXT-RELEASE` in deprecation attributes - use
`#[decprecated(since = "TBD", note = "use bar instead")]`
Lets use it.
=> Introduce usage of TBD instead of NEXT-RELEASE

.github/workflows/rust.yml, bitcoin/CHANGELOG.md, bitcoin/Cargo.toml, bitcoin/contrib/test.sh, bitcoin/embedded/Cargo.toml, bitcoin/src/lib.rs
Now we have the `io` crate we can remove the "no-std" feature.
Do a few cleanups to the `bitcoin` manifest, then remove the "no-std" feature - BOOM!
=> Remove the "no-std" feature

bitcoin/src/crypto/taproot.rs, bitcoin/src/taproot/mod.rs, bitcoin/src/taproot/serialized_signature.rs
Previously `taproot::Signature` could be only serialized into `Vec<u8>`
which forced allocation. This adds a `SerializedSignature` type which
acts like `Box<u8>` but is on stack.
Note: the code was copied from `secp256k1::ecdsa::serialized_signature`
with minimal changes.
=> Taproot sig on stack

bitcoin/src/crypto/sighash.rs
Recently during the rust-bitcoin workshop at TABConf devs were thrown off by the example on `witness_mut`.  We have some work going on to add examples and a cookbook that all demonstrate usage of `witness_mut`.
Remove the docs on `witness_mut` and direct devs to the `examples/sign-tx-*` files.
=> Update docs on witness_mut

bitcoin/src/bip32.rs
In the 0.31.0 release we renamed the bip32 extended key types without leaving the originals in there marked as deprecated. This makes for a bad experience for devs, add them back in.
=> Add deprecated bip32 types back in

bitcoin/src/taproot/mod.rs
Since we do `& 1`, only 0 and 1 are possible values, so the error return there can never happen. I made this explicit by manually setting the parity.
This is a rebase of Steven's change #2163 with a rewrite of `match` to not panic.
=> Remove impossible InvalidParity error variant

bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/script/tests.rs, bitcoin/src/blockdata/transaction.rs
Fixes #2192 
TxOut::minimal_non_dust has 3 problems.
1. There is an invisible dependency on Bitcoin Core's default minrelaytxfee value. It has been made explicit.
2. There is an off by one error. The dust limit comparison uses < and therefore `+ 1` was not needed. It has been fixed.
3. It was not returning 0 amount for OP_RETURN outputs.
Script::dust_value has 2 problems.
1. The dust amount depends on minrelaytxfee which is configurable in Bitcoin Core. This method was not configurable.
2. The division operation was done before multiplying the byte amount, which can cause small differences when using uncommon scripts and minrelaytxfee values.
=> Fix: TxOut::minimal_non_dust and Script::dust_value

.github/workflows/rust.yml, bitcoin/src/lib.rs, bitcoin/src/taproot/merkle_branch.rs, bitcoin/src/taproot/mod.rs
This contains several improvements to `TaprootMerkleBranch` that make the API more idiomatic.
=> `TaprootMerkleBranch` improvements

bitcoin/src/address/error.rs, bitcoin/src/address/mod.rs, bitcoin/src/blockdata/script/owned.rs, bitcoin/src/blockdata/script/witness_program.rs, bitcoin/src/crypto/key.rs, bitcoin/src/sign_message.rs, bitcoin/tests/serde.rs
An `AddressInner` struct (contains `Network` field) is created when parsing address strings however address strings do not map 1:1 to `Network` because signet and testnet use the same bech32 prefix "tb".
We can fix this by inlining the `Payload` variants into `AddressInner` and adding prefix enums for legacy addresses and an `Hrp` for bech32 addresses.
Fix: #1819
=> Remove Network from AddressInner

hashes/src/lib.rs
Is there any interest in a method like this? I'm not necessarily a fan myself, was just in a situation where I was doing this a lot and it would save the me the "engine, from_engine dance" each time.
=> hashes: Add Hash::from_bytes_iter to construct hashes from iterators

units/src/lib.rs
We are not using the `ToOwned` trait, remove it.
Found by clippy.
=> Remove ToOwned from prelude

bitcoin/src/bip152.rs, bitcoin/src/bip158.rs, bitcoin/src/blockdata/block.rs, bitcoin/src/blockdata/script/mod.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/consensus/encode.rs, bitcoin/src/consensus/serde.rs, bitcoin/src/crypto/key.rs, bitcoin/src/crypto/sighash.rs, bitcoin/src/lib.rs, bitcoin/src/merkle_tree/block.rs, bitcoin/src/merkle_tree/mod.rs, bitcoin/src/p2p/address.rs, bitcoin/src/p2p/message.rs, bitcoin/src/p2p/message_blockdata.rs, bitcoin/src/p2p/message_bloom.rs, bitcoin/src/p2p/message_network.rs, bitcoin/src/p2p/mod.rs, bitcoin/src/psbt/map/global.rs, bitcoin/src/psbt/raw.rs, bitcoin/src/taproot/mod.rs, units/src/amount.rs
A few cleanups to how we use the `io` crate, this is reasonably trivial but commit `a6c7e696 Remove qualifying path from Read and Write` is big, I have however gone to some effort to make sure it is easy to flick through the diff.
Done in preparation for another go at the `BufRead` stuff.
=> Clean up `io` usage

bitcoin/src/consensus/validation.rs, bitcoin/src/lib.rs
The `bitcoinconsensus` crate is not fully under our control because it exposes code from Core, so we cannot guarantee its stability across versions. To make our semver compliance easier we can fully encapsulate the `bitcoinconsensus` crate so it does not appear in our public API.
- The `bitcoinconsenus` crate is no longer exported at the crate root
- No `bitcoinconsensus` types appear in our public API
=> Fully encapsulate bitcoinconsensus

io/Cargo.toml, io/src/lib.rs
In preparation for adding the `BufRead` trait do a few improvements, the first ones are all trivial, the last sets the MSRV to Rust 1.56.1
=> Improve the `io` crate

bitcoin/src/lib.rs
In #2278 I mistakenly left in the `use extern crate` after removing the `pub` from it - while not incorrect it is unnecessary.
=> Remove unnecessary private extern crate

bitcoin/embedded/src/main.rs, bitcoin/examples/bip32.rs, bitcoin/examples/ecdsa-psbt.rs, bitcoin/examples/sighash.rs, bitcoin/src/address/mod.rs, bitcoin/src/bip32.rs, bitcoin/src/blockdata/script/witness_program.rs, bitcoin/src/crypto/key.rs, bitcoin/src/lib.rs, bitcoin/src/sign_message.rs
P2WPKH requires keys to be compressed which introduces error handling even in cases when it's statically known that a key is compressed. To avoid it, this change introduces `CompressedPublicKey` which is similar to `PublicKey` except it's statically known to be compressed.
This also changes relevant code to use `CompressedPublicKey` instead of `PublicKey`.
=> Implement `CompressedPublicKey`

internals/src/array_vec.rs, internals/src/const_tools.rs, internals/src/lib.rs
While we decided to use `arrayvec::ArrayVec`, unfortunately it currently isn't `Copy` even if `T` is because of unfortunate interactions with the `Drop` trait. So this adds a super-simple custom version that is `Copy` and may be extended if we need to or replaced with `arrayvec` if they start supporting `Copy`.
=> Implement custom `ArrayVec` that is `Copy`

CONTRIBUTING.md
Returning `Self` instead of the actual type makes refactoring easier, especially for error enums.
=> policy: Add section on returning `Self`

bitcoin/examples/bip32.rs, bitcoin/src/address/mod.rs, bitcoin/src/bip32.rs, bitcoin/src/crypto/key.rs, bitcoin/src/lib.rs, bitcoin/src/network.rs, bitcoin/src/psbt/mod.rs, bitcoin/src/sign_message.rs, bitcoin/tests/psbt.rs, bitcoin/tests/serde.rs
Add a new type `NetworkKind` the describes the kind of network we are on, ether mainnet or one of the test nets (testnet, regtest, signet).
Use it in `Address`, `PrivateKey`, and `bip32`.
=> Add `NetworkKind`

CONTRIBUTING.md
We can have a standard set of derives to make it easier for new devs to work out what to use and also to help us move towards a uniform set in preparation for crate stabilization.
This is not me imposing my view but rather a place for the discussion to happen, could have been a discussions topic also? Using "open" instead of "draft" to aid visibility. Probably requires more than the usual amount of acks.
=> policy: Add section on standard set of derives

.github/workflows/fuzz.yml, bitcoin/src/blockdata/transaction.rs, bitcoin/src/lib.rs
Clippy has introduced a couple new lints that are causing our CI to fail. `allow` them.
=> Whitelist some recent clippy lints

bitcoin/src/blockdata/weight.rs, units/src/amount.rs
Out of bounds indexing is a workaround for const panic until MSRV +1.57
=> Add allow for out of bounds indexing

bitcoin/src/blockdata/transaction.rs
Adds the implementation of `Display` trait for `transaction::Version`
fixes #2308 
This is unrelated to the issue but can anyone suggest some good issues that needs to be fixed. I am also taking a look but I am confused as to which I would be able to solve. I am here to learn more.
Thank you.
=> Add the implementation of `Display` for `transaction::Version`

bitcoin/src/address/mod.rs, bitcoin/src/blockdata/script/witness_program.rs, bitcoin/src/lib.rs, bitcoin/src/psbt/mod.rs
Fixes https://github.com/rust-bitcoin/rust-bitcoin/issues/2261
Introduces a new constructor, `WitnessProgram::from_bytes`, which creates a witness program by copying the program content from a byte slice.
=> use arrayvec to represent witness programs internally

bitcoin/src/address/mod.rs
In #1765 we added a couple of new functions. 
- Patch 1: Fix mis-documented function.
- Patch 2: Do trivial rustdocs fix.
=> Improve address conversion docs

bitcoin/src/blockdata/script/borrowed.rs
This method is not really that useful because it checked an arbitrary condition. There already exists `OP_RETURN` semantics and the method didn't cover all possible ways the script may be invalid.
This deprecates the method and documents why.
Closes #2191
=> Deprecate `Script::is_provably_unspendable`

bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/transaction.rs
The `Push` enum is only ever used to get access to one of its variants. Since it is a private type we can remove it entirely and just return `PushBytes` from the `last_pushdata` function.
Needs careful review but I believe the function name is still correctly descriptive.
This was discovered by of a new nightly clippy warning.
=> Remove Push enum

bitcoin/src/blockdata/script/witness_program.rs
Recently we started using our custom `ArrayVec` for the `program` field of `WitnessProgram`, this means we can now derive `Copy`.
Fix: #2313
=> Derive `Copy` for `WitnessProgram`

bitcoin/src/address/mod.rs
Do two miner docs fixes.
- Patch 1: Fixes some stale docs I left in when refactoring the `AddressInner` type.
- Patch 2: Uses code comments instead of rustdoc and fixes the issue linked below.
Fix: #2315
=> Remove `AddressInner` from rustdocs

hashes/README.md
We do not need to pin with the current MSRV, remove the stale mention of it from the `hashes` readme file.
=> docs: Remove pinning from hashes readme

bitcoin/src/blockdata/script/tests.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/pow.rs
1. Fix typos in rustdocs:
hexidecimal -> hexadecimal
lenght -> length
2. Fix typos in test function names:
u256_wrapping_add_wraps_at_boundry -> u256_wrapping_add_wraps_at_boundary
u256_wrapping_sub_wraps_at_boundry -> u256_wrapping_sub_wraps_at_boundary
=> Fix some typos

bitcoin/src/bip158.rs, bitcoin/src/lib.rs
I don't mind making these PRs, but I think we should start pinning our nightlies, and using a script to update the pin every week (or day, or whatever). When our CI breaks due to tooling changes, it means that our release branches will have permanently broken CI jobs, which I'd like to avoid in the future.
If the automatic pin update failed, we'd close it and manually create one that fixed the nw issues.
=> fix nightly clippy issues

bitcoin/examples/sighash.rs, bitcoin/examples/sign-tx-segwit-v0.rs, bitcoin/examples/sign-tx-taproot.rs, bitcoin/examples/taproot-psbt.rs, bitcoin/src/blockdata/witness.rs, bitcoin/src/crypto/ecdsa.rs, bitcoin/src/crypto/key.rs, bitcoin/src/crypto/sighash.rs, bitcoin/src/crypto/taproot.rs, bitcoin/src/psbt/mod.rs, bitcoin/tests/serde.rs
Applies to both `ecdsa::Signature` and `taproot::Signature`.
Re-name the `Signature` fields with more descriptive names. The names used were decided upon in the issue discussion.
Impove rustdocs while we are at it.
Note, the change to `sign-tx-segwit-v0` is refactor only, the diff does not show it but we have a local variable already called `sighash_type` that is equal to `EcdsaSighashType::All`.
Fix: #2139
=> Improve `Signature` field names

io/README.md, io/src/lib.rs
Simplify the docs in `lib.rs` and copy them into a minimal README file.
=> io: Simplify crate docs and add README

bitcoin/src/p2p/message_network.rs
Better describe what the nonce is used for.
Note this file has not had its docs manicured so the line length is 80 still, just use the same line length instead of the conventional 100.
Fix: #575
=> p2p: Improve nonce documentation

bitcoin/src/psbt/raw.rs
We no longer depend on `core2`, remove stale code comment mention of the crate.
Fix: #2034
=> Remove mention of core2

bitcoin/src/blockdata/transaction.rs
Draft PR for adding effective value calculation to TxOut.  Adding this method was discussed here: https://github.com/rust-bitcoin/rust-bitcoin/pull/2217
=> Add effective value calculation

bitcoin/src/bip152.rs, bitcoin/src/bip158.rs, bitcoin/src/blockdata/block.rs, bitcoin/src/blockdata/locktime/absolute.rs, bitcoin/src/blockdata/script/mod.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/blockdata/witness.rs, bitcoin/src/consensus/encode.rs, bitcoin/src/consensus/serde.rs, bitcoin/src/internal_macros.rs, bitcoin/src/lib.rs, bitcoin/src/merkle_tree/block.rs, bitcoin/src/p2p/address.rs, bitcoin/src/p2p/message.rs, bitcoin/src/p2p/message_blockdata.rs, bitcoin/src/p2p/message_bloom.rs, bitcoin/src/p2p/message_network.rs, bitcoin/src/p2p/mod.rs, bitcoin/src/pow.rs, bitcoin/src/psbt/macros.rs, bitcoin/src/psbt/map/global.rs, bitcoin/src/psbt/raw.rs, io/src/lib.rs
Require `BufRead` instead of `Read` for consensus decode trait.
=> Require `BufRead` instead of `Read`

bitcoin/src/crypto/key.rs
We do not need to use `Cursor` in these tests, remove the usage.
PR touches test code only.
=> Remove `Cursor` usage in `PublicKey` unit test

bitcoin/src/internal_macros.rs, bitcoin/src/psbt/macros.rs, hashes/src/internal_macros.rs, hashes/src/serde_macros.rs, internals/src/macros.rs
Apparently when someone uses a custom `Result` type and then uses some of these macros, they can get type conflict errors.
(Thanks josibake for finding this using the `sha256t_hash_newtype` macro.)
=> Use full path in all macro usage of Result

bitcoin/src/blockdata/transaction.rs
We are mapping outputs not inputs.
=> Fix cut'n'pasta error in map variable

bitcoin/src/blockdata/transaction.rs
Currently we loop over transaction inputs within a loop over transaction inputs - ouch.
Cache the `use_segwit_serialization` outside the iteration loop.
Fix: #2357
=> Remove quadratic algorithm

.github/workflows/coveralls.yml
There has been discussion around generating coverage reports for tests. See #1853  and #2353.
This PR adds an action using llvm-cov and coveralls.
The action generates lcov coverage report using llvm-cov and uploads the generated report to coveralls. You can see sample reports for my fork here: https://coveralls.io/github/pool2win/rust-bitcoin
I am using the [cargo-llvm-cov](https://github.com/taiki-e/cargo-llvm-cov) wrapper around llvm-cov.
I also use the coveralls official github action to push the coverage report to coveralls. It removes the need to deal with repository secrets etc, making the action easy to run for all contributors on their forks.
We can move this action later to rust.yml if we need to.
=> Add github action for llvm-cov coverage

bitcoin/src/blockdata/transaction.rs
Tries to close #2183 
Added the test for invalid segwit transaction (witness flag is set but no witness is present) using [This suggested hex](https://github.com/rust-bitcoin/rust-bitcoin/issues/2183#issuecomment-1901207149) by Kixunil
=> Test: add invalid segwit transaction test

units/src/amount.rs
`Denomination::Bitcoin` and `Denomination::Satoshi` are often used, especially in test code so this change adds `BTC` and `SAT` - short, readable constants. Notably this doesn't add the other constants as that would lead to either unidiomatic names or confusing casing (MSAT meaning millisat not megasat) and they are not used that much anyway.
=> Add convenience constants to `Denomination`

units/src/amount.rs
Our `Amount` type uses an internal `u64` and we maintain no invariants on the inner value. Therefore we should be able to parse `u64::MAX`.
Fix the parsing code by removing the explicit, incorrect check and fix unit tests to mirror this behaviour.
Fix: #2297
=> units: Enable parsing Amount from `u64::MAX`

.github/workflows/rust.yml, bitcoin/contrib/test.sh
We have test coverage by way of `coveralls` now. Remove the old stale `DO_COV` stuff.
Fix: #1853
=> Remove DO_COV

bitcoin/src/pow.rs
Add a kani test to check `div_rem`.
=> Add kani test and remove TODO

bitcoin/src/lib.rs
The only place that `bech32` appears in the pubic API is as a pub extern crate re-export. This is totally unnecessary since no other `bech32` functions or types appear in the public API.
Removing `bech32` from the public API allows us to stabilize `rust-bitcoin` without waiting for `bech32` to stabalize - WIN.
=> Remove bech32 from the public API

bitcoin/examples/bip32.rs, bitcoin/src/address/mod.rs, bitcoin/src/lib.rs, bitcoin/src/taproot/mod.rs
We have a bunch of functions that take `Network` when what they really want is something that can be converted to a `KnownHrp`.
Make `KnownHrp` public and accept `impl Into<KnownHrp>`.
=> Use KnowHrp instead of Network

bitcoin/src/blockdata/transaction.rs
- Patch 1: Improve the name.
- Patch 2: Use `any` instead of manual loop.
=> Improve private function `use_segwit_serialization`

bitcoin/examples/taproot-psbt.rs, bitcoin/src/bip152.rs, bitcoin/src/blockdata/block.rs, bitcoin/src/blockdata/constants.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/merkle_tree/block.rs, bitcoin/src/merkle_tree/mod.rs, bitcoin/src/psbt/error.rs, bitcoin/src/psbt/mod.rs
Rename txid to compute_txid and mark txid as deprecated. 
Closes #2363
=> Rename `txid` to `compute_txid`

bitcoin/src/crypto/sighash.rs, bitcoin/src/psbt/mod.rs
The hadnling of `io::Error` in sighash had a few problems:
* It used `io::ErrorKind` instead of `io::Error` losing inforation
* Changing `io::ErrorKind` to `io::Error` would disable `PartialEq`&co
* The `Io` error wariants were duplicated
It turns out all of these can be solved by moving the `Io` variant into a separate error.
=> Factor out `io::Error` from sighash errors

hashes/Cargo.toml, hashes/contrib/test.sh
As we do for "rand-std" in the `bitcoin` crate we can enable "std" when the "serde-std" feature is enabled. This makes the features more explicit and arguably more ergonomic.
Found while working on #2353, no additional testing added hear (in CI).
=> Remove `serde-std` from `hashes`

bitcoin/src/crypto/key.rs, bitcoin/src/pow.rs
We introduced `hex-conservative` ages ago, use it to display the `PublicKey`.
=> Use hex-conservative to display pubkey

bitcoin/src/crypto/ecdsa.rs, bitcoin/src/crypto/taproot.rs, bitcoin/src/taproot/serialized_signature.rs
Serializing the ecdsa and taproot `Signature` straight to a writer is a useful thing to be able to do.
Add `to_writer` to both `SerializedSignature`s and also to the `Signature`s (calling through to `SerializedSignature`).
Remove TODO comments from code.
=> Add functionality to serialize signatures to a writer

bitcoin/examples/sign-tx-taproot.rs, bitcoin/src/blockdata/witness.rs
Add a function for creating the witness when doing a key path spend for a P2TR output.
This mirrors what we did for P2WPKH when adding `Witness::p2wpkh`.
Includes update to the taproot signing example to use the new constructor.
=> Add `Witness::p2tr_key_spend` function

bitcoin/examples/sighash.rs, bitcoin/src/blockdata/block.rs, bitcoin/src/consensus/encode.rs, bitcoin/src/consensus/serde.rs, bitcoin/src/p2p/message.rs, bitcoin/src/psbt/map/input.rs, bitcoin/src/psbt/serialize.rs, units/src/lib.rs
Done while working on #2368.  There are 5 left. Do we want to leave the MSRV ones in there?
```bash
bitcoin/src/blockdata/weight.rs:66:                 // TODO replace with panic!() when MSRV = 1.57+
bitcoin/src/consensus/serde.rs:101:    // TODO: statically prove impossible cases
bitcoin/src/pow.rs:445:            // TODO: Use `carrying_mul` when stabilized: https://github.com/rust-lang/rust/issues/85532
units/src/amount.rs:595:        // TODO replace whith unwrap() when available in const context.
units/src/amount.rs:599:                // TODO replace with panic!() when MSRV = 1.57+
```
=> Remove TODOs

bitcoin/src/p2p/message.rs
We are currently calling `From` to create the magic bytes, this is unnecessary since `Magic` provides consts.
=> Use `Magic::BITCOIN` in unit tests

units/src/amount.rs
Closes #2265 
Closes #2266 
Disclaimer: I did this in December and don't remember why I haven't pushed it. Maybe because it's somehow broken but I don't see how so please review a bit more carefully just in case.
=> Improve units

justfile
Improve the `justfile` by doing:
- Update linter toolchain
- Add `just sane` to run a minimal set of checks/tests that can be used pre-push but is not as slow as using `DO_FEATURE_MATRIX=true contrib/test.sh`.
=> Improve the `justfile`

units/src/amount.rs, units/src/lib.rs
Using the crate without allocation was previously disabled making the
crate empty without the feature. This chage makes it more fine-grained:
it only disables string and float conversions which use allocator. We
could later provide float conversions by using a sufficiently-long
`ArrayString`.
Note that this is API-breaking because we disallow calling the methods of the sealed `SerdeAmount` trait. However I think it should've been obvious that the thing is internal and calling them is not a great idea. (BTW I only learned this trick recently).
Closes #2389
=> Provide `Amount` & co in no-alloc

bitcoin/src/blockdata/script/mod.rs
The code originally used `if` and incorrectly casted the value into `usize` rather than `u64`. This change replaces the whole thing with `unsigned_abs`.
Closes #1247
=> Use `unsigned_abs` instead of manual code

githooks/pre-commit
We use the nightly toolchain to run `clippy` now, update the git pre-commit hook to mirror this.
=> Use nightly toolchain in pre-commit hook

justfile
`cargo --doc` works from the workspace root, no need to run the docs builds individually.
`cargo test` does not run docs tests if run from the workspace root as it does when run in a crate directory.
=> just: Reduce docs commands

bitcoin/src/blockdata/locktime/absolute.rs, bitcoin/src/parse.rs
The errors returned from various lock time functions had several issues. Among the obvious - `Error` being returned from all operations even when some of its variants were unreachable, there were subtle issues around error messages:
* `ParseIntError` didn't contain information whether the parsed object is `Height` or `Time`.
* Logically overflow and out-of-bounds should be the same thing but produced different error messages.
* Mentioning integers is too technical for a user, talking about upper and lower bound is easier to understand.
* When minus sign is present `std` reports it as invalid digit which is less helpful than saying negative numbers are not allowed.
It is also possible that `ParseIntError` will need to be removed from public API during crate smashing or stabilization, so …
=> Improve lock time errors

.github/workflows/rust.yml, units/src/amount.rs
Recently (in #2379) we patched the `ParseAmountError` but we don't check kani code on every pull request so we broke it.
Fix kani test to use the new `OutOfRangeError`.
EDIT: Attempt, as a separate patch, to add a job that runs on each PR to build the kani test code.
Close: #2424
=> Fix kani test

bitcoin/src/lib.rs, hashes/src/lib.rs, internals/src/lib.rs, io/Cargo.toml, io/src/lib.rs, units/src/lib.rs
Make the trait level attributes uniform across all released crates in the repo. Excludes things that are obviously not needed, eg, bench stuff if there is not bench code.
- Remove `uninhabited_references` - this is allow by default now.
- Remove `unconditional_recursion` and mark the single false positive we have with an `allow`.
Note, this does not add `missing_docs` to the `io` crate. There is an open PR at the moment to add that along with the required docs.
=> Make crate level attributes uniform

bitcoin/src/blockdata/transaction.rs, bitcoin/src/crypto/sighash.rs
Using `non_exhaustive` as well as a public inner field is incorrect, it prohibits users from creating or matching on the error and does not achieve forward comparability.
This was never right, we shouldn't have done it.
=> Remove non_exhaustive from struct errors with pub inner

units/src/amount.rs
Our Kani CI job is currently failing. See https://github.com/rust-bitcoin/rust-bitcoin/actions/runs/7770495422/job/21190756253
This fixes one of the issues; the other is that we're hitting a multiplication assertion in the test we added in https://github.com/rust-bitcoin/rust-bitcoin/pull/2393 which I'm unsure how to deal with.
For reference, testing this was a bit of a PITA. I needed to
```
cargo install kani-verifier
cargo kani
```
This will give you an error located in core/panic.rs or something with the description `This is a placeholder message; Kani doesn't support message formatted at runtime` which is not super helpful. To get the actual failure, you need to write
```
cargo kani --enable-unstable --concrete-playback=inplace
```
which will add a weird unit test which calls into …
=> kani: fix Amount overflow test

bitcoin/src/blockdata/transaction.rs
Printing the `Sequence` as a decimal is not super useful when debugging, print it in hex instead.
Using code:
let seq = Sequence::from_consensus(0xFFFFFFFF);
println!("sequence: {:?}", seq);
Before applying this patch we get:
sequence: Sequence(4294967295)
And after applying we get:
sequence: Sequence(0xffffffff)
=> Print hex in Debug for Sequence

bitcoin/src/pow.rs
Recently we added a kani test that doesn't work because of `debug_assert` calls in ops traits.
Instead of opening the can of worms that is correct panic behaviour in ops lets just remove the test.
=> Remove broken kani test

bitcoin/src/bip32.rs, bitcoin/src/crypto/key.rs, bitcoin/src/psbt/error.rs
For now I have tried to group those functions which can produce more than one error and changed the functions which were  generating single error from `Key::Error` to the respective error. Let me know if this needs to be changed.
Also in `psbt/error.rs` I have changed the `InvalidPublicKey(crate::crypto::key::Error)` to `InvalidPublicKey(crate::crypto::key::FromSliceError)`. What should be done here?
Changes -
- in `from_slice` changed the `error` to `FromSliceError`.
- in `verify` changed to `secp256k1::Error` as it can return only one error.
- in `from_str` changed to `FromSliceError`.
- in `CompressedPublicKey` changed `verify` from `Error` to `secp236k1::Error` as it only returns one error.
- introduces CompressedPublicKeyError
- Removes impl from `bip32.rs`
Potential fix #2291
=> Improve error handling in errors emmited by `keys`

io/CHANGELOG.md, io/src/error.rs, io/src/lib.rs
Do some cleanups to the new `io` crate.
- Make `Take::read_to_end` public
- Add CI script
- Add documentation
- Add changelog
=> io: Cleanup

bitcoin/src/bip152.rs, bitcoin/src/blockdata/fee_rate.rs, bitcoin/src/blockdata/weight.rs, bitcoin/src/pow.rs
Currently running `cargo test --release` blows up because of the tests that panic.  This PR adds a conditional check `debug_assertions` which causes those tests to not be run in release mode.  Besides fixing `cargo test --release` this PR sets the stage for a larger PR to test arithmetic tests that are `unchecked` (will overflow in release mode instead of panic) started here https://github.com/rust-bitcoin/rust-bitcoin/pull/2436.  Also I think we ought to add `cargo test --release` to CI.
=> Add conditional check for debug_assertions

units/src/amount.rs
Its useful to be able to do `let x = -btc_amount;`
Implement `core::ops::Neg for SignedAmount`, returning a `SignedAmount`.
Fix: #2470
=> units: Implement ops::Neg for SignedAmount

io/src/lib.rs, io/src/macros.rs
Remove the blanket impls of `Read`, `BufRead`, and `Write`. Replace them with just the impls required to get `rust-bitcoin` building.
Note, the `TcpStream` stuff is used in `examples/handshake.rs`.
Fix: #2432
=> io: Remove blanket trait impls

bitcoin/src/taproot/mod.rs
Submitting this to fix what I think is an API hole. Please correct me if I'm mistaken here and there is an easier way to do what I'm after.
From what I can tell of the existing 0.31.1 API, there doesn't seem to be any way for a consumer to build a taproot tree using `TaprootBuilder` and then simply output the resulting tap tree merkle root `TapNodeHash`. 
Instead, the API forces me to do `TaprootBuilder::finalize(secp_ctx, internal_key)` first to get a `TaprootSpendInfo`, and then call `TaprootSpendInfo::merkle_root()` to get the root `TapNodehash`. This requires ECC point addition/multiplication for the tweak operation (inside `TaprootBuilder::finalize`), so it is a lot less performant than the simple hashing operations needed to build a taproot tree.
Obviously if I want to spend the …
=> taproot: add TapNodeHash getter method on TapTree and NodeInfo

units/src/amount.rs
The checked variants have worse performance than the unchecked variants due to the additional branching operations.  To improve performance where overflow is either not possible or not a concern, unchecked variants of `Amount` and `SignedAmount` are introduced for addition, subtraction and multiplication.
Note, it seems the default behavior for the test framework is to panic on overflow, so I haven't figured out a good way to add tests for this.  Marking as a draft for now.
closes: https://github.com/rust-bitcoin/rust-bitcoin/issues/2434
=> Add unchecked variants to Amount and SignedAmount

CHANGELOG.md
In preparation for an initial release; add a changelog file. The version number is already set to `v0.1.0`.
=> Release tracking PR: `io v0.1.0`

Cargo-minimal.lock, Cargo-recent.lock, bitcoin/Cargo.toml, hashes/Cargo.toml, io/CHANGELOG.md, io/Cargo.toml
We attempted to release with the current 0.1.0 version forgetting that we had previously released an empty crate with that version to reserve the name on crates.io.
Bump the version to 0.1.1 and release the actual code.
=> io: Bump version to 0.1.1

Cargo-minimal.lock, Cargo-recent.lock, Cargo.toml, base58/Cargo.toml, base58/README.md, base58/contrib/test_vars.sh, base58/src/lib.rs, bitcoin/Cargo.toml, bitcoin/embedded/Cargo.toml, bitcoin/src/lib.rs
Add a new `base58check` crate to the workspace and move the `bitcoin::base58` module to it.
Done as part of crate smashing, specifically so that we can make `bip32` into a separate crate.
=> Add a new base58 crate

bitcoin/src/address/error.rs, bitcoin/src/address/mod.rs
This commit adds the `FromScriptError` struct to handle the errors while generating address from any script. It includes :
- Unrecognized script error.
- Witness Program error.
- Witness Version error.
=> Add the `FromScriptError` for handling errors in `address`

bitcoin/src/address/error.rs, bitcoin/src/address/mod.rs, bitcoin/src/bip32.rs, bitcoin/src/crypto/key.rs, bitcoin/src/lib.rs
We don't add any implementations to the `base58` types so we can just `pub extern` the crate instead of using a module and re-exporting.
=> base58: Use pub extern crate instead of module

bitcoin/src/address/error.rs, bitcoin/src/address/mod.rs
Replaces #2502 because there is going  to be way too much arguing on this to bother a newer contributor with.
This PR takes into consideration #2507 but does not improve the issue, it also does not make it worse. I propose to do this and then consider #2507 since this is a step forwards IMO.
Remove the `address::Error` because its not good. Add a `NetworkValidationError` and return it from `require_network` - leaving the door open for resolving Kix's issue in 2507.
=> Add `NetworkValidationError`

bitcoin/src/crypto/ecdsa.rs, bitcoin/src/crypto/key.rs
Done while working on other error code; two trivial cleanups.
This PR gives us a place to debate the current error `From` impl format. The canonical form is, as far as I understand:
```rust
impl From<FooError> for Error {
#[inline]
fn from(e: FooError) -> Self { Self::Foo(e) }
}
```
=> Trivial error cleanup

units/src/amount.rs
I noticed `uncheced_add` looked really bad with two spaces (my mistake).  Fixed some others as well.
=> Tidy description

bitcoin/src/p2p/address.rs
Only the first byte of a CJDNS address is 0xfc, the second byte should be ignored.
See https://github.com/hyperboria/peers for examples of CJDNS addresses.
=> Fix CJDNS marker byte check

.github/workflows/cron-daily-update-nightly.yml
Rename the bot's committer name to not have special characters, which causes some problem in tcharding's locale; also change the branch name to not overlap with the "weekly CI" job, since it's causing the two jobs to overwrite each others' PRs.
Was part of #2531 but pulled out here to be in a branch that isn't getting clobbered every 24 hours :).
=> tweak nightly CI update

internals/src/error/parse_error.rs
We can't link to `std::error::Error` in rustdoc because it breaks non-std builds. Just use backticks - this is not an optimal solution but I know no other.
I have no clue why this is showing up now.
=> Remove link to std from rustdoc

bitcoin/src/consensus/params.rs
Add consts to the `Params` type for the individual networks.
=> Add consts to Params for individual networks

bitcoin/src/blockdata/locktime/relative.rs, bitcoin/src/blockdata/transaction.rs
The `relative` module has a single general error type, we are moving away from this style to specific error types.
Split the `relative::Error` up into three error structs.
I forget the policy on public inner fields.
=> Split relative locktime error up

Cargo-minimal.lock, Cargo-recent.lock, base58/Cargo.toml, bitcoin/Cargo.toml, bitcoin/src/blockdata/transaction.rs, bitcoin/src/blockdata/witness.rs, bitcoin/src/consensus/serde.rs, bitcoin/src/crypto/key.rs, bitcoin/src/psbt/mod.rs, bitcoin/src/taproot/serialized_signature.rs, hashes/Cargo.toml, hashes/src/internal_macros.rs, hashes/src/lib.rs, hashes/src/sha256.rs, hashes/src/sha256d.rs, hashes/src/util.rs
Upgrade to use the newly released `hex` code.
- Patch 1: Does trivial preparatory cleanup
- Patch 2: Adds some unit tests to check we roundtrip hashes correctly (added because in the test PR I had the `Midstate` iml wrong and it was not being caught).
- Patch 3: Uses macro in place of `forward_hex` and `backward_hex` - needs concept review, I hacked this without understanding why the functions existed in the first place.
- Patch 4: Does the upgrade, I've attempted to make minimal changes, so there is room for a bunch of cleanups if/when this merges. 
- Patch 5: Adds a unit test to verify that we can close #2494
- Patch 6: Removes unnecessary feature gate from unit test.
=> Upgrade to `hex v0.2.0`

units/src/amount.rs
No clue how this got into master, I thought pinning nightly stopped things like this; found with `just sane`.
Clippy emits:
useless conversion to the same type: `amount::ParseAmountError`
As suggested, remove the useless conversion.
=> Remove useless convertion

Cargo-minimal.lock, Cargo-recent.lock, bitcoin/Cargo.toml
Upgrade to the most recent `bitcoinconsensus` version that excludes Taproot verification i.e., one version before latest.
=> Upgrade bitcoinconsenus

bitcoin/src/blockdata/script/witness_version.rs, bitcoin/src/pow.rs, hashes/src/lib.rs
In light of recent discussion go over the codebase and look for some places that the leaf errors are wrong. Does not do the whole code base, excludes `p2p` and a couple of other places.
=> Improve leaf errors

hashes/src/lib.rs, hashes/src/sha384.rs, hashes/src/sha512.rs
Based on #2473 as we need support for 48-byte arrays <-> hex conversions.
Closes #2483
=> Add support for SHA384

bitcoin/src/blockdata/transaction.rs, hashes/src/util.rs
This commit attempts to solve #2505  by ensuring that formatting is not forced using the `:#` in the hex macro code generating in macro rule `hex_fmt_impl` in the hashes/utils.rs file.
The write! macro forces all formatting to add the prefix `0x` by adding an alternate by (#) default 
```rust
impl<$($gen: $gent),*> $crate::_export::_core::fmt::Debug for $ty<$($gen),*> {
#[inline]
fn fmt(&self, f: &mut $crate::_export::_core::fmt::Formatter) -> $crate::_export::_core::fmt::Result {
write!(f, "{:#}", self) // <-- This is where the formatting is being forced.
}
}
```
By removing this formatting, the `:#` must be specified by the user in order for a prefix to be added.
```rust
let outpoint = bitcoin::OutPoint::default();
println!("{:?}", &outpoint);
println!("{:#?}", &outpoint); …
```
=> Removes txid prefix in transaction IDs

bitcoin/src/crypto/key.rs
This PR fixes a bug introduced by me in #2473, and uncovered by #2563 - amazing that it was found so quickly!
Constructing a pubkey using `PublicKey::from_slice` can fail for reasons other than just incorrect length - we should not be using `expect` but rather returning the error.
A purist might argue that we are now returning a nested error type with an unreachable variant:
`ParsePublicKeyError::Encoding(FromSliceError::InvalidLength)`
Is this acceptable or do we want to further improve this?
=> Return error when constructing pubkey from slice

contrib/run_task.sh
I believe there is currently a bug in the MemorySanitizer, when we pass various types across the FFI boundry MSAN gives a unititialized variable error:
- `usize` passed as `size_t` (cannot be uninitialized)
- byte slice passed as `const char *`
In order to let other work continue disable the MSAN job.
The issue is further described in #2579
=> CI: Disable MSAN job

units/src/amount.rs
It is common to display bitcoins using trailing zeros upto 8 decimals. This commit enforces:
- Displaying Amount in BTC with trailing zeroes by eight decimal places if a precision on the Amount is not specified.
- Displaying Amount in BTC upto the precision specified truncating the insignificant zeros.
- Displaying amount in BTC without any decimals if the remainder of the amount divided by the satoshis in 1 BTC is equal to zero using formula `satoshis.rem_euclid(Amount::ONE_BTC.to_sat()) != 0`
These are not breaking changes and all previous tests pass.
A testcase is added to for changes introduced.
Resolves: #2136
=> Enforce displaying Amount with trailing zeros

bitcoin/src/consensus/encode.rs, bitcoin/src/consensus/mod.rs, bitcoin/src/consensus/serde.rs
We have `serialize_hex` and `deserialize` but no `deserialize_hex`, add it.
Move the `IterReader` out of `consensus::serde` to the `consensus` module.
Add some additional logic to the `DecodeError`, I'm not sure why this wasn't there before?
Use the `HexSliceToBytesIter` by way of the `IterReader` to deserialize an arbitrary hex string. Add unit tests to check that we consume all bytes when deserializing a fixed size object (a transaction).
=> Add a `consensus::deserialize_hex` function

bitcoin/src/merkle_tree/block.rs
=> merkle_block: add resource limit check during deserialization

units/src/lib.rs, units/src/locktime/absolute.rs, units/src/test_macros.rs
Currently we are deriving the serde traits for the `absolute::{Height, Time}` types, this is incorrect because we maintain an invariant on the inner `u32` of both types that it is above or below the threshold.
Manually implement the serde traits and pass the deserialized `u32` to `from_consensus` to maintain the invariant.
Close: #2559
=> fix: Manually implement serde traits

bitcoin/src/address/mod.rs
As with the rest of the errors in `address::error` that are returned by a pubic function from the `address` module.
Note please, this PR just makes the `address/mod.rs` file uniform, debating the merit of the re-exports is out of scope.
=> Re-export `address::error::P2shError` from `address` module 

Cargo-minimal.lock, Cargo-recent.lock, Cargo.toml, base58/Cargo.toml, base58/README.md, bitcoin/Cargo.toml, bitcoin/embedded/Cargo.toml
The current name `base58check` is taken, as is `base58`. Use `base58ck` instead.
Add a brief section to the readme about the crate naming.
=> base58: Re-name crate to base58ck

fuzz/Cargo.toml
Using `path` instead of `version` makes the `fuzz` crate easier to maintain because we don't have to update the version number to do releases.
=> fuzz: Use path in manifest instead of version

CONTRIBUTING.md
Reviewers often find themselves linking to blog posts to encourage newer devs to improve their commit logs, we can save everyones time by putting the links in the contributing docs, then we can just point devs there.
=> Document how to write commits

bitcoin/src/blockdata/locktime/absolute.rs, bitcoin/src/blockdata/locktime/relative.rs, units/src/locktime/absolute.rs, units/src/locktime/relative.rs
While implementing https://github.com/rust-bitcoin/rust-miniscript/pull/654 I ran into a number of limitations of the `relative::LockTime` API. This fixes these by
* Copying a ton of functions from `absolute::LockTime` to `relative::LockTime`, adjusting comments and functionality accordingly.
* Adding conversion functions to/from `Sequence` numbers, as well as a method to check whether a locktime is satisfied by a given sequence number.
Fixes #2547
Fixes #2545 
Fixes #2540
=> improve relative locktime API

bitcoin/src/blockdata/script/borrowed.rs
Refactor `witness_version` and `is_witness_program`.
- Patch 2 adds a couple of preparatory unit tests.
- Patch 2 does the refactor
Fix: #2618
=> Call is_witness_program from witness_version

bitcoin/src/blockdata/script/borrowed.rs
When we renamed `dust_value` to `minimal_non_dust` we forgot to keep the original and deprecated it, doing so assists with the upgrade path.
Put back in deprecated `dust_value`, linking to the rename.
Renamed in #2255, found while testing upgrade of downstream software.
=> Put back in deprecated dust_value

base58/Cargo.toml, base58/src/error.rs, base58/src/lib.rs, bitcoin/src/address/error.rs, bitcoin/src/address/mod.rs, bitcoin/src/bip32.rs, bitcoin/src/crypto/key.rs, units/src/amount.rs
Improve the error code in the new `base58` crate.
=> Improve base58 crate

bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/taproot/merkle_branch.rs
We are gearing up for the 0.32.0 release; replace all instances of TBD with the version number of the upcoming release.
=> Replace TBD with 0.32.0

bitcoin/src/address/error.rs, bitcoin/src/address/mod.rs
As requested, return `ParseError` from `Address<NetworkUnchecked>::require_network`.
- Patch 1: Preparatory refactor
- Patch 2: Add the variant.
Replaces #2593.
Close: #2507
=> Add a validation variant to `ParseError`

base58/CHANGELOG.md
In preparation for release add a minimal changelog to the `base58ck` crate.
This crate is currently unreleased and has the version number correctly set to `v0.1.0` - as of today, the crate name `base58ck` is available on crates.io.
=> Release tracking PR: `base58ck v0.1.0`

Cargo-minimal.lock, Cargo-recent.lock, base58/Cargo.toml, bitcoin/Cargo.toml, contrib/run_task.sh, hashes/CHANGELOG.md, hashes/Cargo.toml
In preparation for release add a changlelog entry and bump the version.
Note the hashes 0.13.0 dependency stays in the dependency graph because of secp, we can update secp after releasing `hashes` then update the secp dependency in `rust-bitcoin` thereby removing the `hashes v0.13.0` dependency - phew.
Note we are right to release this immediately, the two open PRs (#2337 and #2541) that touch `hashes` only add a clippy attribute so can safely be ignored.
=> Release tracking PR: `hashes v0.14.0`

contrib/gen_label_config.sh, contrib/release.sh, contrib/run_task.sh, fuzz/cycle.sh, fuzz/fuzz.sh, fuzz/generate-files.sh
Add `euo pipefail` to all non-trial shell scripts, note if `x` is already set we maintain it.
=> Add set -euo pipefail

contrib/gen_label_config.sh
In #2635 we broke the Manage PR CI job but for some reason CI didn't run on that PR so we merged the breakage.
Fix the script by setting default variables when they are not set. Done with ChatGPT.
=> CI: Fix Manage PR job

Cargo-minimal.lock, Cargo-recent.lock, base58/Cargo.toml, bitcoin/Cargo.toml, contrib/run_task.sh, internals/CHANGELOG.md, internals/Cargo.toml, units/Cargo.toml
In preparation for release add a changelog and bump the version number.
Please note, the changelog is pretty terse.
=> internals: Release tracking PR `v0.3.0`

bitcoin/src/blockdata/locktime/absolute.rs, bitcoin/src/blockdata/locktime/relative.rs, bitcoin/src/lib.rs
TL;DR As we do for `absolute::LockTime` and for the same reasons; implement `ArbitraryOrd` for `relative::LockTime`.
locktimes do not have a semantic ordering if they differ (blocks, time) so we do not derive `Ord` however it is useful for downstream to be able to order structs that contain lock times. This is exactly what the `ArbitraryOrd` trait is for.
Fix: #2566
=> Implement ArbitraryOrd for relative::LockTime

bitcoin/src/blockdata/block.rs, bitcoin/src/consensus/params.rs, bitcoin/src/lib.rs, bitcoin/src/pow.rs, hashes/src/lib.rs, internals/src/lib.rs, io/src/lib.rs, units/src/lib.rs
When computing the maximum difficulty transition threshold we forgot to check that the returned `Target` is not bigger than the maximum. This value is network specific so keep the original logic but with `_unchecked` on the function name.
This was noted in the discussion on #2161
=> Add check to max difficulty transition threshold

bitcoin/CHANGELOG.md, bitcoin/Cargo.toml
We forgot to add a release commit to the backport #2614.
=> release 0.31.2

bitcoin/src/pow.rs, units/src/parse.rs
The `pow` types implement `fmt::LowerHex` but do not implement hex parsing.
Add inherent methods `from_hex` and `from_prefixed_hex` to the  `pow` types - as we did for locktime types.
=> Add hex parsing to `pow` types

justfile
Use the nightly version that we use in CI when running `just` commands that use the nightly toolchain.
=> just: Use pinned nightly

bitcoin/src/pow.rs
Follow up to #2514, improve docs in the `pow` module. Done as separate patches because there are 3 distinct improvements. The first two are trivial the last can be verified by running:
`RUSTDOCFLAGS="--cfg docsrs" cargo +nightly rustdoc --all-features -- -D rustdoc::broken-intra-doc-links`
=> Improve docs in pow module

units/CHANGELOG.md, units/src/lib.rs
In preparation for release do two things:
- Patch 1: Attempt to improve the re-exports and HTML docs
- Patch 2: Add an initial changelog file
Note the version number is set already and does not conflict with the current `v0.0.0` version: https://crates.io/crates/bitcoin-units
=> units: Release tracking PR: `0.1.0` - BOOM!

bitcoin/src/address/mod.rs, bitcoin/src/blockdata/constants.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/consensus/params.rs, bitcoin/src/lib.rs, bitcoin/src/network.rs, bitcoin/src/p2p/mod.rs
Minimize usage of the `Network` enum in the public API.
See #2225 for context, and https://github.com/rust-bitcoin/rust-bitcoin/pull/1291#discussion_r1492993788 for an interpretation of that long discussion.
Close: #2169
=> Reduce usage of `Network` in the public API

bitcoin/src/psbt/mod.rs
When signing a Taproot input (in a PSBT) using a key path spend we currently return the pubkey associated with key that signs. However it is common to think of the internal key as being the one that signs even though this is not technically true. We also have the internal key in the PSBT so matching against it is less surprising.
When using the `Psbt` type to sign a Taproot input using a key path spend return the internal key.
- Patch 1: Fix stale docs
- Patch 2: Remove unnecessary panic
- Patch 3: Change the key returned when signing Taproot input as key path spend
Done as part of #2557, this is the release blocking part.
=> psbt: Return internal key for key path spend

Cargo-minimal.lock, Cargo-recent.lock, base58/Cargo.toml, bitcoin/Cargo.toml, units/CHANGELOG.md, units/Cargo.toml
Fix a minor internal bug in error code in `units` and bump the version number so we can do a point release.
This can go in after the RC drops as part of the release candidate cycle if its easier - as long as its in and released before the finale `v0.32.0` release.
=> units: Release tracking PR: `0.1.1`

bitcoin/src/bip152.rs, bitcoin/src/consensus/encode.rs, io/src/lib.rs, units/src/locktime/absolute.rs, units/src/locktime/relative.rs
As `rustc 1.79.0-nightly (9d79cd5f7 2024-04-05)` is released which solves the issue mentioned , but the release has deperacted legacy numeric methods. 
Thus replaced `u16::max_value()` etc with `u32::MAX` & `core::u16` to directly `u16`.
fix #2639
=> Remove deprecated legacy numeric methods

.github/workflows/cron-daily-update-nightly.yml, bitcoin/tests/psbt-sign-taproot.rs
Fixes an issue with #2658 which accidentally disabled our nightly rustc update cronjob, and also fixes a small clippy lint.
After this, we should be able to get back onto the latest nightly :).
=> Minor fixes for latest rustc nightly

bitcoin/src/blockdata/script/borrowed.rs
The deprecation notice for `is_provably_unspendable` contains "is not very useful" which is a bit presumptuous to tell to users, it may very well be useful to them. Use the more helpful text that already exists in rustdoc on the function.
Function was deprecated in #2294
=> Improve deprecation notice

bitcoin/examples/taproot-psbt.rs, bitcoin/src/bip32.rs, bitcoin/tests/psbt-sign-taproot.rs
Recently in #2451 we disallowed bip32 derivation paths with the leading 'm' variable.
There is some confusion as to what exactly the bip specifies however Bitcoin Core RPC call `getaddressinfo` returns a derivation path with a leading "m/". This means we need to be able to parse it irrespective of what the bip says.
Be more liberal in what we accept as a derivation path, including both with and without the leading 'm/'.
Leave the full investigation of the bip to a later date.
Change back some of the test strings as makes sense and include test strings to showcase the full current behaviour.
This PR replaces #2674.
=> Allow m prefix in derivation paths

.github/workflows/rust.yml, units/src/amount.rs
Fix the current failing Kani job on todays PRs. 
FTR our daily `kani` job has been red for ages, perhaps since we created the `units` crate? But today the `--codege-only` job broke (on all PRs). `kani` released a new version 10 days ago, pinning to the previous version seems to resolve the issue. I raised a bug report but did not investigate further. 
- Patch 1: Remove redundant import
- Patch 2: Rename the tests
- Patch 3: Pin kani version
File bug report: https://github.com/model-checking/kani/issues/3142
PR is CI only, can go in with one ack.
(Patch 2 is the result of debugging the _real_ kani failure we have at the moment, I'll save the rant for the PR that fixes it.)
=> Fix kani codegen CI job

bitcoin/src/consensus/params.rs
We have started using `AsRef<Params>` in a few places as a function parameter. If a user of the library wishes to use these functions they need to create a type that can implement this trait. Because we use `non_exhaustive` on the `Params` struct it is not possible to just construct a `Params` type. This may be surprising for some folk.
Add module level docs to the `consensus::params` module with an example of how to create a type that can be used to describe a custom signet network. Use fields inspired by Mutiny Wallet's described usage.
Close: #2690
=> Add docs for custom signets

bitcoin/src/consensus/params.rs
This is a port of #2687 created using `git cherry-pick 6e84548b`.
------
I'm not sure why I haven't see this before during the whole test cycle but while running `cargo kani --only-codegen` we get a bunch of warnings of form:
warning: use of deprecated field `consensus::params::Params::pow_limit`
We deprecated the `pow_limit` field but still set it (obviously) in const structs - just shoosh the warning.
=> Allow deprecated Params field

bitcoin/examples/sign-tx-segwit-v0.rs
In the segwit signing example we are using the incorrect value when creating the signature - we should be using the utxo amount (input amount) not the spend amount (output spend amount).
Close: #2680
=> Fix example spend amount

CONTRIBUTING.md
Add a section on how we do backports and what the merge policy is.
Recently I backported a patch by pushing directly to the `0.32.x` release branch but this is not an optimal process because it leaves no history on github. Instead PR backports in like we do for patching `master` but allow one-ACK merging if the backport is a straight cherry pick of a patch from `master`.
=> Add backport section to contributing docs

bitcoin/src/consensus/params.rs, bitcoin/src/pow.rs
In preparation for release replace "TBD" with the next release version - `v0.32.0`.
=> Set release version in deprecated attribute

bitcoin/src/crypto/sighash.rs
If one writes signing data using one of the two
`*_encode_signing_data_to` functions then creating the message to sign is slightly nuanced and different for each of the functions. For Taproot one must use a specific tagged hash and for ECDSA one must use a sha256d hash.
Add documentation that explains the hashing requirements for each function.
Close: #2703
=> Document the *_encode_signing_data_to functions

.github/workflows/rust.yml
Version `0.49` of `kani` broke our daily CI job, there is now a new release out that fixes the issue.
Remove the explicit `kani` version so we pull the latest version.
=> CI: Run kani daily job with latest version

Cargo-minimal.lock, Cargo-recent.lock, bitcoin/CHANGELOG.md, bitcoin/Cargo.toml
In preparation for releasing `rust-bitcoin v0.32.0` update the changlelog to mirror the state after the rc pathches and bump the version.
Note, there is only one additional patch that effects users since rc1.
=> bitcoin: Release tracking PR: `v0.32.0`

hashes/src/lib.rs
Make the rustdoc imports in `hashes/src/lib.rs` more terse and also use as-underscore.
=> docs: Make rustdoc imports more terse

.github/workflows/manage-pr.yml
The `labeler` job has an input `sync-labels` (default `false`) that configures:
> Whether or not to remove labels when matching files are reverted or no
> longer changed by the PR
ref: https://github.com/actions/labeler
Currently we are using the default which means labels are not synced when a PR is modified.
Example
A PR initially touches the `hashes` and `bitcoin` crates and the labeler action adds `C-hashes` and `C-bitcoin`. Later, a force push removes the changes to `hashes`, the labeler will not remove the `C-hashes` label. Now the labels are incorrect.
Note on `pull_request_target`:
We use `on: pull_request_target`, this means the action is run in the target branch not in the PR branch. So the changes in this patch are not run when this PR is pushed up. Therefore we cannot test …
=> CI: Enable sync-labels for labeler

Cargo-minimal.lock, Cargo-recent.lock, bitcoin/Cargo.toml
Upgrade to the latest release of `base64`. Version 0.22.0 came out about 2 months ago.
No code changes needed and from the release notes it doesn't look like anything that will effect us too much.
https://github.com/marshallpierce/rust-base64/blob/master/RELEASE-NOTES.md
The `base64` crate is part of our public API so this is a breaking change.
=> bitcoin: Upgrade base64 dependency

bitcoin/src/address/mod.rs, bitcoin/src/crypto/sighash.rs
As part of the ongoing effort to improve `hashes`; stop using slicing of hash types and use `as_byte_array()` to get an array reference instead. This gives us more flexability to modify the `hashes` module.
=> bitcoin: Stop slicing hashes

base58/README.md, bitcoin/tests/data/README.md, bitcoin/tests/data/serde/README.md, fuzz/README.md, hashes/README.md, hashes/extended_tests/schemars/README.md, internals/README.md, io/README.md, logo/README.md, units/README.md
according to the github flavor
(https://github.github.com/gfm/)
=> chore: format and standardize all markdowns files

.github/workflows/rust.yml, base58/contrib/test_vars.sh, bitcoin/contrib/test_vars.sh, contrib/run_task.sh, hashes/contrib/test_vars.sh, hashes/src/sha256.rs, internals/contrib/test_vars.sh, io/contrib/test_vars.sh, units/contrib/test_vars.sh
Recently we re-wrote CI to increase VM level parallelism, in hindsite this has proved to be not that great because:
- It resulted in approx 180 jobs
- We are on free tier so only get 20 jobs (VMs) at a time so its slow to run
- The UI is annoying to dig through the long job list to find failures
Have another go at organising the jobs with the main aim of shortening total run time and making it easier to quickly see fails.
Re-write the `run_task.sh` script, notable moving manifest handling to the workflow. Also don't bother testing with beta toolchain.
The diff is hard to read for `rust.yml`, I tried splitting out a bunch of separate patches but it resulted in the same thing (because there are so many identical lines in the yaml file). I suggest just looking at the yaml file and not the …
=> CI: Re-write `run_task.sh`

bitcoin/src/bip32.rs
In #2258 we attempted to add back in deprecated BIP-32 types - but we spelled the identifier incorrectly. The patch was then backported to the `0.31.x` branch in December but was only just noticed now.
Fix typo in deprecated type from `Extendend` -> `Extended`.
=> Fix typo in deprecated type

bitcoin/examples/ecdsa-psbt.rs
"Creater" is a typo, it should be "Creator" role.
Ref: https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki?plain=1#L660
=> fix(typo): examples/ecdsa-psbt.rs

justfile
We already have a `just` command to check the formatting, add one to run the formatter. Use the more terse `just fmt` although the difference from `just format` is not super obvious it is documented in the default output of `just`.
With this applied we have
```bash
$ just
Available recipes:
build             # Cargo build everything.
check             # Cargo check everything.
default
fmt               # Run cargo fmt
format            # Check the formatting
lint              # Lint everything.
sane              # Quick and dirty CI useful for pre-push checks.
update-lock-files # Update the recent and minimal lock files.
```
=> just: Add just fmt

hashes/src/hash160.rs, hashes/src/internal_macros.rs, hashes/src/ripemd160.rs, hashes/src/sha1.rs, hashes/src/sha256.rs, hashes/src/sha256d.rs, hashes/src/sha256t.rs, hashes/src/sha384.rs, hashes/src/sha512.rs, hashes/src/sha512_256.rs, hashes/src/siphash24.rs
Depending on things being in scope for macros to use is bad form, using the fully qualified path is the correct way.
Do not import `str` instead use the fully qualified path to the `core` re-export.
Use fully qualified path instead.
=> hashes: Do not import str

bitcoin/Cargo.toml, bitcoin/src/lib.rs
When we did the `rust-bitcoin v0.30.0` release we had not yet released the `hex-conservative` crate so we forced users to reach into `bitcoin-internals` to get at hex stuff e.g., `DisplayHex`.
To ease the upgrade path for any remaining upgraders add a dependency on the now released `hex-conservative` crate and re-export it from the crate root as `hex` (bit late I know, sorry).
Idea came from: https://github.com/rust-bitcoin/rust-bitcoin/issues/2482#issuecomment-1947075032
We should have done this soon as we released `hex-conservative`.
=> bitcoin: Depend on and export hex-conservative

.github/workflows/cron-semi-weekly-update-nightly.yml
Updating the nightly toolchain every day is overly arduous, lets just update it twice a week.
=> CI: Update nightly semi-weekly

bitcoin/src/bip32.rs, bitcoin/src/psbt/map/input.rs, hashes/src/hmac.rs, hashes/src/lib.rs
Currently we require indexing trait bounds as well as `Borrow` on the `Hash` trait. We also already implement `AsRef`.
It was observed that `Borrow<[u8]>` does not best describe what we want from the `Hash` trait implementor but rather `AsRef<[u8]>` does.
Remove all the inexing trait bounds. Remove the `borrow::Borrow<[u8]>` trait bound. Add a `convert::AsRef<[u8]>` trait bound.
This leaves the `Borrow<[u8]>` implementation for hashes created with `hash_newtype`, I'm not sure if this should be removed or not.
=> hashes: Modify trait bounds

bitcoin/src/crypto/sighash.rs, bitcoin/src/taproot/mod.rs, hashes/CHANGELOG.md, hashes/src/sha256t.rs
First three patches are preparation, improvements to the units tests in `sha256t`.
From the final patch:
Displaying backward is an anomaly of Bitcoin Core's early days and the
double SHA256 hash type. We should not let this unfortunate beast leak
out into other places.
Default to displaying forward when creating a new tagged hash and remove
all the explicit attributes from `bitcoin` that just clutter the code.
This is an API break and may quietly break some users downstream - eventually we should stop doing that sort of thing.
=> Default to forward for tagged hashes

base58/src/lib.rs
In a downstream app I've seen printing a descriptor is not a cheap operation, analyzing the flamegraph it seems base58 encoding of the xpub is the culprit
This PR adds benches for the `encode_check` function, and add the changes gaining more boost, which is also good cause it removes code.
Other attempts didn't provide enough benefit for inclusion but I report them here for knowledge.
```
running 2 tests
test benches::bench_encode_check_50   ... bench:       8,760 ns/iter (+/- 113)
test benches::bench_encode_check_xpub ... bench:      19,982 ns/iter (+/- 109)
running 2 tests
test benches::bench_encode_check_50   ... bench:       7,935 ns/iter (+/- 129)
test benches::bench_encode_check_xpub ... bench:      18,076 ns/iter (+/- 184)
test benches::bench_encode_check_50   ... bench: …
```
=> Bench `base58` encoding and remove `SmallVec` to improve perf

.github/workflows/shellcheck.yml, base58/contrib/test_vars.sh, bitcoin/contrib/test_vars.sh, bitcoin/embedded/scripts/env.sh, contrib/crates.sh, contrib/gen_label_config.sh, contrib/release.sh, contrib/test_vars.sh, fuzz/cycle.sh, fuzz/fuzz.sh, fuzz/generate-files.sh, githooks/pre-commit, hashes/contrib/test_vars.sh, hashes/embedded/scripts/env.sh, internals/contrib/test_vars.sh, io/contrib/test_vars.sh, units/contrib/test_vars.sh
Closes #2739.
I am proposing that we use this GitHub Shellcheck action:
[`ludeeus/action-shellcheck`](https://github.com/ludeeus/action-shellcheck)
since it has most stars (and eyes on it).
I also did all fixes that I could find with
```bash
shellcheck **/*.sh
```
If I've missed any please let me know.
=> ci: shellcheck checks

bitcoin/src/psbt/map/input.rs
Partially addresses #2751 by adding examples (testable code) for `PsbtSighashType`
=> psbt: documentation examples for PsbtSighashType

bitcoin/examples/bip32.rs, bitcoin/examples/ecdsa-psbt.rs, bitcoin/examples/taproot-psbt.rs, bitcoin/src/bip32.rs, bitcoin/src/psbt/mod.rs, bitcoin/tests/bip_174.rs
We discussed in #2752 that `derive_priv` never fails.
This PR addresses that issue.
=> bip32: derive_xpriv should not return a Result

Cargo-minimal.lock, Cargo-recent.lock, bitcoin/Cargo.toml
During the recent release cycle we left `bitcoin` on the last rc version.
Set the version number to `v0.33.0-unreleased` to make it obvious what it is.
Close: #2724
=> bitcoin: Set version number

bitcoin/src/bip152.rs, bitcoin/src/blockdata/constants.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/merkle_tree/mod.rs, bitcoin/src/p2p/message_blockdata.rs
Currently we use the `Hash` trait in a bunch of places to call `all_zeros`. We are attempting to improve the `hashes` API and this usage is both unnecessary and also hindering that effort.
Use the concrete type (e.g. `BlockHash`) instead of calling through the trait method.
=> Use concrete type for all_zeros call

bitcoin/src/taproot/mod.rs
By convention rustdoc headers should not include a colon.
Removed colon from rustdoc headers.
=> Fix rustdoc header format

bitcoin/src/p2p/address.rs, bitcoin/src/p2p/message.rs, bitcoin/src/p2p/message_blockdata.rs, bitcoin/src/p2p/message_network.rs
Clean up the test imports in the `p2p` module:
- Use `use super::*` as is conventional.
- Use `sha256d::Hash` as is conventional.
Refactor, no logic changes.
=> p2p: Cleanup test imports

.github/workflows/rust.yml, CONTRIBUTING.md, api/README.md, api/base58/default-features.txt, api/base58/no-features.txt, api/bitcoin/all-features.txt, api/bitcoin/default-features.txt, api/bitcoin/no-features.txt, api/hashes/all-features.txt, api/hashes/alloc-only.txt, api/hashes/no-features.txt, api/io/all-features.txt, api/io/alloc-only.txt, api/io/no-features.txt, api/units/all-features.txt, api/units/alloc-only.txt, api/units/no-features.txt, contrib/check-for-api-changes.sh, justfile
This PR is #1880 re-opened.
Add a script that checks the public API of `hashes` and `bitcoin`. Document how to use it during development. Call it in CI. Do not add it to githooks because the githooks because its expected to be run per PR not per commit.
Includes a `just` command to run the script: `just check-api`
This PR imposes workflow changes.
Explicitly: all PRs that change the public API of `bitcoin`, `base58`, `hashes`, `io`, or `units` must contain changes to the api text files. 
Suggestion: We add the patch updating api text files as a separate patch at the end of each PR so we can haggle over it separately from the actual code changes.
Fix: #1875
=> Check for changes to the public API

CONTRIBUTING.md
We have started introducing `error` sub-modules for modules that have a lot of error code. This is mainly a code organisation thing.
When importing a function it is annoying to have to go to another module to get the returned error type. Furthermore it leaks our module structure and introduces a maintenance burden because for modules that do not [yet] have an `error` sub-module the error types are in a different place to modules that do have an `error` sub-module.
Furthermore, if function users have to go to the `error` sub-module to read docs etc. they are bombarded with all the hider errors as well (see definitions below).
We can solve both problems by re-exporting all regular errors, making the `error` sub-module public (for niche users), and not re-exporting hider errors.
I believe …
=> policy: Introduce error type re-export policy

CONTRIBUTING.md
An error enum type should not use an `Error` prefix for its variants, mention as such in the policy docs.
=> policy: Mention format of error variants

hashes/src/hash160.rs, hashes/src/hmac.rs, hashes/src/impls.rs, hashes/src/ripemd160.rs, hashes/src/serde_macros.rs, hashes/src/sha1.rs, hashes/src/sha256.rs, hashes/src/sha256d.rs, hashes/src/sha256t.rs, hashes/src/sha512.rs, hashes/src/siphash24.rs
Some of the headers had a //! spare line at the end but most didn't. They have all been removed in hashes/src/ to make the files consistent
=> Removed spare line at end of headers in hashes crate

units/src/amount.rs
Some of the headers had a //! at the end but most didn't. They have all been removed in units/src/ to make the files consistent
=> Removed spare line at end of headers in units crate

bitcoin/src/pow.rs
Add documentation to the `CompactTarget` type explaining the nuance surrounding order/equality.
Close: #2110
=> Document CompactTarget order/equality

hashes/tests/regression.rs
We have regression tests spread out throughout the `hashes` module but they are not labelled as such. To give us more confidence and help debug when patching the `hashes` crate we can add a bunch of regression tests in a single place.
Add a module that does a single regression test for each type, simply hash some arbitrary data and check the hex display against a hard coded hex string.
=> hashes: Add regression tests

CONTRIBUTING.md
For the last few months it has only been myself and tcharding working on this project actively. Prior to that we had Kixunil as well, which allowed us to move forward requiring two ACKs on every PR (though it put a minimum 24-hour delay on everything since we are pairwise 8 hours separated from each other in timezones).
The other listed maintainers, especially Sanket and Matt, are intermittently available, which is awesome but insufficient to get large refactors or long-term work through.
We have increasingly depended on the "one-ACK carveout", an ever-increasing list of exceptions to our two-ACK rule. Most silly, one exception is that if something stays open for two weeks, we don't need the second ACK. So the result is a "one ACK plus 2 weeks" policy which is grating and demoralizing. …
=> reduce two-ACK requirement to one-ACK requirement

bitcoin/examples/sighash.rs, bitcoin/src/blockdata/transaction.rs, internals/src/error/parse_error.rs
In a few cases a function header documents the parameters of the following function under the heading "Arguments", this has been changed to "Parameters".  
Since the description is at the level of the function definition and not where it is being called parameters seems the more accurate term.
=> Header change from arguments to parameters

api/bitcoin/all-features.txt, api/bitcoin/default-features.txt, api/bitcoin/no-features.txt, bitcoin/src/address/mod.rs
We have getters for the pubkey hash and script hash but we forgot one for the witness program - add it.
Done as part of fixing #2784, this is an additive change and is expected to be backported to `v0.32`
=> Enable getting the witness program from an address

Cargo-minimal.lock, Cargo-recent.lock, bitcoin/Cargo.toml, bitcoin/src/blockdata/constants.rs, bitcoin/src/blockdata/transaction.rs
Currently we have a dependency on `hex_lit` and it is used in exactly one place outside of test code, if we instead use a hardcoded array instead we can move the `hex_lit` dependency to `dev-dependencies`.
Hard code the genesis block script bytes as an array of hex digits, link to the blockstream explorer for those interested and comment the bytes liberally since it took me a while to work out what they were.
Move the `hex_lit` dependency and update the lock files.
=> Hard code genesis script bytes instead of hex

bitcoin/src/bip158.rs, bitcoin/src/blockdata/locktime/absolute.rs, bitcoin/src/blockdata/script/owned.rs, bitcoin/src/blockdata/script/push_bytes.rs, bitcoin/src/consensus/validation.rs, bitcoin/src/crypto/key.rs, bitcoin/src/merkle_tree/block.rs, bitcoin/src/merkle_tree/mod.rs, bitcoin/src/psbt/mod.rs, bitcoin/src/psbt/raw.rs, bitcoin/src/taproot/merkle_branch.rs, bitcoin/src/taproot/mod.rs, bitcoin/src/taproot/serialized_signature.rs, internals/src/macros.rs, units/src/amount.rs, units/src/locktime/absolute.rs
The subheadings in the rustdocs have been standardized according to [./CONTRIBUTING.md](https://github.com/rust-bitcoin/rust-bitcoin/blob/master/CONTRIBUTING.md):
```rust
impl FooBar {
/// Constructs a `FooBar` from a [`Baz`].
///
/// # Errors
///
/// Returns an error if `Baz` is not ...
///
/// # Panics
///
/// If the `Baz`, converted to a `usize`, is out of bounds.
pub fn from_baz(baz: Baz) -> Result<Self, Error> {
...
}
}
```
=> Standardize rustdoc subheadings

api/bitcoin/all-features.txt, api/bitcoin/default-features.txt, api/bitcoin/no-features.txt, bitcoin/src/address/mod.rs
We previously made this function Private and added a comment that doing so was somehow better to remove the footgun of hashing the wrong length script. However in hindsight this was a bad idea and users want the functionality.
Make the `Address:p2sh_from_hash` public and document it as we do for `Address::p2sh`.
This is an additive change and is expected to be backported to `v0.32`, as part of the fix to #2784. Please note it introduces the footgun that is described in the function rustdoc. This will be improved as a separate patch and added to the current release.
=> Make `Address:p2sh_from_hash` public

bitcoin/src/address/mod.rs
We previously made this function Private and added a comment that doing so was somehow better to remove the footgun of hashing the wrong length script. However in hindsight this was a bad idea and users want the functionality.
Make the `Address:p2sh_from_hash` public and document it as we do for `Address::p2sh`.
This is a backport of patch 1 from #2795, patch 2 is an update to api files which don't exist on the `\0.32.x` release branch.
=> Make Address:p2sh_from_hash public

api/bitcoin/all-features.txt, api/bitcoin/default-features.txt, api/bitcoin/no-features.txt, bitcoin/src/address/mod.rs
In the 0.32.0 release we removed the `address::Payload` struct because it was deemed an implementation detail. As a byproduct of doing so we made it impossible for users to match on an enum and get the address payload (or data).
- Add a public `AddressData` enum that holds an address' encoded data.
- Add a conversion function to `Address` that returns the data enum.
This patch is additive and is expected to be backported and release as a `0.32` point release.
=> Add an `AddressData` type

bitcoin/examples/ecdsa-psbt.rs, bitcoin/src/address/mod.rs, bitcoin/src/crypto/key.rs, bitcoin/src/crypto/sighash.rs, bitcoin/src/merkle_tree/block.rs, bitcoin/tests/bip_174.rs
Rust nightly as of 2024-05-27 has a new lint which detects list items which are continued by a non-indented line. Markdown treats these as single list items, which they sometimes are, but sometimes we intended them to be on a separate line.
Also changes the docs for `UntweakedKeypair::tap_tweak` because the existing ones were overly technical and out-of-date.
Also fixes a minor "no need to create a vec then dereference it" lint in the examples.
=> doc: fix "lazy line continuations" in markdown

units/src/lib.rs
First patch is the meat and potatoes, second one is just a trivial refactor to the same code, done separately so as to make the changes in the first patch more clear.
From patch 1
```
units: Fix error re-exports
Currently we re-export two error types at the crate root, this is
surprising because:
- Why not none or all the rest?
- Why these two?
Observe that the `ParseIntError` is special in that it is used by
other modules so its good to have at the crate root (other errors are
expected to be used with a module prefix eg, `amount::ParseError`).
There is no obvious reason why `ParseAmountError` is re-exported.
Comment and doc inline the `ParesIntError`, remove the re-export of
the `ParseAmountError`.
```
=> Fix units public re-exports

bitcoin/src/bip152.rs, bitcoin/src/bip32.rs, bitcoin/src/blockdata/constants.rs, bitcoin/src/internal_macros.rs, bitcoin/src/psbt/serialize.rs, internals/src/macros.rs
Currently we have two macros used when creating array wrapper types, one is in `internals` and the other in `bitcoin::internal_macros`. It is not immediately obvious what is what and why there are two.
Improve the macros by:
- Move the inherent functions to `impl_array_newtype`
- Use `*_byte_array` for the names instead of `*_bytes`
- Re-name the other macro to match what it now does
=> Improve array macros

bitcoin/src/psbt/macros.rs, bitcoin/src/psbt/map/input.rs
We have a private function that makes use of the `Hash` trait to generically hash map entries. This usage makes patching the `hashes` module difficult. We can achieve the same thing by using a macro and passing in the concrete type.
This is an internal change, no effect on logic or public API.
=> psbt: Use macro to hash instead of relying on `Hash` trait

Cargo-minimal.lock, Cargo-recent.lock, bitcoin/CHANGELOG.md, bitcoin/Cargo.toml
In preparation for doing a point release add a changelog entry and bump the version.
Note that the changelog risks being lost because this patch is going to go in via the `0.32.x` branch and will not exist on master.
Close: #2784
=> Release tracking PR: `v0.32.1`

api/bitcoin/all-features.txt, api/bitcoin/default-features.txt, api/bitcoin/no-features.txt, api/units/all-features.txt, api/units/alloc-only.txt, bitcoin/src/consensus/params.rs, bitcoin/src/lib.rs, bitcoin/src/p2p/message.rs, bitcoin/src/p2p/message_filter.rs, units/src/block.rs, units/src/lib.rs
Add two simple integer wrapper types for abstracting over block height (from genesis block) and block interval.
This does not include hex because block height is typically written in decimal.
These types are very thin wrappers, their usecase is to assist in code readability instead of enforcing any logic.
Based on discussion in #2533
Close: #2532
=> units: Add BlockHeight and BlockInterval types

base58/contrib/test_vars.sh, bitcoin/contrib/test_vars.sh, contrib/crates.sh, contrib/test_vars.sh, hashes/contrib/test_vars.sh, internals/contrib/test_vars.sh, io/contrib/test_vars.sh, units/contrib/test_vars.sh
Some of our CI shell scripts are meant only to be sourced and not run directly however they include an initial shebang line, implying that they should be run.
Remove the shebang line from `crates.sh` and the various `test_vars.sh` scripts. Add a `shellcheck` directive to inhibit the no-shebang warning.
Please note, the issue mentions the following in the discussion thread and it is _not_ implemented here. 
> It would be good also to find a way to detect whether the script is being run directly, and to print an error message. I'm sure this is a common thing and we can find a stackexchange post telling us how to do it.
I don't see an immediate way to do this because CI is run using `run_task.sh` which is not in this repo. And since one can still run a script without the shebang (by doing …
=> CI: Remove shebang from non-executable scripts

api/hashes/all-features.txt, api/hashes/alloc-only.txt, api/hashes/no-features.txt, hashes/src/hkdf.rs, hashes/src/lib.rs
rustaceanrob and I have been working on a Rust-based BIP324 implementation over at https://github.com/rustaceanrob/bip324. We have been attempting to keep the code pretty clean in hopes of a future "soft landing" in rust-bitcoin. I figured the HKDF implementation is a small, self-contained chunk that might allow us to learn the ropes here first.
There was a mention in the [discussion thread on BIP324](https://github.com/rust-bitcoin/rust-bitcoin/discussions/1691) that the hashes interface may be changing in the near future. I am not sure the effect that would have on this implementation, but happy to work through any issues.
Closes #2551
=> Add HKDF to bitcoin_hashes

CONTRIBUTING.md
Done to try to further help new contributors and save maintainer time.
Add an example of using `just check-api` and an example `git` command for devs to create the api patch now required for all changes to the public API.
=> docs: Add more info to the update api files section

api/bitcoin/all-features.txt, api/bitcoin/default-features.txt, api/bitcoin/no-features.txt, bitcoin/src/blockdata/block.rs, bitcoin/src/blockdata/script/instruction.rs, bitcoin/src/blockdata/script/mod.rs, bitcoin/src/blockdata/script/push_bytes.rs, bitcoin/src/blockdata/script/tests.rs, fuzz/fuzz_targets/bitcoin/deserialize_script.rs
* Moved `read_scriptint` method to `Push_Bytes` struct
* Created `Instruction::read_int` method which acts as a wrappper around this  function.
Done as part of #1547
=> Move `read_scriptint` to `PushBytes` & create `read_int` function

fuzz/fuzz_targets/bitcoin/deserialize_block.rs
This PR adds more coverage for the `deserialize_block` target. First, it serializes the block and compares with the data provided and then call some block functions to ensure they run without any issue.
=> fuzz: add more coverage for `deserialize_block`

bitcoin/Cargo.toml, bitcoin/examples/ecdsa-psbt-simple.rs, bitcoin/examples/taproot-psbt-simple.rs
Adds examples on how to create,
update, sign, and finalize PSBTs version 0
that deals with multiple inputs.
Examples are SegWit V0 and Taproot.
=> bitcoin: Add PSBT multiple inputs examples

bitcoin/src/pow.rs
This is a backport of the 2 patches in #2834, grammar mistakes in the commit log and all.
Note, one difference, we call `hex_u128` instead of `hex_u128_unchecked` because the unchecked version does not exist in `v0.32`.
=> pow: Fix off-by-one error

bitcoin/src/p2p/mod.rs
Contrary to the documentation and the method name, this function does an XOR operation, if there are no flags in `self`, flags from `other` are added.
What should happen to the core::ops::BitXor{,Assign} implementations? I did not touch them because it would break current API usage and would require a minor version bump (on 0.x.y versions).
=> fix ServiceFlags::remove

bitcoin/src/p2p/mod.rs
Removes possible errors when a network is added to the enum (expressed with the comment `// Note: new network entries must explicitly be matched in 'try_from' below.`)
=> generate Network <-> Magic From and TryFrom with a macro

api/bitcoin/all-features.txt, api/bitcoin/default-features.txt, bitcoin/src/p2p/message.rs
I'd like to take out the `payload` of `RawNetworkMessage` and then send it to the actual network message processor, but find there is no way to do it. This commit adds such an API to expose all the inner parts (UPD: so that I don't have to do an unnecessary clone to obtain the owned value of `payload`).
=> Add API for extracting the inner payload of `RawNetworkMessage`

hashes/src/internal_macros.rs, hashes/src/sha256t.rs
The `hash_trait_impls` macro currently adds an impl block for `Hash` - this is not what the docs say since and `impl Hash` block is nothing to do with traits.
Move the impl block and add a duplicate of the functions to the `sha256t::Hash` type.
This is a refactor, no API or logic changes. Note that wrapper types currently do net get these functions - that will be discussed/implemented separately.
=> hashes: Move non-trait functions

bitcoin/src/taproot/mod.rs, hashes/src/sha256t.rs
The `sha256t_hash_newtype` macro is hard to reason about because we allow repetition so which tag goes with which type is slightly obscure.
Remove repetition and call the macro three times.
Internal change in `bitcoin`, API change in `hashes`.
Fix #2811
=> Remove repetition from sha256t_hash_newtype macro

Cargo-minimal.lock, Cargo-recent.lock, bitcoin/Cargo.toml, bitcoin/src/consensus/validation.rs
Updated bitcoinconsensus version to 0.106.0+26.0 in bitcoin/Cargo.toml
The new version supports taproot and has a new parameter for `spent_outputs` in the `verify()` and `verify_with_flags()` functions.
The validation module was changed to keep the existing functionality by adding `None` as the `spent_outputs` and the flag `VERIFY_ALL_PRE_TAPROOT`.
This method does not add taproot features to the verify functions.
=> Update bitcoinconsensus version to 0.106.0+26

bitcoin/Cargo.toml
The "rand-std" feature enables "std" but we use it in examples still. FTR I added this a while ago thinking the explicitness was clearer but in hindsight I think that was wrong and that it makes usage of our features _less_ clear.
No logic changes.
(Pulled out of #2756.)
=> bitcoin: Remove "std" feature from examples

internals/src/error/parse_error.rs
In #2521 I removed the link from `std::error::Error` with the claim that it broke no-std builds. However there are a ton of other places where we link to `std::` types.
I have no idea where the breakage was, I assume it existed and I was sane at the time, CI on this patch will tell us.
Close: #2571
=> Link to std::error::Error

api/bitcoin/all-features.txt, api/bitcoin/default-features.txt, api/bitcoin/no-features.txt, bitcoin/embedded/src/main.rs, bitcoin/examples/bip32.rs, bitcoin/examples/ecdsa-psbt-simple.rs, bitcoin/examples/ecdsa-psbt.rs, bitcoin/examples/sign-tx-segwit-v0.rs, bitcoin/examples/taproot-psbt.rs, bitcoin/src/address/mod.rs, bitcoin/src/blockdata/script/builder.rs, bitcoin/src/blockdata/script/owned.rs, bitcoin/src/blockdata/script/tests.rs, bitcoin/src/blockdata/script/witness_program.rs, bitcoin/src/blockdata/witness.rs, bitcoin/src/crypto/key.rs, bitcoin/src/psbt/mod.rs, bitcoin/src/sign_message.rs
We should pass `Copy` types by value not by reference. Pass the key types by value.
This is patch 1 from #2404
=> Pass keys by value

.github/workflows/README.md, .github/workflows/rust.yml, hashes/contrib/extra_tests.sh
We have a mechanism to run additional custom tests by way of the `extra_tests.sh` script in each crate.
Remove the CI job and run the schemars test using `extra_tests.sh`. This patch changes the test coverage because currently the schemars test is only run with a stable toolchain but with this patch applied it runs with stable, MSRV, and nightly.
Fix: #2787
=> Run schemars test from extra_tests

api/bitcoin/all-features.txt, api/bitcoin/default-features.txt, api/bitcoin/no-features.txt, bitcoin/src/address/error.rs, bitcoin/src/address/mod.rs, bitcoin/src/blockdata/constants.rs, bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/script/mod.rs, bitcoin/src/blockdata/script/tests.rs, bitcoin/src/blockdata/script/witness_program.rs, bitcoin/src/psbt/mod.rs
There are two limits that the Bitcoin network enforces in regard to hashing scripts
- For P2SH the redeem script must be less than 520 bytes (bip 16)
- For P2WSH the witness script must be less than 10,000 bytes (bip 141)
Currently we are only enforcing the p2sh limit when creating an address with `Address::p2sh`.
There are various ways to create addresses from script hashes and if users manually hash a script then use the `ScriptHash` (or `WScritpHash`) our APIs assume the script that was hashed is valid. This means there is the potential for users to get burned by creating addresses that cannot be spent, something we would like to avoid.
- Add fallible constructors to `ScriptHash` and `WScriptHash`
- Add `TryFrom` impls as well to both types
- Remove the `From` impls
Close: #2794
=> Enforce script size limit when hashing scripts

bitcoin/src/blockdata/block.rs, bitcoin/src/blockdata/script/instruction.rs, fuzz/fuzz_targets/bitcoin/deserialize_script.rs
Fixes #2849 
There were a few other usages of PushBytes::read_scriptint(_) in the tests such as [this](https://github.com/rust-bitcoin/rust-bitcoin/blob/406e3486ab4c0bee059ed6442dde0cd60ee4277f/bitcoin/src/blockdata/script/tests.rs#L315), but they couldn't be updated as cleanly as the changes in this PR. I wasn't sure if the intention of this issue was to fix those as well, but I can update this PR if needed
=> Update PushBytes::read_scriptint(x) to x.read_scriptint()

.github/workflows/README.md
Added the new Shellcheck CI job to `./github/workflows/README.md` to fix: #2767
=> Updated workflows/README.md to mention new Shellcheck job

.github/workflows/rust.yml
So that updates don't break our CI setup used a specific version of `cargo-public-api`, this means we will have to update it manually periodically though.
For now, since the latest release just broke us, use the release from a month ago.
=> CI: Pin cargo-public-api version

api/bitcoin/all-features.txt, api/bitcoin/default-features.txt, api/bitcoin/no-features.txt, bitcoin/examples/ecdsa-psbt-simple.rs, bitcoin/examples/ecdsa-psbt.rs, bitcoin/examples/sighash.rs, bitcoin/examples/sign-tx-segwit-v0.rs, bitcoin/src/address/mod.rs, bitcoin/src/bip158.rs, bitcoin/src/blockdata/block.rs, bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/script/owned.rs, bitcoin/src/blockdata/script/tests.rs, bitcoin/src/psbt/mod.rs
We should pass `Copy` types by value not by reference. Pass the hash types by value.
Second step in the pass-copy-types-by-value work, pulled out of #2404.
=> Pass hash types by value

api/bitcoin/all-features.txt, api/bitcoin/default-features.txt, api/bitcoin/no-features.txt, bitcoin/src/taproot/mod.rs
This variant is unused, remove it.
Done as part of #2883.
=> Remove `InvalidInternalKey` variant from `TaprootBuilderError`

CONTRIBUTING.md
Clarifies the wildcard policy in `Contributing.md`. 
Relates to #2875.
=> Contributing: add instructions on wildcards in import statements

bitcoin/src/blockdata/script/push_bytes.rs
The `push_bytes` module has a `private` module that exists solely to protect the invariant on the `PushBytes` inner byte slice. There is a `PushBytes` impl block outside the private module for functions that can not and do not violate the length invariant.
Recently we move the `read_scriptint` method to be on the `PushBytes` but we put it inside the `private` module, since the method only reads off of the slice it cannot invalidate the invariant and does not need to be inside the `private` module.
Move the `read_scriptint` method outside of the `private` module to keep that module as small as possible, helping with its stated aim of being the only place that requires auditing.
Patch 2 is whitespace only.
=> Move `PushBytes::read_scriptint` outside of the `private` module

api/bitcoin/all-features.txt, api/bitcoin/default-features.txt, api/bitcoin/no-features.txt, api/hashes/all-features.txt, api/hashes/alloc-only.txt, api/hashes/no-features.txt, bitcoin/src/blockdata/block.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/crypto/sighash.rs, bitcoin/src/merkle_tree/block.rs, bitcoin/src/p2p/message_blockdata.rs, bitcoin/src/pow.rs, bitcoin/src/psbt/serialize.rs, hashes/src/hmac.rs, hashes/src/internal_macros.rs, hashes/src/lib.rs, hashes/src/sha256t.rs, hashes/src/util.rs
I think these changes are both uncontroversial but they have fairly large diffs so I am PRing them together before making more invasive changes.
=> hashes: remove `all_zeros` and constify constructors

api/bitcoin/all-features.txt, api/bitcoin/default-features.txt, api/bitcoin/no-features.txt, api/hashes/all-features.txt, api/hashes/alloc-only.txt, api/hashes/no-features.txt, bitcoin/src/bip152.rs, bitcoin/src/bip158.rs, bitcoin/src/bip32.rs, bitcoin/src/blockdata/block.rs, bitcoin/src/blockdata/script/mod.rs, bitcoin/src/blockdata/script/tests.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/consensus/encode.rs, bitcoin/src/crypto/key.rs, bitcoin/src/crypto/sighash.rs, bitcoin/src/hash_types.rs, bitcoin/src/psbt/macros.rs, bitcoin/src/psbt/mod.rs, hashes/embedded/src/main.rs, hashes/src/hash160.rs, hashes/src/hkdf.rs, hashes/src/hmac.rs, hashes/src/impls.rs, hashes/src/internal_macros.rs, hashes/src/lib.rs, hashes/src/sha256.rs, hashes/src/sha256t.rs, hashes/src/util.rs, hashes/tests/regression.rs
I'm not thrilled with these names. Personally I would prefer having `ByteArrayWrapper` (for non-general hashes) and `Hash` (for general hashes). But using `Hash` and `GeneralHash` greatly minimizes the diff because most of our use of the `Hash` trait was only for non-general stuff.
Maybe that tradeoff will change as we move stuff to inherents? I hope to do that in the next PR (or maybe the one after that, since I still have some "drop `GeneralHash` work to do for tagged hashes). And after that the hashing API should be "clean" enough that we can figure out HashEngine, possibly even folding GeneralHash into it. But that's the part of #2770 that we didn't finish nailing down so I'm not sure.
But other than naming, I like this PR. I think, if you approve of this PR except the naming, it …
=> hashes: split `Hash` into `GeneralHash` and `Hash`

api/units/all-features.txt, api/units/alloc-only.txt, api/units/no-features.txt, units/src/amount.rs
The denomination `MilliSatoshi` has been removed from `Amount`. 
`NanoBitcoin` and `PicoBitcoin` have also been removed since they are also less than 1 satoshi and the same reason for removing milliSatoshi in Issue #2820 should apply to them.
The second patch fixes the way the denominations with various combinations of upper and lower case are handled when converted from a string.
Close: #2820
=> Remove `Denomination::MilliSatoshi`

api/hashes/all-features.txt, api/hashes/alloc-only.txt, api/hashes/no-features.txt, hashes/src/lib.rs
In an effort to make the `hashes` crate more ergonomic to use add a bunch of type alias' to the crate root.
We intentionally do not rename the `foo::Hash` types so that uses have a choice of either using the module path to differentiate or to use the alias.
Update the crate level docs to use the alias' because they are more terse with no loss of clarity.
=> hashes: Add type alias'

bitcoin/src/address/mod.rs
Remove the unnecessary braces to eliminate the rust-analyzer warning,.
This is trivial, but it causes rust-analyzer to constantly flag a warning, and a simple change removes it.  
I also added a comma at the end, again trivial but as someone who speaks Rust as a second language I have read this is what is normally done and I only mention it to get feedback on if that is correct or not.
=> Remove unnecessary braces

bitcoin/src/bip158.rs, bitcoin/src/network.rs, bitcoin/src/pow.rs, bitcoin/src/psbt/mod.rs, io/src/error.rs
I started taking a look at #2869 and looked for everything that was implementing the `Display` trait:
```rust
impl fmt::Display for _
``` 
but found some places where the imports weren't consistent:
```rust
impl Display for _
``` 
There were only a few instances of the latter, so I went ahead and cleaned those up before starting #2869 
I started pulling this thread when I saw the same thing was happening for `fmt::Debug` and `fmt::Formatter` so I updated the rest of the `use core::fmt::*` statements with a few exceptions:
- No updates to `use core::fmt::*` if it was being called from within a function since I felt like the function scope was small enough to not cause confusion 
- No updates to `use core::fmt::{self, Write as _};`
=>  Make 'use core::fmt' calls consistent

fuzz/fuzz.sh
Currently the `fuzz.sh` script fails with "unbound variable" if called without any arguments, this has gone undetected since we added `set -euox pipefail` because in CI we always call it with an argument.
Use chatGPT to fix the bug.
Fix: #2924
=> Fix fuzz script

api/bitcoin/all-features.txt, api/bitcoin/default-features.txt, api/bitcoin/no-features.txt, bitcoin/src/taproot/merkle_branch.rs, bitcoin/src/taproot/mod.rs
Currently there are a couple of errors in the `taproot` module that are too general, resulting in functions that return a general error type when a specific one would do.
Split two errors out and use them for for enum variants and function returns as possible.
Done as part of #2883
=> taproot: Split errors up

api/bitcoin/all-features.txt, api/bitcoin/default-features.txt, api/bitcoin/no-features.txt, bitcoin/examples/ecdsa-psbt-simple.rs, bitcoin/examples/sighash.rs, bitcoin/examples/sign-tx-segwit-v0.rs, bitcoin/src/blockdata/witness.rs, bitcoin/src/crypto/key.rs, bitcoin/src/taproot/serialized_signature.rs
We should pass `Copy` types by value not by reference.
Currently this is not done in secp, but lets do it here in bitcoin.
Pass by value:
- `SerializedSignature`
- bitcoin sigs
- secp sigs
- secp `Message`
This is a continuation of the work to split up #2404 into manageable PRs.
=> Pass sigs and associated types by value

api/bitcoin/all-features.txt, api/bitcoin/default-features.txt, api/bitcoin/no-features.txt, bitcoin/src/bip32.rs
ChildNumber already has a `From<u32>` impl, but converting `&[u32]` to a `DerivationPath` was still difficult.
=> bip32: add From<&'a [u32]> for DerivationPath

api/bitcoin/all-features.txt, api/bitcoin/default-features.txt, api/bitcoin/no-features.txt, bitcoin/src/address/mod.rs, bitcoin/src/blockdata/script/witness_version.rs
We have a single usage of the `bech32` crate inside the `blockdata` module, to convert a `WitnessVersion` to a `Fe32`. We then have a single call site where we use the conversion in the `address` module.
This code was written without thinking to hard about the introduced dependency on `bech32`, in hindsite it shouldn't have been added.
In preparation for splitting a bunch of code in `blockdata` out into the `primitives` crate remove the `bech32` stuff from the `witness_version` module.
=> Remove `bech32` dependency from `blockdata`

bitcoin/src/blockdata/witness.rs
The `Witness` type is a reasonable complex data structure, make an effort to clarify its structure in the docs on the private fields.
Private docs only.
(Original idea pulled out of #2133.)
=> Improve docs on private `Witness` fields

Cargo-minimal.lock, Cargo-recent.lock, Cargo.toml, addresses/CHANGELOG.md, addresses/Cargo.toml, addresses/README.md, addresses/contrib/test_vars.sh, addresses/src/lib.rs
We intend on splitting the address types and logic out into a separate crate. In preparation for doing so, and so that we can grab the name on crates.io, add an empty crate `bitcoin-addresses`.
Tie it in to the CI infrastructure excluding the `check-api` infrastructure because that is in flux.
=> Create empty `bitcoin-addresses` crate

Cargo-minimal.lock, Cargo-recent.lock, units/CHANGELOG.md, units/Cargo.toml
Backport the fix in #2942 in preparation for release of `units v0.1.1` (and yank of `v0.1.1`).
=> Release tracking PR: `units v0.1.2`

bitcoin/CHANGELOG.md, bitcoin/examples/taproot-psbt.rs, bitcoin/src/address/mod.rs, bitcoin/src/blockdata/block.rs, bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/script/owned.rs, bitcoin/src/blockdata/script/witness_program.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/crypto/key.rs, bitcoin/src/crypto/sighash.rs, bitcoin/src/crypto/taproot.rs, bitcoin/src/merkle_tree/block.rs, bitcoin/src/merkle_tree/mod.rs, bitcoin/src/psbt/error.rs, bitcoin/src/psbt/map/input.rs, bitcoin/src/psbt/mod.rs, bitcoin/src/psbt/serialize.rs, bitcoin/src/taproot/merkle_branch.rs, bitcoin/src/taproot/mod.rs
Taproot, Merkle and Huffman are proper nouns and should be capitalized in strings and docs.
These have been capitalized everywhere.
All cases of `taproot`/`taptree`/`tap tree` in docs and strings have been changed to be `Taproot tree` or ```[`TapTree`]``` as appropriate.
All cases of `tree` have been changed to lower cases, except where it is in title case.
Error messages in `Taproot` have been changed to start with a lowercase character, except when it is a proper noun, and not end with a period.
Close: #2913
=> Capitalize proper nouns

units/Cargo.toml
In a2b019f82 it was claimed that losing the input string without alloc is a bug. It is not, because allowing no-alloc is desired and there's no way to have the input string otherwise so we just accept it'll be missing and modify the messages accordingly. The commit that forced alloc was also horribly misleading since it kept the `alloc` feature but it makes this one easier.
Note that input string is still present by default in all configurations except for no-alloc.
I think we should also backport this and release fixed `units` because of the misleading `alloc` feature in them. Although it's not urgent. The only crate I know of that is kinda broken by it is `ln_types` which is already broken by depending on old `bitcoin`.
=> Revert "bug fix" (actually a bug) from #2655

README.md
The file mentioned in the README for running MSRV no longer exists
closes https://github.com/rust-bitcoin/rust-bitcoin/issues/2934
=> Update README instructions for running MSRV

units/src/amount.rs
Displaying with minimal number of zeros is the default in Rust and we want to follow it. This was originally implemented in #716 but #2604 reversed it claiming this is common, however it broke people who rely on minimal display (e.g. BIP21) without fixing the root cause of #2136.
This reverts commit d887423efcdad8db4c60ffe61f53d2356c82c87c adds a test to prevent this change and also fixes the problem with `{:0.8}` not working.
Closes #2136
Closes #2948
Can we backport this one too?
=> Fix `Amount` decimals handling

Cargo-minimal.lock, Cargo-recent.lock, Cargo.toml, primitives/CHANGELOG.md, primitives/Cargo.toml, primitives/README.md, primitives/contrib/test_vars.sh, primitives/src/lib.rs
Introduce an empty `bitcoin-primitives` crate.
We were give the name on crates.io and previously a version `v0.1.16-alpha` was released so we use `v0.100.0`.
Does not include adding api files since that whole thing is in flux. This is an even smaller step than #2908 that does not include dependencies.
=> Introduce empty primitives crate

bitcoin/src/bip158.rs
Currently we copy data into a new buffer before passing it into the hasher, we can just hash the data directly.
Internal change only, no external change.
Fix: #2917
=> bip158: Hash data instead of copying first

units/src/weight.rs
Weight type implicitly includes witness scale factor
closes https://github.com/rust-bitcoin/rust-bitcoin/issues/2963
=> Remove nonsense method

justfile
Adds `just docsrs` which takes [variadic arguments](https://just.systems/man/en/chapter_41.html?highlight=zero%20or#recipe-parameters) (zero or more after the command).
Kixunil this allows for `just docsrs` and `just docsrs --open`.
Closes #2965.
Using the command from `rust-bitcoin-maintainer-tools`: https://github.com/rust-bitcoin/rust-bitcoin-maintainer-tools/blob/3494ceec521cbc2cbe7e4b0d3fb9219a2164f57d/ci/run_task.sh#L277
=> just: add just docsrs

bitcoin/Cargo.toml, bitcoin/src/lib.rs
Update stale crate level docs in `bitcoin`. Done as two separate patches so the last one is trivial to review, whitespace only.
=> bitcoin: Update crate level docs

bitcoin/src/p2p/message_blockdata.rs
One item in the match statement was missing the `ref` keyword.  This has been added.
=> Add missing `ref` keyword in `p2p`

units/src/amount.rs, units/src/block.rs, units/src/fee_rate.rs, units/src/locktime/absolute.rs, units/src/locktime/relative.rs, units/src/parse.rs, units/src/weight.rs
The rustdocs in the `units` crate has been reviewed and improved.
Some of the links were missing backticks, these have been added.
Some grammatical changes have been made to improve the documentation.
The use of links was inconsistent and has been changed to have links everywhere that seemed appropriate.
A couple of error headings were added and a description as to why a capital M is not accepted in the denomination for MegaSatoshi or MegaBitcoin.
=> Fix rustdocs in `units` crate

.github/workflows/rust.yml, .github/workflows/semver-checks.yml
This is necessary because it needs to run only on pull_request, and not on push events.
Closes #2968.
=> ci: move semver-checks to its own job

bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/script/builder.rs, bitcoin/src/blockdata/script/instruction.rs, bitcoin/src/blockdata/script/owned.rs, bitcoin/src/blockdata/script/witness_program.rs
In the `script` module we currently import `script` types using the fully qualified path, as recently discussed code is easier to maintain if we use `super` when `super != crate`.
Internal change only, no external changes.
=> Use super for imports in script module

Cargo-minimal.lock, Cargo-recent.lock, bitcoin/Cargo.toml, bitcoin/embedded/Cargo.toml, bitcoin/src/blockdata/mod.rs, primitives/Cargo.toml, primitives/src/lib.rs, primitives/src/opcodes.rs
Move the `opcodes` module to the new `primitives` crate. This is pretty straight forward, some things to note:
- Are we ok with the public wildcard re-export from `blockdata`? I think so because the whole `blockdata` module should, IMO, be deleted after everything in it is moved to `primitives`.
- `decode_pushnum` becomes public.
=> Move opcodes to `primitives`

bitcoin/src/address/mod.rs, bitcoin/src/crypto/sighash.rs, hashes/src/hash160.rs, hashes/src/impls.rs, hashes/src/ripemd160.rs, hashes/src/sha1.rs, hashes/src/sha256.rs, hashes/src/sha256d.rs, hashes/src/sha384.rs, hashes/src/sha512.rs, hashes/src/sha512_256.rs
Currently we are using a type alias for a few of the hash engines.
Type alias' allow for potential mixing of types, a struct can better serve our users with not much additional complexity or maintenance burden.
- As preparation add const constructors where possible to hash engines (excl. `HmacEngine`).
- Add a `sha256d::HashEngine` struct
- Add a `hash160::HashEngine` struct
If this goes in we can improve the `sha256t::HashEngine` in a similar manner.
=> Add additional `HashEngine` types

internals/Cargo.toml
During review of #2889 it was noted that we don't need to enable the `derive` feature of `serde` in the `test-serde` feature.
Do not enable `derive` in the `test-serde` feature.
=> internals: Remove derive from test-serde

units/src/lib.rs, units/src/locktime/absolute.rs
The private prelude module has been removed from the units crate and instead imports are stated in full when needed.  As discussed in #2926.
=> Remove private prelude module from `units` crate

base58/src/lib.rs
Most base58 strings in Bitcoin are somewhat short. There was previously an "optimization" putting part of the input on stack which was removed in #2759 because it actually made the code slower. This appears to be mostly because of branches caused by using `iter::Chain`.
Manually splitting the iterations into two helped bring the performance close to what #2759 achieved but that still wasn't worth it. But given that we know the input length in many cases (it's just a slice) we can determine whether it'll fit a buffer upfront and then just call different functions which don't have the branches in loops. To avoid having two functions this uses generics instead. Further, we increase the buffer length to 128 and use `ArrayVec` from `internals` which internally avoids initializing the buffer …
=> Optimize base58 on small inputs

.github/workflows/semver-checks.yml, CONTRIBUTING.md, contrib/check-semver.sh
Crates missing:
- `bitcoin_hashes`
- `bitcoin-units`
- `bitcoin-io`
Also adds:
1. corrects a small error in the CONTRIBUTING.md; and
2. runs on `stable` since `cargo-semver-checks` do not support `nightly` (rustdocs JSON format breaks almost daily)
Closes #2999.
=> ci: add `all-features` semver-checks and run on rust `stable`

addresses/contrib/test_vars.sh, addresses/src/lib.rs, base58/Cargo.toml, base58/contrib/test_vars.sh, base58/src/lib.rs, bitcoin/Cargo.toml, primitives/Cargo.toml, primitives/contrib/test_vars.sh, primitives/src/lib.rs
Eventually we would like all our crates other than `bitcoin` to be able to be used without an allocator. Currently, and during crate smashing, this is not that useful because so much of the code comes from `bitcoin` and relies on the availability of an allocator.
As an initial step, add the `alloc` feature to `addresses` , `base58`, and `primitives`.
In order to to keep `--no-default-features` builds working make the crates empty if the `alloc` feature is not enabled. This is a suboptimal solution because the error messages users will get when they forget to enable `alloc` will be confusing (eg something like primitives does not contain Transaction). However our CI script (`run_task.sh`) expects `--no-default-features` to build cleanly (as do I).
=> Add alloc feature to `base58`, `addresses`, and `primitives`

bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/witness.rs
Bundled these because they are very similar. Got a bunch of larger changes coming up based on these. I've been using these for a while for TXHASH work.
=> Some additional inspectors on Script and Witness

hashes/src/hash160.rs, hashes/src/internal_macros.rs, hashes/src/ripemd160.rs, hashes/src/sha1.rs, hashes/src/sha256d.rs, hashes/src/sha384.rs, hashes/src/sha512.rs, hashes/src/sha512_256.rs, hashes/src/siphash24.rs
Depending on types being in scope when calling macros is bad practice but we have mistakenly done so in `internal_macros` when using the `FromSliceError`.
Use `$crate::FromSliceError` in the macro and remove import statements.
=> hashes: Use `$crate` in macro

bitcoin/src/blockdata/locktime/relative.rs
Update the variable names for `h`/`height` to `required_height` in instances where it was being used to create another height or used comparatively i.e. `required_height + 1` or `required_height < height`
Resolves #2553
=> Specify required_height in variable name when comparing to other height

bitcoin/examples/ecdsa-psbt-simple.rs, bitcoin/examples/ecdsa-psbt.rs, bitcoin/examples/sighash.rs, bitcoin/examples/sign-tx-segwit-v0.rs, bitcoin/examples/sign-tx-taproot.rs, bitcoin/examples/taproot-psbt-simple.rs, bitcoin/examples/taproot-psbt.rs, bitcoin/src/address/mod.rs, bitcoin/src/address/script_pubkey.rs, bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/script/builder.rs, bitcoin/src/blockdata/script/owned.rs, bitcoin/src/blockdata/script/tests.rs, bitcoin/src/crypto/sighash.rs, bitcoin/src/internal_macros.rs, bitcoin/src/psbt/mod.rs
Done in preparation for moving the script types to `primitives`.
Add three public traits, one each for the three `script` types: `Builder`, `ScriptBuf`, and `Script`.
=> Add scriptPubkey extension traits to script types

hashes/src/hash160.rs, hashes/src/hmac.rs, hashes/src/lib.rs, hashes/src/ripemd160.rs, hashes/src/sha1.rs, hashes/src/sha256.rs, hashes/src/sha256d.rs, hashes/src/sha384.rs, hashes/src/sha512.rs, hashes/src/sha512_256.rs, hashes/src/siphash24.rs
Midstates are not generic objects; they don't have universal cryptographic properties and if you are using them you should be using a specific midstate type. Therefore it shouldn't be part of `GeneralHash` or `HashEngine`. Furthermore, in practice it seems like `sha2` midstates are the only ones that anybody uses, at least in bitcoin.
Remove the midstate stuff from the `GeneralHash` and `HashEngine` traits. Keep the `midstate` functionality as inherent functions if it is used internally. Keep the functionality on `sha256` as inherent public functions.
Done as a first step towards #2918.
=> Remove midstate from the `GeneralHash` and `HashEngine` traits

bitcoin/src/psbt/raw.rs
The documentation for `Key` was a bit confusing since `<key> := <keylen> <keytype> <keydata>` was right above the `key` field, when in reality the `key` field represents the key data. Moving the documentation that describes a `Key` as a whole to the struct itself and specifying that `key` represents key data will hopefully clear things up a bit
=> Update Key documentation

hashes/src/lib.rs, hashes/src/util.rs
In an effort to shrink the API of `hashes` remove the `from_raw_hash`, `to_raw_hash`, and `as_raw_hash` inherent functions from types created with the `hash_newtype` macro.
There are a few reasons why this is favourable:
- It allows stable crates to use the macro and not expose unstable `hashes` types in their API.
- It makes types created with the macro less "general" in the sense that its more obscure to just hash any data into them. This allows us to write cleaner APIs in `rust-bitcoin`.
=> Remove to/from/as_raw_hash functions

bitcoin/src/psbt/macros.rs, bitcoin/src/psbt/map/global.rs, bitcoin/src/psbt/mod.rs, bitcoin/src/psbt/raw.rs, bitcoin/tests/serde.rs
Follow-up change from [a comment](https://github.com/rust-bitcoin/rust-bitcoin/pull/3022#issuecomment-2226166039) in #3022 that updates the `key` field in the PSBT `Key` to `key_data`, which more closely follows the doc
=> Rename key field in Key to key_data

units/src/weight.rs
It's common in other modules for the tests to be at the end of the file. Moving the tests to the bottom helps the code base uniformity.
Pulled from stale PR 2215
=> Move impl above tests

units/src/weight.rs
The type created after assignment is a Weight type.  Using a var name vb which is short for virtual byte is incorrect.
Pulled this out of stale PR 2215
=> Rename variable assignment

bitcoin/build.rs, bitcoin/examples/ecdsa-psbt-simple.rs, bitcoin/examples/handshake.rs, bitcoin/examples/sighash.rs, bitcoin/examples/taproot-psbt-simple.rs, bitcoin/examples/taproot-psbt.rs, bitcoin/src/bip152.rs, bitcoin/src/blockdata/block.rs, bitcoin/src/blockdata/constants.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/blockdata/witness.rs, bitcoin/src/consensus/mod.rs, bitcoin/src/crypto/taproot.rs, bitcoin/src/merkle_tree/block.rs, bitcoin/src/merkle_tree/mod.rs, bitcoin/src/p2p/address.rs, bitcoin/src/p2p/message.rs, bitcoin/src/pow.rs, bitcoin/src/psbt/map/global.rs, bitcoin/src/psbt/mod.rs, bitcoin/src/psbt/serialize.rs, hashes/src/util.rs, internals/build.rs, units/src/amount.rs
Error messages should be lower case, except for proper nouns and variable names.  These have all been changed.
~~They should also state what went wrong.  Some expect error messages were positive, giving the correct behaviour or correct input.  These have been changed so that they are now negative, i.e. saying what went wrong.~~
EDIT: After further discussion it was decided not to change the expect messages.
=> Fix error messages

primitives/src/locktime/relative.rs
Following up on [a comment](https://github.com/rust-bitcoin/rust-bitcoin/pull/3026#discussion_r1676744486) from #3026 and removing an unused variable from the LockTime example
=> Remove unused variable from LockTime example

.github/workflows/semver-checks-pr-label.yml, .github/workflows/semver-checks.yml
Ok now I think I've nailed this! 🚀 
Closes #3018.
This PR fix the permissions by adding a secondary job, `semver-checks-pr-label`, that runs only if the `semver-checks` completes and does not fail, i.e. we have either Semver API breaks.
This is a secure job according to internal discussions and https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run
We split the semver checks into the actual check and labeling. This is due to the fact that we were having several permission issues and the original implementation was insecure. Also it is currently failing on several PRs.
1. `semver-checks.yml`: checks for API semver breaks. Upon finding API semver-checks, it creates a file named `semver-break` that has the PR number inside. If this file is present we …
=> ci: fix semver-checks master

units/src/locktime/relative.rs
Adding some test cases for `from_seconds_floor` and one more for `from_seconds_ceil`
=> Add more unit test coverage for relative LockTime

bitcoin/src/blockdata/transaction.rs
We do not have a policy to re-export things from other modules just because they are in the public API - I don't see any other reason to re-export this error, users should go to the `validation` module directly to get the error type.
Raising this trivial change as a separate PR so that we can really pin down our re-export policy. Please review the policy implications as well as the code change.
Note please that this change was introduced in 7d695f6b4 by me, and buried in a PR that did not mention the change. This was wrong, as in the code change was wrong and also the patching method was wrong.
=> Remove public error re-export

bitcoin/src/address/script_pubkey.rs, bitcoin/src/internal_macros.rs
During #2955 I was lazy and did not think through why the macro didn't handle function parameters on individual lines, I just manually re-formatted all function calls onto a single LOC. This was a bit slack of me.
- Patch 1: Fix the macro.
- Patch 2: Revert the manual formatting.
=> Improve `define_extension_trait` 

bitcoin/src/blockdata/script/witness_version.rs, units/src/lib.rs
In d242125 I claimed that `ParseIntError` was somehow special, I no longer thing this is the case. As we pin down the re-export policy (for errors and other types) it is hard if we have one non-typical re-export.
We have https://github.com/rust-bitcoin/rust-bitcoin/issues/3068 to discuss the policy, for now just remove the unusual re-export.
=> Remove re-export of `ParseIntError`

CONTRIBUTING.md
- adds an item that all error messages
should be lower case, except for proper nouns and variable names.
- adds a section on expect messages,
following discussion in #3019 and #3053.
Closes #3053.
=> CONTRIBUTING: error/expect messages

bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/script/mod.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/blockdata/witness.rs
Following up on the [comment](https://github.com/rust-bitcoin/rust-bitcoin/pull/2646#discussion_r1548848611) in #2646 the rustdocs formatting was fixed in `blockdata`.
=> Fix rustdocs in `blockdata`

primitives/src/lib.rs, primitives/src/locktime/absolute.rs, primitives/src/locktime/relative.rs, units/src/lib.rs
Re-export `units` types by doing:
- Patch 1: Remove the public re-export of `serde` so that it does not shadow the private one in `primitives`
- Patch2: Fix formatting (remove attribute and format)
- Patch 3 and 4: Use wildcard re-exports
=> `primitives`: Re-export `units` types

bitcoin/src/blockdata/transaction.rs, bitcoin/src/consensus/mod.rs, bitcoin/src/consensus_validation.rs, bitcoin/src/lib.rs
The `consensus` module is currently doing two things, validation and encoding. These two things are orthogonal.
Move the `consensus::validation` module to `consensus_validation`. Remove the function re-exports from `consensus`.
This was originally discussed here: https://github.com/rust-bitcoin/rust-bitcoin/issues/2779
=> Move `validation` module to `consensus_validation`

githooks/post-merge, githooks/pre-commit
Referring back to [this post](https://github.com/rust-bitcoin/rust-bitcoin/pull/2980#discussion_r1673140172) in #2980, there was discussion that a post-merge githook should be added to check if the user's copied githooks have changed.
In order to distinguish between a githook that a user installed themselves and a rust-bitcoin githook, I chose to add a tag at the beginning of the project's hooks.
=> githooks: Added post-merge githook to check if hooks changed

bitcoin/src/address/script_pubkey.rs, bitcoin/src/blockdata/script/mod.rs, bitcoin/src/blockdata/script/owned.rs, bitcoin/src/crypto/key.rs
We would like to move the `Script` type to `primitives` without moving any key stuff, including pubkey hashes. We may later, before releasing `primitives`, move the `WPubkeyHash` at which time this patch can be reverted or re-implemented on `ScriptBuf`.
The `ScriptBuf::p2wpkh_script_code` function does not take `self` as a parameter but it does return `Self` - this can trivially be made into a standalone function.
Make `ScriptBuf::p2wpkh_script_code` a standalone function.
=> Make `ScriptBuf::p2wpkh_script_code` stand alone

.gitattributes
This slightly improves the diffs shown by git commands.
=> Set `diff=rust` for `*.rs` in `.gitattributes`

bitcoin/src/blockdata/script/tests.rs, bitcoin/src/consensus_validation.rs
Add an extension trait for the validation logic in preparation for moving the `Script` type to `primitives`.
=> Add validation extension to script

hashes/src/hkdf.rs, hashes/src/hmac.rs, hashes/src/impls.rs, hashes/src/lib.rs, hashes/src/siphash24.rs, hashes/tests/regression.rs
Backstory for this patch is in #3084, and this might be enough to close that issue, but I think some follow up work might be required.
I took Kixunil's advice and pushed up the `Default` bound on `HashEngine` all the way to the default methods themselves on the `GeneralHash` trait. I initially placed the bound just on the assocated type `Engine` of `GeneralHash`, which is a tad cleaner and keeps the bound from "leaking" downstream into things like `Hmac` and `Hkdf` implementations. However, that restricts `GeneralHash` implementations to just unkeyed hash functions and I believe there will be value in having `Poly1305` and `SipHash24` still leverage the interface. I struggled a bit on the best spots to put these bounds (even found the syntax a little jarring at times, I found …
=> Push up the Default bound on HashEngine in order to better support keyed hash functions

hashes/src/siphash24.rs
=> Rename Siphash::as_u64 to Siphash::to_u64

bitcoin/src/bip158.rs
Patch 1 is a typo fix, other two are cast improvements. Done as part of #2941.
Leaves a cast to `u64` in there, will be removed once we get to the `ToU64` stuff. One other remaining cast in the module is obviously bit twiddling.
=> bip158: Improve casting

CONTRIBUTING.md, bitcoin/src/blockdata/script/borrowed.rs
As much as it hurts the C hacker inside me we have settled on using `_internal` to mark private function names that clash with a public function of the same name.
Introduce a policy section and rename one instance, I did not grep the codebase looking for other violations.
This came up because I had to look at what `_inner` implied when reading the function name somewhere else.
=> Introduce helper function name policy

bitcoin/src/blockdata/script/owned.rs
The `PushBytes` type enforces len is less than 0x100000000 so we do not need to panic in a catch all pattern after explicitly matching against less than 0x100000000.
Refactor only because of the invariant on `PushBytes` - no logic changes.
=> Remove catch all pattern

hashes/src/internal_macros.rs, hashes/src/lib.rs, hashes/src/sha256t.rs
Add a function `hash_reader` that uses the `BufRead` trait to read bytes directly into the hash engine.
Add the functionality to:
- as a trait method in the `GeneralHash` trait with default implementation
- as inherent functions to all the hash types
Close: #3050
=> hashes: Add a new `hash_reader` function

hashes/src/internal_macros.rs, hashes/src/sha256t.rs
Currently we have duplicate code in inherent functions that also occurs in the default implementation of the `GeneralHash` trait methods, this is unnecessary because we can call through to the trait methods.
=> hashes: Call through to trait methods

base58/src/lib.rs
Done as part of #2941.
Remove or document casts in the `base58` crate. Two separate patches because to assist review, with the hope that reviewers are able to just read the diff without going to the crate's code.
=> base58: Remove or document casts

bitcoin/Cargo.toml, bitcoin/build.rs, bitcoin/src/blockdata/script/mod.rs, bitcoin/src/consensus/encode.rs, bitcoin/src/lib.rs, internals/Cargo.toml, internals/build.rs, internals/src/array_vec.rs
Recently we upgraded the MSRV but forgot to remove the Rust version specific `cfg`s.
=> Remove build cfg for versions less than MSRV

bitcoin/src/blockdata/script/owned.rs, hashes/src/internal_macros.rs, hashes/src/lib.rs, hashes/src/sha256t.rs
Run `rustfmt` and manually fix the places where comments are moved to the wrong place.
=> Manually format

bitcoin/src/bip152.rs, bitcoin/src/bip158.rs, bitcoin/src/blockdata/block.rs, bitcoin/src/blockdata/mod.rs, bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/script/owned.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/consensus/encode.rs, bitcoin/src/internal_macros.rs, bitcoin/src/merkle_tree/block.rs, bitcoin/src/p2p/message.rs, bitcoin/src/psbt/map/global.rs, bitcoin/src/psbt/raw.rs, internals/src/lib.rs
The idea for this was pulled out of Steven's work in #2133 
We already explicitly do not support 16 bit machines.
Also, because Rust supports `u182`s one cannot infallibly convert from a `usize` to a `u64`. This is unergonomic and results in a ton of casts.
We can instead limit our code to running only on machines where `usize` is less that or equal to 64 bits then the infallible conversion is possible.
Since 128 bit machines are not a thing yet this does not in reality introduce any limitations on the library.
Add a "private" trait to the `internals` crate to do infallible conversion to a `u64` from `usize`.
Implement it for all unsigned integers smaller than `u64` as well so we have the option to use the trait instead of `u32::from(foo)`.
=> Introduce `ToU64` trait

bitcoin/src/address/script_pubkey.rs, bitcoin/src/consensus_validation.rs, bitcoin/src/internal_macros.rs
`foo(&self)` is syntax sugar for `foo(self: &Self)`.
The `define_extension_trait` is currently large, ugly, and not that expressive. If we use `self: &Self` then the macro is greatly simplified.
(Also consuming version `self: Self`)
De-sugar only, no logic changes.
=> De-sugar `self`

primitives/src/lib.rs
We have an `alloc` feature but we are unconditionally using `extern crate alloc`, this is broken - clearly we need to add a `no-std` build for `primitives` in CI.
Feature gate the `alloc` crate.
While we are at it just pull types in from `alloc` in the `prelude` - I have no idea why we do not do this in `bitcoin`?
=> primitives: Fix alloc feature

githooks/pre-commit
We don't need to worry about nested quoting in SC2046.
Thanks to Kixunil in https://github.com/rust-bitcoin/rust-secp256k1/pull/697 for pointing that out.
=> githooks: remove unnecessary shellcheck disables

bitcoin/src/pow.rs, primitives/src/lib.rs, primitives/src/pow.rs
Done in preparation for moving `BlockHash` and `block::Header` to `primitives`. 
- Patch 1 introduces an extension trait using `define_extension_trait!`
- Patch 2 is the trivial copy and past to move the type to `primitives`
This one shouldn't be to arduous to review, thanks.
=> Move `CompactTarget` to `primitives`

bitcoin/examples/sighash.rs, bitcoin/examples/taproot-psbt.rs, bitcoin/src/address/mod.rs, bitcoin/src/address/script_pubkey.rs, bitcoin/src/bip158.rs, bitcoin/src/blockdata/block.rs, bitcoin/src/blockdata/script/borrowed.rs, bitcoin/src/blockdata/script/builder.rs, bitcoin/src/blockdata/script/owned.rs, bitcoin/src/blockdata/script/witness_program.rs, bitcoin/src/blockdata/transaction.rs, bitcoin/src/blockdata/witness.rs, bitcoin/src/consensus_validation.rs, bitcoin/src/internal_macros.rs, bitcoin/src/psbt/mod.rs, bitcoin/tests/psbt-sign-taproot.rs, fuzz/fuzz_targets/bitcoin/deserialize_script.rs, fuzz/fuzz_targets/bitcoin/script_bytes_to_asm_fmt.rs
This moves methods from `Script` to extension traits in steps that should be easy to follow.
Moving to `primitives` requires doing the same with `ScriptBuf` so I'm holding off until this approach gets concept ACK (or alternatively someone else can do it :))
Closes #3161
=> Extension trait for `Script`

bitcoin/examples/ecdsa-psbt.rs, bitcoin/examples/taproot-psbt.rs, bitcoin/src/address/mod.rs, bitcoin/src/blockdata/script/builder.rs, bitcoin/src/blockdata/script/instruction.rs, bitcoin/src/blockdata/script/owned.rs, bitcoin/src/crypto/ecdsa.rs, bitcoin/src/crypto/sighash.rs, bitcoin/src/internal_macros.rs, bitcoin/src/psbt/mod.rs, bitcoin/src/psbt/serialize.rs, bitcoin/src/taproot/mod.rs, bitcoin/tests/bip_174.rs, bitcoin/tests/serde.rs
Similar to #3155 but for `ScriptBuf`, however it is a little more involved.
Note:
- the change to use `impl` syntax (and addition of #3179)
- mad trickery of `ScriptBufAsVec` (props to Kix)
- widening of scope of private functions
Onward and upward!
=> Extension traits for `ScriptBuf`

contrib/crates.sh, hashes/contrib/extra_tests.sh, hashes/extended_tests/schemars/README.md, hashes/extended_tests/schemars/src/main.rs, hashes/src/lib.rs, hashes/src/sha256t.rs, hashes/src/siphash24.rs
This is just the bug fixes pulled out of #2861
The root problem here is the bug described in https://github.com/rust-bitcoin/rust-bitcoin-maintainer-tools/issues/10
This PR works around the bug by putting `fuzz` last in the list.
=> hashes: Fix a bunch of bugs caused by broken CI script

io/src/lib.rs
The impl wasn't previously available because we thought we can do a blanket impl for `std` traits. We've removed the `std` blanket impl when we realized it's broken but forgot to add the `&mut T` impls. This adds them.
Note: this is in part an experiment to see if this is API breaking. I suspect it might be.
=> Add blanket impl of io traits for `&mut T`

internals/build.rs
This is a follow up to #3182 which introduced a new way of conditionally including code based on the compiler version.
When originally reviewing I missed the fact that the two loops were controlled by the current compiler version (`minor`) so the created macro is different dependent on the compiler used to build the code.
To help the next guy notice, add a comment.
=> Document the new build script magic

hashes/src/sha256.rs, units/src/amount.rs, units/src/weight.rs
Now that our MSRV is past 1.57 we can panic in const contexts.
Fix: #2427
=> Panic in const context

bitcoin/src/bip158.rs
From [BIP-157](https://github.com/bitcoin/bips/blob/master/bip-0157.mediawiki#filter-headers)
> The canonical hash of a block filter is the double-SHA256 of the serialized filter.
If a user forgets the "double" in double-SHA256 they will be computing a nonsensical filter hash when this is easily handled by the API.
=> feat(bip158): compute canonical filter hash

hashes/src/internal_macros.rs, hashes/src/siphash24.rs
Never break SSOT. Never break SSOT. Never break SSOT. Never break SSOT. Never break SSOT. Never break SSOT. Never break SSOT. ...
Previously we had removed `Default` impl on `siphash24::HashEngine` by
reimplementing the type manually. This was a really bad idea as it
inevitably led to API differences that broke the build which we didn't
notice because of unrelated bug. It should've just split the macro from
the start as was suggested but it was claimed to be difficult, I don't
think was the case as can be seen by this PR.
This commit does what the previous one should've done: it renames the
macro to have `_no_default` suffix, creates another one of the original
name that calls into `_no_default` one and moves anything related to
`Default`. This cleanly ensures all previous hashes stay the …
=> Siphash24 cleanup

bitcoin/src/hash_types.rs, hashes/src/sha256.rs, hashes/src/sha256t.rs
Our `release` job checks for 'TBD', I can't remember exactly why but I thought we introduced `0.0.0-NEXT-RELEASE` because CI was failing when we used TBD - clearly this is not the case now because we have a bunch of `TBD`s in the code base.
Change all the instances of `0.0.0-NEXT-RELEASE` to be `TBD`.
=> Use TBD in deprecated attribute

bitcoin/src/lib.rs, internals/src/macros.rs, units/src/lib.rs
3 patches in preparation for other size related work, this PR does not touch the `ToU64` issue which will be handled separately.
- Patch 1: Don't check pointer width in `units` because its not consensus code
- Patch 2: Modify internal macro `const_assert`
- Patch 3: Use index size to enforce not building on a 16 bit machine
=> Use index size rather than pointer size to enforce convertibility of `u32` to `usize`

bitcoin/src/crypto/ecdsa.rs, bitcoin/src/psbt/error.rs, bitcoin/src/psbt/serialize.rs
There are a couple of issues around the ECDSA signature decoding / parsing code. We have duplicate code in `from_str` and `from_slice` and both use the same error type even though it is impossible to get a hex error in `from_slice`.
Create two errors:
- A `DecodeError` returned by `from_slice`
- A `FromStrError` that has a decode variant and a hex variant
Call through to `from_slice` after parsing hex into a byte vector.
Removes an instance of `unreachable!`.
Fix: #1193
=> ecdsa: Improve error types

Cargo-minimal.lock, Cargo-recent.lock, bitcoin/Cargo.toml, bitcoin/contrib/test_vars.sh, bitcoin/src/blockdata/script/owned.rs, bitcoin/src/blockdata/transaction.rs, units/Cargo.toml, units/contrib/test_vars.sh, units/src/amount.rs, units/src/fee_rate.rs
Adds an example draft showing what is needed to use Arbitrary for coin selection.
Shot out to how nice Arbitrary is for fuzzing a target by taking unstructured randomness and creating structured rust-bitcoin types for fuzzing.  Is there a way we could add this to rust-bitcoin for structuring the fuzz data needed?
This is then the example to fuzz test a SRD algo (after applying this PR to rust-bitcoin) using rust-bitcoin types :)
```
#![no_main]
use arbitrary::Arbitrary;
use bitcoin::{Amount, FeeRate};
use bitcoin_coin_selection::{select_coins_srd, WeightedUtxo};
use libfuzzer_sys::fuzz_target;
use rand::thread_rng;
#[derive(Arbitrary, Debug)]
pub struct Params {
target: Amount,
fee_rate: FeeRate,
weighted_utxos: Vec<WeightedUtxo>,
}
fuzz_target!(|params: Params| {
let Params { target: t, …
```
=> Add Arbitrary

Cargo-minimal.lock, Cargo-recent.lock, units/Cargo.toml
The master branch version of units is behind that of crates: https://crates.io/crates/bitcoin-units
This breaks the ability for those of us trying to patch and work off of master since Cargo ignores the patched version 0.1.1 which is technically ahead.
I'm not sure how this got out of sync and if there's a preferable way/commit to fix this.
closes https://github.com/rust-bitcoin/rust-bitcoin/issues/3171
=> Bump units version

base58/src/lib.rs
Remove useless zeroed vector following https://github.com/rust-bitcoin/rust-bitcoin/issues/3131.
1. Init vector with capacity not to realloc when pushing.
2. If vector is empty(the first iteration), push data from the front.
3. Iterate vector from the front, and copy it from the end.
=> feat: remove zeroed vector by pushing front

bitcoin/src/blockdata/transaction.rs
This one is pretty easy. Leaves the actual move of `TxOut` for later.
=> Introduce `TxOutExt`

.github/workflows/semver-checks-pr-label.yml, contrib/check-semver-feature.sh, contrib/check-semver-pr.sh
Debugging the API breaks without seeing what failed is pretty much impossible. This simply prints the output when a check fails.
=> Show output of failed semver checks

bitcoin/examples/bip32.rs, bitcoin/src/crypto/key.rs, bitcoin/src/psbt/map/input.rs, bitcoin/tests/bip_174.rs, hashes/embedded/src/main.rs, hashes/src/serde_macros.rs, internals/src/serde.rs, units/src/amount.rs
As mentioned in issue #3234 `s.parse::<T>()` is more idiomatic and produces more helpful error messages.
This has been changed in the main codebase, not including examples, rustdocs, and in the `test` modules.
`use std::str::FromStr;` has been removed where this change makes it unnecessary.
To close the issue it may also need to be changed in the examples and the `test` modules and `contributing.md` updated.
=> Change `T::from_str(s)` to `s.parse::<T>()`

bitcoin/src/bip32.rs
In v0.31 we deprecated the long version of what became `Xpub` and `Xpriv` but we had a typo in the name so the this meant that there is no deprecated original. However now we released the typo we need to have both, the original name correctly deprecated _and_ the new typo deprecated type with the typo.
This same change is also being done on the `0.31.x` branch.
Typo fix was done on master in #2693.
=> bip32: Backport without typo

bitcoin/src/psbt/serialize.rs
Fixes #3250.
The serialization is less than ideal and still allocates a lot. I can understand not wanting to (ab)use the consensus encoding traits, but they have a pretty good interface, copying it and creating some `EncodePsbt` and `DecodePsbt` traits with similar interfaces would have been nice imo.
=> fix: re-implement `Psbt` (de)serialization from/to readers/writers

internals/src/array_vec.rs
Currently the source slice must be the exact length to fill the array to max capacity, this is an unnecessary restriction since an `ArrayVec` is a variable sized data structure.
Set the destination slice to be the same length as the source slice (still maintain capacity checks).
=> Fix bug in `ArrayVec::extend_from_slice`

units/src/amount.rs
While proptesting, I've found Arbitrary for SingedAmount to be useful.  Would appreciate adding this as well.
=> Add Arbitrary to SignedAmount type

bitcoin/src/blockdata/witness.rs
The `String` type is only used if the `serde` feature is enabled, move the import statement inside the already feature gated block.
=> Move import inside feature gate

bitcoin/src/lib.rs, internals/src/lib.rs, internals/src/macros.rs
Now that we can panic in const context we can improve the `const_assert` macro by adding a message string.
Original idea by Kix:
https://github.com/rust-bitcoin/rust-bitcoin/pull/2972#discussion_r1726328228
=> Improve const_assert

bitcoin/src/crypto/key.rs
Currently `CompressedPublicKey` debug produces output of form:
```
CompressedPublicKey(PublicKey(2f8b18dc0adcb73d75f7934d9523ea7347083e41c48115398cb37e295a0a6ffe86e0bf8b1ef65888c880c8d8813a30e69e466380cbe2daec18f3ed1e7a553ff2))
```
Although it shows real internal structure together with inner uncompressed public key, it is not too helpful for the purpose of debugging _compressed_ public key.
After this patch, `Debug` output will be equal to `Display` (it, in fact, delegates rendering to `Display`), prepended by the name of the struct:
```
CompressedPublicKey(02fe6f0a5a297eb38c391581c4413e084773ea23954d93f7753db7dc0adc188b2f)
```
=> Show compressed public key in Debug for CompressedPublicKey
