- src/network/message.rs
I just added in the little bits needed for the GetAddr message (seems to work), along with the accompanying serialization test a la verack and mempool.
> Add GetAddr message

- src/util/uint.rs
> add low_u64 to Uint256 and Uit128 types

- src/blockdata/block.rs
- src/util/uint.rs
while target is the precise threshold, difficulty is popular
includes https://github.com/apoelstra/rust-bitcoin/pull/42
> Add difficulty calculation

- .gitignore
Please add IntelliJ project files to .gitignore.
> [Trivial] add IntelliJ IDEA files to .gitignore

- src/blockdata/blockchain.rs
is_on_main_chain is a very useful function upstream, make it public
> [Trivial] is_on_main_chain is a very useful function upstream, make it public

- Cargo.toml
- README.md
- src/lib.rs
- src/util/address.rs
- src/util/base58.rs
- src/util/bip32.rs
- src/util/contracthash.rs
- src/util/hash.rs
- src/util/mod.rs
> Add bech32 support

- fuzz/fuzz_targets/deserialize_transaction.rs
- src/blockdata/transaction.rs
- src/network/encodable.rs
> Add a Transaction.get_weight() method, check it in fuzzing

- src/util/bip143.rs
Based on #69 because I'm still really lazy.
>  Only provide the required TxIn to bip143 sighash_all

- src/util/hash.rs
In a project of mine I needed to check the merkle root before
moving some Vec<Transaction>s around, so need to be able to
calculate the merkle root on a Vec<Sha256dHash> directly.
I'm open to other APIs, but I want to expose it in a form that consumes the Vec, not a &self one, cause you can make that much more effecient.
> Expose merkleroot(Vec<Sha256dHash>) publicly

- src/network/message_blockdata.rs
Add missing BIP144 inv types to get blocks and tx serialized with witness
> add witness inv types

- src/blockdata/opcodes.rs
- src/blockdata/script.rs
- src/blockdata/transaction.rs
- src/internal_macros.rs
- src/network/address.rs
- src/network/encodable.rs
- src/network/listener.rs
- src/network/message.rs
- src/network/message_blockdata.rs
- src/network/message_network.rs
- src/network/serialize.rs
- src/network/socket.rs
- src/util/address.rs
- src/util/base58.rs
- src/util/bip32.rs
- src/util/contracthash.rs
- src/util/decimal.rs
- src/util/hash.rs
- src/util/misc.rs
- src/util/privkey.rs
- src/util/uint.rs
The `?` (try) operator was stabilized in 1.13.0<sup>[1][1]</sup>
[1]: https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1130-2016-11-10
> Remove `try!` macro usage and use the `?` operator instead.

- src/util/bip32.rs
- Add derive_pub to ExtendedPubKey
- Add derive_priv to ExtendedPrivKey
- Removed from_path from ExtendedPrivKey as it is superseded by
derive_priv
- Add checking of derive_pub and derive_priv to test_path
- Add checking of correct error when invoking ckd_pub on a hardened
ChildNumber
- Add test vector 3 from BIP32 specification
> Ready for Review: Add derive_* methods to Extended*Key

- src/network/encodable.rs
- src/network/serialize.rs
- Adjust tests in encodable.rs to account for this change
> Ready for Review: Make deserialize error if input bytes not consumed

- CHANGELOG.md
- Cargo.toml
> bump version to 0.14.0

- src/blockdata/script.rs
It's reasonable to be able to order scripts lexicographically.
> impl PartialOrd, Ord for Script

- src/lib.rs
> `pub use` a ton of stuff at the top level

- src/util/address.rs
Address didn't have serialization like f.e. Sha256dHash and Script.
> Implement serde serialiation for Address

- src/util/bip143.rs
I think tests can serve as docs as well. I've spent some time before I found out what is 
`scriptCode of the input` in bip143 spec and how to generate it. I believe tests helps with it.
> added p2wkh, p2sh-p2wkh tests for bip143 module

- src/blockdata/transaction.rs
I'm sorry for the many lines of error code :)
> Implement FromStr for OutPoint

- src/util/privkey.rs
> Add explicit WIF methods for Privkey

- src/lib.rs
> Export network::constants::Network

- src/blockdata/block.rs
- src/blockdata/mod.rs
- src/util/address.rs
A bunch of nits while reviewing other stuff
> Fix typos and clarify some comment in blockdata, block, address

- src/util/misc.rs
A simple utility function to hash messages using Bitcoin's message signing format, with the `Bitcoin Signed Message:` prefix.
> Implement util::misc::signed_msg_hash()

- src/blockdata/opcodes.rs
- src/blockdata/script.rs
Fixes https://github.com/rust-bitcoin/rust-bitcoin/issues/280.
> Rename OP_NOP2 and OP_NOP3 to OP_CLTV and OP_CSV

- README.md
Most importantly:
- added PSBT mention under features
- mention `rust-bitcoincore-rpc`
> Slightly update README

- README.md
- src/lib.rs
I think this is a good policy to add
> forbid unsafe

- src/consensus/encode.rs
This PR fills in the TODO's in test function "fn serialize_int_test()".
Hopefully the test inputs are suitable, but I am more than willing to revise the pull request :)
> Test negative numbers

- Cargo.toml
- src/blockdata/opcodes.rs
- src/blockdata/script.rs
- src/internal_macros.rs
- src/lib.rs
- src/network/constants.rs
- src/util/bip32.rs
- src/util/key.rs
Reverts rust-bitcoin/rust-bitcoin#325
> Revert "bump version to 0.18.1; semver-trick scripts and keys"

- src/network/message.rs
- src/network/message_network.rs
Quite a dumb message,  will probably disappear. Some nodes are still sending it though and not having it creates errors in parser.
> Add reject message

- src/blockdata/transaction.rs
fixes #339 
Adds a default impl for TxIn, if any of the values are incorrect please let me know
> Add default trait implementation for TxIn

- src/network/address.rs
- src/network/constants.rs
- src/network/message.rs
- src/network/message_network.rs
- src/network/mod.rs
- src/network/stream_reader.rs
@tamasblummer Could you review this?
> Add ServiceFlags type

- CHANGELOG.md
- Cargo.toml
I think we want to wait for https://github.com/rust-bitcoin/rust-bitcoin/issues/284.
> Release v0.22.0

- src/blockdata/constants.rs
- src/blockdata/transaction.rs
I likely missed some constant uses but this is a start.
> Add, use WITNESS_SCALE_FACTOR constant

- src/consensus/encode.rs
- src/util/amount.rs
- src/util/base58.rs
Hi,
I used mutagen(https://github.com/llogiq/mutagen) to find places where our test don't quite check (even if they "cover" as in code coverage).
and wrote more tests to try and cover the edge cases it found.
I didn't managed to run it on all of our code because it's a lot of work so I decided to do it gradually.
For actual CI inclusion I'll wait and see how Matt will do it in https://github.com/rust-bitcoin/rust-lightning/pull/453 
And also: https://github.com/llogiq/mutagen/issues/156 https://github.com/llogiq/mutagen/issues/154
I also found some bugs while writing the tests and fixed them.
> Add tests based on mutagen outputs

- src/blockdata/block.rs
They're a bit tricky to get right (I was missing the size of the tx count varint when I initially implemented this in another project), so could be useful to have this as part of rust-bitcoin.
Depends on #416.
> Add Block::get_size() and Block::get_weight()

- fuzz/Cargo.toml
- fuzz/fuzz_targets/uint128_fuzz.rs
I'm gonna use some of the uint stuff, so is nice to have good coverage for it.
> Add fuzz target comparing native u128 to our Uint type

- src/util/merkleblock.rs
More efficient in cases where the list of txids in the block is already known (as is the case in esplora).
> Allow to construct MerkleBlock using the header and txids

- src/lib.rs
> Remove duplicate code

- src/util/uint.rs
An optimization for https://github.com/rust-bitcoin/rust-bitcoin/pull/435
we already compute the remainder as part of the current division, so I just exposed that internally instead of recomputing it (adding a long subtraction and long multiplication)
I was thinking of renaming all the variables so that more people could follow the algorithm here, but I wanted to minimize the changes to ease review, so if reviewers prefer I'll rename/reformat it.
> Use the remainder from div_rem instead of recomputing it

- src/util/bip143.rs
See docuemntation of the new method for more, but this allows
certain use patterns which were broken with the introduction of
SigHashCache.
> Expose the witnesses of the tx being hashed in SigHashCache

- .gitignore
- src/util/psbt/error.rs
- src/util/psbt/macros.rs
- src/util/psbt/map/input.rs
- src/util/psbt/mod.rs
- src/util/psbt/serialize.rs
Reverts rust-bitcoin/rust-bitcoin#465.
Merged by mistake.
> Revert "Added hash Preimages to psbt"

- src/blockdata/block.rs
Was reading AJ Towns' softfork history writeup and noticed we didn't have BIP-34 support yet :) I think it's useful.
> Add Block::coinbase and Block::bip34_block_height (BIP-34)

- src/util/bip32.rs
Thx @cheako for finding this [doc bug](https://github.com/rust-bitcoin/rust-bitcoin/commit/14af175a116507accebb8b134baf6690d94cdcfd#r43040450)
> Bip32 documentation fix

- src/consensus/encode.rs
- src/network/address.rs
- src/network/message.rs
Thought I'd just open this to see what people's thoughts are on how to do this. 
- I guess we don't want to implement parsing for tor, i2p and cjdns addresses so do we just want to have them all as unknown or do we want to do what I've done here and just store the raw bytes
- Not sure about names
- Do we want to store time separately like it is for addrv1
> BIP155: AddrV2

- .gitignore
- src/util/psbt/error.rs
- src/util/psbt/macros.rs
- src/util/psbt/map/input.rs
- src/util/psbt/mod.rs
- src/util/psbt/serialize.rs
The accidental merge of #465 was reverted by #477. This opens PR is cherry-pick of commits from #465 rebased to master.
> Psbt hash preimages (again)

- src/blockdata/script.rs
- src/consensus/encode.rs
- src/lib.rs
- src/util/address.rs
- src/util/bip32.rs
- src/util/endian.rs
- src/util/key.rs
- src/util/psbt/serialize.rs
- src/util/uint.rs
Followup on https://github.com/rust-bitcoin/rust-bitcoin/pull/506.
> Change PublicKey::write_into to return Result

- src/network/message_blockdata.rs
Sorry for the many small PRs. They seem all quite independent though and I bump into these along the way :)
> Implement PartialOrd and Ord for Inventory

- Cargo.toml
- src/util/mod.rs
- src/util/taproot.rs
Currently blocked on https://github.com/rust-bitcoin/bitcoin_hashes/pull/93.
> Tagged hashes for taproot

- src/util/bip32.rs
- src/util/psbt/error.rs
- src/util/psbt/map/global.rs
- src/util/psbt/mod.rs
Based/depends on https://github.com/rust-bitcoin/rust-bitcoin/pull/470
Part of epic https://github.com/rust-bitcoin/rust-bitcoin/issues/473
> New PSBT global keys

- src/util/bip32.rs
Part of epic https://github.com/rust-bitcoin/rust-bitcoin/issues/473
> Derivation path improvements, closes #473

- src/blockdata/script.rs
- src/internal_macros.rs
> script: add FromHex and FromStr implementations

- src/blockdata/script.rs
I don't know why we didn't do it like this back in #566, was there any reason for it @TheBlueMatt?
> Use `Amount` type for dust value calculation

- src/util/address.rs
Parsed legacy addresses do not always have *one* network. The problem is that testnet, regtest and signet use the same prefix instead of multiple different ones. When parsing such addresses are always assumed to be testnet addresses. But if one wants to check against if the address belongs to the right network a simple comparison is not enough anymore.
> Implement possible_networks function for Address

- src/util/uint.rs
Closes https://github.com/rust-bitcoin/rust-bitcoin/issues/739
> add helpful message to division-by-zero panic

- src/util/address.rs
This allow library clients to plug their own encoding parameters in a
backwards compatible manner.
> util/address: make address encoding more modular

- src/util/amount.rs
Closes https://github.com/rust-bitcoin/rust-bitcoin/issues/740
> add MAX_MONEY public constant to Amount

- src/util/sighash.rs
Still need to add some tests but the code should be ready for review. Please let me know if you have better ideas for the enum naming.
---
Instead of always requiring the full raw script and leaf version, allow
just specifying a raw leaf hash to the sighash computation functions.
This is very useful when dealing with PSBTs, because the
`PSBT_IN_TAP_BIP32_DERIVATION` field only maps a public key to a leaf
hash, so a signer could just take it and produce a signature with it
rathern than having to jump through hoops to recover the full raw
script.
> Allow specifing a raw `TapLeafHash` in sighash computation

- src/util/taproot.rs
Trivial post-merge fixups from review comments in #718
> Taproot trivial post-merge fixups

- src/blockdata/script.rs
- src/lib.rs
- src/util/schnorr.rs
- src/util/taproot.rs
This addresses @Kixunil review comments in #696 post-merge
Update: also closes nits from issues #764 and #770
> Fixups for taproot improvements

- src/util/amount.rs
Follow-up PR from https://github.com/rust-bitcoin/rust-bitcoin/pull/768
https://github.com/rust-bitcoin/rust-bitcoin/pull/768#discussion_r784684641
> replace unncessary closure with function pointer in FromStr::from_str for Deonomation

- src/util/psbt/macros.rs
- src/util/psbt/map/input.rs
- src/util/psbt/map/output.rs
> Fix unused arg in PSBT impl_psbt_get_pair macro

- src/util/psbt/serialize.rs
issue: https://github.com/rust-bitcoin/rust-bitcoin/issues/793
change to using map_err
> Refactor use map_err

- src/blockdata/transaction.rs
Bizarrely the impl block for `EcdsaSigHashType` uses 5 character indentation.
Use 4 character indentation as is typical.
> Use 4 character indentation

- src/blockdata/block.rs
- src/blockdata/script.rs
In an effort to make the code clearer and more explicit, do various refactorings around logical operators. Each done as a separate patch to ease review and limit scope of discussion.
Based on review of https://github.com/rust-bitcoin/rust-bitcoin/pull/806
> Refactor logical operators

- src/util/misc.rs
This is a direct response to this comment: https://github.com/rust-bitcoin/rust-bitcoin/pull/684#issuecomment-1012136845
Currently unsupported addresses simply return `false` which is highly misleading as it is entirely possible that the keys related to a given address were used to sign the message.
If this is successful I can follow up with
> a method to check if a PublicKey is associated with an address
> fix: Throw Error on unsuported addresses in `is_signed_by_address()`

- src/blockdata/opcodes.rs
Code comment contains an off-by-one error, update it to the correct value '61'.
Fixes: #866
> Use correct opcode count

- src/blockdata/block.rs
- src/blockdata/transaction.rs
This one might be a viewed as code churn or unnecessarily modifying the API, feel free to NACK :)
We have a bunch of methods that use the prefix `get_`, they are not exactly getters because they do more than just access a struct fields so Rust convention relating to getters does not apply, however, the `get_` prefix does not add to the descriptiveness of name hence the shorter form can be used with no loss of clarity.
Improve docs and deprecate any methods changed that are pubic.
> Remove get_ prefix

- src/blockdata/transaction.rs
Recently we moved the logic for checking for the SIGHASH_SINGLE bug to
the `signature_hash()` function. Although this left users of the
`encode_signing_data_to()` function without correct handling of the bug
there is not much else we can do but alert users to this behaviour.
Add documentation to highlight the behaviour of `encdoe_signing_data_to`
in regards to the sighash single bug. Requires updating docs for
`signature_hash` also.
Please note, uses non-conventional markdown header `# Warning`.
Closes: #817
> Check for SIGHASH_SINGLE bug in writer fn

- src/util/taproot.rs
> Make TaprootBuilder able to generate Huffman Tree

- src/util/taproot.rs
> Taproot Huffman tree builder u64->u32 fixes

- src/util/schnorr.rs
We forgot about them and marked as TODO. This is clearly an RC fix
> Adds derives to TweakedKeyPair

- src/util/psbt/map/mod.rs
- src/util/psbt/map/output.rs
- src/util/psbt/mod.rs
- src/util/psbt/serialize.rs
- src/util/taproot.rs
> Fix TapTree hidden branches bug

- src/util/psbt/map/output.rs
- src/util/psbt/serialize.rs
These are trivial fixes from extracted from now closed #922
> Trivial improvements for TapTree type

- CHANGELOG.md
- Cargo.toml
See discussion here https://github.com/rust-bitcoin/rust-bitcoin/discussions/941 about whether we want to cut the release now or do another slew of breaking changes between RCs.
> Release 0.28.0

- src/blockdata/constants.rs
- src/util/bip158.rs
- src/util/schnorr.rs
Three trivial clean ups of import aliases.
> Clean up import aliases

- src/util/psbt/mod.rs
- src/util/sighash.rs
Done while working on sighash and PSBT signing. Just the usual docs fixes. Note, does not do the whole `psbt` module just the file mentioned.
> Improve docs in `sighash` and `psbt/mod.rs`

- src/util/psbt/map/input.rs
- src/util/sighash.rs
> refactor: remove SchnorrSignatureHash::Reserved variant

- README.md
> README: remove stale info about upcoming edition change

- src/util/merkleblock.rs
> Add getter methods for PartialMerkleTree fields

- src/blockdata/transaction.rs
- src/util/sighash.rs
Via `Option` return value
Fix #1015
> Expose SIGHASH_SINGLE bug in `encode_signing_data_to`

- src/lib.rs
Same compile_error with more verbose explanation is also on line 66.
> Remove redundant compile_error

- examples/ecdsa-psbt.rs
We recently merged a PR that enables the formatter on the `examples/` directory, at the same time we merged `examples/ecdsa-psbt.rs` but it had formatting issues under the new formatter config.
Run `cargo +nightly fmt` to format the `examples/` directory.
> Run the formatter

- src/network/message.rs
After MSRV bump `try_from` usually refers to `TryFrom` method but
`CommandString` used inherent one making it confusing and non-idiomatic.
This implements `FromStr` and `TryFrom<{stringly type}>` for
`CommandString` and deprecates the inherent method in favor of those.
To keep the code using `&'static str` efficient it provides
`try_from_static` inherent method that only converts from
`&'static str`.
Closes #1135
> Impl string conversion traits for `CommandString`

- contrib/test.sh
1.0.143 bumps MSRV higher than what we support.
Closes #1175 
Unfortunately I have to go now, will try to get back ASAP.
> Pin `serde` to 1.0.142

- src/blockdata/locktime.rs
- src/blockdata/transaction.rs
- src/error.rs
- src/parse.rs
> Remove accidentally-exported internal macros

- .github/workflows/fuzz.yml
- fuzz/Cargo.toml
- fuzz/travis-fuzz.sh
This reverts commit 720ea29865c64e03a2b0c872e20e0dbf99cf305e.
There is a new version of honggfuzz out. Maybe things work now.
> Revert "Temporarily disable fuzzing"

- src/address.rs
- src/internal_macros.rs
- src/util/key.rs
- src/util/sighash.rs
Few cleanups of hex macros. Preparation for #1189
> Hex macros cleanup

- src/util/merkleblock.rs
An attempt to enhance pmt_tests execution time.
fixes: https://github.com/rust-bitcoin/rust-bitcoin/issues/1214
cargo test result : 
> test result: ok. 356 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 5.74s
> Add multithreading for the pmt_tests execution

- internals/build.rs
- internals/src/hex/display.rs
This fixes minor mistakes that I made in previous PR.
> Hex fixups

- internals/src/hex/buf_encoder.rs
- internals/src/hex/display.rs
- internals/src/hex/mod.rs
Add one `rustfmt::skip` statement and run `cargo +nightly fmt`.
> internals: Run formatter

- bitcoin/src/network/constants.rs
- bitcoin/src/network/message.rs
#1266
Added a new type `Magic` for network magic.
> New type network magic

- bitcoin/src/network/constants.rs
Fix #1292 
Had some time so got this out of the way.
> Return custom error from `Network::from_str`

- .github/workflows/fuzz.yml
- Cargo.toml
- fuzz/Cargo.toml
- fuzz/travis-fuzz.sh
- src/consensus/encode.rs
- src/util/psbt/mod.rs
- src/util/taproot.rs
backport of #1315 
reduce crate package from 1.7M to 500k
> bump version to 0.29.2, fix `test_data` exclude

- bitcoin/src/blockdata/witness.rs
Ref: #1323 
This is just to quickly fix some of the smaller nits. Larger changes (deprecations, adding / refactoring of methods) should be in a separate PR.
> Witness: Fix nits from PR 1323

- bitcoin/src/blockdata/script.rs
> Make Instruction Copy

- bitcoin/src/blockdata/script.rs
closes #1408 
Adds logic to extract a `PublicKey` (if able) from a p2pk script
> Implement `Script::p2pk_public_key(&self) -> Option<PublicKey>`

- bitcoin/tests/serde.rs
- hashes/src/ripemd160.rs
- hashes/src/sha1.rs
- hashes/src/sha256.rs
- hashes/src/sha256d.rs
- hashes/src/sha512.rs
My local scripts did not test serde feature on the merge commit. While merging #734, I accidentally broke the serde feature on the latest master. This PR fixes it.
Sorry about that, I will update my local script to be the same as of CI check.
> Hotfix: Fix broken serde

- bitcoin/src/pow.rs
Adds method `Work::log2()` providing value equivalent to Bitcoin Core's `log2_work` in its logs. Fixes #1326.
Questions:
- The original issue (#1326) also suggests to add log2 to Target but it does not seem to be meaningful, does it? Bitcoin Core, to which the issue refers, also displays only log2 of work.
- Although work should not be 0, the type allows it. In this case, log2 would return -inf. I think we could leave it like that but if there are suggestions to deal with it in a different way, please let me know.
> Add log2 to Work

- bitcoin/src/blockdata/transaction.rs
- Add `segwit_weight` and `legacy_weight` methods to `TxIn`
- Add `weight` method to `TxOut`
> Add weight utilities to `TxIn` and `TxOut`

- bitcoin/src/amount.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/consensus/encode.rs
- bitcoin/src/network/message.rs
> Fix typos in docs

- bitcoin/Cargo.toml
upgrades secp256k1 dependency to 0.25.0 
re: #1487
> upgrade secp256k1 to 0.25.0

- bitcoin/src/pow.rs
Add kani verification for `U256::mul_u64`, doing so uncovered a bug in the current implementation due to overflow. Re-write the `mul_u64` method.
Fix: #1497
This PR now _only_ tests `mul_u64`, I will add testing div as a separate PR.
> Verify and fix the `U256::mul_u64` method

- bitcoin/src/blockdata/opcodes.rs
> [WIP] 1514: fix formatting in opcodes

- bitcoin/src/psbt/macros.rs
- bitcoin/src/psbt/raw.rs
- bitcoin/src/psbt/serialize.rs
- bitcoin/tests/psbt.rs
A follow up to address [nits in  #988](https://github.com/rust-bitcoin/rust-bitcoin/pull/988#pullrequestreview-1233687052)
> A crash course in rust perf (#988 nits)

- .github/workflows/rust.yml
- contrib/test.sh
- hashes/contrib/test.sh
- internals/contrib/test.sh
- internals/src/hex/display.rs
Quick merge this while noone's looking ... we forgot to test the new `internals` crate in CI.
> Add CI script for the `internals` crate

- bitcoin/src/amount.rs
Closes #1529 
0 msats should be parasable.
> amount parses 0 msats

- hashes/src/hex.rs
The `HexWriter` is not used any more since we added the new hex code in internals for fast hex encoding.
While we are removing the benches for `HexWriter` also remove the last remaining bench for writing using `Display` because this is not the correct place for that code - its trivial to re add later in the correct module.
> Remove `hashes::hex::HexWriter`

- bitcoin/src/blockdata/transaction.rs
In some scenarios it's useful to create outputs with minimal relayable value. E.g. outputs designated for fee bumping using CPFP. A method for this is useful.
This implements a constructor of `TxOut` that computes the minimal non-dust value from the passed script.
Closes #1459
This one is quite easy, so if we could get it in 0.30, that'd be great.
> Add `minimal_non_dust` to `TxOut`

- bitcoin/src/pow.rs
When we added `Target` and `Work` types we implemented multiplication and division by anything `Into<u64>`, this is not typically done in the Rust stdlib and also is semantically incorrect for the types.
Remove `Mul` and `Div` impls from `Target` and `Work`. Also remove `Mul<T>` for `T: Into<u64>` from the private `U256` type.
Fix #1632
> pow: Remove Mul/Div by arbitrary integer types

- bitcoin/src/merkle_tree/block.rs
add additional variants instead.
as discussed in https://github.com/rust-bitcoin/rust-bitcoin/pull/1365
> Get rid of BadFormat error

- bitcoin/Cargo.toml
Late stage, super anal, manifest cleanup.
- Patch 1: put non-optional dependencies together
- Patch 2: put `optional = true` at the end of the line
> Do trivial manifest cleanup

- bitcoin/src/address.rs
to check if an address creates a particular script without allocating.
fixes rust-bitcoin/rust-bitcoin#1604
> Create Address::matches_script_pubkey method

- bitcoin/src/blockdata/constants.rs
Not sure if this is the best place to put this but it is nice to have a constant for this instead of having other libraries make their own (ie https://github.com/lightningdevkit/rust-lightning/pull/1924#pullrequestreview-1222807626)
> Add constant for coinbase maturity

- bitcoin/src/taproot.rs
Looks like a new clippy lint landed.
> fix clippy lint

- bitcoin/src/blockdata/transaction.rs
There are several common spends in Bitcoin that have known input weight predictions. It can be useful to have these as constants, so this change adds them. However, this only adds native segwit ones as the others are slowly fading away and might clutter the API.
If anyone wants other constants, please write them for me, their value is not that great to me so I'm not motivated to figure out the correct numbers. :)
This would be nice to add to 0.30 since it's small and easy but not critical.
> Add constants to `InputWeightPrediction`

- bitcoin/src/blockdata/fee_rate.rs
Adds some tests for the `FeeRate` type.
> Add tests for the FeeRate type

- bitcoin/src/blockdata/weight.rs
> Fix weight subtract bug

- bitcoin/src/address.rs
It wasn't obvious that displaying address with alternate formatting upper cases bech32 addresses.
This change adds information about this and also a note about the compatibility of various wallets.
BTW why do we prefix upper case `BITCOIN` only in case of bech32? Proper BIP21 should support it for all addresses. (And yest, it still does save space.)
> Improve QR code formatting documentation

- bitcoin/src/blockdata/block.rs
Header had a passthrough method for difficulty so I added one for difficulty_float as well.
> Feature: Add difficulty_float method for block::Header.

- CONTRIBUTING.md
The testing section in `CONTRIBUTING.md` is stale, update it to point readers towards the readme.
> Update testing section

- bitcoin/src/amount.rs
I took a stab at restricting the acceptable forms here.  There was some consensus that "BtC" was confusing that was discussed in a previous pr https://github.com/rust-bitcoin/rust-bitcoin/pull/1715.  
Also, personally I felt that the `PossiblyConfusingDenomination` enum variant was itself confusing.  I think it's probably cleaner to just maintain a list of acceptable forms and treat everything else as unknown.  For now I just created a const of possibly confusing forms.
> create a set of recognized denomination forms

- bitcoin/src/bip32.rs
Some code looks better with slice patterns. This changes `bip32` to use them.
> Use slice patterns

- bitcoin/examples/ecdsa-psbt.rs
- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/amount.rs
- bitcoin/src/bip152.rs
- bitcoin/src/blockdata/constants.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/crypto/sighash.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/tests/psbt.rs
- bitcoin/tests/serde.rs
Propose using `Amount` type for the `TxOut` `value` field.  I only implemented `Decodable ` and `Encodable` enough to compile but this needs to completed obviously if using `Amount` seems like a good idea.
> Use Amount type for TxOut value field

- bitcoin/src/blockdata/transaction.rs
I've been reading over the `predict_weight` function since it is one of the biggest challenges for coin-selection.  IE choosing inputs and constructing an optimal selection strategy requires predicting the weight to get the best selection.  It's great this work has been done but there are some things I don't understand well enough to comment.
1) why are we looking at the size of VarInt struct here
> let script_size = script_len + VarInt(script_len as u64).len()
2) [predict_weight_internal](https://github.com/rust-bitcoin/rust-bitcoin/blob/36500b445168509e4a888b1639805b994fe6126f/bitcoin/src/blockdata/transaction.rs#L1245) has a bunch of magic numbers.  I'd like to be able to comment this as well but I don't fully understand that function.
Also, `Transaction.rs` is a big file and it seems …
> Comment predict_weight

- bitcoin/src/crypto/key.rs
added a function to generate a private key
Resolves: #1823
> feat: generate PrivateKey

- bitcoin/src/blockdata/block.rs
- bitcoin/src/error.rs
- bitcoin/src/lib.rs
Remove the `crate::Error` and replace its usage with `block::ValidationError`.
> Add `ValidationError`

- bitcoin/src/bip32.rs
> made ckd_priv function private and impl AsRef for ChildNumber

- bitcoin/src/blockdata/opcodes.rs
- bitcoin/src/blockdata/script/borrowed.rs
Fixing some comments that were left on #1890
> Fix comments for #1890

- bitcoin/src/blockdata/script/borrowed.rs
- bitcoin/src/blockdata/script/owned.rs
- bitcoin/src/psbt/mod.rs
Noticed that these methods belong in Script.
> script: Move some inspector methods from ScriptBuf to Script

- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/blockdata/weight.rs
Return Weight type for the strippedize function.
> Use weight type for stripped_size

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/Cargo.toml
- bitcoin/src/psbt/mod.rs
- bitcoin/src/sign_message.rs
Closes #2031
The imports are a bit bike-sheddy... but I think this is fine.
> Update base64 usage to 0.21.3

- README.md
- contrib/test.sh
> CI: Pin `syn`

- bitcoin/CHANGELOG.md
Gearing up for the next release add changelog entries for everything merged upto July 24.
> Add changelog entries

- bitcoin/examples/taproot-psbt.rs
The `taroot-psbt.rs` example uses only one input, and therefore the current code may not make it clear that the number of prevout items must correspond to the number of transaction inputs, since the prevout slice is built within a loop.
This PR aims to make this clear to any user who wants to reuse the logic from the example code.
> example: Modify `taproot-psbt.rs` to make the use of prevouts clearer.

- bitcoin/src/pow.rs
Do 2 trivial docs fixes, found while investigating  #2103
> Trivial docs fixes

- .github/workflows/fuzz.yml
- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/amount.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/src/psbt/raw.rs
- bitcoin/src/psbt/serialize.rs
- contrib/test.sh
Ci looks like broken, so this should fix
it
> ci: bump rustc to 1.60 for fuzz test

- bitcoin/src/crypto/sighash.rs
Done as part of the great error clean up.
Currently we are returning a general `Error` from `Prevouts` functions, this is un-informative, we can do better by returning specific types that indicate the exact error path.
> Split Prevouts errors out into specific error types

- CONTRIBUTING.md
In an effort to consolidate knowledge spread out over time in various places on GitHub add a `Policy` section to `CONTRIBUTING.md`.
Add initial sections on import statements, errors, rustdocs,attributes, and licensing.
> Add policy section to docs

- githooks/pre-commit
See #2135 and discussion [#2219#issuecomment-1826437013](https://github.com/rust-bitcoin/rust-bitcoin/issues/2219#issuecomment-1826437013)
> Remove nightly rustfmt check from pre-commit githook

- README.md
> Fix msrv link

- bitcoin/src/crypto/key.rs
Currently we derive `impl Debug for PrivateKey` for "std" builds and manually implement an obfuscated version for "no-std" builds. Since we enable the `hashes` feature of `rust-secp` this is unnecessary because secp takes care of obfuscating the secret for us.
> Derive Debug for PrivateKey for no-std builds

- bitcoin/src/crypto/key.rs
This commit adds the arrayvec dependency to the sortKey.
Potential fix #2276
> fix : adds the arrayvec dependency

- .github/labeler.yml
- .github/workflows/manage-pr.yml
- contrib/gen_label_config.sh
Rather than modifying the labels manually, which we often forget, we can label the PRs automatically. This will make it easier to search PRs.
> Add automated labeler job

- bitcoin/src/blockdata/locktime/absolute.rs
- bitcoin/src/blockdata/script/witness_version.rs
While reviewing #2335 I noticed a few places that error code needed some love.
> Do minor error fixes

- bitcoin/src/blockdata/weight.rs
- bitcoin/src/consensus/serde.rs
- bitcoin/src/pow.rs
- units/src/amount.rs
Add issues and remove the TODOs from the code.
Resolves: #2368
> Remove the remaining TODOs

- bitcoin/Cargo.toml
- bitcoin/contrib/test_vars.sh
- bitcoin/src/blockdata/script/borrowed.rs
- bitcoin/src/blockdata/script/owned.rs
- bitcoin/src/crypto/key.rs
This was done to fix #1920, it may be of questionable value though.
- Patch 1 is definitely useful, its a CI fix.
- Patch 2 adds two new API functions.
Fix: #1920
> Add API functions `p2wpkh_script_code`

- bitcoin/src/blockdata/script/borrowed.rs
This function is a bit unclear and is only called once, just inline it.
> Inline private ScriptBuf::p2wpkh function

- units/src/amount.rs
Closes: #2245 
Adds `TryFrom<SignedAmount> for Amount` and `TryFrom<Amount> for Amount` in units module
> feat: implement TryFrom trait to `SignedAmount` and `Amount`

- bitcoin/src/internal_macros.rs
Byte like types naturally display in hex, therefore they should havean inherent method `from_hex` and not implement `FromHex`.
> Make from_hex inherent for byte-like types

- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/script/builder.rs
- bitcoin/src/blockdata/script/owned.rs
- bitcoin/src/blockdata/script/push_bytes.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/blockdata/witness.rs
- hashes/src/siphash24.rs
Audit the codebase for any function that starts with `/// Creates` and see if we can make it const. Inline them at the same time.
> Make constructors const

- CONTRIBUTING.md
Do two trivial improvements to the contributing doc. Yes, I am struggling to find stuff to work on because hex is clogging the pipeline :)
> Improve contributing doc

- bitcoin/src/blockdata/script/tests.rs
Changed deprecated Function with a supported one.
> Replaced Deprecated Function

- bitcoin/src/crypto/key.rs
Fixes: #2550 
Added some new tests and refactored some older tests.
> Added more tests for PublicKey::from_str

- SECURITY.md
Just caught a small typo in SECURITY.md
> fix: small typo in SECURITY.md

- .github/workflows/coveralls.yml
- .github/workflows/fuzz.yml
- .github/workflows/rust.yml
- contrib/classify-pr.sh
> ci: skip CI for things that modify only markdown files

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/CHANGELOG.md
- bitcoin/Cargo.toml
This PR is just the final patch, primarily the changelog. Pretty happy with my effort, check it out: https://github.com/tcharding/rust-bitcoin/blob/04-04-release-bitcoin-rc1/bitcoin/CHANGELOG.md
> bitcoin: Release tracking PR: `v0.32.0-rc1` - oh yeah!

- bitcoin/src/pow.rs
Hi, I hit a roadblock with the current `pow` API. As far as I can tell, the only workaround to calculate the next work required similar to `bitcoin/src/pow.cpp` is to use a general big integer library, convert the `Target` to bytes, do the math, and convert back to `Target` from bytes. I have also been working with [Floresta](https://github.com/Davidson-Souza/Floresta/tree/780ea8d0b024eb69ccb723ccce9b4e703b143bfd) and their [solution](https://github.com/Davidson-Souza/Floresta/blob/780ea8d0b024eb69ccb723ccce9b4e703b143bfd/crates/floresta-chain/src/pruned_utreexo/consensus.rs#L187) was to fork off and exposed the `U256` struct publicly on their branch. I think these home brewed difficulty adjustment solutions will continually pop up, so I created a `from_next_work_required` method to …
> Add difficulty adjustment calculation

- .github/workflows/rust.yml
During the last month of CI changes a few anomalies have snuck into the main workflow file.
Make quotes uniform.
> CI: Fix workflow quotes

- bitcoin/src/pow.rs
> Format the `pow` module

- api/bitcoin/all-features.txt
- api/bitcoin/default-features.txt
- api/bitcoin/no-features.txt
- api/units/all-features.txt
- api/units/alloc-only.txt
- api/units/no-features.txt
During a bunch of merges the api/ files have gotten out of sync.
Run just check-api, no other changes.
> api: Run just check-api

- api/bitcoin/all-features.txt
- api/bitcoin/default-features.txt
- api/bitcoin/no-features.txt
- bitcoin/src/p2p/mod.rs
Resolves: rust-bitcoin/rust-bitcoin#2814
> Add `const` modifier to `Magic::from_bytes`

- bitcoin/src/bip152.rs
- bitcoin/src/bip158.rs
- bitcoin/src/blockdata/witness.rs
- bitcoin/src/crypto/key.rs
- bitcoin/src/crypto/taproot.rs
- bitcoin/src/sign_message.rs
- hashes/src/sha256t.rs
- units/src/amount.rs
Updated some of the rustdocs to make the style consistent.  There is still more to do which I can work on if it is useful?
> Standardized rustdoc style

- contrib/check-for-api-changes.sh
Fixes the rustdocs build warnings.
This PR is composed by two commits:
- Updates `contrib/check-for-api-changes.sh` to ignore
`rustdoc::broken_intra_doc_links` due to the features being turned on and off
(see rationale below); and
- Adds a `just doc` quick check that will check for all missing rustdoc broken links
to counterbalance the allow flag above.
As jyap808 has pointed out in #2800,
we might not have a simple fix for these rustdoc build warnings inside the `just check-api`.
This can be mitigated by adding a simple allow flag to `RUSTDOCFLAGS` in `contrib/check-for-api-changes.sh`.
> Took a quick look at this. Not sure if there's anything obvious to fix.
>
> A few warnings mentioning [`ordered::ArbitraryOrd`] which is only enabled when the "--features ordered" flag is used. No …
> Fix Rustdocs warnings in `just check-api`

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/CHANGELOG.md
- bitcoin/Cargo.toml
> release 0.32.2

- api/bitcoin/all-features.txt
- api/bitcoin/default-features.txt
- api/bitcoin/no-features.txt
- bitcoin/src/blockdata/block.rs
- bitcoin/src/pow.rs
> make difficulty_float general to all network

- bitcoin/src/blockdata/locktime/absolute.rs
> clarify the meaning of `Height` & `Time` based locktime.

- api/bitcoin/all-features.txt
- api/bitcoin/default-features.txt
- api/bitcoin/no-features.txt
- bitcoin/examples/bip32.rs
- bitcoin/examples/ecdsa-psbt-simple.rs
- bitcoin/examples/ecdsa-psbt.rs
- bitcoin/examples/taproot-psbt-simple.rs
- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/bip32.rs
- bitcoin/src/psbt/mod.rs
> Implement constants for `ChildNumber` enum

- api/bitcoin/all-features.txt
- api/bitcoin/default-features.txt
- api/bitcoin/no-features.txt
- bitcoin/src/blockdata/script/borrowed.rs
- bitcoin/src/blockdata/script/tests.rs
This is the suggestion for #2292 to check OP_RETURN length
> OP_RETURN standardness check

- bitcoin/src/bip152.rs
When deserializing a `HeaderAndShortIds` we could check if the number of txs does not overflow 16 bits. If so, throw an error.
> bip152: check if indexes do not overflow

- README.md
- contrib/copy-githooks.sh
- justfile
Added `just install-git-hooks` and `just remove-git-hooks` (with contrib script). Fix: #2599
> just: install/remove git hooks

- units/src/locktime/relative.rs
Update `from_second_ceil` per [comment](https://github.com/rust-bitcoin/rust-bitcoin/issues/3029#issuecomment-2227459248) and add unit tests 
Resolves #3029
> Throw error instead of panic when from_second_ceil input is too large

- Cargo-minimal.lock
- Cargo-recent.lock
- fuzz/Cargo.toml
> Bump honggfuzz version

- README.md
> Direct link to ./CONTRIBUTING.md

- hashes/src/sha256.rs
There are a number of issues with the two `const_hash` functions in the `sha256` module:
- The two `const_hash` functions in the `sha256` module differ slightly, one finalizes the hash and one is for computing the midstate.
- They are inefficient and provided for usage for const context only.
Fix both issues by renaming the functions as discussed in #3075.
Close: #3075
> hashes:: Rename const_hash functions

- io/Cargo.toml
- io/build.rs
- io/src/bridge.rs
- io/src/lib.rs
This addresses significant API holes. Originally I wanted to add a commit that bumps the IO version but then I remembered we have #3162 which we most likely also want to merge and release.
Closes #3174 
Closes #3175
> Io improvements

- .github/workflows/cron-weekly-update-cargo-semver-checks.yml
typo in the comparison inside jq
Closes #3229
> ci: fix cron update-cargo-semver-checks

- units/src/weight.rs
Adds Arbitrary to the Weight type.  I had meant to add this with the initial Arbitrary PR but I overlooked it.
> Add Arbitrary to Weight

- bitcoin/src/blockdata/witness.rs
The `Witness` struct is non-trivial, in particular it is not immediately obvious where and when the compact size encode value for each witness element is stored.
Make an effort to improve the docs on `Witness` in relation to the compact size encoded length of each witness element.
> Add additional docs to Witness

- bitcoin/src/internal_macros.rs
- hashes/src/internal_macros.rs
- hashes/src/serde_macros.rs
> Use UFCS in macros

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/Cargo.toml
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/blockdata/witness.rs
- primitives/Cargo.toml
- primitives/contrib/test_vars.sh
- primitives/src/locktime/absolute.rs
- primitives/src/sequence.rs
- primitives/src/transaction.rs
Implement `Arbitrary` for Transaction and its child types
> Implement Arbitrary for Transaction

- primitives/src/sequence.rs
Personally, I think this is a bit nicer and easier to reason about.
> Refactor Arbitrary for Sequence

- bitcoin/src/bip152.rs
- bitcoin/src/bip158.rs
- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/blockdata/witness.rs
- bitcoin/src/consensus/encode.rs
- bitcoin/src/lib.rs
- bitcoin/src/merkle_tree/block.rs
- bitcoin/src/p2p/address.rs
- bitcoin/src/p2p/message.rs
- bitcoin/src/psbt/raw.rs
- bitcoin/src/psbt/serialize.rs
- bitcoin/src/sign_message.rs
- bitcoin/src/taproot/mod.rs
- internals/src/compact_size.rs
This the meat and potatoes out of Steven's work in #2133 and also closes #1016
> Remove `VarInt` and use `ReadExt` and `WriteExt` trait methods instead 

- bitcoin/src/p2p/message_network.rs
- bitcoin/src/serde_utils.rs
- hashes/src/serde_macros.rs
- internals/src/parse.rs
> CI fixes for latest nightly

- bitcoin/src/blockdata/block.rs
- primitives/src/block.rs
Implementing `Arbitrary` for `Block` and its child types
> Implement Arbitrary for Block

- bitcoin/src/blockdata/transaction.rs
- primitives/src/transaction.rs
Found some unused imports while working on something unrelated
> Fix unused import

- bitcoin/examples/ecdsa-psbt-simple.rs
- bitcoin/examples/sign-tx-segwit-v0.rs
- bitcoin/examples/sign-tx-taproot.rs
- bitcoin/examples/taproot-psbt-simple.rs
- primitives/src/sequence.rs
follow up https://github.com/rust-bitcoin/rust-bitcoin/pull/3455.
Replace all `ENABLE_RBF_NO_LOCKTIME`(deprecated) with `ENABLE_LOCKTIME_AND_RBF`
> feat: replace ENABLE_RBF_NO_LOCKTIME with ENABLE_LOCKTIME_AND_RBF

- bitcoin/src/sign_message.rs
While it's not hard to create the signature using `secp256k1` modules with `signed_msg_hash`, it's much more convenient and safe to provide one-way function to generate signed signature(even without the understanding about the semantics of bitcoin message signing).
> feat: add sign fn for sign_message

- primitives/src/block.rs
Add unit tests for block `Version`
> Add tests for block version

- CONTRIBUTING.md
Picked up Steven's PR #2137 and corrected `NEXT_RELEASE` to `TBD`.
> Contributing: Add section about release versions and deprecation

- bitcoin/src/sign_message.rs
Just miscellaneous change that doesn't affect any but simpler and cleaner code.
> refactor: compute recid in a single line

- units/src/amount.rs
> Make `Amount::to_sat` and `SignedAmount::to_sat` const

- bitcoin/src/lib.rs
> Expose units::amount::ParseError

- primitives/src/sequence.rs
Add a few unit tests for Sequence
> Add a few unit tests for Sequence

- .github/workflows/README.md
- .github/workflows/rust.yml
- contrib/crates.sh
- hashes/contrib/sanitizer.sh
- hashes/contrib/wasm.sh
Copy the CI setup from `master` branch.
> CI: Copy main workflow from master

- hashes/src/hash160.rs
- hashes/src/hmac.rs
- hashes/src/internal_macros.rs
- hashes/src/lib.rs
- hashes/src/ripemd160.rs
- hashes/src/sha1.rs
- hashes/src/sha256.rs
- hashes/src/sha256d.rs
- hashes/src/sha256t.rs
- hashes/src/sha384.rs
- hashes/src/sha512.rs
- hashes/src/sha512_256.rs
- hashes/src/siphash24.rs
- hashes/src/util.rs
`hashes 1.0.0` can't be far away, here is a quick polish (done while I waited for my car to get fixed).
Everything here is internal except stuff to docs. Note please I claim "internal change only" in a bunch of patches that do code moves but these effect the docs build because order is preserved in some instances.
> Polish the `hashes` crate

- bitcoin/src/address/error.rs
- bitcoin/src/address/mod.rs
When a decoding error occurs for a bech32 address string the error is discarded and the same address string is attempted to be decoded as base58.  This then incorrectly returns a base58 error.
Check the string prefix and decode as bech32 or base58 and return the relevant error.  If the prefix is unknown return an `UnknownHrpError`.
Close #3044
> Decode an address string based on prefix

- bitcoin/src/blockdata/transaction.rs
- primitives/src/lib.rs
- primitives/src/transaction.rs
Turn the crank; move `TxIn` and `TxOut` to `primitives`.
> Move `TxIn` and `TxOut` to `primitives`

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/CHANGELOG.md
- bitcoin/Cargo.toml
- bitcoin/src/blockdata/constants.rs
- hashes/contrib/wasm.sh
In preparation for release add a changelog entry, bump the version, and update the lock files.
> Release tracking PR: `bitcoin 0.32.4`

- internals/src/macros.rs
- primitives/src/pow.rs
- primitives/src/script/mod.rs
- primitives/src/sequence.rs
Fix macro feature gating.
- Patch 1 is preparatory fixes to bot introduced formatting changes
- Patch 2 is the macro fix
Close: #3152
> Fix macro feature gate

- bitcoin/src/blockdata/script/mod.rs
- bitcoin/src/blockdata/script/push_bytes.rs
- primitives/src/script/mod.rs
We thought #3436 was done (well I thought it was), turns out I was wrong.
> Remove more wildcard re-exports

- bitcoin/src/crypto/key.rs
> Remove `private_key_debug_is_obfuscated` test

- units/src/lib.rs
- units/src/locktime/absolute.rs
- units/src/parse.rs
Remove the feature gating from the modules in `units` - BOOM!
Close: #3213
> units: Remove `alloc` feature gating from modules

- chacha20_poly1305/src/lib.rs
No obvious reason not to; copy the crate level attributes that we have in all our other crates.
> Copy crate level attributes to chacha20_poly1305

- bitcoin/src/blockdata/block.rs
> Fix bip34 number parsing for Block

- bitcoin/src/internal_macros.rs
Use W for Write
closes https://github.com/rust-bitcoin/rust-bitcoin/issues/3590
> Update generic param

- units/src/amount/tests.rs
- units/src/amount/unsigned.rs
closes https://github.com/rust-bitcoin/rust-bitcoin/issues/3563
> Split checked_div_by_weight into floor and ceiling version

- units/src/weight.rs
May as well mark these const as well.  Follow up to https://github.com/rust-bitcoin/rust-bitcoin/pull/3605
> Mark funtions const

- units/src/fee_rate.rs
Remove test suffix from test names
> Remove test suffix from test names

- bitcoin/src/blockdata/transaction.rs
- units/src/weight.rs
closes https://github.com/rust-bitcoin/rust-bitcoin/issues/3602
> Deprecate function

- units/src/amount/signed.rs
- units/src/amount/unsigned.rs
Saw this mentioned in #3556 
Fixes #2952
> Remove Amount::fmt_value_in

- units/src/fee_rate.rs
Since there are test cases for other functions here, add test case as follow up for https://github.com/rust-bitcoin/rust-bitcoin/pull/3604.  I forgot to request this during review.
> Add test case

- bitcoin/src/bip32.rs
> Fix documentation of Xpub::identifier

- bitcoin/src/lib.rs
> Fix typo in re-export

- bitcoin/src/taproot/mod.rs
Fixes #3654 by explicitly defining Ord so that we avoid potentially catastrophically changing addresses out from under users
> Explicitly define Ord for NodeInfo

- bitcoin/src/bip32.rs
- bitcoin/src/crypto/key.rs
- bitcoin/src/crypto/sighash.rs
- bitcoin/src/internal_macros.rs
- bitcoin/src/taproot/serialized_signature.rs
- clippy.toml
- primitives/src/locktime/relative.rs
- primitives/src/sequence.rs
- units/src/block.rs
- units/src/locktime/relative.rs
These lints are valuable, lets get at em.
> clippy: Set avoid-breaking-exported-api to false

- units/src/amount/tests.rs
> Test all the valid denomination forms

- bitcoin/src/blockdata/transaction.rs
Two refactorings to make the code easier to read. No logic changes.
> Refactor predict weight

- bitcoin/src/psbt/mod.rs
Separate out refactor commit from https://github.com/rust-bitcoin/rust-bitcoin/pull/3794.  Can be merged independently.
> refactor: use amount type

- base58/src/error.rs
- bitcoin/src/address/error.rs
- bitcoin/src/bip152.rs
- bitcoin/src/bip158.rs
- bitcoin/src/bip32.rs
- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/script/mod.rs
- bitcoin/src/blockdata/script/witness_program.rs
- bitcoin/src/blockdata/script/witness_version.rs
- bitcoin/src/consensus/error.rs
- bitcoin/src/consensus_validation.rs
- bitcoin/src/crypto/ecdsa.rs
- bitcoin/src/crypto/key.rs
- bitcoin/src/crypto/sighash.rs
- bitcoin/src/crypto/taproot.rs
- bitcoin/src/merkle_tree/block.rs
- bitcoin/src/psbt/error.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/src/sign_message.rs
- bitcoin/src/taproot/mod.rs
- internals/src/macros.rs
- units/src/fee_rate/serde.rs
Fixes #3843 
tcharding Copied your commit message from the other `impl_from_infallible` commit 😄
> Remove usage of impl_from_infallible in crates

- io/src/lib.rs
Currently if one calls `set_position` on a cursor setting the position greater than the total length of the inner buffer future calls to `Read` will panic. Bad `Cursor` - no biscuit.
Mirror the stdlib `Cursor` and allow setting the position to any value. Make reads past the end of the buffer return `Ok(0)`.
> io: Allow setting position bigger than inner buffer

- bitcoin/examples/sighash.rs
Use the `Amount` type as parameter in examples code instead of a `u64`.
Done as part of preparation for enforcing MAX_MONEY.
> Use `Amount` in examples

- bitcoin/src/crypto/key.rs
Resolves #3835
In #945fcd09 we forgot to Update impl for ParsePublicKeyError Display and Error traits
> Update for ParsePublicKeyError Display and Error impl

- units/src/amount/mod.rs
Document what each denomination means.
> Improve docs on `Denomination`

- bitcoin/examples/sighash.rs
- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/blockdata/constants.rs
- bitcoin/src/blockdata/script/borrowed.rs
- bitcoin/src/blockdata/script/tests.rs
- bitcoin/src/consensus_validation.rs
- units/src/amount/signed.rs
- units/src/amount/tests.rs
- units/src/amount/unsigned.rs
- units/src/fee.rs
Do a bunch of refactorings to tease out changes from #3794.
The first 8 are uncontroversial. The 9th one is subjective. The last one is unusual but IMO worth doing because of the relationship between the two amount modules.
Do note that this PR is 100% internal changes - please please don't bike shed this to death.
> Refactor amounts

- primitives/src/script/mod.rs
Together with #3971 this fixes all of the mutants in `primitives/src/script` except for those related to `serde`.
> primitives: Add `script` tests

- api/units/all-features.txt
- api/units/alloc-only.txt
- api/units/no-features.txt
- bitcoin/src/blockdata/mod.rs
- units/src/fee.rs
Rename fee_wu and remove fee_vb
closes https://github.com/rust-bitcoin/rust-bitcoin/issues/3908
> Rename fee_wu and remove fee_vb

- primitives/src/opcodes.rs
Cargo mutant found a mutant in opcodes.
Add a test to kill it.
> primitives: Add test to opcodes

- primitives/src/sequence.rs
Add tests to kill the mutants found in Sequence.
> primitives: Add tests to Sequence

- bitcoin/src/blockdata/transaction.rs
The FeeRate module provides a convenience method to calculate the fee.
> refactor: use convenience method to calculate fee

- primitives/src/transaction.rs
Add tests to kill the mutants in `primitives/src/transaction.rs`
> primitives: Add tests to transaction

- primitives/src/witness.rs
Add tests to kill the mutants in `primitives/src/witness.rs`
> primitives: Add tests to witness

- bitcoin/src/crypto/key.rs
For private WIF keys corresponding to a compressed address, the last byte of the key needs to be 0x01, but the API doesn't enforce this when using PrivateKey::from_wif(). So, invalid keys can be accepted.
Thus we check if the last byte is equivalent to 0x01 if the key's length is 34 (which indicates it's
compressed).
resolves #3773
> Validate compressed WIF keys

- primitives/src/locktime/absolute.rs
- primitives/src/locktime/relative.rs
Add tests to kill the mutants in both relative and absolute PartialOrd.
> primitives: Add tests to LockTime

- primitives/src/witness.rs
This PR updates the Debug implementation for the Witness type to improve its readability by displaying the witness data as a slice of hex-encoded strings rather than a concatenated blob or list of raw u8 values. The changes include:
- Improved Output:
The debug output now shows pseudo-fields such as the number of elements and the total length of all elements, making it easier to understand the underlying data without exposing internal indices like indices_start.
- Hex-Encoding:
Each witness element is displayed as a hex-encoded string, similar to Bitcoin Core's output style, which enhances clarity during debugging sessions.
These changes should provide a more developer-friendly view of the witness data and align with similar patterns used elsewhere in the ecosystem.
Closes #4023.
Example …
> Make Debug representation of Witness to be slice of hex-encoded bytes strings to improve readability

- primitives/src/script/borrowed.rs
- primitives/src/script/mod.rs
- primitives/src/script/owned.rs
This implements various improvements related to `Script`. Please refer to the individual commits for details.
This is a part of #4059
> Script improvements

- hashes/src/sha256t/mod.rs
Resolves #4016 which was suggested here: https://github.com/rust-bitcoin/rust-bitcoin/pull/4010#discussion_r1942359979
> hashes: Remove Clone trait bound from Tag

- internals/src/array_vec.rs
- units/src/amount/mod.rs
- units/src/amount/result.rs
> chore: fix some typos in comments

- chacha20_poly1305/src/lib.rs
- hashes/src/lib.rs
- io/src/lib.rs
- primitives/src/lib.rs
- units/src/lib.rs
Make them all uniform after taking 2 minutes online to try find a nice format.
> Improve crate docs headings

- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/crypto/key.rs
- hashes/src/macros.rs
I fixed some typos in the comments, please review it.
> Fix some comments

- bitcoin/src/blockdata/witness.rs
- bitcoin/src/taproot/mod.rs
This backports fixes from #4100
> Backport witness fixes

- primitives/src/transaction.rs
Feature gate the `Infallible` import. Found with `clippy`.
> primitives: Feature gate import

- bitcoin/src/bip32.rs
This PR addresses issue #4195 by adding proper validation when decoding extended private keys:
- Add validation to ensure byte 45 is zero as required by BIP-32 specification for private keys
- For master keys (depth=0), add validation to ensure parent fingerprint is zero
- For master keys (depth=0), add validation to ensure child number is zero
- Add corresponding error types to handle these validation failures
- Add unit tests to verify each validation rule
These checks improve security by rejecting malformed extended keys that could potentially lead to unexpected behavior. As noted in the issue discussion, these validations are explicitly required by the BIP-32 specification.
Added three new unit tests to verify each validation rule:
- test_reject_xpriv_with_non_zero_byte_at_index_45
- …
> Fix BIP32 validation for private keys and master key constraints (#4195)

- bitcoin/examples/ecdsa-psbt.rs
desciptor - descriptor -> `fix typo`
> fix comment ecdsa-psbt.rs

- bitcoin/src/address/mod.rs
> chore: add missing backquotes

- units/src/fee.rs
This pr replaces the individual operator implementations in the fee module with the impl_op_for_references macro to handle reference operations. This removes the need to manually implement reference combinations for operands, simplifying the code and improving consistency.
- Replaces direct implementations of operators with macro usage
- Adds tests to verify that reference operations work correctly
- Maintains the same semantics as the original implementation
Closes #4173
> Use impl_op_for_references macro in fee module

- bitcoin/examples/sighash.rs
- bitcoin/src/blockdata/script/owned.rs
bitcoin/examples/sighash.rs
inde - index `fix errors`
bitcoin/src/blockdata/script/owned.rs
paics - panics `fix errors`
> fix spelling issues

- primitives/src/locktime/absolute.rs
- primitives/src/locktime/relative.rs
Increase the test coverage in `primitives/src/locktime/*`.
Modify existing tests and add new ones where required to increase the test coverage to 100% for all features excluding `arbitrary` and `serde`.
> primitives: Increase test coverage in LockTime

- base58/README.md
- primitives/README.md
- units/README.md
> docs: fix LICENSE  link

- hashes/src/sha256/crypto.rs
- internals/src/macros.rs
I fix some typos in the comments to improve readability.
> chore: fix some typos in comment

- bitcoin/CHANGELOG.md
Hey , I read through the whole `CHANGELOG.md` and fixed all the links + adjusted some
> updated and corrected links CHANGELOG.md

- bitcoin/src/blockdata/constants.rs
tesnet - testnet `fixed`
How may blocks - How many blocks `fixed`
> fix correction typos

- bitcoin/src/blockdata/mod.rs
> fix correction in comment mod.rs

- bitcoin/src/address/mod.rs
- bitcoin/tests/psbt-sign-taproot.rs
> add copy trait to address and AddressInner

- units/src/fee.rs
- units/src/fee_rate/mod.rs
A couple of quick docs fixes while trying to polish `units`.
> units: Do trivial docs fixes

- primitives/src/witness.rs
New mutants found in weekly mutation testing in `Witness`.
Add a test to kill the mutants in From impl,  and expand the test to kill PartialEq mutants.
Closes #4296
> primitives: Add tests to kill mutants

- units/src/lib.rs
Add a bit more to the crate level docs. This is a simple crate so we don't need all that much.
Done for: C-CRATE-DOC
> units: Improve crate level docs

- bitcoin/src/p2p/message.rs
Please fix this error, thank you
> minor docstring fixups message.rs

- units/src/result.rs
Document the `NumOpResult` type. 
Note that this includes two new getters on the `NumOpResult`, API hole found during review of the new docs.
Fix: #4222
> Document the `NumOpResult` type

- bitcoin/src/blockdata/script/builder.rs
- bitcoin/src/blockdata/script/owned.rs
Currently `push_slice` doesn't check the standard minimal push rule, which could result in possible money loss(e.g. if non minimal push is used in output script of p2wsh or p2tr).
Introduce `push_slice_non_minimal` to provide the way to push as now, and change `push_slice` logic to follow standard minimal push rule.
https://github.com/bitcoin/bitcoin/blob/99a4ddf5ab1b3e514d08b90ad8565827fda7b63b/src/script/script.cpp#L366
> fix: enforce standard minimal push for push_slice

- bitcoin/src/blockdata/transaction.rs
closes: https://github.com/rust-bitcoin/rust-bitcoin/issues/2455
Also, what about moving `effective_value` to `InputWeightPrediction`?
Marking as a draft until we can add api changes again.
> Use InputWeightPrediction to calculate effective_value

- primitives/src/witness.rs
This PR implements `from_hex` function for deserialize `Witness` from a list of hex strings. Added unit test.
This PR fixes #4350
> Deserialize witness from a list of hex strings

- bitcoin/src/taproot/mod.rs
> Add ControlBlock constructor that takes a hex string

- primitives/src/witness.rs
This PR implements the FromIterator trait for the Witness struct, addressing issue #4351.
Changes:
- Added FromIterator<T: AsRef<[u8]>> implementation for Witness, allowing for convenient creation of Witness from iterators
- Added unit test to verify the implementation works correctly
This PR fixes #4351
> Implement FromIterator for Witness

- primitives/src/transaction.rs
> Make Version::maybe_non_standard and Version::is_standard const

- bitcoin/src/taproot/serialized_signature.rs
`signtature` --> `signature` --fix typo
> fix typo in serialized_signature.rs

- bitcoin/src/pow.rs
hi! found typo
Matagen -- typo
Mutagen -- fix
> fix error in comment pow.rs

- bitcoin/src/blockdata/script/tests.rs
Following https://github.com/rust-bitcoin/rust-bitcoin/pull/4368.
I omitted to test OP_0(empty bytes) and can be covered by this PR.
> test: push minimality check for zero(empty)

- bitcoin/CHANGELOG.md
fix `funtions` - `functions`
no impact on functionality, local tests passed
thx
> docs: correction CHANGELOG.md

- README.md
nothing fancy, just changed wording and improved punctuation
> fix: wording and punctuation

- bitcoin/examples/sign-tx-taproot.rs
- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/blockdata/script/witness_program.rs
- bitcoin/src/crypto/key.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/src/taproot/mod.rs
> Add as_inner method to TweakedKeypair

- bitcoin/src/bip32.rs
The corresponding PR on master is #4387, but this doesn't really resemble that PR. Rather than changing all the error enums, this just adds a new variant to the #[non_exhaustive] bip32::Error enum and returns that when adding 1 to 255 when deriving child keys.
This is therefore not an API break and can be released in a minor version. Although it does change the error return on private derivation from a "succeeds except with negligible probability" to "there is an error path you may need to check for".
Fixes #4308
> [backport 0.32.x] bip32: return error when attempting to derive past maximum depth

- hashes/src/hash160/mod.rs
- hashes/src/internal_macros.rs
- hashes/src/ripemd160/mod.rs
- hashes/src/sha1/mod.rs
- hashes/src/sha256/mod.rs
- hashes/src/sha256d/mod.rs
- hashes/src/sha256t/mod.rs
- hashes/src/sha384/mod.rs
- hashes/src/sha512/mod.rs
- hashes/src/sha512_256/mod.rs
- hashes/src/siphash24/mod.rs
This is a followup to https://github.com/rust-bitcoin/rust-bitcoin/pull/4010 which does some simple cleanups to the hash macros and some function signatures.
> hashes: several cleanups

- justfile
More terse more betterer - `just ulf` already.
> just: Add update-lock-files alias

- units/src/result.rs
> Introduce `map` function for `NumOpResult`

- bitcoin/src/blockdata/transaction.rs
The constructor currently has no test coverage.
> test: Add constructor test

- bitcoin/src/blockdata/transaction.rs
Use map combinator instead of match
> refactor: Use map combinator instead of match

- .github/workflows/cron-weekly-rustfmt.yml
`rustfmt` bad robot, remove trailing whitespace already.
> CI: Manually remove trailing whitespace

- chacha20_poly1305/Cargo.toml
> fix: add author to the chacha20_poly1305 crate

- .cargo/mutants.toml
- units/src/block.rs
- units/src/locktime/relative.rs
- units/src/result.rs
Weekly mutation testing found new mutants.
Add tests to kill the valid mutants.
Add deprecated functions to the exclude list so they are not mutated.
Closes #4488, Closes #4528
> units: Kill mutants found in weekly mutation testing

- bitcoin/src/psbt/mod.rs
Looks like this code was written before we added support for dividing `Amount` by `Weight`.
Refactor, no logic change.
> Use / to divide fee by weight

- primitives/tests/api.rs
Add missing backtick in comment.
> chore: add missing backticks

- bitcoin/src/bip32.rs
Refactor tests like its our job.
Co-developed-by: Jamil Lambert <jamil.lambert@proton.me>
> Clean up `bip32` test

- bitcoin/src/bip32.rs
apoelstra Each trait forwards formatting to the inner u32 index. For Hardened variants, a suffix is appended based on whether alternate formatting is used per the discussion.
See discussion: https://github.com/rust-bitcoin/rust-bitcoin/pull/4620#issuecomment-2974023604
> impl LowerHex, UpperHex, Octal, and Binary for ChildNumber

- units/src/locktime/absolute.rs
- units/src/locktime/relative.rs
In preparation for release go over the locktime rustdocs. 
Close: #4463
> Improve locktime docs

- io/src/bridge.rs
Hey team, fix correction io/src/bridge.rs
`No ide why` - `No idea why`
> minor correction bridge.rs

- primitives/src/locktime/relative.rs
> Add Arbitrary impl for relative::LockTime

- api/units/all-features.txt
- api/units/alloc-only.txt
- api/units/no-features.txt
Another PR slipped in before the check-api came into effect. Update the API files so CI is green again.
> Update the API files

- p2p/src/message.rs
Commit one:
The only purpose of the function signature using a `u32` is to ensure no overflow occurs within the body. This API doesn't mirror it's counterpart, `FeeRate::to_sat_per_kvb_*` which returns a u64. Considering `FeeRate::MAX == u64::MAX`, the respective bodies can have complimentary APIs.
Furthermore, the only use for `kvb` I am aware of is BIP-133 feefilter, which is expressed as a `u64` over the wire.
Commit two: 
The previous `i64` is obviously not type-safe and I believe it is also wrong. BIP-133 states this value is encoded as a uint64_t. The `u64` is decoded of the wire and interpreted as sats per kvb with the help of the previous commit.
> Use `FeeRate` in `FeeFilter` message

- docs/roadmap.md
This makes an effort to introduce some way of documenting dependencies between items. Please review aggressively.
> doc: Add miniscript item

- docs/bip-32.md
Add link to the roadmap file for BIP-32.
> docs: Link to bip-32 super issue

- CONTRIBUTING.md
- bitcoin/src/blockdata/script/mod.rs
- bitcoin/src/merkle_tree/mod.rs
- bitcoin/src/taproot/mod.rs
re-opening #4781 due to [this comment](https://github.com/rust-bitcoin/rust-bitcoin/pull/4781#issuecomment-3156846897)
> docs: clarify "iff" to "if and only if"

- chacha20_poly1305/src/lib.rs
- p2p/src/lib.rs
- primitives/src/lib.rs
- units/src/lib.rs
Two trivial clean ups that fell out of some other work.
> Do trivial module / extern crate clean up

- bitcoin/src/consensus/encode.rs
Currently we have a macro that implements for a vector of a bunch of types, also we implement manually for `Vec<u8>`. This was done because of the lack of specialization in Rust. However we can check the type ID of the generic type at run time and switch on it.
Implement both traits using `TypeId` to dynamically run separate code blocks for `u8` vs any other type. 
NOTE: Introduces a single line usage of `unsafe`.
> Implement `Encodable`/`Decodable` for list of `u8`

- units/Cargo.toml
We worked hard on this crate, its a team effort and at a minimum both Andrew and I should be held accountable for any bugs or mistakes made. I'm also proud of the code we produced.
Add my name to the authors list of the `units` crate.
> units: Add my name to authors list

- chacha20_poly1305/src/chacha20.rs
Correct spelling error "inefficientcies" -> "inefficiencies"
> docs: fix typo "inefficientcies" -> "inefficiencies"

- bitcoin/src/blockdata/witness.rs
There are multiple issues with these docs:
* They repeatedly say "according to the rules of BIP XYZ". Duh. We should document when we're *not* following the rules.
* In the Taproot methods, we then say that we're just looking for 0x50 bytes but not really parsing stuff, which is untrue because we do parse the witness stack...
* ...and we say that the user should call Script::is_p2tr to see if the output is really Taproot, which is untrue according to BIP 341...
* ...and we don't even explain that the user needs to call is_p2tr on the *output script* and not the script being returned from this function.
Furthermore, we have two methods `tapscript` and `taproot_leaf_script`. We say that the latter "does not return the control block". Neither one returns the control block. We don't say how …
> witness: rewrite the docs on several Taproot-related methods and deprecate one method

- bitcoin/src/blockdata/block.rs
> Do trivial import clean up

- bitcoin/src/consensus/encode.rs
As promised in https://github.com/rust-bitcoin/rust-bitcoin/pull/4762
I am not convinced that our decoding of large transactions and blocks is properly tested to make sure that we don't accidentally start rejecting very large objects. Add a unit test specifically for this.
> bitcoin: add "extreme object size" deserialization unit test

- p2p/src/message_network.rs
vulerablities -> vulnerabilities
> chore: fix grammatical typo in comment

- bitcoin/src/bip158.rs
Would be nice to have this logic change in a patch release
> Backport #4964

- consensus_encoding/src/encode/encoders.rs
At one stage during development, IIRC, I was trying to mutate the encoder from within a loop and was unable to do so so I added a current index instead. With Andrew's later improved version of `advance` this was no longer the case but I left the `cur_idx` variable in there. Remove it.
This was noticed during review but kindly left for a follow up since its an internal change.
This is a follow up to #4982
> Remove current index from `SliceEncoder`

- primitives/src/hash_types/generic.rs
Do a couple of trivial lint fixes.
Goodness me, see #5060 for why this stuff got past CI.
> units: Fix lint warnings

- bitcoin/src/crypto/sighash.rs
- p2p/src/message.rs
- units/src/sequence.rs
in sighash.rs - extra "
in message.rs "on at"
in sequence.rs - "if any of it's inputs" -> "if any of its inputs"
> docs: fix typos

- primitives/src/block.rs
- primitives/src/transaction.rs
Trivial now everything else is done - LFG!
> Implement `Encodable` for `Block`
