rust-bitcoin/rust-bitcoin

- bitcoin/src/blockdata/constants.rs
~~Script number can be up to 2^39 - 1 to encode locktime.~~
~~If it's only for the integer operation besides locktime, it must be 2^31 - 1, not 2^31.~~
I agree with apoelstra  opinion to deprecate this value.
> fix: deprecate wrong and unused max script num

- hashes/src/hkdf.rs
- hashes/src/hmac.rs
- hashes/src/internal_macros.rs
- hashes/src/lib.rs
- hashes/src/util.rs
This makes sure `Hash::Bytes` is an array. We've discussed this somewhere but I don't remember where.
I'm not sure if the second commit is actually valuable but hopefully shouldn't make things worse.
> Enforce that `Hash::Bytes` is an array

- bitcoin/src/bip152.rs
- bitcoin/src/psbt/map/input.rs
- io/src/error.rs
- units/src/amount.rs
A new nightly version (`nightly-2024-08-28`) introduces a few warnings because of our rustdocs. These are valid warnings and should be fixed, thanks `clippy` team.
(The `bip152` change is a bit sloppy, open to suggestions.)
> Fix clippy rustdocs warnings

- internals/src/macros.rs
It was correctly pointed out during review of #3215 (when we made `const_assert` panic) that using a `bool` added no additional information.
Remove the `bool` and just use unit.
> Remove bool from const_assert

- .github/workflows/rust.yml
- contrib/crates.sh
Instead of manually setting the crates list it is less error prone to do so mechanically. This required some changes to the `run_task` script which have now merged, so we update to use the new commit hash at the same time.
- Use shell to set the `CRATES` env var used by `run_task.sh`.
- Use latest revision of  rust-bitcoin-maintainer-tools
> CI: Generate `CRATES` using shell

- bitcoin/src/blockdata/script/mod.rs
- bitcoin/src/crypto/ecdsa.rs
- bitcoin/src/crypto/key.rs
- bitcoin/src/p2p/mod.rs
- bitcoin/src/pow.rs
- bitcoin/src/taproot/mod.rs
- internals/src/macros.rs
- primitives/src/lib.rs
- primitives/src/pow.rs
- primitives/src/sequence.rs
Created a macro that implements `to_hex` for types that currently have `core::fmt::LowerHex` and called it on types that have `core::fmt::LowerHex` implemented. I put the macro in the `internals` crate since there are types across the whole project that can potentially use this. 
Resolves #2869
> Create a macro that implements `to_hex` for types that have `core::fmt::LowerHex` implemented

- bitcoin/src/blockdata/transaction.rs
- primitives/src/lib.rs
- primitives/src/transaction.rs
As per title, in tiny small chunks, move the `transaction::Version` over to `primitives`. Only the type, its associated consts, and its `Display` impl are moved. The two methods are left in an extension trait.
Was originally attempted in #3253
> Move `transaction::Version` to `primitives`

- units/src/locktime/relative.rs
Its "time is measured" not "time is measure".
> units: Fix typo in measured

- bitcoin/src/sign_message.rs
- hashes/src/sha256t.rs
As brought up in issue #3102 support for Rust arrays is now much better so slice-accepting methods that require a fixed length can be replaced with a method that accepts an array.
`from_slice()` methods that require a fixed length have been deprecated and where needed a `from_byte_array()` method created that accepts an array.
There are still `from_slice` methods that rely on changes to external crates before they can be changed to arrays.
> Deprecate `from_slice` methods in favor of arrays

- hashes/src/internal_macros.rs
These are only called from within the crate but it is still more correct to use `$crate` and saves this from biting us later if we copy the code someplace else.
Internal change only.
> hashes: Use $crate in internal macros

- units/src/amount.rs
From [this comment](https://github.com/rust-bitcoin/rust-bitcoin/issues/2954#issuecomment-2325679334) in #2954, update the documentation to indicate that the Display implementation in Amount is unstable
> Update the documentation to indicate that the Display implementation in Amount is unstable

- bitcoin/src/blockdata/transaction.rs
Currently we have `all_zeros` functions and `null` functions but we can do better.
Add associated consts and improve the names to better describe what these dummy zero hashes are used for.
Deprecate related functions.
> priority: Add coinbase associated consts

- bitcoin/src/blockdata/script/instruction.rs
- bitcoin/src/blockdata/script/mod.rs
- internals/src/lib.rs
- internals/src/script.rs
The `UintError` type (returned by `read_uint_iter`) is not that useful because one variant is unreachable. Re-write the function by doing:n
- Re-write the function to reduce the error cases returned.
- Re-name it to `read_push_data_len`
- Move it to `internals`
- Use `PushDataLenLen` enum instead of an int parameter
> priority: Re-write (and re-name) `read_uint_iter`

- base58/src/lib.rs
- bitcoin/src/consensus/serde.rs
- bitcoin/src/lib.rs
- hashes/src/lib.rs
Two patches to clear the million warnings when running the bench code.
> Shoosh linter in bench build

- bitcoin/Cargo.toml
- hashes/Cargo.toml
- hashes/contrib/sanitizer.sh
- hashes/contrib/test_vars.sh
- hashes/embedded/Cargo.toml
- hashes/src/hmac.rs
- hashes/src/impls.rs
- hashes/src/internal_macros.rs
- hashes/src/lib.rs
- hashes/tests/io.rs
- hashes/tests/regression.rs
Currently we only get `std::io::Write` impls when the `bitcoin-io` dependency is used. This is overly restrictive, it would be nice to have `std::io::Write` imlps even without the `bitcoin-io` dependency.
Copy the logic out of the `bitcoin_io::impl_write` macro into `hashes` but feature gate it differently.
Call the new macro inside `hash_type` (and in `hmac`), remove the `impls` module, and move the tests to the integration test directory.
Remove the `io` feature from `hashes`, now if users enable `std` they get `std::io::Write` impls and if they enable `bitcoin-io` they get `bitcoin_io::Write` impls as well.
> hashes: Remove `io` feature

- bitcoin/src/blockdata/witness.rs
- internals/src/compact_size.rs
- internals/src/lib.rs
We would like to move the witness module to `primitives` but there is a bunch of usage of `VarInt`.
Introduce a module that does the encoding and decoding instead, note that while the functionality is internal decoding returns an error which may one day end up in the public API. So put the module in `primitives` and make it public.
Adds the module to `primitives`, adds a public `MAX_ENCODABLE_SIZE` variable that is commented with an issue link.
https://github.com/rust-bitcoin/rust-bitcoin/issues/3264
> priority: Introduce and use a new `compact_size` module

- internals/src/macros.rs
The new `impl_to_hex_from_lower_hex` macro causes build warnings when `internals` is built without the `alloc` feature.
There are two macro implementations depending on feature gates, duplicate the rustdocs from the other one.
While we are at it reduce the lines of code for the empty case.
> internals: Fix lint warnings on macro

- bitcoin/src/blockdata/constants.rs
- bitcoin/src/blockdata/transaction.rs
Either our CI is failing us or `deprecated` does not work as expected, either way we should not be using the `OutPoint::null()` or `is_null` functions any more because we deprecated them already.
> Stop using deprecated `OutPoint` functions

- bitcoin/src/blockdata/transaction.rs
The `OutPoint` type has two public fields, providing a `new` constructor that just sets these two fields adds no value.
Done after discussion in #3340 as part of `primitives` work.
> Deprecate `OutPoint::new` constructor

- .github/workflows/cron-semi-weekly-update-nightly.yml
Currently we run the job at midnight here and in `sepc256k1`, this led recently to one using the nightly toolchain from the 10th of Sep and the other using the toolchain from 11th of Sep.
Update to run at 5 past so this doesn't happen again.
> CI: Run the nightly update job at 5 past midnight

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/examples/ecdsa-psbt-simple.rs
- bitcoin/examples/sign-tx-segwit-v0.rs
- bitcoin/examples/sign-tx-taproot.rs
- bitcoin/examples/taproot-psbt-simple.rs
- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/constants.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/internal_macros.rs
- bitcoin/src/merkle_tree/mod.rs
- primitives/Cargo.toml
- primitives/src/lib.rs
- primitives/src/transaction.rs
Move the `Txid` and `Wtxid` hash wrapper types over to `primitives`. This introduces to `primitves` an unconditional dependency on `hashes`.
> priority: Move txid hash types to `primitives`

- hashes/src/cmp.rs
With a recent nightly toolchain `clippy` gives us an error:
error: missing documentation for a constant
I'm not sure why the error is emitted but wrapping the function in a `tests` module as is standard practice clears the error.
> hashes: Put test function in a module

- bitcoin/Cargo.toml
- bitcoin/src/blockdata/script/borrowed.rs
- bitcoin/src/blockdata/script/builder.rs
- bitcoin/src/blockdata/script/mod.rs
- bitcoin/src/blockdata/script/tests.rs
- primitives/Cargo.toml
Move the `Script` and `ScriptBuf` types to `primitives`. There were still a few preparations required, things we had missed while creating the extension traits.
Note also please, in the last patch, we enable `hex` from the `serder` feature. This is not the final state we want but like we did for `alloc` it is a step to reduce the size of the diff.
> priority: Prepare moving script types to `primitives`

- units/src/amount.rs
closes https://github.com/rust-bitcoin/rust-bitcoin/issues/3307
> Add a condition for parsing zero from string when not denominated.

- bitcoin/src/sign_message.rs
Closes #3249 
Seems not required for Kixunil's immediate use case anymore, but figured I'd open a PR anyways.
> Support `impl AsRef<[u8]>` in `signed_msg_hash`

- bitcoin/src/merkle_tree/mod.rs
Removes unnecessary usage of vector and adds a missing assert. Closes #3353.
Note: Kixunil in the [referred comment](https://github.com/rust-bitcoin/rust-bitcoin/pull/3288#discussion_r1756514494) wondered about missing 'unused variable' warning. It seems that rustdoc [adds](https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html#pre-processing-examples) allows to the documentation tests. However, these warnings [can be enabled](https://doc.rust-lang.org/rustdoc/write-documentation/documentation-tests.html#showing-warnings-in-doctests) on module level. Do we want that? I tried to enable and there are already some occurrences of unused variables and imports. Caveat: it seems that we can't deny warnings on that, only print the warnings to stdout with `--show-output`.
> Improve documentation test in merkle_tree

- bitcoin/src/psbt/mod.rs
- bitcoin/tests/psbt-sign-taproot.rs
- The first commit is the simplest fix for a bug where the fingerprint wasn't compared correctly.
- The second & third commits are optional refactoring to reuse `Xpriv::get_key` for `$set<Xpriv>::get_key`, so the Xpriv matching logic only has to be maintained in one place.
- The forth commit adds support for signing with `Xpriv`s that are direct children of the `KeySource` -- possibly what the original (buggy) code author had in mind?
Of course, feel free to take just the first commit if the others seem unnecessary. The last one is kind of meh, not sure if really useful.
Note that multi-`Xpriv` signing does not actually work until #2850 is addressed too.
> Fix GetKey for sets (plus some related changes)

- internals/src/macros.rs
Moving the feature flag inside the macro definition. Since the feature flag is moved inside the macro def, we don't need to keep the definition of the one behind `#[cfg(not(feature = "alloc"))]`
Fixes #3348
> Move feature flag inside impl_to_hex_from_lower_hex macro

- bitcoin/src/psbt/mod.rs
It appears that the `BTreeSet<Xpriv>`/`HashSet<Xpriv>` sets currently implementing `GetKey` cannot actually be constructed, because `Xpriv` does not implement `Ord` nor `Hash`. (And that the rust-bitcoin code referencing these sets should not even compile? yet evidently it does :eyes: )
This PR adds support for `Vec<Xpriv>` to enable signing with multiple `Xpriv`s, but does not address the issue with the existing sets.
The added test case demonstrates the issue:
```rust
error[E0277]: the trait bound `bip32::Xpriv: std::hash::Hash` is not satisfied
--> bitcoin/src/psbt/mod.rs:2301:24
|
2301 |         HashSet::new().insert(xpriv.clone());
|                        ^^^^^^ the trait `std::hash::Hash` is not implemented for `bip32::Xpriv`
|
note: required by a bound in …
```
> Implement GetKey for Vec<Xpriv>

- units/src/fee_rate.rs
Update doc comment to make clear that the ceiling is computed instead of the default behavior for integer division.
> Add doc comment detailing fee calculation

- addresses/src/lib.rs
- base58/src/lib.rs
- bitcoin/src/address/mod.rs
- bitcoin/src/bip32.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/crypto/sighash.rs
- bitcoin/src/lib.rs
- bitcoin/src/merkle_tree/block.rs
- bitcoin/src/network/params.rs
- bitcoin/src/psbt/map/input.rs
- hashes/src/lib.rs
- internals/src/lib.rs
- internals/src/macros.rs
- io/src/lib.rs
- primitives/src/lib.rs
- primitives/src/locktime/absolute.rs
- primitives/src/locktime/relative.rs
- units/src/lib.rs
As mentioned in #3362 examples in documentation are not linted in the same way as other code, but should still contain correctly written code.
#![doc(test(attr(warn(unused))))] has been added to all lib.rs files
In the docs throughout all crates:
- Unused imports have been removed.
- Unused variables, structs and enums have been used e.g. with an `assert_eq!` or prefixed with `_`
- Unused methods have been called in the example code.
> Remove unused inports, and fix unused variables and methods in docs

- bitcoin/src/crypto/sighash.rs
With the stricter doc tests required to pick up unused imports etc. the code under the `compile_fail` tag also creates an Error.
Changed `compile_fail` to `ignore` to remove the Error.
> Ignore doc example that has a compile error

- justfile
In order to show warnings for unused imports etc. in doc examples as mentioned in #3362, an extra test has been added to the justfile for `just lint` and the doc test in `just sane` has been removed since it calls `just lint`.
> Add stricter doc test to justfile

- primitives/Cargo.toml
We keep optional deps in a separate group to non-optional deps, move the new `arbitrary` dependency.
Internal change only.
> primitives: Move optional dependency to correct place

- Cargo-minimal.lock
- Cargo-recent.lock
- base58/Cargo.toml
- bitcoin/Cargo.toml
- internals/CHANGELOG.md
- internals/Cargo.toml
- io/Cargo.toml
- primitives/Cargo.toml
- units/Cargo.toml
In preparation for releasing `internals v0.4.0` bump the version number, add a changelog entry, update the lock files, and depend on the new version in all crates that depend on `internals`.
> Release tracking PR: `bitcoin-internals 0.4.0`

- hashes/src/hash160.rs
- hashes/src/hmac.rs
- hashes/src/lib.rs
- hashes/src/ripemd160.rs
- hashes/src/sha1.rs
- hashes/src/sha256.rs
- hashes/src/sha256d.rs
- hashes/src/sha384.rs
- hashes/src/sha512.rs
- hashes/src/sha512_256.rs
- hashes/src/siphash24.rs
- hashes/src/util.rs
The hash engine types have a `length` field that is used to cache the number of bytes hashed so far, as such it is an arbitrary number and could use a `u64` instead of `usize`.
While we are at it rename `length` to `bytes_hashed` to remove any ambiguity of what this field is. Note this field is private, we already have the public getter `n_bytes_hashes` to get the value.
Introduce a private function `incomplete_block_size`, the purpose of this function is to put all the casts in one place so they can be well documented and easily understood.
Fix: #3016
> hashes: Rename length field and use u64

- README.md
Currently we use the word "always" in the MSRV docs, we mean to say "there are no set of features that will break the build" but this usage of "always" may be interpreted as "always, for all time" which is definitely not what we mean.
Soften the wording on MSRV by removing the word always.
> Soften wording on MSRV

- units/src/fee_rate.rs
I can't think of a reason to not support addition and subtraction with `fee_rate`.  If two fee rates are added, the resulting units `sat/wu` units are viable.
Without this, I have to do some shenanigans like:
```rust
let tmp = fee_rate.to_sat_per_kwu();
fee_rate = FeeRate::from_sat_per_kwu(tmp - 1);
```
> Add FeeRate addition and subtraction traits

- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/crypto/sighash.rs
- bitcoin/src/psbt/mod.rs
Currently we provide `Default` implementations for a couple of types in the `transaction` module, the values returned are meaningless and it seems these impls were added to make writing test code easier. In hindsight this was the wrong thing to do.
Break the API and remove the `Default` implementations for `OutPoint` and `TxIn`.
Add an associated const `TxIn::EMPTY_COINBASE` that is, as the name suggests, an empty transaction input with the prevout set to all zeros as for the coinbase transaction.
> transaction: Remove `Default` implementations

- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/address/mod.rs
- bitcoin/src/blockdata/constants.rs
- bitcoin/src/blockdata/script/builder.rs
- bitcoin/src/blockdata/script/tests.rs
- fuzz/fuzz_targets/bitcoin/deserialize_script.rs
Fix the issue https://github.com/rust-bitcoin/rust-bitcoin/issues/1530. In the discussion of https://github.com/rust-bitcoin/rust-bitcoin/issues/1530, the suggested solution is to implement `ScriptInt` type to embrace the various type of integer(`i32, u32, i64, u64, i128, u128, isize, usize...`) to support both script number and locktime number.
However, as `push_locktime` and `push_sequence` implemented, there’s no need to support `u32` of lock time for `push_int` anymore. Therefore, I’ve just changed the type of parameter to `i32`, and only check if it’s `i32::MIN`(which overflows 4 bytes sign-magnitude integer).
~I also added push_uint method to use internally for `push_locktime` and `push_sequence`, which have a dependency on `push_int` method.~
UPDATE: also add `push_int_unchecked` …
> fix: script number overflow check for push_int

- .github/workflows/rust.yml
Recently we discovered a bug in the `run_task` script where we forgot to use `--no-default-features` in a subset of test runs (the feature matrix stuff).
Upgrade to use the latest version of `run_task.sh`.
> CI: Use latest run_task version

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/CHANGELOG.md
- bitcoin/Cargo.toml
In preparation for doing a point release add a changelog entry, bump the version number, and update the lockfiles.
This release is just the single PR currently on the `0.32.x` branch, no point backporting if we don't release it.
> Release tracking PR: `bitcoin 0.32.3`

- bitcoin/src/crypto/ecdsa.rs
- bitcoin/src/crypto/sighash.rs
- bitcoin/src/crypto/taproot.rs
Implementing `Arbitrary` for some signature types in preparation for #3366
> Implement Arbitrary for signature types

- bitcoin/examples/bip32.rs
- bitcoin/examples/ecdsa-psbt-simple.rs
- bitcoin/examples/ecdsa-psbt.rs
- bitcoin/examples/taproot-psbt-simple.rs
- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/bip32.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/tests/bip_174.rs
Adds `Xpriv::to_xpub` and makes naming of methods related to extended and non-extended keys on `Xpub` and `Xpriv` consistent and easier to discover:
- if method takes or returns extended key, its name uses `xpriv` or `xpub`
- if method takes or returns non-extended key, its name uses `public_key` or `private_key`
Previous naming of the methods was confusing and unclear and this PR deprecates them.
Closes #3327.
- `xpriv` and `xpub` could be without `x`, I opted for this version to remove any ambiguity
- also considered `raw` or similar name (as suggested) for methods with non-extended keys, however `raw` is usually not used in this context and `to_public_key` vs. `to_x_only_public_key` did not look alright with any other name
- if splitting this PR into two would be desirable, please let …
> Add Xpriv::to_xpub and improve related method names

- bitcoin/src/merkle_tree/mod.rs
- primitives/src/lib.rs
- primitives/src/merkle_tree.rs
In preparation for moving the `block::Header` struct over to `primitives` move the `merkle_tree` hash types.
> Move `merkle_tree` hash types to `primitives`

- bitcoin/src/bip152.rs
- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/constants.rs
- bitcoin/src/p2p/message_blockdata.rs
- bitcoin/src/pow.rs
- primitives/src/block.rs
- primitives/src/lib.rs
As an initial step in moving the `block` module, just move over the hash types `BlockHash` and `WitnessCommitment`.
Patch 2 introduces an associated const `BlockHash::GENESIS_PREV_BLOCKHASH` and removes `all_zeros`.
> Move the `block` hash types over to `primitives`

- bitcoin/src/blockdata/witness.rs
In preparation for moving the `Witness` type over to `primitives` refactor and improve all the unit tests that will be moved, do not touch the ones that will stay behind.
The first five patches are from #3406, the last is just a re-name of the test function I tried to refactor in https://github.com/rust-bitcoin/rust-bitcoin/commit/ac6fe3a8815127e8c4df5fbe3f8a7241679e7c48
> Improve `witness` unit tests

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/src/bip152.rs
- bitcoin/src/blockdata/transaction.rs
- primitives/Cargo.toml
- primitives/src/transaction.rs
Just the minimal move of `OutPoint` to `primitives`.
The last patch closes #3347
> Move `OutPoint` to `primitives`

- hashes/src/lib.rs
In b9643bf3e9b21e4e2207ea210d1d57ffa014d271 we introduced an incorrect `cfg` attribute, that has just shown up, no clue why clippy only just presented me with this error now. Anywho, the current code is buggy and the rustdoc tests are never being run.
Fix `cfg` attribute to use the feature name correctly and fix the imports so the code runs.
Maintain the explicit `main` so that we can return an error using the `?` operator. Remove the empty `main` because its not needed anymore, it is a hang-over from Rust back in the day (before main was automatically added, IIUC).
> Fix buggy cfg in rustdocs

- hashes/src/sha256.rs
This is a follow up to #3010
Fixes #3079
> Rename Midstate::into_parts to Midstate::to_parts since it derives Copy

- bitcoin/src/blockdata/witness.rs
Prepare `Witness` to be moved to `primitives`.
This is the first three patches out of #3406. Patch 1 and 2 are internal changes, path 3 is also internal but introduces a slight perf hit by doing multiple writes.
> Prepare `Witness`

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/Cargo.toml
- primitives/Cargo.toml
- units/CHANGELOG.md
- units/Cargo.toml
In preparation for releasing `units v0.2.0` bump the version number, add a changelog entry, update the lock files, and depend on the new version in all crates that depend on `units`.
Close: #3095
> Release tracking PR: `bitcoin-units 0.2.0`

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/Cargo.toml
- hashes/Cargo.toml
- io/CHANGELOG.md
- io/Cargo.toml
- primitives/Cargo.toml
In preparation for releasing `io v0.2.0` bump the version number, add a changelog entry, update the lock files, and depend on the new version in all crates that depend on `io`.
> Release tracking PR: `bitcoin-io v0.2.0`

- bitcoin/src/address/mod.rs
- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/constants.rs
- bitcoin/src/blockdata/script/push_bytes.rs
- bitcoin/src/lib.rs
- bitcoin/src/network/mod.rs
- bitcoin/src/network/params.rs
- bitcoin/src/p2p/mod.rs
- bitcoin/tests/psbt-sign-taproot.rs
Fixed: https://github.com/rust-bitcoin/rust-bitcoin/issues/2749
1. Adjust `Network` to support `Testnet4`. (Based on https://github.com/rust-bitcoin/rust-bitcoin/issues/2749#issuecomment-2152366608 as an implementation idea.)
2. Handle conflicting procedure macros and declaration macros, since the original macros can't handle the new `Network::Testnet(TestnetVersion)` structure properly, and make internal implementations compatible with previous versions (e.g., `testnet` for `Testnet3`, `testnet4` for `Testnet4`, to minimize user-side effects). 
3. add `Testnet4` related Params, Block. 
4. optimize compatibility test cases.
5. Regarding `fn: genesis_block`, calling `bitcoin_genesis_tx` with any Network type internally gets a reasonable `merkle_root`, but not `Testnet4`. (By comparison, I …
> Support Testnet4 Network

- CONTRIBUTING.md
Example code in rustdocs should be error free and not produce warnings when copy pasted.
The section on rustdocs has been expanded to clarify that example code should compile without any errors or warnings with the stricter `lint` that has been added to the justfile.
All existing example code in the rustdocs has now been fixed and there are no warnings from unused code, the justfile has been updated to have a stricter `lint` which produces warnings and this addition to `CONTRIBUTING.md` has clarified that new additions should follow these rules.
Close #3362
> Add stricter rustdoc requirement to `CONTRIBUTING.md`

- primitives/src/sequence.rs
c24630e7b13312ea34f0f54ed832783ced8dde3f
- `LOCKTIME` is used for both absolute and relative one without clear classification, which is confusing and could lead to an unexpected bug. Although it's API breaking change, current constant is so ambiguous unless understand the details of `LOCKTIME` semantic.
9cc5dfeef178f03ea4d0786cfbaa3b8709fed644
- Add constant `ENABLE_ALL` and `DISABLE_ALL`, which is useful for those who want to enable(disable) rbf, absolute/relative locktime.
> sequence: clarify sequence constant name and add FINAL

- bitcoin/src/blockdata/transaction.rs
Following up on https://github.com/rust-bitcoin/rust-bitcoin/issues/630#issuecomment-2392050517.
I amended the docstring on `InputWeightPrediction::weight()` to clarify that it only returns the signature weight. I'm not sure what the rationale was for only returning partial input weight, and if there are any arguments against something like `InputWeightPrediction::total_weight()` which returns `self.weight() + Weight::from_non_witness_data_size(32 + 4 + 4)` (and maybe deprecate `weight()` eventually to prevent misuse).
> Input weight prediction helpers for nested P2WPKH

- hashes/src/ripemd160.rs
- hashes/src/util.rs
In #3298 `HashEngine.length` was changed to `HashEngine.bytes_hashed` and changed from `usize` to `u64`.  
Behind a `hashes_fuzz` feature gate there were a couple of occurrences of length that had not been updated and caused a fuzztest failure.  These have been updated to the new name and type.
Fix #3448
> Fix fuzztest failure

- units/src/amount.rs
- units/src/fee_rate.rs
Adds the checked variant of `amount / weight`.  I also added a test to the non-checked version for comparison so the reviewer knows they compute the same way (integer division rounded down).
Also added assertion to `checked_weight_mul test` showing the results are rounded up.
> Add checked div by weight to amount

- primitives/src/sequence.rs
We just renamed this and forgot to use the new name. This should have been caught by CI.
> Use new Sequence::ENABLE_RBF_AND_LOCKTIME

- bitcoin/src/blockdata/transaction.rs
- primitives/src/transaction.rs
Topologically restricted transactions are now considered standard as of Bitcoin 28.0.
> Add version three variant to transaction version

- bitcoin/src/blockdata/transaction.rs
Ran `./maintainer-tools/ci/run_task.sh stable` without error locally, so I don't think this import is needed.
> Remove unused import

- addresses/src/lib.rs
- base58/src/lib.rs
- bitcoin/src/address/script_pubkey.rs
- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/blockdata/witness.rs
- bitcoin/src/crypto/ecdsa.rs
- bitcoin/src/crypto/sighash.rs
- bitcoin/src/lib.rs
- bitcoin/src/merkle_tree/block.rs
- bitcoin/src/psbt/error.rs
- bitcoin/src/psbt/macros.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/src/psbt/serialize.rs
- bitcoin/src/taproot/merkle_branch.rs
- bitcoin/src/taproot/mod.rs
- hashes/src/hmac.rs
- hashes/src/internal_macros.rs
- hashes/src/lib.rs
- hashes/src/serde_macros.rs
- hashes/src/util.rs
- internals/src/lib.rs
- primitives/src/lib.rs
- units/src/lib.rs
This is a bit curly because of current `serde` logic, fixed in patch 4. All the other patches are trivial.
> Enable attribute `deprecated_in_future`

- bitcoin/CHANGELOG.md
When we create point releases we merge the release tracking PR directly into the version branch, including the changelog entries. This means the changes never end up on `master`. We need to make a mental note to patch `master` anytime we merge a point release PR.
Audit all crates with a non-zero current point release and check we have the changelog entries on `master`.
> Update CHANGELOG files

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/Cargo.toml
Recently we added a use of `Arbitrary` for `[u8; 64]` (schnorr sig). I hit a build failure locally and discovered that
- `arbitrary 1.0.0` does not implement `Arbitrary` for 64 byte array
- We use `arbitrary = 1` in the `bitcoin` manifest
- We have `arbitrary 1.3.2` in the `Cargo-minimal.lock` file
Fix this all up by doing:
- Use `1.0.1` in the `bitcoin` manifest because that is a hard minimum version required to build
- Downgrade the `Cargo-minimal.lock` file to use `arbitrary v1.0.1`
- Upgrade the `Cargo-recent.lock` file while we are at it for good measure.
> Update lock files and downgrade minimum arbitrary

- bitcoin/src/sign_message.rs
- io/src/lib.rs
- units/src/fee_rate.rs
New lint warnings from a recent nightly toolchain show some explicit lifetimes that can be omitted.
The unnecessary lifetimes have been removed.
An unused import warning has also been fixed by placing the use statement behind the relevant feature gate.
> Fix lint errors

- bitcoin/src/bip32.rs
- bitcoin/src/blockdata/constants.rs
- bitcoin/src/blockdata/script/borrowed.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/blockdata/witness.rs
- bitcoin/src/crypto/ecdsa.rs
- bitcoin/src/crypto/taproot.rs
- bitcoin/src/hash_types.rs
- bitcoin/src/network/params.rs
- bitcoin/src/p2p/mod.rs
- bitcoin/src/pow.rs
- bitcoin/src/sign_message.rs
- bitcoin/src/taproot/merkle_branch.rs
- hashes/src/sha256.rs
- hashes/src/sha256t.rs
- primitives/src/sequence.rs
- units/src/amount.rs
Following the suggestion in Issue #3306 all the deprecated note fields have been changed to be lower case and in the format "use `abc` instead".
> Unify deprecated note field format

- bitcoin/src/consensus/serde.rs
In serde `#[allow(unused_variables)]` has been dropped and the unused variables have been "used" when `debug_assertions` is off.
Close #3332
> Remove `allow_unused` flag in serde

- CHANGELOG.md
- README.md
Add links to the README and also add a workspace root dummy CHANGELOG file with the same links.
This is Steven's patch from #3169 shepherded in by me.
> Make changelogs more discoverable

- bitcoin/src/lib.rs
We are trying to make our upgrade path as painless as possible, as such we are deprecating things and leaving them in for ages. Some things are hard to deprecated (e.g. struct field re-names). A solution is to deprecated in a point release to `0.32.x` so that when users eventually upgrade to use `primitives` they will already have done a bunch of the changes (or preparations).
As an example, we want to change the transaction field names. If we deprecated them in a `0.32.x` point release and add getter functions then in `primitives` we can use the new names (and eventually deprecate the original getters if we want to).
To try and keep the diff between `0.32.x` and master as small as possible lets just allow deprecated things on the `0.32.x` branch. This way we can have some chance of …
> bitcoin: Allow deprecated

- Cargo-minimal.lock
- Cargo-recent.lock
- Cargo.toml
- chacha20_poly1305/Cargo.toml
- chacha20_poly1305/README.md
- chacha20_poly1305/contrib/test_vars.sh
- chacha20_poly1305/src/chacha20.rs
- chacha20_poly1305/src/lib.rs
- chacha20_poly1305/src/poly1305.rs
Hopefully this isn't a little too (or grossly) ambitious, but figured I'd open a PR for feedback and guidance.
BIP324 depends on the ChaCha20 stream cipher and the Poly1305 authenticator. We coded these up for our [BIP324 library](https://github.com/rust-bitcoin/bip324/tree/main/protocol/src/chacha20poly1305) (this is mostly copy/paste from there), but I believe we want these lower-level protocols to live in rust-bitcoin. This follows with how Core has its implementation and also lets others in the ecosystem depend on it. For example, the Payjoin project is looking to specifically use this AEAD algorithm.
While I don't believe this is a case of "rolling your own crypto" since the intention was to match the RFCs, and all test vectors are coded up and passing, I'll admit to being a bit …
> Add the ChaCha20Poly1305 AEAD algorithm

- bitcoin/src/bip152.rs
- bitcoin/src/bip158.rs
- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/locktime/absolute.rs
- bitcoin/src/blockdata/script/mod.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/blockdata/witness.rs
- bitcoin/src/consensus/encode.rs
- bitcoin/src/internal_macros.rs
- bitcoin/src/lib.rs
- bitcoin/src/merkle_tree/block.rs
- bitcoin/src/p2p/address.rs
- bitcoin/src/p2p/message.rs
- bitcoin/src/p2p/message_blockdata.rs
- bitcoin/src/p2p/message_bloom.rs
- bitcoin/src/p2p/message_network.rs
- bitcoin/src/p2p/mod.rs
- bitcoin/src/pow.rs
- bitcoin/src/psbt/macros.rs
- bitcoin/src/psbt/map/global.rs
- bitcoin/src/psbt/raw.rs
The Rust world has, sadly, standardized on `Read` for the type from which objects are deserialized. This makes forcing users into `BufRead`s in a library crate somewhat impractical - a `rust-bitcoin` user may implement some deserialization trait provided by a third-party and be stuck with a `Read`. Now, to read a `rust-bitcoin` object they'll have to wrap the `Read` in some `BufRead` wrapper that only buffers single bytes, wrecking their performance. While the user who is using this library should pass a `BufRead` (and may do so), the library using `rust-bitcoin` may not have any choice in the matter.
Thus, here, we standardize on the same trait that the entire Rust world has standardized on, using `Read` for bounds in deserialization methods rather than `BufRead`.
Here we avoid …
> [0.32] Bound decode methods on `Read`, rather than `BufRead`

- bitcoin/src/sign_message.rs
Follow up https://github.com/rust-bitcoin/rust-bitcoin/pull/3456.
add test to verify the signature generated from newly added `sign` fn.
> test: add test for new sign fn

- bitcoin/src/blockdata/block.rs
- bitcoin/src/pow.rs
- primitives/src/block.rs
- Patch 1: Trivial preparation. 
- Patch 2 and 3: Reduce the API surface in a disappointing way due to the orphan rule.
- Patch 4: Do the move.
> Move `block::Header` to `primitives`

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/Cargo.toml
We would like to create branches in other repos/crates that track master in this repo for testing purposes. In order to do so we need a non-0.32 version otherwise `cargo` pulls from crates.io.
Set the version to `0.33.0-alpha` - try not to get too excited, this release is a looong way away.
> bitcoin: Set version to `0.33.0-alpha`

- Cargo-minimal.lock
- Cargo-recent.lock
- README.md
- bitcoin/examples/ecdsa-psbt-simple.rs
- bitcoin/examples/sign-tx-segwit-v0.rs
- bitcoin/examples/sign-tx-taproot.rs
- bitcoin/examples/taproot-psbt-simple.rs
- bitcoin/src/blockdata/witness.rs
- internals/Cargo.toml
- internals/src/serde.rs
- primitives/Cargo.toml
- primitives/README.md
- primitives/src/lib.rs
- primitives/src/witness.rs
Patch 1 introduces a new policy to the codebase, we use `foo__unstable` for public unstable functions and there are zero semver guarantees if you call these functions.
Patch 2 does the move.
Close #3406
> Move `Witness` to `primitives`

- bitcoin/src/pow.rs
As discussed in https://github.com/rust-bitcoin/rust-bitcoin/pull/2740#issuecomment-2420076657 this is a backport of #2740 to 0.32.x. I've simply cherry-picked the commit and all tests are passing locally.
> backport 2740 (diff adjustment) to 0.32

- bitcoin/src/address/script_pubkey.rs
- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/script/borrowed.rs
- bitcoin/src/blockdata/script/owned.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/blockdata/witness.rs
- bitcoin/src/consensus_validation.rs
- bitcoin/src/internal_macros.rs
- bitcoin/src/pow.rs
The extension traits are temporary just while we try to stabalize `primitives`, they are not intended to be implemented by downstream.
Seal the extension traits so that downstream crates cannot implement them.
Fix: #3231
> Seal extension traits

- bitcoin/src/blockdata/script/borrowed.rs
- bitcoin/src/crypto/key.rs
- bitcoin/src/crypto/sighash.rs
- bitcoin/src/taproot/mod.rs
- primitives/src/lib.rs
- primitives/src/taproot.rs
Move the three `taproot` hash types and their associated tags over to the `primitives` crate.
First two patches are preparation, third on is the move - this one is a no-brainer.
> Move `taproot` hash types to `primitives`

- hashes/contrib/wasm.sh
The WASM job is not working. `wasm-pack build` works fine but `wasm-pack test` doesn't compile.
Comment out the line that runs `wasm-pack test`.
> CI: Hobble WASM job

- internals/src/serde.rs
Linter with new nightly toolchain finds another lifetime that can be elided, do so.
> Remove unnecessary lifetimes

- bitcoin/src/address/error.rs
- bitcoin/src/address/mod.rs
In #2381 we attempted to fully encapsulate the `bech32` crate to help with stabalizing `rust-bitcoin` however we failed to notice the `address:ParseError` has a variant that includes `bech32`. Public enums have public variant internals in Rust. Also the `From<bech32::segtiw::DecodeError` makes `bech32` public.
Closes: #3043
> Remove `bech32` from `address::ParseError`

- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/mod.rs
- bitcoin/src/blockdata/witness.rs
- bitcoin/src/lib.rs
- bitcoin/src/merkle_tree/mod.rs
- primitives/src/lib.rs
- primitives/src/locktime/absolute.rs
- primitives/src/locktime/relative.rs
Up until recently we were using wildcard re-exports for types moved to `units` and `primitives`. We have decided against doing so in favour of explicit re-exports.
Audit `units` and `primitives` using `git grep 'pub enum'` (and `struct`) and explicitly re-export all types.
Remove all wildcards except for the re-exports from `opcodes`, there are too many opcodes, explicitly re-exporting them does not aid clarity.
> Explicitly re-export stuff from crates down the stack

- bitcoin/src/psbt/macros.rs
- bitcoin/src/psbt/map/input.rs
Using fully qualified paths in macros reduces maintenance burden. We have one macro where we use relative path to access the `psbt` module.
Refactor only, no external change.
> Use fully qualified path in macro

- bitcoin/src/psbt/raw.rs
In #2906 we switched from using a `u8` for type keys to using a `u64` and encoding as a compact int (inline with the spec). Note that a `u8` encodes to the same bytes as a `u64` when the value is < 252.
In that patch, I introduced a bug because the length returned by `PoprietaryKey::consensus_encode` uses a hard code 1 for the length of the encoding (because of single byte) instead of the variable length for the new compact encoding.
Bug showed up in fuzzing, and was isolated by Jamil - mad props.
Fix: #3501
> psbt: Fix bug in Subtype consensus_encode

- bitcoin/CHANGELOG.md
While upgrading `miniscript` to use tip of master I made some notes to help users upgrade. Just throw them in the changelog file or now.
> bitcoin: Add some upgrade notes

- bitcoin/src/p2p/message.rs
> I'd like to take out the `payload` of RawNetworkMessage and then send it to the actual network message processor, but finds there is no way to do it. This commit adds such an API to expose the owned value of inner `payload`.
Quoted from original author, but as they said this would be a nice-to-have
> Add API for extracting the inner payload of RawNetworkMessage

- bitcoin/examples/ecdsa-psbt.rs
- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/address/mod.rs
- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/mod.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/consensus_validation.rs
- bitcoin/src/crypto/sighash.rs
- bitcoin/src/psbt/mod.rs
- fuzz/fuzz_targets/bitcoin/deserialize_transaction.rs
- hashes/src/siphash24.rs
- primitives/src/lib.rs
- primitives/src/transaction.rs
First introduce the `Transaction` extension traits manually (without using the `define_extension_trait` macro) then move the `Transaction` to `primitives`.
Note please patch 5, ugly due to language requirements.
> Move `Transaction` to `primitives` 

- chacha20_poly1305/CHANGELOG.md
The initial release for the `chacha20-poly1305` crate. No other preparation needed for release since the version, `v0.1.0`, is already set in Cargo.toml.
> Release tracking PR: `chacha20-poly1305` v0.1.0

- bitcoin/src/internal_macros.rs
- bitcoin/src/lib.rs
There is an unstable feature that puts up a little 'i' in a circle next to any function that returns a type that implements an notable trait. For us this means we can make the extension traits more discoverable.
ref: https://doc.rust-lang.org/unstable-book/language-features/doc-notable-trait.html
Close: #3232
> Use `doc(notable_trait)`

- base58/src/error.rs
- base58/src/lib.rs
Currently we have a bunch of public errors in the `base58` crate. Only two are returned by public functions `decode()` and `decode_check()` (`Error` and `InvalidCharacterError` respectively).
- Close the two public errors by adding private inner errors.
- Add getters on the public errors to get the error data.
- Make all other errors private.
- Call `impl_from_infallible` for _all_ error types.
Done as part of #3261
> base58: Close all errors

- chacha20_poly1305/src/chacha20.rs
- chacha20_poly1305/src/lib.rs
- chacha20_poly1305/src/poly1305.rs
I unfortunately forgot to copy over the `no_std` configuration when I promoted the chacha20_poly1305 from an internal module (where it inherited the setting) to the main module of the new crate.
This crate is using a slightly simpler no_std pattern than some other crates in the org. I like the simple approach, but can update it if consistency is valued in this case.
> Add no_std flag to the chacha20-poly1305 crate

- hashes/CHANGELOG.md
The version has already been bumped on `master`.
In preparation for releasing `hashes v0.15.0` add a changelog entry.
> Release tracking PR: `bitcoin_hashes 0.15.0`

- addresses/src/lib.rs
- bitcoin/src/address/mod.rs
- bitcoin/src/blockdata/constants.rs
- bitcoin/src/blockdata/witness.rs
- bitcoin/src/lib.rs
- hashes/src/lib.rs
- internals/src/lib.rs
- io/src/lib.rs
- primitives/src/lib.rs
- primitives/src/witness.rs
- units/src/lib.rs
This has been fixed and we use nightly to lint so we have access to the merged fix.
> Remove needless_borrows_for_generic_args

- primitives/src/lib.rs
Add re-exports of types from `taproot` and `merkle_tree`.
> primitives: Add missing re-exports

- Cargo-minimal.lock
- Cargo-recent.lock
- io/CHANGELOG.md
- io/Cargo.toml
In preparation for release bump the version, add a changeloge entry, and update the lock files.
> io: Bump version to 0.1.3

- primitives/src/locktime/absolute.rs
- primitives/src/locktime/relative.rs
- primitives/src/sequence.rs
During move of code to `primitives` we removed a few links to types that were not yet moved, we can now put these back in.
Close: #2997
> primitives: Add rustdoc links back in

- bitcoin/src/lib.rs
- primitives/src/lib.rs
For users who want to just grab stuff from the crate root it makes total sense for there to be a `BlockHeader`.
Another nice thing, in the HMTL docs it makes BlockHeader be in the struct list right along with `Block`, `BlockHash`, and `BlockHeight`.
Close: #3548
> Re-export `block::Header` as `BlockHeader`

- bitcoin/src/lib.rs
- primitives/src/lib.rs
Is there any advantage trying to lay out the re-exports to give users an idea of the crate structure?
We have the explicit aim that users who depend on `bitcoin` do not ever need to reach directly into `primitives` (or `units`) however it is kind of nice to know where things come from, saves jumping to multiple files looking for them (for those of us that jump to files manually).
I do not know how all the re-exports interact with other folks IDEs, I personally open files manually and just remember where stuff is.
> bitcoin: Re-format crate level re-exports

- bitcoin/examples/taproot-psbt.rs
- units/src/amount/signed.rs
- units/src/amount/tests.rs
- units/src/amount/unsigned.rs
- units/src/fee_rate.rs
- units/src/lib.rs
Improve the `amount` module by doing:
- Patch 1: Add/update `from_int_btc` and `from_int_btc_const` functions
- Patch 2:  Add type to debug output for `Amount`
- Patch 3: Fix incorrect docs
- Patch 4: Make docs use correct style and be uniform across the two amount types
- Patch 5: Fix docs on `FromStr`
> Improve the `amount` module

- hashes/src/error.rs
- hashes/src/internal_macros.rs
- hashes/src/lib.rs
- hashes/src/sha256t.rs
Hide the internals of the `hashes::FromSliceError`.
> hashes: Hide error internals

- bitcoin/src/address/mod.rs
Change the wording of the Address constructor function docs to be a standard format. Following up on [#3584 comment](https://github.com/rust-bitcoin/rust-bitcoin/pull/3584#issuecomment-2457197066)
> Reword `Address` constructor docs

- chacha20_poly1305/README.md
Making it clear in the chacha20-poly1305 documentation that this implementation is maintained by bitcoin developers and targeted specifically for bitcoin ecosystem use cases.
> Add callouts to the chacha20-poly1305 public docs

- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/script/push_bytes.rs
- bitcoin/src/lib.rs
- chacha20_poly1305/src/lib.rs
- primitives/src/lib.rs
- units/src/amount/signed.rs
- units/src/amount/unsigned.rs
When we messed with the re-exports recently we failed to notice that the formatter would move the `pub use` blocks around because I only put `rustfmt::skip` on one block, I thought that had the effect of stopping all exports below that block being changed, turns out I was wrong.
Run the formatter then make some minor changes to the re-exports in `bitcoin`, including changing comments that do not make sense with the new layout.
> Fix re-exports and (manually) format the codebase

- units/src/fee_rate.rs
This is partially to check my understanding. I did poorly in physics class as part of my misunderstanding of unit conversions. 
The `feefilter` message expresses the fee as satoshis per 1,000 vbyte, see the [p2p handling](https://github.com/bitcoin/bitcoin/blob/1dda1892b6bcc3d4f9678960cc9e9920f491e87e/src/net_processing.cpp#L5331) which calls [this function](https://github.com/bitcoin/bitcoin/blob/master/src/policy/feerate.h#L63) on the mempool. I presume all that needs to happen to express this in `kwu` is to divide by 4, but ideally a `FeeRate` may be constructed directly from a `feefilter` message using a constructor. 
My conversion is (sat / kvb * kvb / 4 kwu)
> Add constructor to `FeeRate`

- units/src/weight.rs
We discussed marking from_vb as const here: https://github.com/rust-bitcoin/rust-bitcoin/issues/3602
However, from what I can tell, map() isn't const and I don't see a tracking issue for changing it.  Also, the question mark operator isn't available in const context either, although there is a tracking issue for that: https://github.com/rust-lang/rust/issues/74935.  It will be a long while before that makes it into this projects MSRV if/when it lands.
There are some other functions in this module that could use the same re-write to make them const as well it looks like.
> Mark function as const

- bitcoin/src/blockdata/witness.rs
- primitives/src/witness.rs
In #2646 we introduced a bug in the taproot witness stack getter functions, of which we have three:
- `tapscript`
- `taproot_control_block`
- `taproot_annex`
Each returns `Some` if a possible bytes slice is found (with no other guarantees).
Use `taproot_annex` combined with getters from `primitives` to implement the other two getters. This simplifies the code and fixes the bug.
Add an additional getter to `primitives` `Witness::third_from_last`.
Fix: #3598
> Fix bug in witness stack getters

- primitives/src/transaction.rs
The `Transaction` type was created way back when, and the field names were named using singular (`input` and `output`). In hindsite plural probably should have been used since its more idiomatic Rust but the fields have been around so long now that re-naming them is going annoy a whole bunch of people.
As a compromise add getters that use plural, immutable and mutable versions, for both the `input` and `output` fields.
Close: #822
> transaction: Add plural field getters

- bitcoin/src/bip152.rs
- bitcoin/src/bip158.rs
- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/constants.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/lib.rs
- bitcoin/src/merkle_tree/block.rs
- bitcoin/src/merkle_tree/mod.rs
- bitcoin/src/pow.rs
- fuzz/fuzz_targets/bitcoin/deserialize_block.rs
- primitives/src/block.rs
- primitives/src/lib.rs
Re-design the `Block` API and move the type to `primitives`.
> Re-design and move `Block` to `primitives`

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/Cargo.toml
- primitives/CHANGELOG.md
- primitives/Cargo.toml
- primitives/src/lib.rs
Its 00:02 on the 15th UTC now, I'm hoping this merges within 24 hours - then the date is correct.
> Release tracking PR: `primitives 0.101.0`

- units/src/amount.rs
We an use `Amount::display_in` now, this was done on master in PR #2951.
> backport: Deprecate Amount::fmt_value_in

- .github/workflows/rust.yml
- bitcoin/Cargo.toml
- bitcoin/src/bip158.rs
- bitcoin/src/bip32.rs
- bitcoin/src/blockdata/script/mod.rs
- bitcoin/src/crypto/key.rs
- bitcoin/src/crypto/sighash.rs
- hashes/Cargo.toml
- hashes/embedded/Cargo.toml
- hashes/embedded/src/main.rs
- hashes/src/hmac.rs
- hashes/src/internal_macros.rs
- hashes/src/lib.rs
- hashes/src/macros.rs
- hashes/src/sha256.rs
- hashes/src/sha256t.rs
- hashes/tests/io.rs
- hashes/tests/regression.rs
- primitives/Cargo.toml
- primitives/src/block.rs
- primitives/src/merkle_tree.rs
- primitives/src/taproot.rs
- primitives/src/transaction.rs
This is done in 3 parts:
1. Pull the `serde` stuff out of `impl_bytelike_traits` to fix the bug described here: https://github.com/rust-bitcoin/rust-bitcoin/issues/2654#issuecomment-2470716693
2. Prepare the `hashes` trait by removing string/hex trait bounds from `GeneralHash` and also pull the hex/string stuff out of `impl_bytelike_traits`
3. Make hex optional, including adding custom debug logic when `hex` feature is not enabled
Patch 3 is tested in `hashes/embedded`, by the new `debug` unit test, and there is a `Midstate` unit test as well that covers the `Debug` impl.
Close: #2654 - BOOM!
> Hashes: Make `hex` dependency optional

- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/script/tests.rs
- bitcoin/src/consensus/encode.rs
- bitcoin/src/network/mod.rs
- bitcoin/src/p2p/address.rs
- bitcoin/src/p2p/message.rs
- bitcoin/src/p2p/message_blockdata.rs
Convention is to not include test as a suffix
Used `git grep -n _test` and renamed all the tests that made sense to rename.  There are a number of fn `do_test(data: &[u8]) {` that I felt it would be better not to touch.  Everything else that was a testname I renamed if it had a _test suffix.
> Rename tests that have _test suffix

- units/src/fee_rate.rs
Following on from #3608 and #1174 more functions have been marked as const.
Mark `checked_` functions in `units/src/fee_rate.rs` as const.
Replace `map()` and `?` operators, which are not allowed in const context, with match statements.
> Mark functions `const` in `fee_rate`

- bitcoin/src/psbt/mod.rs
- units/src/amount/signed.rs
- units/src/amount/unsigned.rs
Following on #3608, #3627 and #1174 the rest of the `checked_` functions in all `rust-bitcoin` have been marked as const.  Except for tests and traits.
> Mark `checked_` functions as `const`

- README.md
The Kani badge was not displayed due to using `imp` rather than `img` and link was broken. Also the `no-std` details need to be updated.
> README: Fix Kani badge and update `no-std` details

- bitcoin/src/address/mod.rs
Adds an ergonomic way to convert any `Address` (network can be checked
or unchecked) into an `Address<NetworkUnchecked>` without cloning, which
I've found useful in several contexts.
Removes an unnecessary `match` which I noticed while implementing `Address::into_unchecked`.
The style guide in `CONTRIBUTING.md` notes to return `Self` when possible, but that doesn't apply here as the `Address` being returned is different from the `Address` type referred to by `Self`, due to the changed `NetworkValidation` type.
> address: Add `Address::into_unchecked`

- units/tests/api.rs
In an effort to check off items in the Rust API guidelines checklist (#3632) add an integration test file that tests:
- The location of re-exports for various typical usage styles.
- Regressions in the API surface (things being accidentally moved).
- All public types implement Debug (C-DEBUG).
- For all non-error types:
- `Debug` representation is never empty (C-DEBUG-NONEMPTY)
- For all error types:
- Derive standard traits as defined by `rust-bitcoin` policy.
- All data structures implement `serde` traits (C-SERDE).
I used the `cargo check-api` script we have laying around from ages ago (#2986) to parse `units` and get a list of the public types.
> units: Add integration test of API surface

- bitcoin/src/address/mod.rs
Manually backport the 2 patches from #3640. I did not investigate why the patches didn't apply cleanly I just grabed the changes from each patch. I did keep the patches separate and retained the commit logs. Holla if there is a better way to do this since we are backporting often these days.
> Manually backport 3640

- bitcoin/src/lib.rs
`rust-bitcoin` is a lot further from 1.0 than `bech32` is. We previously removed the re-export of `bech32` because we thought it might hold us up releasing `rust-bitcoin 1.0` but in hindsite this was incorrect.
Having a public re-export of dependencies helps users keep their deps in sync with those in `rust-bitcoin` and is thus useful.
Close: #3650
> Re-export bech32 crate

- bitcoin/src/taproot/mod.rs
In commit: `39f7dcb Reduce API surface of tagged wrapped hash types` I introduced a typo in the tagged hash tag type. Fortunately it has no effect because the tag type controls how an engine  is created (when the tag is input into the engine) and has no effect on the call to `from_engine`. However the typo makes the code confusing.
This bug is currently unreleased.
Fix: #3649
> Fix typo in hash tag type

- bitcoin/src/blockdata/transaction.rs
Closes https://github.com/rust-bitcoin/rust-bitcoin/issues/3645
I'm not sure if `total_weight` is the most accurate.  Please advise if there's a different name that is better.
> Deprecate iwp weight

- bitcoin/src/lib.rs
Backport #3657
---
`rust-bitcoin` is a lot further from 1.0 than `bech32` is. We previously removed the re-export of `bech32` because we thought it might hold us up releasing `rust-bitcoin 1.0` but in hindsite this was incorrect.
Having a public re-export of dependencies helps users keep their deps in sync with those in `rust-bitcoin` and is thus useful.
> backport: Re-export bech32 crate

- bitcoin/src/network/params.rs
- bitcoin/src/pow.rs
[In Core](https://github.com/bitcoin/bitcoin/blob/f7144b24be09e7db2173a0b15d73f99a08b98118/src/pow.cpp#L56), the timespan is defined as a signed int64. This PR will update `from_next_work_required` to take in an `i64` instead of a `u64`
Fixes #3652
> Update `from_next_work_required` to take an i64 for timespan

- bitcoin/src/blockdata/transaction.rs
A fix for https://github.com/rust-bitcoin/rust-bitcoin/pull/3653/commits/261c8d8ae659d98fd3f63228f16d8f2eb4010b7e.  Maybe it's better to roll back that commit instead.  Clearly there needs to be a test or two added here as well since this change causes not test failures.
> Fix internal weight calculation

- bitcoin/Cargo.toml
- bitcoin/examples/create-p2wpkh-address.rs
Add example for creating p2wpkh address.  It would be helpful to add examples the other address types (p2tr etc) either in separate files or in one.  Note this should be created in the Address crate however that crate is currently empty.
> Add p2wpkh address creation example

- bitcoin/src/blockdata/script/tests.rs
In commit:
`a10d5e15b3 Extract the Script assembly creator from fmt::Debug`
A test case was refactored and where there used to be two test case, one for `Debug` and one for `Display`, two identical test cases were left.
Remove duplicate test case.
> Remove duplicate test case

- bitcoin/src/crypto/sighash.rs
- primitives/src/transaction.rs
- units/src/amount/signed.rs
- units/src/amount/unsigned.rs
The `Amount` and `SignedAmount` were not supposed to implement `serde` traits by design because doing so implicitly uses sats. We provide two modules `as_sat` and `as_btc` to allow users to explicitly serialize in their preferred format.
In commit: `d57ec019d5 Use Amount type for TxOut value field` derives were added for `serde` and we did not notice it during review.
> units: Remove serde from amounts

- units/tests/str.rs
Add regression tests for `Display` and `FromStr` impls. Exclude error types and helper types (`amount::Display`).
Done as part of #2498 and also as part of the 1.0'ing effort.
> Add string regression tests in leaf crates 

- units/tests/api.rs
Add structs to the `api` integration test file that verify the set of common traits.
> units: Test C-COMMON-TRAITS

- bitcoin/src/lib.rs
- units/src/parse.rs
- units/tests/api.rs
As part of the 1.0 effort close the errors in the `units::parse` module.
> units: Close the hex parse errors

- units/src/amount/signed.rs
- units/src/amount/tests.rs
- units/src/amount/unsigned.rs
- units/src/block.rs
- units/src/fee_rate.rs
Enables summing an iterator of values. Note that this does not include either `LockTime`s. `absolute::LockTime` should not be added and for `relative::LockTime` we have https://github.com/rust-bitcoin/rust-bitcoin/issues/3676
Close: #1638
> units: Implement `iter::Sum` for all types that implement `ops::Add`

- hashes/src/lib.rs
To conform to Rust API guidelines in Issue #3633 examples should use ?, not try!, not unwrap (C-QUESTION-MARK).
The examples were originally labelled `## Commonly used operations`, change the label to `# Examples`.
Replace `unwrap()` with `expect()` since these cases cannot error.  
Two uses of `unwrap()` have been left since they are in a set of three writes with an engine that can not error and the first case uses `expect()` with the relevant error message.
> hashes: Documents C-QUESTION-MARK

- bitcoin/src/crypto/taproot.rs
This `if...else` block can be replaced with one `if` block, by changing `==` to `!=`.
> refactor: remove unnecessary if block

- units/src/amount/error.rs
- units/src/amount/mod.rs
- units/src/amount/signed.rs
- units/src/amount/tests.rs
- units/src/amount/unsigned.rs
Close the two pubic enum error types in `units::amounts`. All the other structs are closed already because they either have private fields or marked `non_exhaustive`.
> Close `amounts` error types

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/CHANGELOG.md
- bitcoin/Cargo.toml
- units/CHANGELOG.md
Needs release notes but there are 20 pages of them, that feels like too many to go through manually.
> Release tracking PR: `bitcoin 0.33.0-alpha.0`

- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/psbt/mod.rs
- units/src/amount/tests.rs
- units/src/amount/unsigned.rs
As discussed in #3688 and #3691 using `u64::MAX` causes errors when converting to `f64` so `MAX_MONEY` is should be used as the maximum `Amount`.  
- `Amount::MAX` changed to equal `MAX_MONEY`
- Add a check to add, multiply and from_str functions
- Change tests to account for new lower maximum
Different approach to the existing PR #3692.  I have only done Amount and not SignedAmount until there is feedback on which approach to use.
> Change `Amount::MAX` from `u64::MAX` to `Amount::MAX_MONEY`

- .github/workflows/rust.yml
- CONTRIBUTING.md
- api/README.md
- api/hashes/all-features.txt
- api/hashes/alloc-only.txt
- api/hashes/no-features.txt
- api/io/all-features.txt
- api/io/alloc-only.txt
- api/io/no-features.txt
- api/primitives/all-features.txt
- api/primitives/alloc-only.txt
- api/primitives/no-features.txt
- api/units/all-features.txt
- api/units/alloc-only.txt
- api/units/no-features.txt
- contrib/api.sh
- contrib/check-for-api-changes.sh
- justfile
Last time we did this there was push back by Kixunil because he did not like updating the API files. This time we only add API files for those crates we are focused on stabalizing.
As we try to do the checklists for making sure the crates conform to the Rust API guidelines one has to repeatedly audit the code. Being able to quickly get lists of things out of the code is super useful.
And the after we release 1.0 these API text files become valuable for review. 
--
Add a script to generate API files using `cargo check-api` for the crates that we are trying to stabalise.
- hashes
- io
- primitives
- units
Add a script to query the API files. E.g., `contrib/api.sh units types`
Current commands are
`types`: Show all public structs and enums
`types_no_err`: Show all public structs and enums …
> Add API scripts and output files

- units/tests/api.rs
Done as part of the Rust API guidelines checklist.
Add a unit test for `Send` and one for `Sync`.
> units: test for C-SEND-SYNC

- primitives/src/lib.rs
- primitives/src/sequence.rs
Recently we reduced the `alloc` requirements in `units` but we did not propagate these changes up to `primitives`.
Remove a bunch of `alloc` feature gating from `primitives`.
> primitives: Reduce alloc requirements

- units/Cargo.toml
- units/src/amount/serde.rs
- units/src/amount/tests.rs
Sometimes JSON parsers may munge floats. Instead of using `f64` we can serialize BTC amounts as strings.
Close: #894
> Support serde serializing Amount as string

- primitives/src/block.rs
- primitives/src/lib.rs
- primitives/src/opcodes.rs
- primitives/src/script/borrowed.rs
- primitives/src/script/owned.rs
- primitives/src/witness.rs
Enable lint `clippy::return_self_not_must_use` and add attribute `must_use` as required.
Also run the linter with `clippy::must_use_candidate` enabled and manually check every warning site.
Done as part of #3185
> primitives: Add `must_use`

- io/src/lib.rs
Enable lint `clippy::return_self_not_must_use`. Does not generate any new warnings.
Also run the linter with `clippy::must_use_candidate` enabled. Also does not generate any new warnings.
Done as part of #3185
> io: Add lint `return_self_not_must_use`

- hashes/src/lib.rs
- hashes/src/sha256.rs
Enable `return_self_must_use` and also run the linter locally with `must_use_candidate`.
Add `must_use` attribute as required excluding obvious functions (conversion, getters, etc).
Done as part of #3185
> hashes: Add `must_use`

- Cargo-minimal.lock
- Cargo-recent.lock
- base58/CHANGELOG.md
- base58/Cargo.toml
- bitcoin/Cargo.toml
In preparation for release add a changelog entry, bump the version, and update the lock files.
> base58ck: Bump version to 0.2.0

- units/src/amount/mod.rs
- units/src/amount/signed.rs
- units/src/amount/unsigned.rs
- units/src/fee_rate.rs
- units/src/lib.rs
- units/src/locktime/relative.rs
- units/src/weight.rs
Enable return_self_must_use and also run the linter locally with must_use_candidate.
Add must_use attribute as required excluding obvious functions (conversion, getters, etc).
Done as part of https://github.com/rust-bitcoin/rust-bitcoin/issues/3185
> units: Add `must_use`

- api/primitives/no-features.txt
In a recent PR (#3682) we introduced api text files. Then in another PR (#3711) we removed `alloc` feature gating. Possibly due to the timing of running through CI and merging these two PRs managed to get merged without an update to the API text files.
As would be expected; removing the `alloc` feature gate adds a bunch of new lines to the `no-features` api text file.
> Add new api text file changes

- units/src/amount/signed.rs
- units/src/amount/tests.rs
To prevent rounding errors converting to and from f64 change `SignedAmount` `MAX` and `MIN` to +/- `MAX_MONEY` which are within the limit in f64 that has issues.
Add checks to `from_str_in`, `checked_add`,  `checked_sub` and `checked_mul` that the result is within MIN and MAX.
Modify tests to work with new `MIN` and `MAX`.
Discussed in #3688 and #3691
> Change `SignedAmount` `MAX` and `MIN` to equal +/- `MAX_MONEY`

- units/src/lib.rs
- units/src/parse.rs
As we do in `bitcoin` add a module for usage in macros to prevent naming clashes if a module called `core` exists.
Overly paranoid yes but this is bitcoin after all.
> units: Add _export::_core

- units/src/amount/mod.rs
Put the list of possibly confusing forms in the same order as the enum and fix the rustdocs to show the actual error variants returned.
> Clean up possibly confusing

- bitcoin/src/lib.rs
> Use backticks on amount types

- bitcoin/src/blockdata/transaction.rs
The `ToU64` trait is not meant to be used publicly, remove the mention of it from rustdocs.
> Remove ToU64 from rustdocs

- bitcoin/src/blockdata/transaction.rs
The `deprecated` attribute already fully explains the status of a deprecated function and the replacement - no need to repeat this.
> Remove unnecessary rustdocs

- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/transaction.rs
- units/src/weight.rs
This constructor is an anomaly in this repo. Also it is ugly to have the type parameter hard coded in the function name.
The problem the constructor is trying to solve is that we don't like casts that don't obviously loose data. We have a solution for that already in `internals::ToU64`. This trait cannot be used in const contexts though so we do introduce a single cast in this patch.
> Remove Weight::from_wu_usize function

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/Cargo.toml
- primitives/Cargo.toml
- units/Cargo.toml
Out with the old in with the new, update to the latest minor version of arbitrary.
No real reason to do this except that I wanted to add the minor version instead of using just `1` so that we don't accidentally pull a new minor version in during a patch release (after we 1.0).
(I'm unsure if this is necessary and did not test it against MSRV.)
> Update to arbitrary v1.4

- api/primitives/all-features.txt
- api/primitives/alloc-only.txt
- api/primitives/no-features.txt
- api/units/all-features.txt
- api/units/alloc-only.txt
- api/units/no-features.txt
- bitcoin/src/blockdata/constants.rs
- bitcoin/src/blockdata/script/mod.rs
- primitives/src/script/mod.rs
Woops, this should have been done before v0.101.0 was released.
Move the `ScriptHash` and `WScriptHash` types to `primitives`.
Requires moving constants and error types as well. We re-export the errors because they are in the `mod.rs` file so they should appear in both `primitives::script::FooError` and `bitcoin::script::FooError`.
> Move script hash types to `primitives`

- bitcoin/src/lib.rs
Make slight improvement to the extern crates we re-export from `bitcoin`.
> bitcoin: Improve rustdocs on extern crates

- units/src/amount/unsigned.rs
Update rustdocs in `units::Amount` to conform to the API guidelines.
`# Examples` API guideline quote:
> "is not always to show how to use the item. ... Rather, an example is often intended to show why someone would want to use the item."
This guideline is subjective, and in the cases in `Amount` the why is often trivial.  Where the example is trivial it has been included once, and for similar functions left off e.g. included for `from_sat` but not `from_btc`, etc.
> units::Amount Make rustdocs conform to the API guidelines

- units/src/amount/signed.rs
- units/src/amount/unsigned.rs
Currently the consts in the `amount` modules repeat the type. For `Amount` this isn't a big deal but for `SignedAmount` its quite noisy.
Use `Self` as the type in const declarations inside `Amount` and `SignedAmount`.
Internal change, no logic changes.
> Use Self in amount consts

- bitcoin/src/address/mod.rs
These docs are stale, update them.
- Mention segwit and legacy
- Improve example code to show feature gating
- Fix headings to be as typical
> Improve rustdocs on addresses module

- api/units/all-features.txt
- api/units/alloc-only.txt
- api/units/no-features.txt
- units/src/amount/signed.rs
- units/src/amount/tests.rs
- units/src/amount/unsigned.rs
We have multiple constructors for `Amount`, one of which accepts an integer representing whole bitcoin.
In an attempt to make the API crystal clear change the parameter type used for whole bitcoin to `u32` instead of a `u64` which may well be mapped to sats in the mind of developers (it is in mine anyway).
> Change paramater type used for whole bitcoin

- api/units/all-features.txt
- api/units/alloc-only.txt
- api/units/no-features.txt
- units/src/weight.rs
It is not immediately obvious why we have floor and ceil versions of `to_vbytes` but not for `to_kwu`.
Add a conversion function to get weight by kilo weight units rounding up.
And then clean up the `weight` unit tests.
> Add `Weight::to_kwu_ceil`

- units/src/amount/tests.rs
We added the "cBTC" denomination but forgot to test it.
Add units test for "cBTC" as we do for the other denominations. Put all the tests lines of code in the same order as the enum variants so a reader can see easily that all cases are tested.
> Add units tests for cBTC

- CONTRIBUTING.md
- api/README.md
- contrib/check-for-api-changes.sh
Closes #3764.
yancyribbens can you test it locally? It works in my end both with and without `cargo-public-api`. Of course without gives the error message that I was supposed to see.
EDIT: You can run it with `just check-api`.
> contrib: check if the user has cargo-public-api

- api/units/all-features.txt
- api/units/alloc-only.txt
- api/units/no-features.txt
- units/src/amount/signed.rs
- units/src/amount/tests.rs
- units/src/amount/unsigned.rs
- units/src/fee_rate.rs
- units/src/internal_macros.rs
- units/src/lib.rs
- units/src/weight.rs
Sort out `Add`, `AddAssign`, `Sub`, and `SubAssign` for the following types:
- `Amount` 
- `SignedAmount`
- `FeeRate`
- `Weight`
And clean up as we go.
Note that `BlockInterval` isn't touched in this PR - it looks correct already.
The unit tests in the two patches "Add ops tests ..." can be moved if you want to verify that they don't build without the patch they follow.
> units: Unify and flesh out ops impls

- Cargo-minimal.lock
- Cargo-recent.lock
- base58/Cargo.toml
- bitcoin/Cargo.toml
- hashes/CHANGELOG.md
- hashes/Cargo.toml
- primitives/Cargo.toml
We need to do a quick release because our current `bitcoin` manifest does not work with hashes `v0.15.0` and we'd like to release an alpha version with the current state of `master`. https://github.com/rust-bitcoin/rust-bitcoin/pull/3718
```
the package `bitcoin` depends on `bitcoin_hashes`, with features: `hex`
but `bitcoin_hashes` does not have these features. It has a required
dependency with that name, but only optional dependencies can be used as
features.
```
Add a changelog, bump the version, depend on the new version repo wide, and update the lock files - like its our job.
> Release tracking PR: `hashes 0.16.0`

- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/p2p/mod.rs
- units/src/amount/mod.rs
- units/src/amount/signed.rs
- units/src/amount/unsigned.rs
> Remove double spacing in rustdocs

- units/src/amount/tests.rs
Unchecked methods have been removed in a previous commit, therefore the tests are no longer applicable.
> Remove deprecated tests

- units/src/amount/tests.rs
The MIN/MAX for SignedAmount recently changed from i64::MIN and i64::MAX to MAX_MONEY/MIN_MONEY.  Update the tests to reflect this new MIN/MAX since it is no longer valid to create a value above or bellow MAX_MONEY/MIN_MONEY.
> Test types MIN/MAX instead of i64::MIN/i64::MAX

- internals/Cargo.toml
- internals/src/array_vec.rs
- units/src/amount/verification.rs
PR does two things because a recent upgrade of `kani` broke our setup. I'm not sure why it just showed up.
We fix the verification for `amount` types which recently broke because of `MAX_MONEY` changes and then we add a verification function to `internals` because build fails and one fix is to just add something.
- Patch 1: units: Assumes correct values
- Patch 2: units: Removes a stale check now that MAX_MONEY is being used for MAX
- Patch 3: Add verification to `internals::ArrayVec`.
> A couple of kani fixes

- units/src/amount/signed.rs
- units/src/amount/unsigned.rs
Update rustdocs in `units::SignedAmount` to conform to the API guidelines.  Add examples to `Amount` to match the ones added to `SignedAmount`.
> units::SignedAmount make rustdocs conform to the API guidelines 

- contrib/api.sh
Was working on #3777 and noticed that `amount::Denomination` didn't show up when running `contrib/api.sh units types`. There are some structs/enums in `api/<crate>/all-features.txt` that dont have a `\(`, `;`, or ` ` after the struct/enum name, and the line just ends, so matching the end of line `$` should also be added.
This allows the script to find the additional type from `units`:
`#[non_exhaustive] pub enum bitcoin_units::amount::Denomination`
Also tested this in `primitives`, and it returned:
```
script::Script
BlockChecked
BlockUnchecked
absolute::LockTime
block::Checked
block::Unchecked
locktime::absolute::LockTime
locktime::relative::LockTime
opcodes::Class
opcodes::ClassifyContext
relative::LockTime
BlockHash
BlockHeader
CompactTarget
Sequence
TapBranchTag
TapLeafHash
TapLeafTag …
```
> Update regex lookahead to match when there are no characters

- api/units/all-features.txt
- units/src/amount/mod.rs
- units/src/block.rs
- units/src/fee_rate.rs
- units/src/locktime/absolute.rs
- units/src/locktime/relative.rs
- units/tests/api.rs
Implement Arbitrary for the rest of the types in `units`. Also moved the implementation in `FeeRate` right before the `tests` module
Closes #3705
> Implement Arbitrary for units types

- api/units/all-features.txt
- api/units/alloc-only.txt
- api/units/no-features.txt
- units/src/amount/mod.rs
- units/tests/api.rs
The `untis::error` module is just a code organisation thing it should never have been public. We already re-export all the error types and this is verified by the `units/tests/api.rs` test file.
Make the module private and remove it from the paths in the `api` test.
> units: Make `amount::error` module private

- api/units/all-features.txt
- api/units/alloc-only.txt
- api/units/no-features.txt
- units/src/amount/unsigned.rs
- units/src/fee_rate.rs
In ops functions we typically use `rhs` but for the more unconventional `checked_*_by_*` functions lets use a more descriptive parameter name.
Interestingly `cargo public-api` thinks this is an API breaking change. This is obviously an internal change but the api files are updated because the parameter names appear in the api text files.
> Rename parameter `rhs` to `weight`

- api/units/all-features.txt
- api/units/alloc-only.txt
- api/units/no-features.txt
- bitcoin/src/blockdata/transaction.rs
- units/src/amount/signed.rs
- units/src/amount/tests.rs
- units/src/amount/unsigned.rs
Any SignedAmount can now be cast to Amount since the range is the same.  Specifically, the range for SignedAmount is (- 21 million, 21 million) while the range for Amount is (0, 21 million).  Therefore any value from Amount can be cast to a SignedAmount and it will work.  Note it's not the same and still requires checking when going from SignedAmount to Amount since Amount can't handle the negative range.
> Change method return type for to_unsigned()

- units/src/amount/signed.rs
- units/src/amount/unsigned.rs
Code comments that comment and arbitrary block "section" of code are almost always pointless and almost always go stale over time.
These particular code comments add almost no value.
Remove code comments.
> Remove unnecessary floating code comment

- api/hashes/alloc-only.txt
- api/hashes/no-features.txt
- hashes/src/macros.rs
We have two macro definitions feature gated on `serde`. At some stage we added the `doc(hidden)` attribute to one of them but forgot to add it to the other. This technically makes our features non-additive. This macro is "internal" so its unlikely that this is being used in the wild.
Add `doc(hidden)` to the `serde_impl` macro that is missing it.
Found by `cargo semver-checks` after recent upgrade to 0.38
> hashes: Hide both macros

- api/units/all-features.txt
- api/units/alloc-only.txt
- api/units/no-features.txt
- units/src/amount/signed.rs
- units/src/amount/tests.rs
- units/src/amount/unsigned.rs
This is a small-ish changeset in order to mirror what was started in #3769 and reduce the diff in #3794
- Patch 1: Trivial refactor to use `Amount::ZERO`.
- Patch 2: Add the constructor and refactor a single unit test to use it.
- Patch 3: Use the two `_unchecked` constructors throughout `units/src/amount/tests.rs`.
- Patch 4: Add the API text file changes.
> Introduce an unchecked constructor for the `Amount` type

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/Cargo.toml
- primitives/Cargo.toml
I just went to town on the `rust-ordered` crate to get it ready for releasing a `1.0` version. None of the changes effect our usage here in `rust-bitcoin`.
Upgrade to the latest version of `rust-ordered` - `v0.3.0`.
> Update to latest `rust-ordered`

- contrib/api.sh
The regex is still wrong, it misses structs with generics.
Currently `contrib/api.sh io types` returns:
ErrorKind
Error
Sink
But with this patch applied it returns:
FromStd<T>
ToStd<T>
ErrorKind
Cursor<T>
Error
Sink
Take<'a, R: bitcoin_io::Read + ?core::marker::Sized>
Thanks ChatGPT, good robot.
> api: Include generics in regex

- bitcoin/src/p2p/message.rs
- bitcoin/src/p2p/message_blockdata.rs
I am working on adding BIP324 V2 p2p network message support to the p2p module and ran into a little snag. I can post a draft branch of that work if helpful, but the general strategy is to add a `V2NetworkMessage` which operates in parallel with the existing `RawNetworkMessage` type (which is a bit of misnomer and may be better described in the future as `V1NetworkMessage`, see #3157). This allows both p2p message types to hook into the existing `Encodable`/`Decodeable` chain.
But the `Error` variant of the `Inventory` type message does not have symmetrical encoding and decoding paths. Encoding writes out a zero'd 32 bytes while decoding ignores it completely. And while it is not clear to me if there is [requirement written down](https://en.bitcoin.it/wiki/Protocol_documentation#Inventory_ …
> Add hash data to Inventory's Error variant

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/Cargo.toml
- primitives/Cargo.toml
We just released a version of `ordered` that makes `ArbitraryOrd` object safe - use it.
Upgrade to the latest version of `rust-ordered` - `v0.4.0`.
> Update to rust-ordered 0.4.0

- api/units/all-features.txt
- api/units/alloc-only.txt
- api/units/no-features.txt
- units/src/parse.rs
Document the public macros in `units::parse`. Done as part of #3632
First 2 patches are trivial preparatory refactor.
> units: Document public macros

- primitives/src/lib.rs
This is not strictly needed but we would like to copy the public macros from `units` to primitives and they use `$crate::_export` paths.
> primitives: Add core re-exports

- bitcoin/src/blockdata/script/builder.rs
- bitcoin/src/p2p/mod.rs
- internals/src/macros.rs
- primitives/src/opcodes.rs
Rust macros, while at times useful, are a maintenance nightmare. And we have been bitten by calling macros from other crates multiple times in the past.
In a push to just use less macros remove the `debug_from_display` macro and just write the code.
This is an API breaking change to `internals` but an internal change only to any of the _real_ crates.
> Remove macro `debug_from_display`

- hashes/src/error.rs
- primitives/src/script/mod.rs
- primitives/src/transaction.rs
- units/src/amount/error.rs
- units/src/amount/mod.rs
- units/src/locktime/absolute.rs
- units/src/parse.rs
Rust macros, while at times useful, are a maintenance nightmare. And we have been bitten by calling macros from other crates multiple times in the past.
In a push to just use less macros remove the usage of the `impl_from_infallible` macro in all the leaf crates and just write the code.
> Remove usage of impl_from_infallible in leaf crates

- bitcoin/src/merkle_tree/block.rs
- Corrected a grammatical error by adding "are" to the comment in MerkleBlock::from_block_with_predicate.
> Fix typo in MerkleBlock::from_block_with_predicate comment

- units/src/amount/mod.rs
- units/src/amount/serde.rs
- units/src/amount/tests.rs
- units/src/block.rs
- units/src/fee_rate/mod.rs
- units/src/locktime/absolute.rs
- units/src/locktime/relative.rs
- units/src/parse.rs
- units/src/weight.rs
Preemptively addressing these mutants before introducing the `cargo-mutants` workflow. There are several types of changes:
- Changes that address mutants that were actually missing
- Changes that address test values that cause `cargo-mutants` to think mutants were missed. For example, `cargo-mutants` will replace the return values for unsigned integer types with 0 and 1. While this case might be tested, the test might be testing this with a call that results in 0 or 1. When `cargo-mutants` substitutes the function call with `Ok(1)`, the test will still pass, and it will consider this a mutant. `cargo-mutants` also replaces operations (+, -, /, %), bitwise operations (&, |, ^, etc), so an operation such as `3 - 2` results in a mutant because changing it to `3 / 2` yields the same result
- …
> Address mutants in units

- bitcoin/src/blockdata/block.rs
- bitcoin/src/pow.rs
- chacha20_poly1305/src/poly1305.rs
Recent clippy nightly update introduces warnings about precedence. While ours are, IMO, clear the lint docs have some cases that are not so I don't think we should ignore this lint. Specifically I could easily miss this one
1 << 2 + 3 equals 32, while (1 << 2) + 3 equals 7
ref: https://rust-lang.github.io/rust-clippy/master/#/precede
Add parenthesis to explicitly show precedence. Refactor only no logic changes.
> Add parenthesis to explicitly show precedence

- api/io/all-features.txt
- api/io/alloc-only.txt
- api/io/no-features.txt
- io/src/bridge.rs
- io/src/lib.rs
- io/tests/api.rs
- units/tests/api.rs
As we did for `units` add an integration test for the API surface of the `io` crate.
The first two patches are cleanup to the `units` test. Patch 3 is trivial refactor.
> Introduce an API surface test file

- units/src/locktime/relative.rs
As we do for absolute locktime types add a couple of `serde` roundtrip tests to the relative locktime types.
> Add serde roundtrip tests to relative locktime types

- api/units/all-features.txt
- api/units/alloc-only.txt
- api/units/no-features.txt
- units/src/parse.rs
We do not want to commit to any public macros in `units`. Recently we (I at least) learned that adding `doc(hidden)` signals to users that the macro is unstable and should not be relied upon.
Hide the remaining two macros so we can release 1.0 and not worry about later breaking them.
With this applied there are no exported macros that are not hidden. Verify using `git grep -A 1 macro_export`.
> units: Hide the remaining public macros

- bitcoin/examples/ecdsa-psbt-simple.rs
- bitcoin/examples/sign-tx-segwit-v0.rs
- bitcoin/examples/sign-tx-taproot.rs
- bitcoin/examples/taproot-psbt-simple.rs
- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/blockdata/constants.rs
- bitcoin/src/blockdata/script/tests.rs
- bitcoin/src/crypto/sighash.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/tests/serde.rs
- units/src/amount/tests.rs
We have a `_unchecked` constructor now for both `Amount` and `SignedAmount`. Soon we would like to start enforcing the `MAX_MONEY` invariant in both amount types. To make that change easier do a few refactorings:
- Patch 1 and 2 introduce local variables for amount constructors. 
- Patch 3 replaces the local variables introduce in  (1) and (2) with macros 
- Patch 4 uses `_unchecked` constructor for hard coded integers
The strange patch separation is done intentionally so we don't inadvertently reduce test coverage by using the wrong constructor. I made this mistake already in a previous PR, lesson learned.
Note please, the macro introduced in patch 3 is in preparation for enforcing `MAX_MONEY`. The macros allow us to panic (`from_sat().unwrap()`) instead of using the `_unchecked` …
> Use `_unchecked` to construct amounts

- bitcoin/src/blockdata/script/push_bytes.rs
The `PushBytesError` is the only error type in the codebase to derive `Copy`. Without thinking too hard this is unusual - remove it.
Thinking a bit harder it makes the code less maintainable because we must commit to implementing `Copy`.
> Remove Copy from `PushBytesError`

- bitcoin/src/consensus/error.rs
All error types in the repo use either [0]:
- `#[derive(Debug, Clone, PartialEq, Eq)]``
- `#[derive(Debug)]`
However the `consensus` error types do not have `Clone` derived.
Derive `Clone` on `consensus::ParseError` and `consensus::Error`.
[0] Excluding `PushBytesError`, fixed in #3879
> Derive `Clone`on consensus errors

- io/tests/api.rs
- units/tests/api.rs
The `api` test for types implementing `Send` and `Sync` is part of both C-SEND-SYNC and also C-GOOD-ERR (for error types).
Refactor the two tests into a single one and document appropriately. This is mirrors how we do it in `io/tests/api.rs`.
> units: Refactor Send/Sync api test

- bitcoin/src/address/mod.rs
Currently it is not possible for downstream to use a generic on the `Address` type in structs in conjuncture with
derives (`serde::Deserialize` and `Display`) because our impls are only done for `NetworkUnchecked` (as they should be).
However, as observed by dpc, if we add a secondary marker trait and use it to bound the impls, implementing the new marker for `NetworkUnchecked` then downstream can use derives by way of
```
#[derive(Serialize, Deserialize)]
struct Foo<V>
where V: NetworkValidation,
{
#[serde(bound(deserialize = "V: NetworkValidationUnchecked"))]
address: Address<V>,
}
```
This is cool as hell because the `Address` type is currently a royal PITA.
Patch 1 is trivial cleanup.
To get past a build error in `FromStr` I used this little trick
```rust
// We know that `U` is only …
```
> Bound `Address` parsing on `NetworkValidationUnchecked`

- bitcoin/src/p2p/message.rs
Migrating over the BIP324's library's V2 network message encoding and decoding. As discussed over in https://github.com/rust-bitcoin/rust-bitcoin/discussions/2959, this is probably the natural home for it and also cleans up some gross copy/pasta of some of the encoding/decoding chain logic.
This patch adds `V2NetworkMessage` which wraps a `NetworkMessage`, but handles the V2 encoding and decoding. It is a parallel of the existing `RawNetworkMessage` (which mentioned before, may be better described as `V1NetworkMessage` https://github.com/rust-bitcoin/rust-bitcoin/issues/3157). A priority of this patch was to not re-invent any wheels and try to use the existing patterns as much as possible.
> Add BIP324 V2 p2p network message support

- units/src/amount/unsigned.rs
- units/src/fee.rs
- units/src/fee_rate/mod.rs
- units/src/lib.rs
We have a bunch of functions and impl blocks scattered around the place for calculating fee from fee rate and weight.
In an effort to make the code easier to read/understand and also easier to audit introduce a private `fee` module and move all the code that is related to this calculation into it.
This is in internal change only.
> Refactor fee calculation code

- units/src/amount/tests.rs
Reorder assertions in `units::amount::tests` to follow got, want order.
Makes debugging easier, as there's no need to check the test to verify the order.
Close #3860
> Reorder assertions in units::amount::tests to follow got, want order

- api/io/all-features.txt
- api/io/alloc-only.txt
- api/io/no-features.txt
- io/src/lib.rs
So that our `io` crate is not surprising it seems we should generally, unless there is a good reason not to, follow `std::io`.
Copy the derived trait implementations from `std::io` for `Cursor`, and `Sink`. `Take` is correct already, just `Debug`.
Done while investigating C-COMMON-TRAITS
> io: Add traits

- bitcoin/Cargo.toml
- bitcoin/examples/io.rs
In an effort to improve the documentation on `bitcoin_io` add an example in `bitcoin` crate that demonstrates a few things:
- Encode/Decode a `rust-bitcoin` type to/from a stdlib type.
- Encode to a custom type by implementing `bitcoin_io` traits.
- Encode to a foreign custom type by using the `bitcoin_io::bridge::FromStd` wrapper.
Later we can link to this example online in the `bitcoin_io` docs.
> bitcoin: Add an example of doing I/O to encode/decode

- bitcoin/src/address/mod.rs
> typo: `Address::is_valid_for_network`

- io/src/lib.rs
Add two unit tests:
- Check we can read into an empty buffer as validation of args as part of C-VALIDATE
- Do basic read using `Take::read_to_end` since it is currently untested.
> io: Add unit tests for `Take`

- api/units/all-features.txt
- api/units/alloc-only.txt
- api/units/no-features.txt
- bitcoin/src/blockdata/script/witness_version.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/lib.rs
- primitives/src/transaction.rs
- units/src/parse.rs
Currently `InputString` is in the public API of `units` because of the trait bound on `parse::int()`. We can just do the monomorphisisation manually to remove it.
This patch renames `int` to have three different names, one for `&str` one for `String`, and one for `Box<str>` e.g., `units::parse::int_from_str`.
Close #3708
> units: Remove `InputString` from the public API

- api/io/all-features.txt
- api/io/alloc-only.txt
- api/io/no-features.txt
- io/src/lib.rs
Mirror the `std::io::Cursor` type by making the same methods `const`.
> Make `Cursor` methods const

- api/io/all-features.txt
- io/src/error.rs
The `description` method was deprecated in Rust `v1.42`. The `cause` method was deprecated in Rust `v1.33`. Our MSRV is now Rust `v1.63`.
We do not need to implement the deprecated functions any longer.
Fix: #3869
> Remove deprecated `std::error::Error` trait method impls

- units/src/amount/tests.rs
Add `sat` and `ssat` throughout the `amount::tests` module after new tests were added recently.
> units: Define constructor variable in amount tests

- api/units/all-features.txt
- api/units/alloc-only.txt
- api/units/no-features.txt
- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/blockdata/constants.rs
- units/src/amount/signed.rs
- units/src/amount/unsigned.rs
The mining reward for the first epoc is 50 bitcoin. For mainnet this is old news but for regtest it is still relevant.
Add and use a new const `FIFTY_BTC` to the `Amount` type. To keep the amount types uniform also add it to the `SignedAmount`.
> Add FIFTY_BTC const to the amount types

- units/src/fee_rate/serde.rs
Update `fee_rate/serde.rs` documentation to correctly reference fee rates instead of amount
> docs: fix fee rate serde module documentation

- units/src/parse.rs
- units/tests/api.rs
Phew! dyn compatibility is a non-trivial concept. There are four public traits in `units`, only one is dyn compatible.
This patch is done in order to check off C-OBJECT from the Rust API guidelines checklist.
Add a test to check the public traits in `units` for dyn compatibility.
While we are at it add a code comment on `Integer` stating why its not dyn-compatible.
ref: https://rust-lang.github.io/api-guidelines/flexibility.html#c-object
> units: Test for dyn compatibility

- units/src/parse.rs
Audit the `units::parse` module checking for sanity of the API. Could still possibly do with more improvements to the docs but for the `1.0-alpha` this is good to go IMO. 
Close: #3710
> Polish `units::parse` docs

- units/src/parse.rs
In preparation for units 1.0 address #3868 and make sure "constructs" is used instead of "creates" in rustdocs.
> units: Change `create` to `construct` in rustdocs

- hashes/src/lib.rs
This trait is private and is meant just for sealing. It already will not show up in public docs and cannot be used by downstream users.
Resolve: #3912
> Remove unnecessary `doc(hidden)`

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/Cargo.toml
- bitcoin/src/pow.rs
- primitives/Cargo.toml
- primitives/src/locktime/absolute.rs
- primitives/src/locktime/relative.rs
Back in 2022 we elected to use `mutagen` for mutation testing. Since then `cargo mutants` has progressed to a point where we would now like to use it instead.
Remove all the `mutagen` stuff.
Close: #2829
> Remove mutagen

- .cargo/mutants.toml
- .github/workflows/cron-weekly-cargo-mutants.yml
- .gitignore
- units/src/amount/tests.rs
- units/src/fee_rate/mod.rs
- units/src/fee_rate/serde.rs
- units/src/locktime/relative.rs
This PR introduces `cargo-mutants` via a Github weekly workflow, similar to how the formatter job runs. It can also be updated to run against [incremental changes in a PR](https://mutants.rs/pr-diff.html) or to create an issues that list the new mutants. To address #3796, I've configured it to only run in `units` for now since that's nearing 1.0. 
Here's a [sample run](https://github.com/shinghim/rust-bitcoin/actions/runs/12457984710) i did in my fork, if anyone would like to see what's in the `mutants-out` artifact that gets generated.
> Introduce cargo-mutants workflow

- units/src/amount/mod.rs
- units/src/amount/tests.rs
`µ` is the correct letter for the SI unit micro but is not on most standard keyboards.  `u` was used instead because it looks similar.
Add `µBTC` to the list of recognized strings for MicroBitcoin.  This is an addition only, `uBTC` still works as normal.
Change `uBTC` to `µBTC` in the rustdocs.  The examples have been left as `uBTC` since this is easier for most people to use.
Add `µBTC` and `µbtc` to the tests.
Close #3941
> Add `µBTC` as a recognized `str` form of a MicroBitcoin Denomination

- units/src/amount/tests.rs
Cargo mutant found missed mutants in the bitcoin constants in both signed and unsigned amounts.
Add a test to check their values.
> Fix mutants in units

- primitives/src/locktime/absolute.rs
- primitives/src/locktime/relative.rs
Cargo mutant found untestesd mutants in `relative::Locktime` and `absoulte::LockTime`
Add/improve tests to kill the mutants.
> Fix mutants in `LockTime`

- units/src/amount/mod.rs
Reduce the noise in the examples.
> Improve examples on `Denomination`

- io/src/bridge.rs
- io/src/error.rs
- io/src/lib.rs
- io/src/macros.rs
As part of #3643 improve the public documentation on the `io` crate.
While doing this I also checked:
- C-FAILURE
- C-LINK
-  C-METADATA
- C-RELNOTES
- C-HIDDEN
> io: Improve the docs

- primitives/src/locktime/absolute.rs
- primitives/src/locktime/relative.rs
As mentioned in https://github.com/rust-bitcoin/rust-bitcoin/pull/3948#discussion_r1927690822 the variable naming in the tests in both `relative::LockTime` and `absolute::LockTime` is inconsistent and possibly confusing.
Make variable names consistent.
In `absolute::LockTime` incorporate the two standalone tests `satisfied_by_same` into `satisfied_by` to simplify the tests and conform to what is done in `relative::LockTime` .
> Refactor `LockTime` tests

- primitives/src/witness.rs
Change the iterator `#[must_use]` message to be the same as stdlib uses.
Message taken from https://doc.rust-lang.org/src/core/iter/traits/iterator.rs.html#38
Close #3962
> Change `#[must_use]` to be the same as stdlib

- primitives/src/script/borrowed.rs
- primitives/src/script/owned.rs
Add tests to both `primitives/src/script/borrowed.rs` and `primitives/src/script/owned.rs` to kill the mutants found by running `cargo mutants`.
> primitives: Add tests to `script::borrowed` and `script::owned`

- api/hashes/all-features.txt
- api/hashes/alloc-only.txt
- api/hashes/no-features.txt
- hashes/src/hmac.rs
- hashes/tests/regression.rs
The `HmacEngine` should be created using a key. Currently we are providing a `Default` impl that uses `&[]` as the key. This is, I believe, a hangover from when we had a `Default` trait bound somewhere else. It is incorrect and an API footgun - remove it.
Note this PR includes changes to the bench code in `hmac` that highlights the footgun - pity the poor user we even shot ourselves.
Patch 2 adds a constructor `Hmac::engine` and uses it in the bench code.
> Do not implement `Default` for `HmacEngine`

- primitives/src/locktime/absolute.rs
- primitives/src/locktime/relative.rs
To conform to API guidelines add examples to both `relative` and `absolute` `LockTime`.
As discussed in #3967 add an example that doesn't round trip in `relative::LockTime::from_consensus`.
> Add `LockTime` examples

- bitcoin/src/address/error.rs
Incorrect spelling kept as a deprecated, hidden, function.
> Fix spelling of `invalid_legcay_address_length`

- hashes/src/hash160.rs
- hashes/src/sha256d.rs
In order to use the `general_hash_type` macro the must exist a standalone `from_engine` function. Currently this function is in different places in different modules. In an effort to make the `hashes` code easier to reason about put the functions right below the macro.
Code move only, no other changes.
> hashes: Move from_engine functions

- api/units/all-features.txt
- api/units/alloc-only.txt
- api/units/no-features.txt
- units/src/fee.rs
Following up on #3736, this PR adds `checked_mul_by_fee_rate` to `Weight` to mirror the existing `checked_mul_by_weight` method on `FeeRate`. 
This makes the fee calculation more symmetrical.
Changes:
- Add `Weight::checked_mul_by_fee_rate` method
- Add corresponding test cases
The new method allows users to calculate fees starting from either Weight or FeeRate. This makes fee calculations more intuitive regardless of which type the user starts with.
Closes #3766
> Add symmetrical fee calculation method to Weight

- api/hashes/all-features.txt
- api/hashes/alloc-only.txt
- api/hashes/no-features.txt
- hashes/src/siphash24.rs
The other hashes that require initial state (keys etc) both have an `engine` function on the hash type because they cannot use the `GeneralHash::engine` function.
Add an `engine` function to the `siphash24::Hash` type.
> Add engine function to `siphash24::Hash`

- primitives/src/block.rs
Running `cargo mutants` on `primitives/src/block.rs` found multiple mutants.
Add tests to kill the mutants and replace one verbosely written out sum with the result.
> primitives: Add tests to `block.rs`

- primitives/src/locktime/absolute.rs
- primitives/src/locktime/relative.rs
Aims to resolve #3976
Apart from the examples in the `relative.rs` file, I see others in the **examples** folder. If this patch is good, I can continue with them.
I will happily appreciate a review.
> Update example imports to use `relative::*`

- primitives/src/pow.rs
Add tests to pow.rs to kill the mutants found in CompactTarget.
> primitives: Add tests to CompactTarget

- hashes/src/hash160/mod.rs
- hashes/src/hmac/mod.rs
- hashes/src/ripemd160/mod.rs
- hashes/src/sha1/mod.rs
- hashes/src/sha256/mod.rs
- hashes/src/sha256d/mod.rs
- hashes/src/sha384/mod.rs
- hashes/src/sha512/mod.rs
- hashes/src/sha512_256/mod.rs
Public types typically should implement `Debug`.
Derive `Debug` for all the hash engines.
> hashes: Derive `Debug` for all hash engines

- primitives/src/lib.rs
There are re-exports in the bitcoin root from primitives that were not re-exported in the primitives crate root.
Add the missing re-exports to primitives crate root.
First mentioned here https://github.com/rust-bitcoin/rust-bitcoin/pull/4012#discussion_r1943895283
> Add missing re-exports to primitives crate root

- units/src/amount/signed.rs
- units/src/amount/unsigned.rs
The ops traits return `Self::Output` not `Self`. The current code builds because `Self` and `Self::Output` are both the same type.
Use `Self::Output` as the return value of `ops::Rem`.
> Return `Self::Output` from `ops::Rem`

- .cargo/mutants.toml
- units/src/fee.rs
Recent changes to units created new mutants.
Skip mutants from deprecated functions.
Modify existing test to kill `checked_mul_by_fee_rate` mutant.
Close #4026
> Kill mutants found by github-actions

- units/src/fee.rs
This PR removes the `alloc` feature gating from fee module
Closes #3815
> units: Remove alloc from fee module

- hashes/Cargo.toml
- hashes/src/cmp.rs
- hashes/src/hash160/mod.rs
- hashes/src/hkdf/mod.rs
- hashes/src/lib.rs
- hashes/src/ripemd160/tests.rs
- hashes/src/sha1/tests.rs
- hashes/src/sha256/tests.rs
- hashes/src/sha256d/mod.rs
- hashes/src/sha256t/mod.rs
- hashes/src/sha384/mod.rs
- hashes/src/sha512/tests.rs
- hashes/src/sha512_256/mod.rs
- io/Cargo.toml
`hex/std` and `hex/alloc` should only be included if optional dependency `hex` is enabled.  A bunch of tests that need `hex` relied on an `alloc` feature gate to ensure `hex/alloc` was enabled.  
Add feature gates to the tests that require `hex`.
Add `?` so `hex/alloc` or `hex/std` are only included if the optional feature `hex` is enabled.
Audit rest of crates `Cargo.toml` files: no other cases found.
Close #4035
> hashes: Only enable hex/std, and hex/alloc when hex is

- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/psbt/mod.rs
- units/src/amount/mod.rs
- units/src/amount/result.rs
- units/src/amount/signed.rs
- units/src/amount/tests.rs
- units/src/amount/unsigned.rs
- units/src/amount/verification.rs
- units/src/internal_macros.rs
We would like to return an error when doing math ops on amount types. We cannot however use the stdlib `Result` or `Option` because we want to implement ops on the result type.
Add an `NumOpResult` type. Return this type from all math operations on `Amount` and `SignedAmount`.
Implement `core::iter::Sum` for the new type to allow summing iterators of amounts. 
Note please this removes `AddAssign` impls for amount types.
> Introduce monadic `NumOpResult` type

- contrib/test-miri.sh
To ensure that all target features are tested we simply enable all of them. However some of them are problematic. We already have an exception to not enable `crt-static`. This change also adds `soft-float` to the list because `miri` was warning about it being UB.
> Do not enable `soft-float` when running `miri`

- hashes/src/macros.rs
The two main public macros can be used in function scope - prove it.
While we are at it prove that additional attributes are supported by them both as well as visability keywords.
> hashes: Test macros in function scope

- units/src/amount/result.rs
> Add `inline` to all small functions in the new `result` module

- hashes/src/hkdf/mod.rs
Currently the `Hkdf` type does not derive any traits.
Derive `Copy` and `Clone` and implement `Debug` based on secret obfuscation algo in `rust-secp` (in the `secret` module).
> hashes: Add `Copy`, `Clone`, and `Debug` imlps for `Hkdf`

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/Cargo.toml
- bitcoin/contrib/test_vars.sh
- bitcoin/src/lib.rs
- primitives/Cargo.toml
- primitives/contrib/test_vars.sh
- primitives/src/locktime/absolute.rs
- primitives/src/locktime/relative.rs
These two things are related so we remove them both in the same PR. Please see commit logs for full explanation.
For more context see discussion below and also:
- #2500
- #4002
- #3881
Close: #4029
> locktimes: Remove `PartialOrd` and `ArbitraryOrd`

- .github/workflows/rust.yml
We have made a couple of improvements to the `run_task` script lately (*cough* actually test code with `--all-features`).
Lets update to use it.
This PR explicitly tests https://github.com/rust-bitcoin/rust-bitcoin-maintainer-tools/pull/20 because it uses the commit hash created in that PR.
> Update to latest maintainer-tools

- bitcoin/src/blockdata/constants.rs
- bitcoin/src/p2p/message.rs
- hashes/src/hash160/mod.rs
- hashes/src/hmac/mod.rs
- hashes/src/internal_macros.rs
- hashes/src/lib.rs
- hashes/src/macros.rs
- hashes/src/sha256d/mod.rs
- hashes/src/sha256t/mod.rs
- hashes/src/siphash24/mod.rs
The `hashes::error::FromSliceError` error is only returned from `from_slice`. We attempted to deprecate this function but it seems we only did half a job at it.
- deprecate _all_ instances of the method/function
- deprecate the error type
- stop using the deprecated functions in `bitcoin`
Close: #4053
> Properly deprecate `Hash::from_slice`

- chacha20_poly1305/Cargo.toml
- chacha20_poly1305/src/benches.rs
- chacha20_poly1305/src/lib.rs
Add benchmarks for chacha20. These could be useful to understand future improvements.
I copied the same 10, 1k and 64k sizes as used in the sha256 benchmark. Some of the lines changed here, such as in `Config.toml`, are a little mysterious to me as I am new to rust, so please check.
```
➜  chacha20_poly1305 git:(jr_chachabench) RUSTFLAGS='--cfg=bench' cargo +nightly bench
...
test benches::chacha20_10  ... bench:         188.67 ns/iter (+/- 2.70) = 53 MB/s
test benches::chacha20_1k  ... bench:       2,885.83 ns/iter (+/- 90.06) = 354 MB/s
test benches::chacha20_64k ... bench:     186,493.88 ns/iter (+/- 5,074.53) = 351 MB/s
```
> chacha20: add benchmarks

- CONTRIBUTING.md
- contrib/update-lock-files.sh
1. Updates `CONTRIBUTING.md` with latest instructions on using `just` to create new lock files. See discussion [here](https://github.com/rust-bitcoin/rust-bitcoin/pull/4045/files).
2. For the command `cp`,  `--force` is not an option on the Mac. Changed to `-f` which as far as I can tell is equivalent.
```
➜  rust-bitcoin git:(jr_update_contrib) ✗ cp --force
cp: illegal option -- -
```
> documentation: update instructions for building lock files

- internals/src/lib.rs
- internals/src/wrap_debug.rs
- primitives/src/witness.rs
This pr introduces `WrapDebug` in `internals` and updates `Witness` debug implementation to use it. The previous `DebugElements` struct has been removed in favor of an ad-hoc closure inside `WrapDebug`, which formats witness elements as a debug list of hex-encoded values.
By abstracting out the "debug-print hex fields" pattern, we reduce code duplication and improve maintainability.
Closes #4074
> Abstract out "debug-print hex fields" using WrapDebug

- bitcoin/src/crypto/sighash.rs
A note suggestion for the `p2wsh_signature_hash` in the same vein as the one in the "sister" function `p2wpkh_signature_hash`: https://github.com/rust-bitcoin/rust-bitcoin/blob/33f5e5a6acddc34d6c436a9d73bb50988c067b29/bitcoin/src/crypto/sighash.rs#L863-L867
Any better wordings are welcomed. Not married to my sentences.
> sighash: Document `witness_script` in p2wsh

- bitcoin/src/blockdata/transaction.rs
- bitcoin/tests/psbt-sign-taproot.rs
- primitives/src/transaction.rs
This commit addresses #4041 by making the `transaction::Version` field private. 
This forces people to either use the associated constants (`Version::ONE/TWO/THREE`) or the `non_standard`/`from_consensus` methods for any other transaction version.
This aligns with our approach to `block::Version`
> Make transaction::Version field private

- bitcoin/CHANGELOG.md
We release `v0.32.4` and `v0.32.5` already but forgot to merge the changelog entries back into master.
Grab the missing changelog entries from the `0.32.x` release branch.
> Grab missing changelog

- units/src/amount/result.rs
- units/src/amount/tests.rs
- units/src/fee_rate/mod.rs
- units/src/internal_macros.rs
- units/src/weight.rs
This introduces a general macro which takes some number of `impl ops::Whatever<A> for <B>` and replicates them with all the permutations of references. It also takes a syntax which resembles the code for the initial impl block.
Uses it for all the binary opcodes on `Amount`, `SignedAmount`, `Weight`, `FeeRate`, as well as the numeric mul/div on those types, as well as generic impls on `NumResultOp<T>` (which are expanded to cover more cases).
> units: macroize the op implementations

- bitcoin/examples/sighash.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/crypto/key.rs
- internals/src/error/input_string.rs
This pull request contains changes to improve clarity, correctness and structure.
- Corrected typos in multiple files (e.g., `transacton` → `transaction`, `function panics` formatting).
- Improved readability of comments in `transaction.rs`, `key.rs`, and `input_string.rs.`
- No functional code changes, only documentation updates.
This message provides a clear summary of what was done and why the changes were made. Let me know if you need any modifications!
> fix: typos in documentation files

- fuzz/fuzz_targets/bitcoin/deserialize_script.rs
We currently have the `script_bytes_to_asm_fmt` which fuzzes the `fmt_asm` function. However, this function is deprecated and the script's Display impl should be used instead. This PR adds fuzz coverage for it.
> fuzz: add coverage for Display for Script

- bitcoin/src/address/mod.rs
- bitcoin/src/address/script_pubkey.rs
- bitcoin/src/blockdata/script/witness_program.rs
Add support for the newly created Pay2Anchor output-type which was introduced in bitcoin 28.0
See https://github.com/bitcoin/bitcoin/pull/30352
> Add support for pay to anchor outputs

- bitcoin/src/crypto/sighash.rs
Backport #4113 
Cherry-picked the 2 commits and manually fixed merge conflicts.
> backport: Fix `is_invalid_use_of_sighash_single()` incompatibility with Bitcoin Core

- bitcoin/src/policy.rs
Align with Bitcoin Core's policy by reducing the minimum non-witness transaction size from 82 to 65 bytes. 
This will allow for more minimal transaction cases (eg: 1 input with 1 OP_RETURN output) while maintaining protection against CVE-2017-12842.
The 65-byte minimum consists of:
- 60 bytes: minimal tx (10B skeleton + 41B input + 9B output)
```
```
- 5 bytes: minimum `scriptPubKey`
Closes https://github.com/rust-bitcoin/rust-bitcoin/issues/4108
> Policy: Relax MIN_STANDARD_TX_NONWITNESS_SIZE to 65

- units/src/parse.rs
We have two macros that are hidden because they are code de-duplication tools. However the output they produce is, and has to be, stable so that we can use them in `units` and `primitives` without inadvertently breaking semver in `primitives`.
> units: Improve code comment on macros

- bitcoin/src/blockdata/script/instruction.rs
- bitcoin/src/p2p/message.rs
- bitcoin/src/taproot/serialized_signature.rs
- units/src/amount/mod.rs
This PR fixes several typos in comments across multiple files:
- Fixed typo `interpretted` -> `interpreted` in `blockdata/script/instruction.rs`
- Fixed typo `neccessity` -> `necessity` in `p2p/message.rs` 
- Fixed typo `underlflow` -> `underflow` in `taproot/serialized_signature.rs`
- Fixed typo `ambigous` -> `ambiguous"` in `units/src/amount/mod.rs`
These changes only affect comments and documentation, no functional code changes.
> Fix typos in code comments and documentation

- hashes/README.md
Hi,
I suggest some typo fix' for this doc:
1- "since these are needed to display hashes anway."  Should be "since these are needed to display hashes anyway." (spelling error).
2- "bench mark" and "bench marks" Should be "benchmark" and "benchmarks" (incorrect spacing; "benchmark" is a single word).
Thanks.
> Typo fix in: README.md

- units/src/fee.rs
We have a bunch of 'Returns [`None`] if .. ' statements. Make the whole module uniform.
> Use uniform return statement in docs

- primitives/src/block.rs
- primitives/src/locktime/absolute.rs
- primitives/src/locktime/relative.rs
- primitives/src/opcodes.rs
- primitives/src/pow.rs
- primitives/src/sequence.rs
- primitives/src/transaction.rs
- primitives/src/witness.rs
Functions that fit the below criteria should be inline:
> Basically, if a function jut delegates into another function and passing through arguments, it should be inline. Also when doing assignment of `u32` or similarly trivial operation. Also if it checks the validity of argument(s) and then performs something simple (like a call to `_unchecked`).
_Originally posted by Kixunil in https://github.com/rust-bitcoin/rust-bitcoin/pull/4099#discussion_r1966156399_
Add `#[inline]` to all functions in `primitives` that fit the criteria.
> primitives: Inline small functions

- units/src/weight.rs
Weight implements `Div` but not `Rem`.
Add the `Rem` implementation.
Add a test for the remainder operation on `Weight`
Close #4171
> Implement `Rem` for `Weight`

- bitcoin/src/blockdata/mod.rs
- bitcoin/src/blockdata/opcodes.rs
- bitcoin/src/blockdata/script/mod.rs
- bitcoin/src/blockdata/script/tests.rs
- bitcoin/src/lib.rs
- primitives/src/lib.rs
Duplicate `opcodes` in `bitcoin` and hide it in `primitives` so we do not have to commit to the API.
We use opcodes in `impl fmt::Display for Script`.
Close: #4144
> Move `opcodes` back to bitcoin

- bitcoin/examples/ecdsa-psbt-simple.rs
- bitcoin/examples/sign-tx-segwit-v0.rs
- bitcoin/src/hash_types.rs
- bitcoin/src/lib.rs
The `{W}PubkeyHash` and `{W}ScriptHash` types are not likely to be used directly by consumers of the library because we have other function that return them and are more ergonomic to use. There is therefor no good reason to re-export them from the crate root.
> bitcoin: Remove hash type re-exports

- fuzz/fuzz_targets/bitcoin/deserialize_psbt.rs
- fuzz/fuzz_targets/bitcoin/deserialize_script.rs
- fuzz/fuzz_targets/bitcoin/fuzz_utils.rs
This PR adds fuzz coverage for `count_sigops`, `count_sigops_legacy`, `minimal_non_dust` and `minimal_non_dust_custom`. In order to not duplicate `consume_random_bytes`, it moves it to a util file and adds a `consume_u64` function to be used in the `deserialize_script` target to fuzz `minimal_non_dust_custom`.
> fuzz: cover more stuff for Script

- .github/workflows/cron-daily-kani.yml
- .github/workflows/rust.yml
GitHub is deprecating the ubuntu-20.04 runner, with removal scheduled for 2025-04-01 (see [GitHub Issue #11101](https://github.com/actions/runner-images/issues/11101)).
This PR updates the CI/CD workflows to use ubuntu-24.04 instead of ubuntu-20.04 for the following workflows:
- cron-daily-kani.yml
- rust.yml (Kani codegen job)
This change should resolve the CI/CD error in the Kani codegen - stable toolchain job triggered by pull requests.
> ci: update Kani GitHub Actions runners to ubuntu-24.04

- bitcoin/src/crypto/key.rs
- bitcoin/src/psbt/serialize.rs
This fixes the bug introduced in #4154 and deprecates `from_slice` method in favor of `from_byte_array` (see commits).
Closes #4191
> Private key from slice fix

- bitcoin/src/bip152.rs
- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/constants.rs
- bitcoin/src/lib.rs
- bitcoin/src/pow.rs
- primitives/src/block.rs
- primitives/src/lib.rs
- units/src/lib.rs
- units/src/timestamp.rs
- units/tests/api.rs
Bitcoin block headers have a timestamp. Currently we are using a `u32`. While this functions correctly it gives the compiler no chance to enforce type safety.
Add a `Timestamp` newtype that is a thin wrapper around a `u32`. Document it and test the API surface in `api.rs`.
> Add `Timestamp` newtype

- bitcoin/src/lib.rs
- primitives/src/lib.rs
As we do for other types add two new alias' at the crate root of `primitives` and mirror it in `bitcoin`:
- `BlockVersion`
- `TransactionVersion`
> Add additional re-exports

- primitives/src/transaction.rs
- units/src/amount/tests.rs
This kills 15 mutants found with the mutants workflow. Ran `cargo mutants` locally to confirm
Closes #4156 
Closes #4106
> Kill mutants in primitives and units

- .github/workflows/coveralls.yml
- .github/workflows/cron-daily-fuzz.yml
- .github/workflows/cron-weekly-cargo-mutants.yml
- .github/workflows/cron-weekly-rustfmt.yml
- .github/workflows/cron-weekly-update-cargo-semver-checks.yml
- .github/workflows/cron-weekly-update-nightly.yml
- .github/workflows/cron-weekly-update-stable.yml
- .github/workflows/gh-release.yml
- .github/workflows/manage-pr.yml
- .github/workflows/miri.yml
- .github/workflows/release.yml
- .github/workflows/rust.yml
- .github/workflows/semver-checks-pr-label.yml
- .github/workflows/semver-checks.yml
- .github/workflows/shellcheck.yml
- fuzz/generate-files.sh
This PR updates all GitHub workflow files to use `ubuntu-24.04` instead of `ubuntu-latest`. 
This change improves CI reliability by:
- Pinning to a specific Ubuntu version instead of a floating reference
- Preventing unexpected CI failures when GitHub updates the `ubuntu-latest` alias
- Ensuring consistent build environments and reproducible CI results
- Allowing for controlled migration to newer Ubuntu versions when ready
The modification affects all workflow files in the `.github/workflows/` directory and the fuzz generation script.
Context:
> Yeah, I prefer the explicit version (and would prefer changing the other `-latest` ones to use the explicit version too). But I don't feel strongly.
_Originally posted by apoelstra in https://github.com/rust-bitcoin/rust-bitcoin/pull/4188#discussio …
> ci: Update GitHub workflows to use ubuntu-24.04 instead of ubuntu-latest

- bitcoin/src/bip32.rs
- bitcoin/src/consensus/encode.rs
- bitcoin/src/psbt/macros.rs
- bitcoin/src/psbt/map/input.rs
- hashes/src/hash160/mod.rs
- hashes/src/hkdf/mod.rs
- hashes/src/hmac/mod.rs
- hashes/src/internal_macros.rs
- hashes/src/lib.rs
- hashes/src/ripemd160/mod.rs
- hashes/src/sha1/mod.rs
- hashes/src/sha256/mod.rs
- hashes/src/sha256d/mod.rs
- hashes/src/sha256t/mod.rs
- hashes/src/sha384/mod.rs
- hashes/src/sha512/mod.rs
- hashes/src/sha512_256/mod.rs
- hashes/src/siphash24/mod.rs
- hashes/tests/regression.rs
- io/src/hash.rs
- io/src/lib.rs
This is the done as part of #4051.
Requires some surgery on the `Hmac` and `Hkdf` types as well as a few other patches to maintain the logic that is currently provided by the trait. Final patch is a pure red diff - enjoy.
> Remove the `GeneralHash` trait

- units/src/amount/mod.rs
A public enum with simple variants gets an automatic integer variant that can be cast by library consumers. This puts a unnecessary maintenance burden upon us because we cannot then add variants in the middle of others.
Add a hidden variant to the single public non-error enum in `units`.
> units: Prevent casting pub enums as ints

- bitcoin/src/blockdata/transaction.rs
This fixes #4141
Changed `count_witness_sigops` to take the `spent` closure by value instead of `&mut`
This removes the need for `&mut` when calling the function while still allowing mutable closure to be passed when needed
> Take `spent` closure by value in `count_witness_sigops`

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/src/taproot/merkle_branch.rs
- hashes/Cargo.toml
- hashes/src/ripemd160/crypto.rs
- hashes/src/ripemd160/mod.rs
- hashes/src/sha1/crypto.rs
- hashes/src/sha1/mod.rs
- hashes/src/sha256/crypto.rs
- hashes/src/sha256/mod.rs
- hashes/src/sha512/crypto.rs
- hashes/src/sha512/mod.rs
- internals/src/lib.rs
- internals/src/slice.rs
This is now ready for review.
In the past we've been using `chunks_exact` because const generics were unstable but then, when they were stabilized we didn't use `as_chunks` (or `array_chunks`) since they were unstable. But the instability was only because Rust devs don't know how to handle `0` being passed in. The function is perfectly implementable on stable. (With a tiny, easy-to-understand `unsafe` block.) `core` doesn't want to make a decision for all other crates yet but we can make it for our own crates because we know that we simply never pass zero. (And even if we did, we could just change the decision.)
It also turns out there's a hack to simulate `const {}` block in our MSRV, so we can make compilation fail early.
This commit adds an extension trait to internals to provide the …
> Replace uses of `chunks_exact` with `as_chunks`

- bitcoin/src/blockdata/mod.rs
When we added the `fee_rate::serde` module we forgot to re-export it. This is needed so downstream can do specify serde attributes on struct fields.
```rust
#[serde(with = "bitcoin::fee_rate::serde::as_sat_per_kwu")]
rate: FeeRate,
```
> Add `fee_rate::serde` re-export

- units/src/amount/result.rs
- units/src/amount/tests.rs
Improve the test coverage and add missing implementations of math operations for the amount types.
Along the way close #4030.
> Improve ops for amount types

- fuzz/fuzz_targets/bitcoin/deserialize_psbt.rs
- fuzz/fuzz_targets/bitcoin/deserialize_script.rs
- fuzz/src/fuzz_utils.rs
- fuzz/src/lib.rs
#4185 introduced a new file `fuzz/fuzz_targets/bitcoin/fuzz_utils.rs` which is not a valid fuzz target.  This causes the daily fuzz workflow to fail on `verify-execution`.
Move the module to the `src/` directory. Create a `lib.rs` file.
> Fix fuzz targets

- bitcoin/src/blockdata/script/instruction.rs
- bitcoin/src/taproot/serialized_signature.rs
- units/src/amount/mod.rs
- units/src/amount/signed.rs
- units/src/amount/unsigned.rs
The use of underflow is misleading.  Adding one to MAX and subtracting one from MIN are both considered an overflow.
Note I tried to keep to 80 column line length so a paragraph needed some shuffling.
closes https://github.com/rust-bitcoin/rust-bitcoin/issues/4187
> Replace underflow with overflow in doc comments

- io/src/error.rs
docs: The quotation marks are incorrect.
> docs: The quotation marks are incorrect.

- README.md
- bitcoin/Cargo.toml
- primitives/Cargo.toml
Hey there!
I am just getting up to speed with the project and in following the README discovered that there are still references to the previous mutation testing tool `mutagen`. I updated the README to refer to the new tool, `cargo-mutation`.
I'm suggesting the user use the same command, `cargo mutants --in-place --no-shuffle`, as is run in the weekly CI workflow.
I noticed that there are still references to the old `mutate` attribute in the following files. I removed these as well as per [feedback](https://github.com/rust-bitcoin/rust-bitcoin/pull/4228#issuecomment-2709407253).
`primitives/Cargo.toml`:
```
[lints.rust]
unexpected_cfgs = { level = "deny", check-cfg = ['cfg(mutate)'] }
```
and 
`bitcoin/Cargo.toml`:
```
unexpected_cfgs = { level = "deny", check-cfg = ['cfg(bench)', …
```
> docs: Update README to replace use of mutagen with cargo-mutants

- bitcoin/src/blockdata/script/borrowed.rs
- bitcoin/src/blockdata/script/tests.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/tests/serde.rs
- units/src/amount/mod.rs
- units/src/amount/result.rs
- units/src/amount/signed.rs
- units/src/amount/tests.rs
- units/src/amount/unsigned.rs
- units/src/fee.rs
- units/tests/str.rs
We want to start enforcing MAX_MONEY as an invariant in the amount types. There are a few more steps we can do first to make that change easier to review.
> Prepare to enforce MAX_MONEY invariant

- bitcoin/src/blockdata/constants.rs
fad0d9ea2d1e807806fa141238e279fddea6ae99: add `MAX_BLOCK_SERIALIZED_SIZE` as constant, which also exists in [bitcoin-core](https://github.com/bitcoin/bitcoin/blob/59ff17e5af4e382cbe16f183767beef1bdcd9131/src/consensus/consensus.h#L13).
I originally thought it would be better to use this value for checking limit of push_bytes [here](https://github.com/rust-bitcoin/rust-bitcoin/blob/0870cd1660edd21739cc94075e4b3a1c7f1a7d15/bitcoin/src/blockdata/script/push_bytes.rs#L31), as it's the actual limit(`OP_PUSHDATA4` semantic says it could allow up to 4GB though). However, I'm not sure whether there might be need to push_bytes larger than `MAX_BLOCK_SERIALIZED_SIZE`, so just let developer use this constant to check the actual limit rather than enforcing it.
> feature: introduce MAX_BLOCK_SERIALIZED_SIZE to check limit

- bitcoin/src/p2p/mod.rs
Include `P2P_V2` on `service_flags_test`
> test: add coverage for ServiceFlags::P2P_V2

- bitcoin/src/blockdata/script/borrowed.rs
- bitcoin/src/lib.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/tests/psbt-sign-taproot.rs
- primitives/src/transaction.rs
- units/src/amount/mod.rs
- units/src/amount/result.rs
- units/src/amount/serde.rs
- units/src/amount/signed.rs
- units/src/amount/tests.rs
- units/src/amount/unsigned.rs
- units/src/amount/verification.rs
- units/src/fee.rs
Enforcing the `MAX_MONEY` invariant is quite involved because it means multiple things:
- Constructing amounts is now fallible
- Converting from unsigned to signed is now infallible
- Taking the absolute value is now infallible
- Integer overflow is eliminated in various places
Details:
- Update `from_sat` to check the invariant
- Fix all docs including examples
- Use the unchecked constructor in test code
- Comment any other use of the unchecked constructor
- Deprecate `unchecked_abs`
- Fail serde (using the horrible string error variant)
- Try not to use the unchecked constructor in rustdocs, no need to encourage unsuspecting users to use it.
- Use `?` in rustdoc examples (required by Rust API guidlines)
- Remove `TryFrom<Amount> for SignedAmount` because the conversion is now …
> Enforce MAX_MONEY invariant in amount types

- bitcoin/src/address/mod.rs
Users may wish to ask of an address 'what kind of address is this?' We have the `NetworkKind` struct that abstracts over the answer but currently no API to ask the question.
The address may have been parsed or constructed and weather the network has been checked already is immaterial. Hence we add the function for both `NetworkChecked` and `NetworkUnchecked` addresses.
Fix: #4247
> Enable getting the network kind from an address

- bitcoin/examples/ecdsa-psbt-simple.rs
- bitcoin/examples/sighash.rs
- bitcoin/examples/sign-tx-segwit-v0.rs
- bitcoin/examples/sign-tx-taproot.rs
- bitcoin/examples/taproot-psbt-simple.rs
- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/blockdata/script/tests.rs
- bitcoin/src/crypto/sighash.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/tests/serde.rs
- units/src/amount/error.rs
- units/src/amount/mod.rs
- units/src/amount/signed.rs
- units/src/amount/tests.rs
- units/src/amount/unsigned.rs
- units/src/fee.rs
This does some followups to #4157.
It pulls in #4254, which changes the signature of `Amount::from_int_btc_const` and also replaces a `checked_mul` which can't ever fail with a `*`.
It then renames `from_int_btc_const` to `from_btc_u16`/`from_btc_i16` as appropriate, since these names reflect what the function does. It also adds an analogous method for making `Amount`s from sats rather than BTC.
Then it systematically removes every instance of `from_sat_unchecked`. There wind up being 7 instances in tests that I just added unwraps() to, plus one instance where we had `let sat = Amount::from_sat_unchecked` which I also added an unwrap() to.
In the real code, there was one instance (`Amount::to_signed`) where I needed to add an `expect`. Every other instance I was able to remove, by …
> Followups to #4157: remove Amount::from_sat_unchecked

- bitcoin/src/blockdata/witness.rs
- bitcoin/src/taproot/merkle_branch.rs
- bitcoin/src/taproot/merkle_branch/borrowed.rs
- bitcoin/src/taproot/merkle_branch/buf.rs
- bitcoin/src/taproot/merkle_branch/mod.rs
- bitcoin/src/taproot/mod.rs
This implements a bunch of changes needed to make `ControlBlock` alloc-free. In particular, this allows constructing `Witness` without the intermediate allocation. It is also a step towards having `P2TrSpend` public.
Closes #1614 
This also intentionally does **not** address decoding of `ControlBlock` from `Witness` since I'm not sure about the API.
Rationale for doing the `Buf` rename: while doing it with `Script` was very painful it shouldn't be here since it's not used that often and also we can just backport the first commit with deprecated type alias. I was thinking of having `TaprootMerkleBr` but it'd be inconsistent and the name is silly.
(Also if anyone is wondering why I did this: I was too exhausted to do more important stuff but felt like doing something nice and easy like …
> Alloc-free (AKA zero-copy) control block

- base58/src/lib.rs
- bitcoin/src/address/mod.rs
- bitcoin/src/address/script_pubkey.rs
- bitcoin/src/bip152.rs
- bitcoin/src/bip158.rs
- bitcoin/src/bip32.rs
- bitcoin/src/crypto/key.rs
- bitcoin/src/crypto/taproot.rs
- bitcoin/src/lib.rs
- bitcoin/src/psbt/serialize.rs
- bitcoin/src/taproot/mod.rs
- internals/src/array.rs
- internals/src/lib.rs
- internals/src/slice.rs
- primitives/src/witness.rs
Previously we've used `try_into().expect()` because const generics wer
unavailable. Then they become available but we didn't realize we could
already convert a bunch of code to not use panicking conversions. But we
can (and could for a while).
This adds an extension trait for arrays to provide basic non-panicking
operations retutning arrays, so they can be composed with other
functions accepting arrays without any conversions. It also refactors a
bunch of code to use the non-panicking constructs but it's certainly not
all of it. That could be done later. This just aims at removing the
ugliest offenders and demonstrate the usefulness of this approach.
> Remove a bunch of `try_into().expect()`

- bitcoin/src/blockdata/constants.rs
- bitcoin/src/p2p/message.rs
- hashes/src/macros.rs
- primitives/src/transaction.rs
The `hash_newtype` macro is explicitly designed to produce a hash that is not a general purpose hash type to try and prevent users hashing arbitrary stuff with it. E.g., `Txid` isn't meant to be just hash arbitrary data. However we provide a `From` impl that will convert any instance of the inner hash type into the new type. This kind of defeats the purpose. We provide `from_byte_array` and `to_byte_array` to allow folk to 'cast' from one hash type to another if they really want to and its ugly on purpose.
Also, it is becoming apparent that we may be able to remove the `hashes` crate from the public API of `primitives` allowing us to stabalise `primitives` without stabalising `hashes`.
For both these reasons remove the `From` impl from the `hash_newtype` macro. Note that deprecating …
> Remove `From<hash>` for not-general-hash types

- bitcoin/src/taproot/merkle_branch/buf.rs
- units/src/amount/signed.rs
- units/src/amount/unsigned.rs
This PR makes two main changes:
1. Standardizes the function signatures in the `Amount` and `SignedAmount` implementations by consistently using `Self` as the return type instead of the concrete type names. This improves code consistency, maintainability, and follows Rust's idiomatic practices.
2. Renames `impl_try_from_array` to `impl_from_array` to better reflect its functionality.
**Consistent usage of Self instead of concrete types**
- Replace all occurrences of `-> Amount` with `-> Self `in unsigned.rs
- Replace all occurrences of `-> SignedAmount` with `-> Self` in signed.rs
- Make similar replacements for Option/Result return types
- Use `Self::` instead of explicit type name for static method calls
**Function rename**
Renamed `impl_try_from_array` to `impl_from_array` for better …
> Make code style consistent and fix naming in macro Array implementations

- bitcoin/src/blockdata/witness.rs
- primitives/src/witness.rs
This is supposed to go in front of #4250 
`Witness` lacked a bunch of APIs that were making it harder to use and test, so this also adds them in addition to cleaning up tests. (I only realized they are missing when I tried to clean up tests and got a bunch of errors.)
> `Witness` api improvements and test cleanups

- bitcoin/src/hash_types.rs
- bitcoin/src/lib.rs
BIP-158 (Compact Block Filters for Light Clients) is not so common as to require re-exorting its types at the crate root - remove them.
> Remove bip158 types from crate root

- bitcoin/src/psbt/serialize.rs
```
warning: it is more concise to loop over containers instead of using explicit iteration methods
--> bitcoin/src/psbt/serialize.rs:209:21
|
209 |         for cnum in self.1.into_iter() {
|                     ^^^^^^^^^^^^^^^^^^ help: to write this more concisely, try: `&self.1`
```
> chore: remove explicit into iteration

- Cargo.toml
- base58/Cargo.toml
- bitcoin/Cargo.toml
- bitcoin/embedded/Cargo.toml
- hashes/Cargo.toml
- hashes/embedded/Cargo.toml
- io/Cargo.toml
- primitives/Cargo.toml
- units/Cargo.toml
This PR want to:
1. make all workspace members use `workspace = true` syntax to import dependencies.
2. use `path = [balabala]` to define dependencies, instead of useing `[patch.crates-io.balabala]` , fix: https://github.com/rust-bitcoin/rust-bitcoin/issues/4283
> Use `path = [bala]` for `rust-bitcoin`'s workspace members dependencies. remove `[patch.crates-io.balab]` 

- .cargo/mutants.toml
- units/src/amount/tests.rs
- units/src/time.rs
Weekly mutation testing found mutants in `Amount` and `BlockTime`.
Add a test to `BlockTime`.
Add two asserts to `Amount` tests.
Exclude deprecated function from mutation testing.
Closes #4225, #4243, #4278
> units: Kill mutants found in weekly mutation testing

- bitcoin/src/address/error.rs
- bitcoin/src/address/mod.rs
- bitcoin/src/blockdata/script/push_bytes.rs
- bitcoin/src/blockdata/witness.rs
- bitcoin/src/crypto/key.rs
- bitcoin/src/taproot/merkle_branch/borrowed.rs
- bitcoin/src/taproot/mod.rs
- hashes/src/internal_macros.rs
- hashes/src/sha256t/mod.rs
- internals/src/lib.rs
- internals/src/macros.rs
- io/src/bridge.rs
- primitives/src/script/borrowed.rs
- primitives/src/script/mod.rs
- primitives/src/script/owned.rs
Well, I thought this PR will be just the last commit... :sweat_smile: 
Anyway, this implements a bunch of changes to allow returning `ControlBlock` from `Witness` method(s). One cool side effect is that this PR also reduces the number of `unsafe` blocks.
> Return `ControlBlock` from `Witness::taproot_control_block`

- bitcoin/src/blockdata/script/witness_version.rs
The correction is important because “P2WPK” is not a valid name. In the BIP141 specifications, the correct terms are “P2WPKH” and “P2WSH”.
> fix err `P2WPKH` to `P2WSH` witness_version.rs

- hashes/src/cmp.rs
- hashes/src/hmac/mod.rs
Fuzzers want to break memcmp calls into separate comparisons for coverage monitoring, allowing them to not-quite-brute-force find inputs that fully match. Thus, we disable our fancy fixed-time comparison when built with the `hashes_fuzz` cfg.
> [hashes] Disable fixed-time equality cmp when building for fuzzers, use fixed-time equality for `Hmac`

- units/src/fee_rate/serde.rs
- units/src/locktime/absolute.rs
- units/src/parse.rs
There’s no reason to use ? to short-circuit when execution of the body will end there anyway.
> chore: remove needless question mark

- base58/src/error.rs
- bitcoin/CHANGELOG.md
- units/src/amount/error.rs
- units/src/fee_rate/mod.rs
- units/tests/api.rs
base58/src/error.rs:
- Corrected grammar in error comment: "Found a invalid ASCII byte" → "Found an invalid ASCII byte".
bitcoin/CHANGELOG.md:
- Fixed typo in function name: p2wpkh_signiture_hash → p2wpkh_signature_hash.
units/src/amount/error.rs:
- Fixed grammar: "was large than" → "was larger than".
units/src/fee_rate/mod.rs:
- Corrected typo: "assoctiated" → "associated".
units/tests/api.rs:
- Grammar fix: "THE POINT of tests are" → "THE POINT of tests is".
> chore: fix grammatical errors

- Cargo-minimal.lock
- Cargo-recent.lock
- hashes/Cargo.toml
checked by [shear](https://github.com/boshen/cargo-shear)
```
bitcoin_hashes -- hashes/Cargo.toml:
serde_json
Fixed 1 dependencies!
```
cargo +nightly build  in local env is ok, local cargo.lock  is ok(not include serde_json) so no need update cargo.lock
```
[[package]]
name = "bitcoin_hashes"
version = "0.16.0"
dependencies = [
"bitcoin-internals",
"hex-conservative 0.3.0",
"serde",
"serde_test",
]
```
but check CI seems need update 
`error: the lock file /home/runner/work/rust-bitcoin/rust-bitcoin/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.`
> chore: remove unused serde_json dep

- bitcoin/src/blockdata/script/builder.rs
This pr improves the script builder API to better align with Bitcoin semantics when working with relative timelocks:
- Add `push_relative_lock_time()` method that takes a `relative::LockTime` parameter, which correctly represents the semantic meaning when working with CHECKSEQUENCEVERIFY
- Deprecate `push_sequence()` in favor of `push_relative_lock_time()` to avoid confusion between sequence numbers and relative timelocks
This addresses a potential confusion point in the API where developers might incorrectly push raw sequence numbers in scripts when what they actually need is to push a relative locktime value that will be checked against the transaction's sequence numbers by CHECKSEQUENCEVERIFY.
Closes #4301
> Add push_relative_lock_time() and deprecate push_sequence()

- CONTRIBUTING.md
Lately we have had a bunch of new devs bumping PRs trying to get things merged. Everyone gets excited, no need to be too harsh on them. At least we can try to explain why we might be taking so long.
We (*cough* Andrew) runs a custom CI box that leads to slightly unusual merge behaviour in this repo if one is unaware of it.
Document our CI better and ask folk not to bump too much.
> Update contributing guide re merging and CI

- bitcoin/tests/bip_174.rs
This pull request renames the variable 'indecies' to 'indices' throughout the bip_174.rs file to use the correct plural form of 'index'. The change affects both variable names and comments, ensuring consistent and proper terminology throughout the codebase.
Changes include:
- Renamed 'indecies' to 'indices' in comments
- Renamed the variable declaration and all references
- Updated the for loop iteration
This is a simple terminology correction with no functional changes to the code.
> Rename 'indecies' to 'indices' in bip_174.rs for correct terminology

- units/src/amount/mod.rs
- units/src/amount/result.rs
- units/src/amount/tests.rs
- units/src/fee.rs
- units/src/internal_macros.rs
- units/src/lib.rs
- units/src/result.rs
First 4 patches are preparatory clean up. Patch 5 and 6 make all implementations of `Div` in the crate return `NumOpResult`. Done as two separate patches to assist review and in case we need to iterate, patch 5 is likely trivial to review.
Fix: #4215
> units: Return `NumOpResult` when implementing `Div`

- hashes/Cargo.toml
Update serde from 1.0 to 1.0.103 to align with versions used in other workspace crates. This makes the dependency constraint match reality since it was almost always implicitly raised by the other crates.
I ran the `update-lock-files`, but no changes, which makes sense since other crates in the workspace bumped the version.
A bit more info in https://github.com/rust-bitcoin/rust-bitcoin/issues/4313#issuecomment-2786281653 with talk about minimal version testing.
> hashes: update serde dependency to match workspace

- internals/src/array.rs
This PR corrects a typo in the documentation comment for the array splitting method in `internals/src/array.rs`. Changed "overlaping" to the correct spelling "overlapping".
> fix typo in `array.rs` documentation

- primitives/src/script/borrowed.rs
- primitives/src/script/mod.rs
Update test in borrowed to cover the `default` implementation of `Script`.
Add tests to cover all `TryFrom` implementations in `Script`
> primitives: Add tests to improve coverage

- bitcoin/src/blockdata/script/tests.rs
Description:
This PR fixes a typo in the test function name `p2pk_pubkey_bytes_emptry_script_returns_none()` by correcting 'emptry' to 'empty'. This is a minor correction that improves code readability without affecting functionality.
> fix typo in test function name

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/Cargo.toml
- primitives/Cargo.toml
- primitives/src/block.rs
- primitives/src/merkle_tree.rs
- primitives/src/script/mod.rs
- primitives/src/transaction.rs
- primitives/src/witness.rs
Make the `hex` dependency optional. This means not implementing
`Display` for some types if `hex` is not enabled and only implementing
`Debug`.
Also without `hex` enabled:
- We loose the ability to parse an `OutPoint` from string because we
can no longer parse `Txid`.
- We loose the hex formatting of witness elements.
Note also that `primitives` builds with the `serde` feature even if
`hex?/serde` is excluded from the `serde` feature. I found this
surprising.
Close: #4183
> primitives: Make `hex` optional

- bitcoin/src/blockdata/script/borrowed.rs
- bitcoin/src/blockdata/script/tests.rs
- bitcoin/src/blockdata/transaction.rs
Closes #4221 
This removes the `Option` return type from `minimal_non_dust
Overflow is only possible in 2 cases:
- `dust_relay_fee` would need to be excessively high
- script size would have to exceed ~6.15 × 10¹⁵ bytes (≈ 6 petabytes)
we now panic with the same message we had before in  https://github.com/rust-bitcoin/rust-bitcoin/blob/cf12ba262a646a6341098ee3f4c178a52fc90211/bitcoin/src/blockdata/script/borrowed.rs#L412
> Remove Option return from `minimal_non_dust`

- bitcoin/src/bip152.rs
- bitcoin/src/blockdata/script/tests.rs
Fix the typos in the comments and variables
> chore: Fix the typos in the comments and variables

- units/src/amount/mod.rs
The and_then combinator performs a kind of bitwise and operation on two Option types here.  This is useful since the `checked` arithmetic returns an option thereby accumulating Option types.  Therefore, either the checked arithmetic operation performs the addition of the unwrapped accumulator, or it returns None.
Instead of using `and_then` use the provided `try_fold` method which will short circuit on `None` when the checked arithmetic is used.  Also, simplify the staring condition using `Amount:ZERO` since this is logically equivalent to using the first value if one exists.
Lastly, by using the built in `try_fold`, it's possible the performance will be improved by making use of the short circuit ability instead of evaluating each item even when the accumulator holds a None type.
> refactor: Replace fold with try_fold

- primitives/src/script/borrowed.rs
- primitives/src/script/owned.rs
The byte slice/vector in the to/from methods for the script types does not include the length prefix that is used when consensus encoding.
Add docs to make this more clear.
> primitives: Document script to/from bytes

- hashes/tests/api.rs
As we did for `units` and as part of the stabalization effort.
Add an `api` test module that verifies the public API for the `hashes` crate.
Close: #3927
> hashes: Add an `api` test module

- Cargo-minimal.lock
- Cargo-recent.lock
- primitives/Cargo.toml
- primitives/src/block.rs
Not all the fields within `block::Header` implement `Display` however a block header can reasonably be displayed by using 160 hex characters.
Implement `Display` for `block::Header` by printing the header in hex in the same layout as we hash it in `block_hash`.
Close: #3658
> Implement `Display` for  `Header`

- units/src/amount/signed.rs
- units/src/amount/unsigned.rs
This is a follow up to #4256 - onwards and upwards!
- Patch 1: Fix the incorrect BTC value in panic message
- Patch 2: Strictly adhere to the sanity rules (#4090)
Close: #4140
> units: Improve code enforcing privacy boundry

- units/src/amount/error.rs
- units/src/amount/signed.rs
- units/src/amount/unsigned.rs
- units/src/fee.rs
- units/src/fee_rate/mod.rs
- units/src/locktime/absolute.rs
- units/src/locktime/relative.rs
- units/src/result.rs
- units/src/weight.rs
I have read through all of the `units` docs and made a few changes.
- Highlight `Warning!` in bold in `Amount` and `SignedAmount`
- Change the one occurrence of fee-rate to fee rate to be consistent with the rest.
- Make all of the error structs have the same title format of `Error returned...`
- Make all other structs have the same format concisely stating what it is opposed to what it does.
> units: Go over the rendered docs for the whole crate

- primitives/src/script/mod.rs
Expand existing tests and add new ones to increase the test coverage in `primitives/src/script/` to 100% excluding `serde` and `arbitrary` features.
> primitives: Increase test coverage in `Script`

- primitives/src/script/borrowed.rs
- primitives/src/script/mod.rs
- units/src/amount/mod.rs
- units/src/fee.rs
- units/src/fee_rate/mod.rs
- units/src/time.rs
- units/src/weight.rs
Add privacy boundary for `FeeRate`, `BlockTime`, and `Weight`. The lock times are a bit curly so just doing these ones for now.
> units: Implement privacy boundaries

- units/src/result.rs
Follow up from #4312, improve the `MathOp` type by:
- Do not provide public constructor
- Add cast protection
> units: Make minor improvements to `MathOp`

- bitcoin/Cargo.toml
Gating like the other features should do the trick.
> Allow using the 'base64' feature in `no_std` environments

- bitcoin/src/taproot/mod.rs
The PR introduces a new function `try_into_tap_tree()` to replace `try_into_taptree()`. `try_into_taptree()` has been deprecated.
This PR fixes #4364
> Rename `try_into_taptree` to `try_into_tap_tree`

- bitcoin/src/blockdata/script/tests.rs
Following https://github.com/rust-bitcoin/rust-bitcoin/pull/4322.
Test `push_slice` and `push_slice_nom_minimal` from OP_1...OP_16 and OP_1NEGATE.
> test: add test for push slice minimal

- primitives/src/block.rs
This error path cannot happen, and if it could, failing formatting is not the correct source of action, because the std docs say that formatting may only fail if the formatter says so.
Fixes comment in #4269
> primitives: replace error propagation with `expect`

- bitcoin/examples/ecdsa-psbt.rs
- bitcoin/src/address/mod.rs
- bitcoin/src/bip158.rs
- bitcoin/src/blockdata/script/mod.rs
- bitcoin/src/consensus/encode.rs
- chacha20_poly1305/src/lib.rs
- hashes/src/internal_macros.rs
- hashes/src/macros.rs
- primitives/src/block.rs
- primitives/src/locktime/absolute.rs
- primitives/src/locktime/relative.rs
- primitives/src/script/borrowed.rs
- primitives/src/sequence.rs
- primitives/src/transaction.rs
- units/src/parse.rs
- units/src/result.rs
In the rustdocs both `# Parameters` and `# Arguments` are used to mean the same thing.  In a previous PR #2792 it was decided to go with Parameters everywhere.  Since then there have been a few additions of "Arguments" into the rustdocs.
There is also a mix in the usage of `#`, `##` or `###` for headings.  Noticed here https://github.com/rust-bitcoin/rust-bitcoin/pull/2792#issuecomment-2125775974.
- Fix a typo found when looking into this.
- Change all occurances to use `# Parameters` in rustdocs.
- Change all heading levels to H1 `#`
- Change all subheading levels to H3 `###` to make the small difference in the rendered font size noticable
Closes #4380
> rustdocs: Make headings consistent

- base58/src/lib.rs
- bitcoin/src/bip158.rs
- bitcoin/src/bip32.rs
- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/constants.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/blockdata/witness.rs
- bitcoin/src/crypto/sighash.rs
- bitcoin/src/merkle_tree/block.rs
- bitcoin/src/p2p/address.rs
- bitcoin/src/p2p/message.rs
- bitcoin/src/p2p/message_blockdata.rs
- bitcoin/src/p2p/message_network.rs
- bitcoin/src/psbt/mod.rs
We have the `hex_lit` dependency for converting a hex string literal to an array.
Currently we have a `test_hex_unwrap` macro in the `hex v0.3.0` release but not on either `master`
or the upcoming `v1.0.0-alpha.0` release. This is making PRs around releasing and depending on the
release more noisy than required.
Introduce a `test_hex_unwrap` macro in internals for usage when the input is not a string literal.
Use `hex_lit::hex` where possible (often needing an additional call to
> Introduce and use `test_hex_unwrap` macro in `internals`

- bitcoin/src/internal_macros.rs
- bitcoin/src/network/params.rs
- bitcoin/src/p2p/message_compact_blocks.rs
- bitcoin/src/psbt/error.rs
- bitcoin/src/psbt/serialize.rs
- bitcoin/src/taproot/mod.rs
This PR addresses several minor issues across the codebase, including:
- Fixing typographical errors in comments and documentation (e.g., "deserilaization" → "deserialization", "send" → "sent").
- Improving sentence clarity and grammar in doc comments (e.g., correcting sentence structure and word choice).
- Enhancing code readability without changing any logic or functionality.
These changes are purely cosmetic and aimed at improving maintainability and developer experience.
> Fix minor typos and improve clarity in documentation and comments

- bitcoin/src/address/mod.rs
- bitcoin/src/address/script_pubkey.rs
- bitcoin/src/blockdata/script/witness_program.rs
Closes #4124.
This PR fixes documentation on `impl WitnessProgram` by replacing instances of `address` to `[WitnessProgram]`, adds punctuation and capitalization where it was lacking and extends the `valid_v1_witness_programs` test to include the P2A output.
> chore: fix docs for `WitnessProgram` and extend test for P2A

- units/src/result.rs
**Description:**
This PR fixes a small typo in the documentation comment in units/src/result.rs where "operatons" was misspelled as "operations". This improves code documentation clarity and consistency.
Changes:
- Corrected spelling of "operatons" to "operations" in the documentation comment
- No functional changes, documentation-only update
> Fix typo in result.rs documentation: "operatons" -> "operations"

- CONTRIBUTING.md
Removed API documentation section due to dead link - couldn't locate the referenced api folder or README file. Happy to restore this with correct link info if someone can provide the proper reference path. Just let me know!
> docs: Remove dead API documentation link in CONTRIBUTING.md

- primitives/src/locktime/relative.rs
- units/src/lib.rs
- units/src/locktime/relative.rs
- units/src/mtp_height.rs
This PR fixes #4299
- Computed MtpAndHeight structure
- Checked if relative time and height is satisfied by MtpAndHeight
- Compared the Ordering of MtpAndHeight with time and height
- Checked MtpAndHeight satisfaction and comparison in Locktime
- Added unit tests for all the implementation
I've reviewed and adhered to the contribution guidelines
> Locktime MtpAndHeight

- bitcoin/Cargo.toml
- bitcoin/examples/ecdsa-psbt.rs
- bitcoin/examples/script.rs
- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/address/mod.rs
- bitcoin/src/blockdata/script/borrowed.rs
- bitcoin/src/blockdata/script/owned.rs
- bitcoin/src/blockdata/script/tests.rs
- bitcoin/src/crypto/sighash.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/src/psbt/serialize.rs
- bitcoin/src/taproot/mod.rs
- bitcoin/tests/bip_174.rs
- bitcoin/tests/serde.rs
- primitives/src/script/mod.rs
Done while investigating #3910 - this PR is quite invasive.
- Patch 1 adds an example that shows the current behaviour of various API calls for converting scripts to/from hex.
- Patch 2 adds a pair of functions that do not use the length prefix and makes script to/from_hex use the prefix.
- Patch 3 makes `LowerHex` and `UpperHex` use the len prefix also
- Patch 4 runs the formatter
Explicitly keeps serde untouched - i.e., without the len prefix
> Improve the script hex APIs

- .cargo/mutants.toml
cargo-mutants 25.0.1 introduced a new mutation pattern that deletes an arm of a match statement or replaces a match guard with true and false. These are applied in sections that have been excluded from mutation testing and cause false positives.
The match patterns are also now stricter causing previously excluded `impl` to be included.
Exclude the new match arm and guard mutation patterns.
Add `impl fmt::` versions for Debug and Display.
Closes #4402
> Mutation testing: Add exclusions for match arm/guard mutants

- primitives/src/sequence.rs
- primitives/src/transaction.rs
The output of `Display` should not change in stable crates for types that have well defined formatting and ones that implement `FromStr`. Error types do not need to be tested. Discussed in #4415.
Add missing tests for all implementations in `primitives` and round trips for types that implement `FromStr`.
> primitives: Add regression tests for `Display` implementations

- units/src/amount/tests.rs
- units/src/locktime/absolute.rs
- units/tests/str.rs
The output of Display should not change in stable crates for types that have well defined formatting and ones that implement FromStr. Error types do not need to be tested.  Discussed in #4415.
Patch 1 is a simple rename to allow for clearer naming when both height and time locktimes are tested.
Patch 2 adds the missing time locktime and denomination `Display` and round trip tests to the existing macro
Patch 3 adds all the other missing `Display` tests in `units`
> units: Add regression tests for `Display` implementations

- githooks/post-merge
Replaced “re-reun” with “re-run” in the post-merge hook notice to provide clear instructions for reinstalling project githooks.
> Fix typo in githooks warning message

- primitives/src/locktime/absolute.rs
If one wishes to verify a script that contains CLTV is valid in a transaction then one must compare the argument to CLTV (the locktime) to the transaction locktime. And to be valid the CLTV locktime must be less than or equal to the transaction locktime. This usage kind of lends itself to the term 'implied by' and we have a function already `is_implied_by` that does exactly this.
Improve the docs by adding a section mentioning this usecase.
> Improve docs on absolute::LockTime::is_implied_by

- .cargo/mutants.toml
The output of Display should not change in stable crates for types that have well defined formatting and ones that implement FromStr. Crates that are included in the mutation testing have been updated to have regression tests for all relevant Display implementations in #4420 and #4422.
Remove the exclusion so that the Display implementations are included in mutation testing.
Together with #4420 and #4422 Closes #4415
> mutants: Remove `impl Display` from mutants.toml exclusion list

- bitcoin/CHANGELOG.md
Fixed malformed markdown links in bitcoin/CHANGELOG.md that were causing errors. Specifically, removed double parentheses from links to primitives and units  CHANGELOG.md files, ensuring proper rendering and accessibility of the documentation.
> Fix broken changelog links

- bitcoin/src/p2p/address.rs
This PR removes support to TorV2 since it's deprecated and no longer useful to have it.
> bitcoin: remove torv2 support

- bitcoin/src/crypto/key.rs
In #4373 we added a couple new conversion methods and deprecated the `to_inner` ones. During that the deprecation date was set to `0.33.0`.
We have backported the changes and will deprecate in `0.32.6` so set the version number now so we don't forget later.
> Set deprecation to released date of to_inner

- bitcoin/examples/sign-tx-taproot.rs
- bitcoin/examples/taproot-psbt-simple.rs
- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/address/mod.rs
- bitcoin/src/address/script_pubkey.rs
- bitcoin/src/bip32.rs
- bitcoin/src/blockdata/script/witness_program.rs
- bitcoin/src/crypto/key.rs
- bitcoin/src/crypto/sighash.rs
- bitcoin/src/psbt/map/input.rs
- bitcoin/src/psbt/map/output.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/src/psbt/serialize.rs
- bitcoin/src/taproot/mod.rs
- bitcoin/tests/psbt-sign-taproot.rs
This PR addresses issue #4361 by creating a wrapper type for XOnlyPublicKey instead of directly re-exporting it from the secp256k1 library.
1. Created a new `XOnlyPublicKey` struct that wraps `secp256k1::XOnlyPublicKey`
2. Implemented custom error types:
- `ParseXOnlyPublicKeyError` for handling parsing errors
- `TweakXOnlyPublicKeyError` for tweaking an `XOnlyPublicKey`
3. Updated all imports and usage throughout the codebase
4. Implemented necessary traits and methods for compatibility
Closes #4361
> Wrap secp256k1::XOnlyPublicKey to improve error handling

- primitives/src/locktime/relative.rs
- units/src/lib.rs
- units/src/result.rs
There is a lint warning about unused variables and imports in the rustdoc examples.
Remove the unused imports and prefix the unused variables with an underscore.
> rustdoc: Fix unused lint warnings

- bitcoin/src/blockdata/transaction.rs
- units/src/fee.rs
- units/src/result.rs
Prefer the more descriptive NumOpResult return type over Option where return types are fallible.
Closes https://github.com/rust-bitcoin/rust-bitcoin/issues/4419
> Use NumOpResult instead of Option

- bitcoin/examples/sign-tx-taproot.rs
- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/blockdata/script/witness_program.rs
- bitcoin/src/crypto/key.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/src/taproot/mod.rs
Backport #4373, authored by Shing Him Ng.
Original gitlog:
For TweakedKeypair, `to_inner` is also renamed to `to_keypair` to maintain consistency. Similarly, `to_inner` is renamed to `to_x_only_pubkey` for TweakedPublicKey
> backport: Add methods to retrieve inner types

- bitcoin/src/crypto/key.rs
- bitcoin/src/psbt/mod.rs
Backport two PRs:
- #3356
- #4238
The first includes a bug fix in a `GetKey` impl and the second is a feature we want to release. And the three refactor patches touch code that #4238 builds on so I figured we should backport them all.
All 5 patches required a small amount of massaging to get in. The first 4 was just adding a `?` to the calls to `derive_priv`. The last patch needed a few calls in the unit test changing.
> backport: Add XOnlyPublicKey support for PSBT key retrieval and improve Taproot signing

- internals/src/slice.rs
The example code is supposed to fail to compile, but if it does run it panics. This somehow confuses the compiler so that either the `compile_fail` tag compiles but causes a lint warning about the panic or using `should_panic` fails to compile.
Change the tag to `ignore`
Closes #4259
> Change rustdoc tag from `compile_fail` to `ignore`

- primitives/src/witness.rs
- primitives/tests/api.rs
In preparation for 1.0-ing `primitives` add an `api` test module that makes an effort to verify the API surface.
This is similar to what is in `units` and what is in development for `hashes` (in #4017).
Note, there is a WIP attempt at this in #3992.
Close: #3928
> primitives: Add an API test module

- units/src/fee.rs
- units/src/result.rs
Follow up from https://github.com/rust-bitcoin/rust-bitcoin/pull/4428 to assert the error type which I agree improves the test.
Added some helper functions since it can be nice to see what type of overflow happened.
> Assert num op error

- units/src/block.rs
This is Rust not C, use functional style.
Close: #4464
> units: Use functional style

- units/src/fee.rs
Allow external const calls to access this method
Followup from https://github.com/rust-bitcoin/rust-bitcoin/pull/4428
> Mark method as constant

- contrib/gen_label_config.sh
Removed unnecessary quotes around the `!=` operator in the Bash test expression, so the `--force` flag is now evaluated correctly instead of always passing.
> Fix argument check in labeler script

- bitcoin/src/blockdata/script/builder.rs
- bitcoin/src/blockdata/script/tests.rs
- primitives/src/script/owned.rs
Enable the creation of `bitcoin::script::Builder` with a preallocated capacity.
This is pretty minor, but it provides a small speedup if used correctly. I've observed a 0.4% speedup and a 0.7% speedup in two code bases that create lots of outputs (on the order of tens to hundreds of thousands). It provided a much larger speedup (5% or so) in the latter code base before some other optimizations dwarfed it.
I have a branch that also uses it for `ScriptBufExt::new_*()` but while it provides a small performance improvement for all script types except one, `ScriptBufExt::new_p2tr()` actually causes a small performance regression. Since the only use case I have for creating lots and lots of scripts is in taproot with CHECKTEMPLATEVERIFY, I'm holding back that change if/until I figure out what's …
> Add `Builder::with_capacity()`

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/CHANGELOG.md
- bitcoin/Cargo.toml
In preparation for release bump the version, add a changelog entry, and update the lock files.
> Release tracking PR: `bitcoin 0.32.6`

- primitives/src/locktime/absolute.rs
Current rustdocs link is not correct. Just remove the brackets because we have a fully labelled link right below.
> Fix link to BIP-113

- units/src/amount/result.rs
- units/src/amount/tests.rs
- units/src/fee_rate/mod.rs
- units/src/weight.rs
The pr implements `Div<NonZeroU64>` and `Div<NonZeroI64>` for the following types in `units` crate: `Amount`, `SignedAmount`, `FeeRate`, `Weight`
For handling owned/borrowed variants, each impl is wrapped in the existing `impl_op_for_references!` macro, which generates: `T  / NonZero*` , `&T / NonZero*`, `T  / &NonZero*`, `&T / &NonZero*`
close: #4442
> Implementing Div<NonZeroU64|I64> for Amount, SignedAmount, FeeRate, and and Weight

- units/src/amount/serde.rs
- units/src/fee_rate/serde.rs
- units/tests/serde.rs
Clean up the `serde` stuff for `FeeRate` and `Amount`. This is all pretty trivial.
> units: `serde` cleanup

- units/src/locktime/relative.rs
- units/src/time.rs
- units/src/weight.rs
For types that have private inner fields we would like to manually implement `serde` traits instead of deriving them.
This hardens the crate against making future mistakes if we want to change the inner fields.
Do so for:
- `Weight`
- `BlockTime`
- `NumberOfBlocks`
- `NumberOf512seconds`
> units: Manually implement serde traits

- bitcoin/src/blockdata/script/borrowed.rs
- bitcoin/src/blockdata/script/owned.rs
We (I) have recently done to PRs patching the way we handle converting scripts to and from hex.
In doing these I made a mess of the deprecation because after both PRs were in I had managed to change the return type and the behaviour of the deprecated function.
On top of that the docs were either outright wrong or not that clear.
Props to Kix for doing post merge review and finding my mistakes.
Close #4498
> Fix up script to/from hex

- units/src/block.rs
We recently added a bunch of types in the `block` module that are wrappers around `u32`. When we did we slapped `pub` on the inner fields.
Lets be more mindful and make the inner fields private. Note all these types have `to_u32`, `from_u32` and `From` in both directions.
> units: Make block-related types have private inner fields

- bitcoin/src/p2p/address.rs
Closes #4436.
Note: I made the `AddrV2::Cjdns` to `SocketAddr` conversion throw the `CjdnsNotRecommended` error. Do we want this behavior or just assume the user knows what he is doing? cc Kixunil
- Implement `From<SocketAddr> for AddrV2`.
- Implement `TryFrom<AddrV2> for SocketAddr`.
- Implement `AddrV2ConversionError` enum and it's `fmt::Display`.
- Tests for these conversions.
> feat(p2p): add `AddrV2` <> `SocketAddr` conversions

- bitcoin/src/psbt/mod.rs
- units/src/fee_rate/mod.rs
- units/tests/str.rs
Parsing and displaying strings is a PITA. `FeeRate` is likely not that heavily used at the moment and users can always just call `to_sat_per_kwu()` to format it.
So we can get the `units-1.0-alpha.0` release out the door just remove the `Display` and `FromStr` impls for now. They can be added back in later when we have time to get #4339 in.
> Remove Display/FromStr for FeeRate

- Cargo-minimal.lock
- Cargo-recent.lock
- chacha20_poly1305/CHANGELOG.md
- chacha20_poly1305/Cargo.toml
Getting out this big bug fix for performance: https://github.com/rust-bitcoin/rust-bitcoin/pull/4083
> Release tracking for chacha20-poly1305 v0.1.2

- bitcoin/src/psbt/mod.rs
Replace a hardcoded fee rate numbers in PSBT high-fee checks test with named constants.
Close #4378
> psbt: replace the fee rate magic numbers with named constants in tests

- .actrc
Closes #4531.
Removes the useless and unused `.actrc` file.
> chore: delete unused `.actrc`

- units/src/fee.rs
We have 4 functions, 2 ceil, 2 floor but they are ordered ceil, floor, floor, ceil - this causes my head to twitch when I read it.
The logic in the floor versions is easier so put them first, this is uniform with `fee_rate/mod.rs`.
Code move only.
> units: re-order ceil/floor functions

- units/src/fee_rate/mod.rs
This function leaks the inner unit of `FeeRate`. We want to change the unit, best to break downstream so they notice.
> Remove `impl From<u64> for FeeRate`

- units/src/fee_rate/mod.rs
Currently the `checked_add` and `checked_sub` functions use a `u64` for the right hand side. This leaks the inner unit because the RHS value is implicitly in the same unit.
Make the functions have `FeeRate` on the RHS.
> Fix FeeRate::checked_add/sub

- CONTRIBUTING.md
Hi devs! I replaced dead link 
`https://github.com/bitcoin/bips/blob/master/bip-0000.mediawiki` to `https://github.com/bitcoin/bips/blob/master/bip-0001.mediawiki`
thanks
> fix dead link CONTRIBUTING.md

- .github/workflows/cron-daily-fuzz.yml
- bitcoin/src/p2p/address.rs
- fuzz/Cargo.toml
- fuzz/fuzz_targets/bitcoin/p2p_address_roundtrip.rs
This PR adds conversion traits between `AddrV2` and standard IP types, inspired by #4519.
- Implement `From<IpAddr>` for `AddrV2`.
-  Implement `From<Ipv4Addr>` for `AddrV2`.
-  Implement `From<Ipv6Addr>` for `AddrV2.`
- Implement `TryFrom<AddrV2>` for `IpAddr`.
- Implement `TryFrom<AddrV2>` for `Ipv4Addr`.
- Implement `TryFrom<AddrV2>` for `Ipv6Addr`.
- Implement `AddrV2ToIpAddrError` enum and it's `fmt::Display`.
- Implement `AddrV2ToIpv4AddrError` enum and it's `fmt::Display`.
- Implement `AddrV2ToIpv6AddrError` enum and it's `fmt::Display`.
- Renamed `AddrV2ConversionError` to `AddrV2ToSocketAddrError`
- Tests for `TryFrom` conversions.
> feat(p2p): add AddrV2 <> IpAddr conversions

- units/src/fee_rate/mod.rs
By convention we put assertions in the order `got` then `want`. This makes debugging easier.
> fee_rate: Put test assertions in correct order

- bitcoin/src/blockdata/transaction.rs
This type creates sane Arbitrary InputWeightPrediction types that do not panic.  To this end, when a custom type is created by calling new() or from_slice() constructor, only use values that would no greater than block size 4 MB of witness data or 1 MB of non-witness data.  This idea is from the discussion here  https://github.com/rust-bitcoin/rust-bitcoin/issues/4547
I'd be up for a future PR that limits the constructors to no greater than 1MB or 4MB witness data, although I feel like this Arbitrary type will be less controversial.
Furthermore, I did test this locally against my application and no panics where produced either through the constructor nor auxiliary methods `total_weight` or `witness_weight`.
> Sane InputWeightPredition Arbitrary Type

- bitcoin/src/psbt/map/input.rs
- bitcoin/src/psbt/map/output.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/src/psbt/serialize.rs
This change adds support for serializing and deserializing two PSBT keys from BIP-373: `PSBT_IN_MUSIG2_PARTICIPANT_PUBKEYS` and `PSBT_OUT_MUSIG2_PARTICIPANT_PUBKEYS`
This is a part of #4207 that can be implemented independently of the rest (which depends on https://github.com/rust-bitcoin/rust-secp256k1/pull/716). I believe this satisfactorily avoids changing things multiple times on end users, *however* it's not *completely* transparent to end users, since any code that currently accesses these fields through `unknown` will need to be updated. Later, when `PSBT_IN_MUSIG2_PUB_NONCE` and `PSBT_IN_MUSIG2_PARTIAL_SIG` are supported, code will need to be updated a second time to retrieve them from the correct place instead of `unknown`. I'm of the opinion that this imposes a very minor …
> Add support for de/serializing PSBT_{IN,OUT}_MUSIG2_PARTICIPANT_PUBKEYS

- bitcoin/src/network/mod.rs
The `ServiceFlags` type is already tested within p2p/mod.rs with a nearly identical test. This type also has nothing to do with `network`
ref: https://github.com/rust-bitcoin/rust-bitcoin/blob/master/bitcoin/src/p2p/mod.rs#L400
> Remove redundant `ServiceFlags` test

- hashes/src/ripemd160/crypto.rs
Hi devs! Found and fixed one typo in `hashes/src/ripemd160/crypto.rs`
`Porallel` - `Parallel`
> fix typo Porallel to Parallel crypto.rs

- bitcoin/src/blockdata/mod.rs
- bitcoin/tests/serde.rs
- primitives/src/locktime/absolute.rs
- primitives/src/locktime/relative.rs
- primitives/tests/api.rs
- units/src/block.rs
- units/src/locktime/absolute.rs
- units/src/locktime/relative.rs
- units/tests/api.rs
Make the APIs uniform in relative and absolute locktimes in relation to the `is_satisfied_by` functions. In doing so improve the API and fix an off-by-one bug when checking satisfaction of locks by height.
Done in three patches but maybe should be squashed? Probably easiest to review by looking at all the `is_satisfied_by*` functions and convincing yourself we got it right.
EDIT: Now has 5 cleanup patches also (mostly docs cleanups).
> Improve lock times - fix off-by-one bug

- Cargo-minimal.lock
- Cargo-recent.lock
- Cargo.toml
- p2p/CHANGELOG.md
- p2p/Cargo.toml
- p2p/README.md
- p2p/contrib/test_vars.sh
- p2p/src/lib.rs
Peer to peer messages change on occasion, and we would like to add messages as they are released from Bitcoin Core. Add an empty crate to take the crate name.
> Introduce empty p2p messages crate

- bitcoin/src/blockdata/script/borrowed.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/psbt/mod.rs
- fuzz/fuzz_targets/bitcoin/deserialize_script.rs
- units/src/amount/tests.rs
- units/src/fee.rs
- units/src/fee_rate/mod.rs
- units/src/fee_rate/serde.rs
- units/src/result.rs
- units/tests/serde.rs
The `FeeRate` is a bit entangled with amount and weight.  Also we have an off-by-one bug caused by rounding errors and the fact that we use kwu internally.
We can get more precision in the fee rate by internally using per million virtual bytes.
- Fix: #4516
- Fix: #4497
- Fix: #3806
> Make `FeeRate` use MvB internally

- units/src/locktime/absolute.rs
Weekly mutation testing found new mutants in both `Height::is_satisfied_by` and `MedianTimePast::is_satisfied_by` functions.
Test these two functions and kill the mutants.
Closes #4587
> units: Add `is_satisfied_by` locktime tests

- units/src/fee_rate/mod.rs
Some users may find it more ergonomic to pass in an `Amount` when constructing fee rates. Also the strong type adds some semantic meaning as well as imposes the `Amount::MAX` limit.
Add an equivalent constructor for each of the existing ones that uses an argument of type `Amount` instead of `u64` sats.
(This was pulled out of #4610.)
Close: #4734
> Add fee rate constructors that take `Amount` as arg

- bitcoin/src/bip32.rs
DerivationPath now supports a display format using both 'h' a single quote (') to indicate hardened components. 
This aligns it with its ChildNumber's output style.
Resolves: #4618
> Add alternate print format to DerivationPath using 'h' suffix

- units/src/result.rs
- units/tests/api.rs
A lot has changed over the last few months. Fix up the API integration test to match the current state of the crate.
Includes a patch to implement `Arbitrary` for types from the new private `result` module.
> units: Fix up the api test

- units/src/block.rs
- units/tests/str.rs
Recently we changed the names of some locktime types but kept aliases to the original names. To assist with ongoing maintenance lets use the new names already.
~Internal change only.~
Added a patch that does the same in some rustdocs.
> Use new type names instead of deprecated aliases

- primitives/src/transaction.rs
- units/src/amount/tests.rs
- units/src/fee_rate/mod.rs
- units/src/locktime/relative.rs
Weekly mutation testing found new mutants in units and primitives.
- Add tests or improve existing tests to kill all of the mutants. 
- Remove a duplicate test in `fee_rate`
Closes #4601, Closes #4622
> Add tests to kill mutants

- bitcoin/examples/bip32.rs
- bitcoin/examples/ecdsa-psbt-simple.rs
- bitcoin/examples/ecdsa-psbt.rs
- bitcoin/examples/taproot-psbt-simple.rs
- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/bip32.rs
- bitcoin/src/psbt/mod.rs
This enables a couple more things to be passed to the bip32 derive methods, with (afaict) no downside (all existing call sites remain valid and work as before).
Given
```
let secp = Secp256k1::new();
let path: DerivationPath = "42'/350'/0".parse().unwrap();
let xpriv: Xpriv = "xprv9s21ZrQH143K3QTDL4LXw2F7HEK3wJUD2nW2nRk4stbPy6cq3jPPqjiChkVvvNKmPGJxWUtg6LnF5kejMRNNU3TGtRBeJgk33yuGBxrMPHi".parse().unwrap();
```
The following *new* ways to call derive are enabled:
```
/// Derive using only part of the path
xpriv.derive_xpriv(&secp, &path[1..])
```
```
/// Derive moving into the method
xpriv.derive_xpriv(&secp, path)
```
The second case is probably of questionable usefulness, but I've ended up writing something like
```
let path: DerivationPath = path.into_iter().skip(n).cloned().collect() …
```
> Improve `Xpriv::derive_xpriv` and `Xpub::derive_xpub` ergonomics slightly

- bitcoin/src/blockdata/transaction.rs
Use u32 for struct and member variables in InputWeightPrediction (saturating to u32::MAX).  To avoid panics during construction and while using auxiliary methods such as `total_size()`, support saturating operations.
closes: https://github.com/rust-bitcoin/rust-bitcoin/issues/4547
> Saturate iwp constructors to u32 max

- bitcoin/src/bip32.rs
The error message contains "do you have an hardened child number" but should be "do you have a hardened child number"
> fix: typo in error message

- .cargo/mutants.toml
- .github/workflows/cron-weekly-cargo-mutants.yml
Closes #4653
This removes the delete match arm and match guard exclusion as these mutations can now be targeted individually.
~~In draft as I have yet to run the mutations locally to add any exclusions that may still need to be added~~
> Remove match arm and guard mutant exclusion

- bitcoin/src/lib.rs
- bitcoin/tests/bip_174.rs
`units::Denomination` does not exist, it is only at `units::amount::Denomination`. Our policy is to make the following three equivalent `bitcoin::Foo`, `primitives::Foo`, and `units::Foo` therefor we should not re-export `Denomination` at the crate root of `bitcoin`.
> bitcoin: Remove re-export of Denomination

- units/src/result.rs
Took some inspiration from [a comment](https://github.com/rust-bitcoin/rust-bitcoin/pull/4689#issuecomment-3073834482) in #4689 and looked through the rest of the codebase to update `u.int_in_range(0..=1)` to use `bool::arbitrary(u)`
> Update NumOpResult arbitrary impl to only consume 1 byte of entropy

- bitcoin/Cargo.toml
- bitcoin/src/address/mod.rs
- bitcoin/src/blockdata/script/owned.rs
- bitcoin/src/blockdata/script/witness_program.rs
Manually backport PR #4111. Of note, here we put `new_p2a` on `ScriptBuf` instead of on the `script::Builder` because that seems to be where all the other `new_foo` methods are in this release. 
From the original patch:
Add support for the newly created Pay2Anchor output-type.
See https://github.com/bitcoin/bitcoin/pull/30352
> backport: Add support for pay to anchor outputs

- primitives/src/pow.rs
- primitives/src/script/borrowed.rs
- primitives/src/script/mod.rs
- primitives/src/script/owned.rs
- primitives/src/sequence.rs
Macros are basically just a pain in the arse. This one is used to reduced code duplication/verbosity even thought the function can be written as a one-liner.
Also calling macros across crate boundries is error prone and a constant source of maintenance grief.
Note also:
- The generated docs are quite general
- `#[inline]` is missing
- The docs on the macro are wrong in regards to the no-op
Remove all calls to the macro from `primitives` and inline using terse syntax by way of the `format!` macro.
Add `deprecated` attribute and direct users to just use `format!("{var:x}")` instead.
> primitives: Inline `impl_to_hex_from_lower_hex` macro and deprecate

- bitcoin/examples/ecdsa-psbt-simple.rs
- bitcoin/examples/ecdsa-psbt.rs
- bitcoin/examples/sighash.rs
- bitcoin/examples/sign-tx-segwit-v0.rs
- bitcoin/examples/sign-tx-taproot.rs
- bitcoin/examples/taproot-psbt-simple.rs
- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/lib.rs
bitcoin: Add crate level public ext module
Add a public `ext` module and re-export all the extension traits anonymously traits so users can use wildcard imports of form: `use bitcoin::ext::*;`
If, for some reason, users want the name in scope they have to go to the module its defined in e.g., `use bitcoin::script::ScriptExt`.
Update all files in the `examples` directory to use wildcard import, thereby verifying it all works as expected.
Note this is not exactly what is described in issue #4660 but it resolves it none the less.
Close: #4660
> bitcoin: Add public ext modules

- bitcoin/src/blockdata/script/borrowed.rs
- bitcoin/src/blockdata/script/owned.rs
By convention we do not re-export things from modules where they are used. Also the `borrowed` and `owned` modules are private so these public re-exports make no sense.
FTR users can do both of these already
- `use bitcoin::script::{Script, ScriptBuf};`
- `use bitcoin::{Script, ScriptBuf};`
> script: Remove public re-exports

- bitcoin/src/network/mod.rs
Remove typo; duplicate word 'this'.
> doc: Remove duplicate word

- io/tests/api.rs
Fix a typo in the function name `all_non_error_tyes_implement_send_sync` by changing "tyes" to "types" to maintain consistency with other function names like `api_all_non_error_types_have_non_empty_debug`
> fix: correct typo in test function name "tyes" to "types"

- bitcoin/src/bip152.rs
- bitcoin/src/bip158.rs
- bitcoin/src/merkle_tree/block.rs
These are some children types of some `p2p` types for which I'm updating the fuzzing targets
> Add Arbitary impls for some bip152, bip158 & merkle block types

- .github/workflows/README.md
- .github/workflows/rust.yml
- api/units/all-features.txt
- api/units/alloc-only.txt
- api/units/no-features.txt
- contrib/check-for-api-changes.sh
Now that `units`  is stabilising we can bring back the API checking script so that it is intentionally cumbersome for devs to change the public API and also to help catch mistakes in case we accidentally do so.
> units: Check the API using `cargo public-api`

- units/src/amount/signed.rs
- units/src/amount/unsigned.rs
These functions explicitly do not panic, just allow the lint.
> Allow missing panics docs in const functions

- docs/README.md
- docs/address.md
- docs/bip-32.md
- docs/psbt.md
- docs/roadmap.md
Add a `docs` directory including a basic README. The purpose is outline in the readme.
Add an initial `roadmap`, done as a single patch because the roadmap is referenced in the readme.
> Add docs directory

- p2p/src/message.rs
When using `p2p` and version one messaging, the user is put into a strange position where they must figure out how many bytes to read, but cannot do so without implementing some version of this type in their crate. Add a first-class `V1MessageHeader` so users may first decoded this, then the rest of the message.
An example is in Floresta here: https://github.com/vinteumorg/Floresta/blob/5e78a8179da596101508ac6ad1a454e80c1635bc/crates/floresta-wire/src/p2p_wire/transport.rs#L85
Which is used to parse data here: https://github.com/vinteumorg/Floresta/blob/5e78a8179da596101508ac6ad1a454e80c1635bc/crates/floresta-wire/src/p2p_wire/transport.rs#L333
> p2p: Add a `V1MessageHeader`

- p2p/README.md
Fixed broken link to License
Now the link looks like just in primitives/README.md, base58/README.md and units/README.md
> Fix LICENSE link in p2p/README.md

- p2p/src/message_network.rs
This PR fixes spelling errors in the documentation comments within `p2p/src/message_network.rs`:
- **Fixed:** `vulerable` → `vulnerable` (3 occurrences)
> Fix typos in message_network.rs comments

- addresses/src/lib.rs
- bitcoin/src/lib.rs
- chacha20_poly1305/src/lib.rs
- fuzz/src/lib.rs
- hashes/src/lib.rs
- internals/src/lib.rs
- io/src/lib.rs
- p2p/src/lib.rs
- primitives/src/lib.rs
- units/src/lib.rs
rustdocs renders the title the same with and without the #
Resolves: #4677
> Remove # from crate rustdoc titles

- Cargo-minimal.lock
- Cargo-recent.lock
- bitcoin/CHANGELOG.md
- bitcoin/Cargo.toml
In preparation for release bump the version, add a changelog entry, and update the lock files.
> Release tracking PR: `bitcoin 0.32.7`

- p2p/examples/handshake.rs
- p2p/src/lib.rs
- p2p/src/message.rs
- p2p/src/message_blockdata.rs
- p2p/src/message_network.rs
Protocol versions should be comparable by name when considering if we would like to maintain a connection or not. For instance it is nice to be able to say "reject all connections below this feature". It is also nice to know you aren't sending some nonsense version (e.g. 70071) because of a typo.
The naming comes from similar constants defined in Bitcoin Core [here](https://github.com/bitcoin/bitcoin/blob/master/src/node/protocol_version.h).
> Add a `ProtocolVersion` type with named values

- p2p/src/lib.rs
We deprecated this const when backporting the testnet v4 stuff in  #3453 and even though we typically keep deprecated things around for two releases since `p2p` is a new crate lets just get rid of it.
FTR with this applied there are no more uses of the `deprecated` attribute in `p2p`.
Close: #4711
> p2p: Remove deprecated const

- p2p/examples/handshake.rs
- p2p/src/message.rs
- p2p/src/message_network.rs
There is a BIP that defines what a typical user agent should look like in a `version` message sent by a bitcoin node. All of the formatting suggestions are just recommendations, but users that would like to follow the recommendations should be able to do so easily. Instead of wasting their time reading a string formatting BIP, I attempt to make it as easy as possible here to create a user agent correctly. In practice people put stupid shit in here all the time, so there is no validation when reading these off the wire.
Originally inspired by some work of nyonson, so tagging him here for a review.
Hoping to not waste too much reviewer bandwidth here, so all of the test cases are pretty much unaltered. This is a convenience type for users that want to play by the rules.
ref: …
> p2p: Add a `UserAgent` type

- units/src/sequence.rs
Fix various documentation issues including incorrect URLs, improper spacing, and formatting inconsistencies in the sequence.rs file
> docs: fix documentation typos in sequence.rs

- primitives/src/lib.rs
As we do in `units` document in the crate level rustdocs that the `primitives` types are all re-exported at the same place in `bitcoin`.
Close: #3616
> primitives: Document re-exports

- hashes/src/ripemd160/crypto.rs
Fixed typo in comment: Porallel Round 2 → Parallel Round 2 in hashes/src/ripemd160/crypto.rs.
> fix: correct typo in comment in crypto.rs

- bitcoin/Cargo.toml
- bitcoin/contrib/test_vars.sh
- bitcoin/examples/serde.rs
I had to check how to serde struct fields by way of consenus encoding so I threw together an example.
> bitcoin: Add a serde example module

- bitcoin/src/bip152.rs
- bitcoin/src/bip158.rs
- bitcoin/src/bip32.rs
- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/script/borrowed.rs
- bitcoin/src/blockdata/script/owned.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/blockdata/witness.rs
- bitcoin/src/merkle_tree/mod.rs
- bitcoin/src/pow.rs
How, when, and why we use macros has evolved over time. We are kind of only begrudgingly using them. And we are trying to not call them across crate boundaries. 
Clean up how we call private macros to use a single level of path so the calls are terse but explicit.
> Refactor how we call private macros

- .github/workflows/rust.yml
When cargo-public-api releases a new version with a super new nightly requirement it breaks our CI for not a lot of added value. Lets pin the version and go right ahead and remember to update `cargo-public-api` at some stage.
> Pin cargo public-api version

- .cargo/mutants.toml
- units/src/amount/result.rs
Closes #4766
- Add unit tests for `core::iter::Sum`
- Exclude deprecated `to_hex` functions that have uncaught mutants.
> unit: kill new mutants

- bitcoin/src/blockdata/block.rs
The multi-line foramt is not clearer and takes up a bunch of lines, just go over the usual column with on this one.
> Add rustfmt skip to macro call

- addresses/src/lib.rs
- primitives/src/block.rs
- primitives/src/lib.rs
- primitives/src/opcodes.rs
- primitives/src/pow.rs
- primitives/src/script/borrowed.rs
- primitives/src/script/mod.rs
- primitives/src/script/owned.rs
- primitives/src/transaction.rs
- primitives/src/witness.rs
Fixes #4681 by making `primitives` and `addresses` crates consistently use `#![no_std]` like the `units` crate.
**Changes:**
- Change from conditional `no_std` to always `no_std` 
- Add test macro imports to resolve `format!`/`vec!`/`println!` issues
This makes the test environment consistent with production and aligns all crates in the codebase.
> Use no_std when testing

- p2p/src/message.rs
While this collection of crates does not try to implement the bitcoin consensus logic, it can help prevent obvious spam or noise. Any list of block headers must be connected in a linked list by their hashes, and each header must pass its own work requirement, regardless of network.
Adding this in `p2p` because I imagine anyone that uses these types would want to know if they are receiving garbage.
> p2p: Add `HeadersMessage` wrapper with useful methods

- fuzz/fuzz-util.sh
- internals/src/array.rs
I changed “output” to “outputs” to make the verb agree with the singular subject “a fuzz case”.
I changed it to “intentionally shadows” to match doc style — present simple states a fact, not an ongoing action.
> fix: grammar

- hashes/src/hmac/mod.rs
- hashes/src/internal_macros.rs
- hashes/src/lib.rs
- hashes/src/macros.rs
- hashes/src/sha256/mod.rs
- hashes/src/sha256t/mod.rs
- hashes/src/siphash24/mod.rs
Policy is to keep deprecated stuff for two releases. We have released 0.16.0 already so we can remove stuff deprecated in 0.15.0 (assuming 0.17.0 is out next).
Furthermore this assists with the `primitives` stable release because it removes `FromSliceError` from the API of crates that call public macros across crate boundaries from `hashes`.
> hashes: Remove code deprecated in `v0.15.0`

- units/src/fee_rate/mod.rs
During some work on updating the fuzz targets, I came across an overflow error during this call when `FeeRate::MAX` was passed in:
```rust
script.minimal_non_dust_custom(fee_rate);
```
This calls `FeeRate::to_sat_per_kvb_ceil()` under the covers, which was where the overflow was happening. I also updated similar functions that would have run into the same issue
> Fix overflow during *_ceil FeeRate conversions

- chacha20_poly1305/src/lib.rs
- Add missing space in comment about format! macro
- Fix article from "a" to "an" before "authentication tag"
> fix: correct typos in comments

- units/src/locktime/relative/error.rs
Updated the error text to say “lock-by-time” for IsSatisfiedByTimeError::Incompatible.
> fix: IsSatisfiedByTimeError::Incompatible wording to lock-by-time

- contrib/check-for-api-changes.sh
Sort order is effected -> Sort order is affected
> chore: fix typo 'effected' to 'affected'

- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/script/builder.rs
- bitcoin/src/blockdata/script/witness_version.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/lib.rs
- bitcoin/src/network/params.rs
- bitcoin/tests/psbt-sign-taproot.rs
In days gone past we decided try to minimize merge conflicts by keeping use statements really separate, over time we moved more and more towards combining them (ie., not reaching into modules all the time but using re-exports).
Now, in a push to make our codebase's imports mirror downstream usage while still keeping our aims don't reach into `units` or `primitives`, just grab things by way of their re-export.
> bitcoin: Improve import statements

- docs/README.md
Fix spelling error in **docs/README.md** where `Depenency tree` was missing the letter `d` and should be `Dependency tree`
> docs: fix typo "Depenency" -> "Dependency" in README

- .github/workflows/cron-daily-fuzz.yml
- fuzz/Cargo.toml
- fuzz/fuzz_targets/units/arbitrary_weight.rs
- fuzz/generate-files.sh
- units/src/weight.rs
Pulling on the same thread from #4838, I started looking into `units` where a similar bugs may have happened and found a few for `Weight`. Found a few instances of the overflow bug in a few constructors so fixing them here
> Fix overflows in `Weight` and add fuzz target

- p2p/src/message_network.rs
corrected `semi_colon_delimeter` to `semi_colon_delimiter` x2
> docs: fix typo in message_network.rs

- Cargo-minimal.lock
- Cargo-recent.lock
- base58/Cargo.toml
- base58/src/lib.rs
The `hex` dev dependency is only used in tests, we have a crate for that lets use it.
Remove `hex-conservative` dev dependency and use `hex_lit`.
> base58: Remove hex dependency

- io/Cargo.toml
In `io` we use a macro from `internals` that has feature gated code dependent on "alloc" but currently we are not enabling "alloc". This is a bug -
Repeat after me: calling macros across crate boundries is an incessant source of bugs.
> io: Enable features in internals crate

- primitives/src/block.rs
- primitives/src/transaction.rs
Fixed grammar: "if version bits is" → "if version bits are" 
also 'CTtransaction' to 'CTransaction'
> fix: correct grammar in block and transaction docs

- docs/dependencies.md
Add a document for evaluating dependencies vs NIH'ing functionality. Content pulled out of
https://github.com/rust-bitcoin/rust-bitcoin/discussions/1243
> Add dependency policy doc

- bitcoin/src/consensus/error.rs
Currently the `ParseError` is a mess. The correct fix is likely to use an associated type in `Decodable` for the error but that can wait.
Right now we are using `hex` in the `Display` impl for `ParseError`. This will cause trouble when we move the error type to `consenus_encoding` because `hex` is a feature. Even if we do not do so this code is a mainitenance burden.
Just manually print hex characters by accessing the array. Logic is already tested with a static string, this patch does not change the output.
> Manually print `InvalidChecksum`

- CONTRIBUTING.md
fixed grammatical error by removing the redundant article "a" from the phrase "the workflow is a as follows" to make it grammatically correct as "the workflow is as follows"
> docs: remove redundant "a" in CONTRIBUTING.md

- docs/crypto.md
some minor typos: 
bitcoin::cryto::key -> bitcoin::crypto::key (cryto-crypto)
PriviateKey > PrivateKey
> docs: fix typos

- api/units/all-features.txt
- api/units/alloc-only.txt
- api/units/no-features.txt
- bitcoin/src/blockdata/script/witness_version.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/lib.rs
- bitcoin/src/pow.rs
- primitives/src/lib.rs
- primitives/src/transaction.rs
- units/CHANGELOG.md
- units/src/block.rs
- units/src/lib.rs
- units/src/locktime/absolute/error.rs
- units/src/locktime/absolute/mod.rs
- units/src/locktime/relative/mod.rs
- units/src/parse.rs
- units/src/parse_int.rs
- units/src/sequence.rs
- units/src/weight.rs
- units/tests/api.rs
Patch 1 removes the hidden macros from `units` and then it makes sense to rename the `parse` module to `parse_int`. With this all done, fix the re-export in `primitives` and add one in `bitcoin` (all in patch 2).
> Rename `units::parse` to `parse_int`

- bitcoin/src/blockdata/script/instruction.rs
Replace `self.data.len() == 0` with `self.data.as_slice().is_empty()` to fix clippy::len_zero warning in the size_hint implementation for Instructions iterator.
This addresses the Clippy lint that recommends using is_empty() instead of comparing len() to zero, which is more idiomatic Rust. Uses stable slice.is_empty() via as_slice() to avoid unstable exact_size_is_empty feature.
Fixes: clippy::len_zero warning in bitcoin/src/blockdata/script/instruction.rs:193
> fix: resolve clippy::len_zero lint in Instructions::size_hint

- primitives/src/block.rs
- primitives/src/transaction.rs
Now we want to only import using crate re-exports if possible in `bitcoin` and `primitives`. We fixed `bitcoin` already, now do `primitives`.
> primitives: Use new import policy

- bitcoin/examples/script.rs
- bitcoin/src/blockdata/script/owned.rs
While reviewing the code to better understand `script::Builder` (issue #4917), I noticed we referenced functions in deprecation notes and comments that don't exist
This PR: 
- Fix deprecation note: `from_hex_string_no_length_prefix()` → `from_hex_no_length_prefix()`
- Fix comment in script example: `from_hex_string_prefixed` → `from_hex_prefixed`
> fix: correct function names in deprecation notes

- primitives/src/transaction.rs
- primitives/src/witness.rs
- units/src/amount/tests.rs
- In transaction.rs: changed "be encoded" → "to be encoded" 
- In witness.rs: corrected "features is" → "features are" 
- In amount tests: fixed typo "crate" → "create"
> fix(docs): correct typos in transaction, witness, and amount test comments

- hashes/src/lib.rs
- hashes/src/sha3_256/mod.rs
- hashes/tests/api.rs
- hashes/tests/regression.rs
My first commit message motivates this change. The brief explanation is Tor nodes are advertised by ED25519 public key, but are often discoverable as `.onion` addresses. To go from public key to onion address, one must take `SHA3(".onion checksum" | PUBKEY | VERSION)` for a checksum. I will leave the rest for the commit message, as well as all reference material.
> Add a `sha3_256` module with `SHA3-256`

- bitcoin/examples/script.rs
- bitcoin/examples/serde.rs
- Fix missing `w` in `these two calls` in script.rs
- Fix pronoun `the` to `they` in serde.rs comment
> fix: correct grammatical errors in example code comments

- bitcoin/src/address/mod.rs
grammatical errors: remove extra space in "i.e." and add missing article "an" before "uppercase version"
> fix: correct grammar in address documentation comments

- bitcoin/src/blockdata/script/borrowed.rs
Replace explicit match expression with more idiomatic map_or method in Script::is_op_return(). This change maintains identical semantics while making the code more concise and following Rust best practices
> simplify is_op_return() using map_or instead of match

- consensus_encoding/src/encode/encoders.rs
A couple of trivial docs fixes done while hacking on adding support to `primitives` for encoding.
> encoding: Do trivial docs fixes

- bitcoin/src/blockdata/constants.rs
Correct the function name reference in the panic message 
from `chain_hash_genesis_block` to `chain_hash_and_genesis_block` to match the actual function name
> fix function name in panic message for chain_hash_and_genesis_block

- consensus_encoding/src/encode/mod.rs
- consensus_encoding/src/lib.rs
- consensus_encoding/tests/encode.rs
- units/Cargo.toml
Another little addition to the new encoders, I am not sure how controversial some of this is, so opening as a draft in case better as just food for thought.
* first patch fixes up the units dependency on consensus_encoding which wasn't exercising std dependent code before.
* second patch adds helper methods for allocation and std I/O write operations which allows encoders to easily dump bytes into a vector or writer
This is largely inspired by Kix's I/O driver, but slimmed down. I initially switched it to an extension trait for Encoder instead of adding more methods to encoder itself. Was convinced the hit on discover-ablity wasn't worth it. Plus a little awkward to have on all `Encoder` implementing types which are never directly called to be encoded (usually nested in a transaction of …
> Standard I/O ops for encoders

- bitcoin/Cargo.toml
Patch f80cf2cb2aa318978da3a6c5df49d82c49344763 (PR #4154) somehow got past review with a change that unconditionally enabled `rand` feature for `secp256k1` - this is incorrect.
There is no mention of the change in the PR description or review comments - review fail.
> Do not enable secp rand feature

- Cargo-minimal.lock
- Cargo-recent.lock
- consensus_encoding/Cargo.toml
- consensus_encoding/src/encode/encoders.rs
- consensus_encoding/src/encode/mod.rs
- internals/src/compact_size.rs
- primitives/src/script/borrowed.rs
- primitives/src/script/mod.rs
Includes a bunch of preparatory clean up as well as a patch to add support to `BytesEncoder` to encode with length prefix.
> primitives: Implement `Encodable` for `&Script<T>`

- consensus_encoding/src/encode/encoders.rs
I ran `cargo clippy --fix --lib -p consensus-encoding` and whala some things got changed. I hope this stuff got past CI because of update to nightly.
> consensus_encoding: Fix clippy lifetime warnings

- docs/primitives.md
- primitives/src/transaction.rs
```markdown
Minor documentation improvements and typo fixes across the codebase.
- **`docs/primitives.md`**:
- Fix typo: `consenus-encoding` → `consensus-encoding`
- **`primitives/src/transaction.rs`**:
- Fix typo: `pre-pended` → `prepended` in serde comment
```
> docs: fix typos 

- benches/Cargo.toml
- benches/chacha20_poly1305/chacha20poly1305.rs
Existing benches only use the raw ChaCha20 keystream without Poly1305/authentication overhead.
Add Criterion benchmarks to ChaCha20-Poly1305 using Authenticated Encryption with Associated Data. The three benchmarks are encryption with and without additional authenticated data, and decryption.
> Add chacha20_poly1305 Criterion AEAD benchmarks

- consensus_encoding/Cargo.toml
- consensus_encoding/contrib/test_vars.sh
- consensus_encoding/examples/encoder.rs
- consensus_encoding/src/encode/encoders.rs
- consensus_encoding/src/lib.rs
- consensus_encoding/tests/wrappers.rs
Add some integration test for how we expect the `consensus_encoding` crate to be used (i.e., with wrapper encoder types). Then implement a `SliceEncoder` - BOOM!
> Implement `SliceEncoder`

- api/units/all-features.txt
- consensus_encoding/src/encode/encoders.rs
- consensus_encoding/src/encode/mod.rs
- consensus_encoding/tests/encode.rs
Inspired by https://github.com/rust-bitcoin/rust-bitcoin/pull/5003 (which I believe is the [elidable_lifetime_names](https://rust-lang.github.io/rust-clippy/master/index.html#elidable_lifetime_names) clippy rule) I experimented with some lifetime elision in the encoder_newtype macro. This drops the implicit requirement that the encoder struct's lifetime be called `'e` to match the internal macro's usage.
This might be a subtle change in the requirements themselves since they are no longer explicitly tied together, however, I haven't been able to come up with a unit test to break that in any way.
> Remove the implicit lifetime name requirement in the encoder_newtype macro

- bitcoin/src/merkle_tree/block.rs
Looks like 'CMerkleBlock' is a C++ class name and correct here is 'MerkleBlock' ?
> docs: replace CMerkleBlock with MerkleBlock in test documentation

- consensus_encoding/src/encode/encoders.rs
Cleaning up the `encoders` unit tests and adding some helper types for further testing. But posting now because adding a few SliceEncoder tests like `encode_empty_slice` exposed a bug in the `SliceEncoder::advance` method. For an empty slice, the compact size is never cleared. I added a fix in the second commit and tests in the third, but I know a lot of iterations were just spent on this so don't have full confidence it didn't hurt some other goal (at one point branch prediction was brought up).
Separately, the `encode_slice_with_zero_sized_arrays` test is kinda weird, but I think logically checks out...just don't think we will ever be sending zero-byte arrays in real life.
> Clean up encoders unit tests and fix empty SliceEncoder

- consensus_encoding/src/decode/decoders.rs
- consensus_encoding/src/encode/encoders.rs
The encoder/decoder composers just delegate to an inner encoder/decoder, inlining these simple calls might help the compiler optimize things. Working on the `Read` driver for decoders got me thinking that this might help the compiler optimize the buffer a bit better.
> consensus_encoding: tag composers with inline

- bitcoin/src/blockdata/script/borrowed.rs
- bitcoin/src/blockdata/script/witness_version.rs
Fixed typos in 2 files.
if its valid -> if it's valid
Returns `None` is the instruction is data push -> Returns `None` if the instruction is data push
Cannot not convert -> Cannot convert
> chore: fix typos

- api/units/all-features.txt
- consensus_encoding/src/decode/decoders.rs
- consensus_encoding/src/decode/mod.rs
- consensus_encoding/src/lib.rs
- consensus_encoding/tests/composition.rs
- units/src/amount/unsigned.rs
- units/src/block.rs
- units/src/locktime/absolute/mod.rs
- units/src/sequence.rs
- units/src/time.rs
Getting the ball rolling on I/O drivers for the decode side, which I think is going to be more interesting than the encode side since the buffered interface is different.
The simple drivers for slice and bufreader.
These are water'd down versions of push_decode. Some simplifications were made like making `ReadError` less generic by hard-coding to the std::io error type.
But this does get right to the chase for the decode-side complexity: is it cool to have a separate driver for `BufReader` and `Read`?
The complex driver for `Read`.
Following push_decode's design, introduced a new requirement on the `Decoder`'s to expose a `min_bytes_needed`. This allows the read driver to efficiently manage its internal buffer. I just put this requirement straight on `Decoder` because I think we can …
> Add decoder I/O drivers

- hashes/tests/api.rs
- io/tests/api.rs
- primitives/tests/api.rs
```markdown
Fixed subject-verb agreement in API test documentation comments.
- **Files affected:** `hashes/tests/api.rs`, `io/tests/api.rs`, `primitives/tests/api.rs`
- **Fix:** Changed "The point of these tests **are**" → "The point of these tests **is**"
The subject "The point" is singular, requiring the singular verb "is" instead of "are".
```
> fix grammar in API test comments

- docs/policy.md
Correct missing `fn` keyword in function declaration example.
Remove redundant `do` word from sentence describing type ordering constraints.
> docs: fix syntax errors and grammar in policy.md

- docs/crates.md
Fix chacha20_poly135 to chacha20_poly1305 and update [address.md] link to [addresses.md] to match actual filename
> docs: correct crate name and link reference

- contrib/check-for-api-changes.sh
Recently we added `--locked` to all the `cargo` invocations in the script to check API text files. But if one has an updated lock file (newer than recent) then this achieves nothing. I.e., if one has run `cargo` _without_ `--locked` then the local lock file will have deps that are too new (*cough* serde I'm looking at you).
Copy the recent lock file into place when the script is run locally but preserve the lock file state once the script is finished running.
> Use recent lock file when checking API files

- bitcoin/src/merkle_tree/block.rs
Replace deprecated `hash_types::Txid` imports with direct `Txid` imports in merkle_tree/block.rs documentation and tests.
The public re-export of Txid through hash_types is deprecated in favor of direct imports from the crate root.
This change:
- Updates doc example from `use bitcoin::hash_types::Txid;` to `use bitcoin::Txid;`
- Updates test import from `use crate::hash_types::Txid;` to `use crate::Txid;`
> docs: update deprecated hash_types::Txid imports to direct Txid imports

- io/src/lib.rs
The current behavior of Cursor doesn't match what we have in `std` we need to:
- Remove assertion in `consume()` that panics when amount > buffer length (now it just increment position)
- Fix `fill_buf()` to return empty slice when positioned past end
Closes #5019
> fix: remove assertion in Cursor when reading past end

- consensus_encoding/src/decode/decoders.rs
- consensus_encoding/src/decode/mod.rs
- consensus_encoding/src/lib.rs
- fuzz/fuzz_targets/bitcoin/arbitrary_witness.rs
- fuzz/fuzz_targets/units/parse_int.rs
- internals/src/compact_size.rs
Implement `CompactSizeDecoder`, `ByteVecDecoder`, and `VecDecoder<T>`.
Pulled out of #4998 because I was too optimistic about doing the whole thing at once.
> consensus_encoding: Implement additional decoders

- units/src/amount/verification.rs
Replace `use super::*;` with `use super::{Amount, SignedAmount};` in amount verification module. Only these two types are actually used in the verification tests. Improves code readability and follows Rust best practices of preferring specific imports over wildcards
> units: replace wildcard import with specific imports in verification

- api/units/all-features.txt
- consensus_encoding/src/encode/mod.rs
- primitives/src/transaction.rs
- primitives/src/witness.rs
- units/src/amount/mod.rs
Up front re-export the `AmountEncoder`, we missed it before (and update the API text files).
Then add consensus encoding functionality for the `Witness` and the types in `transaction`.
> Add `Encodable` for transaction types

- consensus_encoding/src/encode/encoders.rs
- consensus_encoding/src/lib.rs
- primitives/src/witness.rs
Add `CompactSizeEncoder` implementation and simplify `WitnessEncoder` by using the new `CompactSizeEncoder` + `Encoder2` composition.
Discussed in: https://github.com/rust-bitcoin/rust-bitcoin/pull/4992#issuecomment-3362279460
Closes: #5077
> consensus_encoding: Add `CompactSizeEncoder` and refactor `WitnessEncoder` 

- consensus_encoding/src/encode/encoders.rs
- primitives/src/lib.rs
- units/src/amount/tests.rs
There are a few lint errors in `units` and `primitives` with `no-default-features`.
Fix the lint errors in `units` and `primitives` with `no-default-features`.
> Fix clippy lint with `no-default-features` in `primitives` and `units`
