- src/network/message.rs
A fixed buffer of 12 bytes was unsafely copied from the bytes of a string - if the string was shorter than that, memory from outside would leak into the packet.
Replace the unsafe copy by a safe loop. Also add a panic if an attempt is made to use a command string longer than 12 bytes.
> Fix data leak in CommandString::consensus_encode

- fuzz/.gitignore
- fuzz/Cargo.toml
- fuzz/fuzzers/fuzzer_script_1.rs
- src/network/encodable.rs
Found a couple of panics using `cargo-fuzz` which are fixed by the following changes.
> Sanity checks for vector length

- Cargo.toml
Jsonrpc uses old and unsupported version of hyper.
> Fix vulnerabilities which found by `cargo audit`.

- Cargo.toml
- src/blockdata/transaction.rs
- src/util/hash.rs
This is needed to for a sane BIP143 implementation. Should be exactly equivalent to
serializing data into a vector then hashing that vector for all types.
> util: add Sha256dEncoder to allow streaming data into a hash

- Cargo.toml
- src/blockdata/transaction.rs
With Segwit transactions `bitcoin_hash()` is no longer sufficient to get a txid.
> transaction: add txid() method

- src/internal_macros.rs
This resolves a segfault due to unsafe code.
> Fix argument to copy_nonoverlapping in internal_macros

- Cargo.toml
- src/blockdata/script.rs
- src/internal_macros.rs
- src/util/bip143.rs
- src/util/mod.rs
Fixes #37 
cc @TheBlueMatt
Example usage:
```rust
use bitcoin::util::bip143;
// let tx = some Transaction with a couple inputs
let sighash_comp = bip143::SighashComponents::new(&tx);
let sighash0 = sighash_comp.sighash_all(&tx, 0, witness_input0, value_input0);
let sighash1 = sighash_comp.sighash_all(&tx, 1, witness_input1, value_input1);
// etc
// Now you can sign these sighashes to get the signatures for the appropriate input
```
> util: add `bip143` module to create BIP143 signature hashes

- src/util/uint.rs
Debug output was misleading, displaying 0 u64 as 00 instead of 0000000000000000
> fixing debug output for Uint256 and Uint128

- src/network/message.rs
bitcond sporadically sends alert "Alert key compromised, upgrade required"
Since alert message was removed here: bitcoin/bitcoin#7692 this PR only makes minimal effort needed to avoid "unrecognized network command" error.
> minimal implementation of alert message

- src/network/message.rs
RawNetworkMessage::command should be public. It is useful for debug messages and does no harm.
> [Trivial] RawNetworkMessage::command should be public.

- src/blockdata/blockchain.rs
tip height is a useful information readily computed by the tree. It is e.g. needed to set the height in a version message that a peer would send. Added a public method to retrieve it.
> [Trivial] add get_best_tip_height to blokchain

- README.md
- src/blockdata/script.rs
- src/util/address.rs
- src/util/contracthash.rs
- src/util/mod.rs
- src/util/privkey.rs
PrivKey was shadowing SecretKey only to implement a WIF, removed.
Implemented pay-to-pk address
unified parameter order as: key, compressed, network
> Implemented segwit address types. Moved PrivKey into its own module.

- src/blockdata/constants.rs
- src/blockdata/transaction.rs
This is a rather large breaking API change, but is significantly
more sensible. In the "do not allow internal representation to
represent an invalid state" category, this ensures that witness
cannot have an length other than the number of inputs. Further,
it reduces vec propagation, which may help performance in some
cases by reducing allocs. Fianlly, this just makes more sense (tm).
Witness are a per-input field like the scriptSig, placing them
outside of the TxIn is just where they are serialized, not where
they logically belong.
> Move witness inside of TxIn.

- src/util/uint.rs
Sometimes `uint` values need to be printed.
> Added `impl Display` to `construct_uint` macro

- README.md
Everyone using rust can be expected to know how to do this, and besides, the version was wrong. :)
> Remove cargo usage from README

- src/util/uint.rs
Recently I had some issues with multiplication method for `Uint256`. 
Result of multiplication was always 0, and `mul_u32` panicked sometimes.
So I added some tests to detect those issues and fixed the problem.
> Fix multiplication for uint256

- src/blockdata/script.rs
- src/blockdata/transaction.rs
is_coin base is a convenience function
direct data access to Script content is needed as eg. BIP158 implementation does not use serialization of Script but Script content directly.
> add is_coin_base

- src/blockdata/script.rs
Needed for BIP158 that ignores OP_RETURN outputs. This is faster than extracting Vec via data() and cheking content.
> check if output is OP_RETURN

- src/util/bip32.rs
There seemed to be some confusion as to whether the internal
represenation of a ChildNumber is supposed to be the index (0..2^31-1
for _both_ Normal and Hardened) or the actual number (0..2^31-1 for
Normal and 2^31..2^32-1 for Hardened). This commits fixes this
confusion.
- Make clear that the internal representation is the index rather
than the actual number
- Make the internal representation non-public
- Provide methods for creating valid ChildNumbers
- Change relevant callers and tests to conform to this new ChildNumber
My rationale for using index rather than the actual number as internal
representation is that the difference between the two enum variants
already encode wether a ChildNumber is a normal one or a hardened one,
so the only bit of extra information left to be encoded is …
> Ready for Review: Improve consistency for bip32::ChildNumber

- src/util/bip32.rs
ExtendedPubKey and ExtendedPrivKey implemented `ToString` directly but
Rust documentation says to implement `Display` and get the `ToString`
implementation for free.
> Implement `Display` trait instead of implementing `ToString` directly.

- src/network/listener.rs
IIUC, this shadowing is not required.
> Remove variable shadowing in listener.rs

- src/blockdata/script.rs
> Fix compilation warning when comparing usize and u64 on 32-bit arch

- .travis.yml
- Cargo.toml
- src/blockdata/opcodes.rs
- src/blockdata/script.rs
- src/blockdata/transaction.rs
- src/internal_macros.rs
- src/lib.rs
- src/macros.rs
- src/test_macros.rs
- src/util/bip32.rs
- src/util/decimal.rs
- src/util/hash.rs
**Status:** Ready for review
<hr/>
> Update to serde 1.0

- fuzz/fuzz_targets/deserialize_block.rs
- fuzz/fuzz_targets/deserialize_script.rs
- fuzz/fuzz_targets/deserialize_transaction.rs
- src/blockdata/block.rs
- src/blockdata/opcodes.rs
- src/blockdata/script.rs
- src/blockdata/transaction.rs
- src/internal_macros.rs
- src/network/address.rs
- src/network/constants.rs
- src/network/encodable.rs
- src/network/listener.rs
- src/network/message.rs
- src/network/message_blockdata.rs
- src/network/message_network.rs
- src/network/mod.rs
- src/network/serialize.rs
- src/network/socket.rs
- src/util/address.rs
- src/util/hash.rs
- src/util/misc.rs
- src/util/mod.rs
- src/util/privkey.rs
- src/util/uint.rs
- Separate serialize::Error and network::Error from util::Error
- Remove unneeded propagate_err and consume_err
Closes #131
> Fix Error type for SimpleDecoder and SimpleEncoder

- fuzz/Cargo.toml
- fuzz/fuzz_targets/deserialize_decimal.rs
- fuzz/fuzz_targets/deserialize_udecimal.rs
- src/util/decimal.rs
> Implement `FromStr` for `UDecimal`/`Decimal`.

- Cargo.toml
This updates the version of rust-secp dependencies and other invisible-to-rust-bitcoin changes.
> update rust-secp dependency to 0.11

- fuzz/fuzz_targets/deserialize_script.rs
- src/blockdata/transaction.rs
- src/network/encodable.rs
Rejects non-compact lengths and Segwit transactions which set the witness flag without providing witnesses (see https://github.com/bitcoin/bitcoin/pull/14039 ).
This is technically a breaking change, but it breaks behavior that should never have been valid, so I think it's OK to push into a point release.
> Various serialization fixes

- src/util/hash.rs
The FromStr implementation just delegates to the `from_hex` method for
the actual parsing.
The main intent for implementing this is to allow Sha256dHash to appear in type arguments with a `FromStr` trait bound.
> Add FromStr for Sha256dHash

- src/util/address.rs
Added an example to the address rustdoc (addresses https://github.com/rust-bitcoin/rust-bitcoin/issues/160)
> Added example for creating an address from a public key

- fuzz/fuzz_targets/deserialize_transaction.rs
- src/blockdata/transaction.rs
> transaction: make 0-input de/serialization always use Segwit 

- src/util/base58.rs
Instead of always allocating a `Vec` this implementation will work on the stack only as long as the output stays below 100 characters.
Closes #145
> Avoid heap usage when encoding to base58

- src/blockdata/constants.rs
- src/blockdata/opcodes.rs
- src/blockdata/script.rs
- src/util/address.rs
This is the same as #193 from @kazcw but with my patch for rust-1.14.0 compatibility.  I didn't check every opcode constant, but generally @kazcw's changes look good. @apoelstra should I do some automated validation or should our tests catch faulty opcode constants?
> Safe opcodes 1.14.0

- .travis.yml
It seems from IRC conversations and other discussions that `1.20.0` is an acceptable version to bump our rustc to.
- It is less than `1.24.0`, which is packaged by debian stable
- Associated constants is introduced in `1.20.0`
------------
This PR is now for bumping to 1.22.0
> Bump rustc version to 1.22.0

- src/util/hash.rs
> It is annoying to have a difference between debug and regular print for Sha256dHash

- src/util/address.rs
There is no address format for p2pk.
Script Descriptors should probably be used to construct scriptPubkeys and scriptSigs for using them instead of the `Address` type.
> Remove Address::p2pk

- src/consensus/encode.rs
- src/lib.rs
- src/util/address.rs
- src/util/bip143.rs
- src/util/key.rs
- src/util/mod.rs
- src/util/privkey.rs
- Move util::privkey::PrivKey to util::key::PrivateKey.
- Clean up util::key::PrivateKey.
- Add new util::key::PublicKey struct.
- Modify util::address::Address to appropriately wrap new
util::key::PublicKey.
@apoelstra @stevenroose I've introduced a few `.clone()'s` that I would like to remove, and am not entirely happy about the copying that happens in `util::key::PublicKey::serialize`. Would love your opinions on how to design this better.
> Ready for Review: Introduce util::key and deprecate util::privkey

- .travis.yml
- contrib/test.sh
This allows people to locally run `contrib/test.sh` on their fast hardware before Travis gets to it.
> Extract travis testing into locally-runnable script

- src/blockdata/script.rs
Exposes a method to get the assembly string without the `Script( ... )` wrapper.
I would personally also remove the wrapper from `fmt::Display`, but that's subject to opinion. With this, nothing changes, just the method to get the unwrapped string.
> Extract the Script assembly creator from fmt::Debug

- src/util/bip32.rs
> bip32: Add DerivationPath type

- src/blockdata/block.rs
- src/blockdata/constants.rs
- src/util/hash.rs
Merkle root calculation for a block should use txid() of transactions. 
There was no specialized implementation of MerkleRoot for Block, but one for &[ ? :BitcoinHash] which matches the txdata vector in Block, thereby misleading to use it for merkle root calculation of blocks.
> Merkle root calculation and witness commitment check for Block

- src/consensus/encode.rs
> Remove unused Option en/decoding

- fuzz/Cargo.toml
- fuzz/fuzz_targets/deserialize_psbt.rs
- src/consensus/encode.rs
- src/util/mod.rs
- src/util/psbt/error.rs
- src/util/psbt/macros.rs
- src/util/psbt/map/global.rs
- src/util/psbt/map/input.rs
- src/util/psbt/map/mod.rs
- src/util/psbt/map/output.rs
- src/util/psbt/mod.rs
- src/util/psbt/raw.rs
- src/util/psbt/serialize.rs
This is currently a non-working work-in-progress to add BIP174 (de)serialization support to rust-bitcoin.
I'm wondering about the conventions of this project so I can conform to them better, namely:
1. Could I add the type aliases I'm defining here to the relevant modules? (e.g. adding `KeyID` to `util::bip32::ExtendedPubKey`)
2. Does `psbt.rs` belong in `src/network` or some other module?
First time contributing... Excited :smile:
> BIP174 (de)serialization support

- Cargo.toml
This makes the `Address::Payload::WitnessProgram` inner type compatiblewith rust-lightning-invoice's `Fallback::SegWitProgram`'s inner type.
This allows specifying fallbacks from addresses.
> Bump bitcoin-bech32 dependency

- src/util/key.rs
These are mainly utility methods around the existing way to serialize the key types.
> util::key: Provide to_bytes() methods for key types

- Cargo.toml
- src/util/contracthash.rs
Builds on #246 though it's conceptually independent.
This module should be removed and its functionality subsumed into Miniscript, but to ease that transition we should first make it use the Bitcoin key types. As a side effect, it now supports uncompressed keys.
> contracthash: use `PublicKey` and `PrivateKey` types; minor cleanups

- src/blockdata/block.rs
- src/network/message.rs
The protocol has a bug where a 0u8 is pushed at the end of each
block header on the wire in headers messages. WHy this bug came
about is unrealted and shouldn't impact API design.
> Drop LoneHeaders and just use BlockHeader

- fuzz/travis-fuzz.sh
- src/consensus/encode.rs
- src/network/message.rs
- src/util/uint.rs
This makes the (obvious) improvement of swapping out repeated single-byte reads for a read_slice method. For my network crawler (https://github.com/TheBlueMatt/dnsseed-rust/) this took CPU usage down from pegging 4 ARM cores for not-that-many connections to something more manageable. There's tons of functions left to migrate, but this is a good start. Note that, long-term, I'd really, really like to limit the generics that support Encodable/Decodable. Notably, its really easy to accidentally call [T]'s Decode when you meant to call [T; 32]'s Decode (they do different things...).
Also slipped in adding SendHeaders support, cause I need it and don't feel like separating it into its own PR.
> Speed up consensus::[d]encode significantly

- Cargo.toml
- fuzz/Cargo.toml
- fuzz/fuzz_targets/deserialize_amount.rs
- src/lib.rs
- src/util/amount.rs
- src/util/misc.rs
- src/util/mod.rs
- src/util/psbt/mod.rs
Supersedes https://github.com/rust-bitcoin/rust-bitcoin/pull/252.
After long discussion about whether `Amount` should be `u64` or `i64` internally and after switching between them several times, we agreed on having two types.
> Add Amount and SignedAmount

- src/blockdata/block.rs
Fixes https://github.com/rust-bitcoin/rust-bitcoin/issues/182.
> Rename BlockHeader::spv_validate to validate_pow

- src/blockdata/transaction.rs
Avoids having to use the 4-line constructor when txid and vout are variable names already.
> Add OutPoint::new() for one-liner construction

- src/blockdata/constants.rs
- src/lib.rs
- src/util/merkleblock.rs
- src/util/mod.rs
This is a port of the bitcoin-core `CPartialMerkleTree` and `CMerkleBlock` classes.
Here they are called PartialMerkleTree and MerkleBlock.
These are useful for SPV clients that wish to verify that a transaction is
present in a specific block in an authenticated way.
This is a better attempt than my previous PR #19.
Note regarding the doc examples, I used `ignore` attribute to avoid failures with the older 1.22.0 Rust on TravisCI. It could be related to the usage of `extern crate ...` in the examples. The doc tests pass as of Rust 1.32.0.
> Add a MerkleBlock construction

- fuzz/fuzz_targets/deserialize_transaction.rs
- src/blockdata/opcodes.rs
- src/blockdata/script.rs
- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/consensus/mod.rs
- src/internal_macros.rs
- src/lib.rs
- src/network/address.rs
- src/network/constants.rs
- src/network/message.rs
- src/network/message_blockdata.rs
- src/util/address.rs
- src/util/merkleblock.rs
- src/util/psbt/macros.rs
- src/util/psbt/map/global.rs
- src/util/psbt/mod.rs
- src/util/psbt/raw.rs
- src/util/psbt/serialize.rs
- src/util/uint.rs
> clean up encoding/decoding traits

- src/util/bip143.rs
For p2wsh the scriptCode is the witness script, but for p2wpkh, it's the
equivalent legacy p2pkh output script.
The name scriptCode is used in the BIP, so it's less confusing.
> bip143: Rename witness_script to script_code

- Cargo.toml
- src/blockdata/transaction.rs
- src/util/bip158.rs
- src/util/mod.rs
Code moved here from murmel. Has been running there fore a while.
@stevenroose dependency on siphasher is temporary. Will use bitcoin_hashes if https://github.com/rust-bitcoin/bitcoin_hashes/pull/46 is merged.
> Add client side block filter (BIP158)

- src/blockdata/transaction.rs
- src/internal_macros.rs
- src/util/address.rs
- src/util/bip32.rs
Serialized OutPoint as `"<txid>:<vout>"` instead of a struct when a human-readable (de)serializer is used, f.e. JSON.
It should be noted that this is a breaking change for people relying on the current JSON serialization of OutPoint as a struct.
This PR is on top of https://github.com/rust-bitcoin/rust-bitcoin/pull/269, but doesn't have to be.
Closes https://github.com/rust-bitcoin/rust-bitcoin/issues/202.
> Add special human-readable serde for OutPoint and most bip32 types

- Cargo.toml
- src/network/stream_reader.rs
This removes `tempfile` as a dependency.
it wasn't really needed anyway, anything that was done via the fs can be done with in memory buffers.
this solves #306 and #305
> Remove tempfile as a dependency

- src/util/bip158.rs
Since block filters are likely cached it is advisable to reduce memory footprint of an individual filter even if this makes the API a bit more complex.
> Reduce blockfilter memory

- src/util/amount.rs
This should fix #300
Basically if the precision is longer than the length of the number than it's too precise.
This should also solve another unwanted behavior I thought of, 
which is:
if `last_n==s.len()`.
then `s` will be `""`. 
which will make this loop: `for c in s.chars()` to never run(chars is size 0).
`decimals` will be unwrapped to 0, `max_decimals` is also 0.
so `scale_factor` is now zero (`let scale_factor = max_decimals - decimals.unwrap_or(0);`)
so `for _ in 0..scale_factor` won't run either.
which means the function will return with the default value of `value`(0)
Edit: Fixes #311 too
> Check that the amount precision isn't more than the size of the amount

- Cargo.toml
- fuzz/fuzz_targets/deserialize_script.rs
- src/blockdata/script.rs
- src/consensus/encode.rs
- src/lib.rs
- src/util/address.rs
Inspired by: https://github.com/ElementsProject/rust-elements/pull/16/.
- use `address::Error` instead of `encode::Error`
- replace using bech32-bitcoin with `Payload::WitnessProgram` variant
- add `Address::from_script`, `Payload::from_script` and `Payload::script_pubkey`
Closes https://github.com/rust-bitcoin/rust-bitcoin/issues/253.
> Refactor Address

- src/blockdata/block.rs
- src/blockdata/script.rs
- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/internal_macros.rs
- src/lib.rs
- src/network/message_blockdata.rs
- src/network/message_filter.rs
- src/util/address.rs
- src/util/base58.rs
- src/util/bip143.rs
- src/util/bip158.rs
- src/util/bip32.rs
- src/util/contracthash.rs
- src/util/hash.rs
- src/util/merkleblock.rs
- src/util/misc.rs
- src/util/psbt/mod.rs
This export `bitcoin_hashes` as `bitcoin::hashes` and `secp256k1` as `bitcoin::secp256k1`.
This would mean that users of rust-bitcoin, (1) don't have to manually import those dependencies anymore and more importantly (2) can avoid certain dependency imcompatibility issues if some other module they use is using another version of `bitcoin_hashes` or `secp256k1`.
Solves https://github.com/rust-bitcoin/rust-bitcoin/issues/288.
> Export some dependencies

- .travis.yml
- Cargo.toml
- contrib/test.sh
- src/blockdata/script.rs
- src/lib.rs
- src/util/amount.rs
Thanks for @dtolnay for bringing to our attention that we don't use `serde-derive` outside of testing (https://github.com/serde-rs/serde/issues/1602#issuecomment-522274093)
I removed that, and added a test that use `rust-bitcoin` as a dependency.
And added a deny unused imports to help see when we don't actually use something.
2 things I'm not sure about:
1. what's the best way to abstract the features used in that test in a way that will be easy for future features.
2. Is it bad that now in the tests the `serde` version and `serde-derive` version might not much (and the `serde-test` version too)
> Remove serde-derive as a dependency

- src/blockdata/script.rs
- src/blockdata/transaction.rs
Avoid allocation of a HashMap that is just one possible implementation of finding TxOut for an OutPoint. Do not require retrieval of the entire transaction, just the output that is spent.
> use lambda instead of a hash map to find spent outputs

- src/blockdata/block.rs
Transaction is already also serde serializable. The same is desirable for block and blockheader since extensions to consensus encoding are no longer possible outside this crate. serde encoded objects might contain block and blockheader not only transactions.
> [TRIVIAL] enable serde serialization for block and blockheader

- src/blockdata/script.rs
Fix incorrect documentation for `is_p2pk(...)`.
Found while investigating this issue in `rust-miniscript`: https://github.com/apoelstra/rust-miniscript/issues/51
> Fix incorrect documentation for is_p2pk(...)

- src/network/stream_reader.rs
`StreamReader` is now generalized to allow:
* reading not only data from network `TcpStream`, but any input stream, including files
* supporting `Read`, which is more performance-efficient than a raw read
* parses and returns not just `RawMessage`, but any serializable data type
* because of this, `next_message` function is renamed into `read_next`
* ~~embedded stream is now boxed~~
Since the changes are compatibility-breaking, if the PR will be accepted, the version number has to be bumped accordingly.
Necessary testcase included. You can play as well with this minimalistic test parsing shortened version of the `blk00000.dat` file: <https://github.com/pandoracore/bpdump>
Code sample:
```rust
let mut stream_reader = match filename {
Some(name) => {
let buf_read: Box<dyn io::Read> = …
```
> Improvements to `StreamReader`

- src/consensus/encode.rs
It has been a long time since Bitcoin's maximum network message
length was 32MB, so we should follow suit. This is also an important
DoS limit, so we should limit it as much as possible.
> Drop message decode max length to 4_000_000

- README.md
I hope this can prevent future PRs like 
https://github.com/rust-bitcoin/rust-bitcoin/pull/346 
https://github.com/rust-bitcoin/rust-secp256k1/pull/123
and others.
we could also add a `rust-toolchain` file, but then we also need to edit the CI to be explicit on the right toolchain that *isn't* what's in `rust-toolchain` https://github.com/rust-lang/rustup#override-precedence
> Adding MSRV to the readme

- Cargo.toml
- contrib/test.sh
This PR adds two patches that expose feature flags from the underlying `secp256k1` library.
The primary benefit here is that we can activate the `rand` feature from a crate that only depends on `rust-bitcoin` but would like to make use of the feature-gated `rand` functionality in `secp256k1`. The current workaround here is to add an additional dependency on `secp256k1` that includes the feature flag. This works because cargo accumulates feature flags across the dependency tree.
Unfortunately, this requires to activately keep those versions in sync. By giving access to the `rand` feature flag of `secp256k1` through a `rand` feature flag in `rust-bitcoin`, this situation can be avoided.
Additionally, I noticed that the `serde` feature in `secp256k1` is not included in the `use-serde` …
> Expose secp256k1 features

- src/network/message_network.rs
> Nit in VersionMessage documentation

- Cargo.toml
- src/blockdata/block.rs
- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/lib.rs
- src/network/message_network.rs
- src/util/base58.rs
- src/util/bip158.rs
- src/util/bip32.rs
- src/util/endian.rs
- src/util/mod.rs
- src/util/psbt/raw.rs
Taking deps for such trivial things is.....really not useful, especially since bitcoin_hashes has its own hex impl.
> Drop hex and byteorder (non-test) deps (and disable useless lints)

- src/network/message_blockdata.rs
Trivial addition. Without this, we can't use Inventory in maps or sets.
> Implement std::hash::Hash for Inventory

- src/blockdata/constants.rs
- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/util/bip143.rs
- src/util/key.rs
- src/util/misc.rs
- src/util/psbt/mod.rs
We're using the `encode::Error` in places where we probably shouldn't. I know it's a silly breaking change, so I'd be ok with having it stale here for a while until we're going to release a breaking version.
It's hard to get all encode errors out of the psbt module because of a circular dependency otherwise. (There is an `encode::Error::Psbt` variant.)
> Overloaded encode error

- src/network/message.rs
- src/network/message_network.rs
The TODO comments are invalid thanks to contributions in recent months
https://github.com/rust-bitcoin/rust-bitcoin/blame/master/src/network/message_network.rs#L57
https://github.com/rust-bitcoin/rust-bitcoin/blame/master/src/network/message.rs#L119
> Remove two old TODO comments [nit]

- src/network/constants.rs
This adds a mandatory service flag to implement BIP157 as defined on the Bitcoin Core implementation:
https://github.com/bitcoin/bitcoin/blob/dd577bef3c4e1f227809a71ad43679b4548fbacf/src/protocol.h#L258
> bip157: Add NODE_COMPACT_FILTERS Service Flag

- src/network/address.rs
This PR makes debug output for `Address` easier to read. 
Cons:
* Slower performance-wise. I guess, it is acceptable for `fmt::Debug`.
Result:
```
Address {services: ServiceFlags(9), address: [0, 0, 0, 0, 0, 65535, 2560, 1], port: 8333}
Address {services: ServiceFlags(NETWORK|WITNESS), address: 10.0.0.1, port: 8333}
Address {services: ServiceFlags(NETWORK_LIMITED), address: fd87:d87e:eb43::ffff:a00:1, port: 8333}
```
> Improve fmt::Debug for network/Address

- src/blockdata/block.rs
- src/blockdata/constants.rs
- src/lib.rs
- src/util/bip158.rs
- src/util/hash.rs
- src/util/merkleblock.rs
Replaced by a `block_hash` method on both `Block` and `BlockHeader`.
Fixes https://github.com/rust-bitcoin/rust-bitcoin/issues/383.
This is a breaking change and is not very urgent. So either we can just stall it until we want another breaking change, or when we merge it we'd need a 0.23.x branch for minor releases.
> Remove the BitcoinHash trait

- src/blockdata/transaction.rs
- src/util/bip143.rs
Resolves https://github.com/rust-bitcoin/rust-bitcoin/issues/384
Tests generated manually in Core.
I can add more tests and dedup the strings a bunch once approach is agreed upon.
> Add bip143 sighash support for other flags

- Cargo.toml
Here we go again.
serde-json broke MSRV last night and raised it to 1.31.
diff: https://github.com/serde-rs/json/compare/v1.0.44...v1.0.45
also documented in the README as a badge: https://github.com/serde-rs/json#serde-json----
> Yet another MSRV breaking change

- src/hash_types.rs
- src/util/uint.rs
Fixing all external macro dependencies.
While this is not critical at all, I had to do this job for a dependent project (using an exportable version of this macro), so just thought why not to backport it into the main.
> Improving `construct_uint` macro

- README.md
For convenience, added links to the `CHANGELOG.md` and `LICENSE` that are referenced in `README.md`.
> readme: Add links to CHANGELOG.md and LICENSE

- src/blockdata/transaction.rs
Useful to compute the size of a transaction without having to re-serialize it. 
For my specific use-case, this will allow the esplora-electrs indexer to avoid re-serializing blocks in order to determine their size.
> Add Transaction::get_size()

- examples/handshake.rs
Since it recently took me some time to figure out how to use `rust-bitcoin`, and the contribution of example code is explicitly mentioned in the README, I thought I'd start with a basic handshake example: the supplied code connects to a Bitcoin node, complete the initial `version`/`verack` handshake, before it disconnects again. 
Let me know if I should change something. If it is desired, I'd consider adding more small examples, if I stumble upon something worth highlighting.
> Added a simple handshake example.

- src/lib.rs
Just thought this might be useful for some people. I don't think there will every be a conflicting type named Denomination anyway. If people think this clutters the API, just as good.
> Export the util::amount::Denomination type

- src/blockdata/block.rs
- src/blockdata/opcodes.rs
- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/network/address.rs
- src/network/constants.rs
- src/network/message.rs
- src/network/message_blockdata.rs
- src/util/address.rs
- src/util/amount.rs
- src/util/base58.rs
- src/util/bip158.rs
- src/util/bip32.rs
- src/util/hash.rs
- src/util/merkleblock.rs
- src/util/misc.rs
- src/util/psbt/macros.rs
- src/util/psbt/map/global.rs
- src/util/psbt/map/input.rs
- src/util/psbt/map/output.rs
- src/util/psbt/mod.rs
Hi,
This PR includes a bunch of stuff,
the first thing is to see how people feel about clippy suggestions, unlike rustfmt clippy's suggestions don't change that often and contain a lot of useful suggestions.
Commit e5ad634f3de824253501e812392900b14f8bd13b should increase performance by batching allocations. 
(https://rust-lang.github.io/rust-clippy/master/index.html#slow_vector_initialization, https://rust-lang.github.io/rust-clippy/master/index.html#map_entry)
Commit c9ba8ec9b9b07c89d183533238ccff43903f7f96 might reduce memory usage by removing needless references and pass by value small Copy objects.
Commit ae26c7d0daf73c55f2fcfceb534f4e26ef50fb9e is one that I think is important, `PartialEq` and `Hash` *must* agree (meaning that `a==a` means that `Hash(a)==Hash(a)`) so it is really …
> Cargo clippy changes

- src/internal_macros.rs
Fixes #374 
The `Deserialize` impls generated by `serde_struct_impl` and `serde_struct_human_string_impl` need to be able to handle serialization formats which serialize structs as sequences (such as bincode).
This PR adds `visit_seq` methods to the `Visitor` types defined by these macros, in addition to the existing `visit_map` methods. The implementation is taken directly from the serde docs: https://serde.rs/deserialize-struct.html
> Fix serde struct macros deserialization impls

- src/network/message_blockdata.rs
From BIP144: "MSG_WITNESS_TX getdata requests should use the non-witness serialized hash."
> Fix: Change WitnessTransaction inv type to use txid

- src/blockdata/script.rs
- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/network/mod.rs
- src/util/address.rs
- src/util/amount.rs
- src/util/base58.rs
- src/util/bip158.rs
- src/util/bip32.rs
- src/util/contracthash.rs
- src/util/key.rs
- src/util/mod.rs
- src/util/psbt/error.rs
Now that 1.42.0 is out `std::error::Error::description` is officially deprecated. 
sadly we can't stop using it because of our MSRV, but at least we lay the ground and encourage our users to stop using it too.
> Deprecate Error::description

- src/blockdata/block.rs
This implements the counterparty to `BlockHeader::compact_target_from_u256`, to convert a compact `u32` to a `Uint256`.
This is needed for difficulty calculations, eg. when handling `pow_limit` (a `Uint256`) from `consensus::params`.
> Add `BlockHeader::u256_from_compact_target` function

- src/util/bip32.rs
It's needed to implement extended public keys for rust-miniscript and also closes #442 (it's a superset of changes).
> Derive more traits to use for bip32 Types

- src/util/merkleblock.rs
Otherwise, `cargo doc` fails with:
```
warning: Rust code block is empty
--> src/util/merkleblock.rs:442:9
|
442 |     /// ```
|         ^^^
|
help: mark blocks that do not contain Rust code as text
|
442 |     /// ```text
|         ^^^^^^^
warning: 1 warning emitted
```
> Remove empty code block

- src/network/message.rs
Very small change, but I've run into this too many times now. `NetworkMessage` has `Clone`, but not `RawNetworkMessage`. It's useful to have when there are multiple "consumers" of incoming network messages.
> Add `Clone` instance to `RawNetworkMessage`

- fuzz/fuzz_targets/deserialize_script.rs
- src/blockdata/script.rs
- src/util/contracthash.rs
- Rename the `iter` method to `instructions`.
- Add `instructions_minimal` for minimal-enforced iteration.
- Iterator has `Result<Instruction, Error>` as items.
Fixes https://github.com/rust-bitcoin/rust-bitcoin/issues/396.
> Improve the Instructions iterator for scripts

- src/consensus/params.rs
`cloudhead` on IRC was asking how to properly use
`BlockHeader::validate_pow()` on genesis (or similar) when the
pow_limit field isn't expressible as a compact target (and, thus,
does not actually represent the PoW limit/genesis target). We
swap it for the actual PoW limit by truncating the way a compact
encoding round-trip would.
Note that, in Bitcoin Core, the original value is only ever used
once in its original form:
```
if (bnNew > bnPowLimit) // Note: bnPowLimit is params.powLimit
bnNew = bnPowLimit;
return bnNew.GetCompact();
```
Thus, even if Core adopted our change, as long as there exist no
256-bit integer x which satisfies
`x <= powLimit && x > encoding_roundtrip_truncated(powLimit)` and
`enoding_roundtrip_truncated(x) != powLimit`, the change would have
no impact on consensus. …
> Set Params::pow_limit to an attainable value not a theoretical one

- src/blockdata/script.rs
- src/util/address.rs
I know that we do plan to utilize miniscript as much as possible, but as an intermediate step I propose to sort out some code duplication issues. Right now, we had script generation logic in `address::Payload`, which was a duplication of the same code in `Script` class. With this PR I have:
* moved all logic to `Builder`, which seemed to be a more appropriate location
* added `P2PK` generation logic
* added test cases
~~* sorted out unnecessary usage of `HashEngine` where `hash` function of the new hash types can be used instead~~
> Refactoring script generating functions into a single place

- .gitignore
- src/util/psbt/error.rs
- src/util/psbt/macros.rs
- src/util/psbt/map/input.rs
- src/util/psbt/mod.rs
- src/util/psbt/serialize.rs
Added hash preimages to psbt as per modified BIP 174. See https://github.com/bitcoin/bips/pull/955. This will allow rust-miniscript a complete finalizer that can finalize hash preimages. (https://github.com/rust-bitcoin/rust-miniscript/pull/119) . 
Since the current version of the BIP does not have any tests for these, ~~I plan to add some roundtrip tests for the changes~~. 
Edit: Added tests
> Added hash Preimages to psbt

- Cargo.toml
I am particularly interested in the recovery feature since gdk is [using it](https://github.com/Blockstream/gdk/blob/master/subprojects/gdk_rust/gdk_electrum/Cargo.toml#L28) by adding explicit secp dependency, but I thought also endomorphism and lowmemory feature could be interesting
> Expose features of secp256k1

- src/blockdata/script.rs
- src/hash_types.rs
- src/util/key.rs
Introduces functions to compute bitcoin hashes for `PublicKey` and `Script` which were strangely missed out
> Hash functions for public keys and scripts

- src/util/bip32.rs
Currently one has to convert the path into a `Vec<ChildNumber>`, extend it and finally convert it back again.
> Allow easy concatenation of bip32 derivation paths

- src/util/bip32.rs
- src/util/psbt/map/input.rs
- src/util/psbt/map/output.rs
- src/util/psbt/mod.rs
- src/util/psbt/serialize.rs
Combinations of `(Fingerprint, DerivationPath)` are frequently used with PSBTs throughout this library and in many dependencies (like Lightning, Miniscript). It even had it's own serializer! So I think it is reasonable to introduce a type for representing this pair. After a brief discussion in https://github.com/rust-bitcoin/rust-miniscript/pull/131#discussion_r487444127 it was decided to name it `KeySource`, but we can change the name if needed.
> Introducing `bip32::KeySource`: wrapper for `(Fingerprint, DerivationPath)`

- src/internal_macros.rs
- src/network/constants.rs
- src/util/bip32.rs
- src/util/uint.rs
This is the first step in an attempt to simplify the macros we use in this crate.
I tried removing anything that can be derived. and removing the general functions implementation that might made sense on crates like `rust-secp256k1` for ffi reasons but less so here.
cc #352 
I'm trying to "Modernize" some of the great code @apoelstra wrote way before any of us ever heard of rust :)
The next stage is when these are simple enough I can write a custom derive crate for the rest of the things.
Sadly a thing that can greatly simplify the Index operations was is only stable from 1.28 https://github.com/rust-lang/rust/issues/35729
The breaking changes are:
1. removing a bunch of `as_pt` etc. implementations from `ChainCode` and `Fingerprint` (as I said before I don't think they make any sense …
> Simplifying macros

- Cargo.toml
- fuzz/fuzz_targets/deser_net_msg.rs
- fuzz/fuzz_targets/deserialize_address.rs
- fuzz/fuzz_targets/deserialize_amount.rs
- fuzz/fuzz_targets/deserialize_block.rs
- fuzz/fuzz_targets/deserialize_psbt.rs
- fuzz/fuzz_targets/deserialize_script.rs
- fuzz/fuzz_targets/deserialize_transaction.rs
- fuzz/fuzz_targets/outpoint_string.rs
- fuzz/fuzz_targets/uint128_fuzz.rs
- src/blockdata/script.rs
- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/hash_types.rs
- src/lib.rs
- src/network/mod.rs
- src/util/address.rs
- src/util/amount.rs
- src/util/base58.rs
- src/util/bip158.rs
- src/util/bip32.rs
- src/util/contracthash.rs
- src/util/hash.rs
- src/util/key.rs
- src/util/merkleblock.rs
- src/util/mod.rs
- src/util/psbt/error.rs
This is akin to https://github.com/rust-bitcoin/rust-secp256k1/pull/232
but also finally really removed the `hex` dependency from the tests (I have no idea how did I miss it in #381 )
> Small modernization after MSRV bump

- src/blockdata/transaction.rs
- src/util/bip143.rs
Hash engines don't product I/O errors, so encoding into them
shouldn't produce errors either.
This change was introduced in https://github.com/rust-bitcoin/rust-bitcoin/commit/3618d7a41d8aadd1f3c1762969893012cefff899 but wasn't needed and accidentally broke the API. This repairs that.
> Revert the sighash method signatures

- src/util/bip158.rs
In working on a bip157 implementation, I ran into the lack of `Clone` & `Debug` on `BlockFilter`. I can live with only `Debug` and `Clone`, but eventually someone will ask for `Eq`, so I added it :)
> BlockFilter `Clone`, `Debug` etc. derives

- Cargo.toml
- contrib/test.sh
- src/lib.rs
- src/util/misc.rs
I do realize that adding a dependency might be controversial. Also, if anyone knows a better base64 crate, please let me know. The one I used is one I created some months ago based on the `base64` crate but making it compatible with Rust v1.19.0, something [they refused to do](https://github.com/marshallpierce/rust-base64/pull/113).
> Add MessageSignature type for dealing with signed messages

- examples/bip32.rs
Dear 🦀-bitcoin people, I started using rust-bitcoin crate for my thesis and it is wonderful! Thank you for your amazing work!
For some people like myself it might be difficult to start using the crate without hello-world examples.
So I got up the courage to offer an example on the bip32 functionality.
Excuse me if the quality of my code does not meet the standards. I will be happy to improve it if you give me a code review.
> Add an example for bip32 key derivation

- CHANGELOG.md
- Cargo.toml
- src/blockdata/script.rs
- src/consensus/encode.rs
- src/util/endian.rs
- src/util/key.rs
- src/util/uint.rs
I went over all existing assertions, the ones I left are mostly wrong user input on methods that expect slices of a fixed size (like in decoding for endianness or so), I think those still make sense.
I just hit the `PublicKey::write_into` debug assertion running a long test involving programs sending messages over TCP connections (and not building with `--release`). So when one peer closes a TCP connection at the exact moment the other side is writing a public key, the assertion would cause the sender to panic.
> Avoid a few assertions that shouldn't be necessary

- src/blockdata/constants.rs
- src/consensus/params.rs
- src/network/constants.rs
- src/util/address.rs
- src/util/bip32.rs
- src/util/key.rs
This PR adds the "signet" network type to the list of networks.
See also:
* https://github.com/rust-bitcoin/constants/pull/8
> add signet support

- src/network/constants.rs
- src/network/message.rs
- src/network/message_blockdata.rs
BIP339 support was just merged into core: https://github.com/bitcoin/bitcoin/pull/18044
Not sure about changing the protocol version because I don't think every protocol is supported in rust-bitcoin yet
Not sure about the name for the new inv type, we already have WitnessTransaction
> BIP339: Add wtxidrelay message and WTx inv type

- src/consensus/encode.rs
- src/hash_types.rs
- src/network/message.rs
- src/network/message_filter.rs
- src/util/bip158.rs
These two types represent different hashes:
Filter hash is the sha256d hash of the bytes of the filter
Filter header is the sha256d hash of the filter hash concatenated with the previous filter header
``` filter_id() ``` is replaced with ```filter_header()``` to better describe what it returns
Calculating the filter header is moved to the filter hash type because you need to calculate the filter header from a filter hash when you do not have access to the full filter.
> Implement new FilterHeader type to differentiate from FilterHash

- src/util/bip32.rs
Binary (non-base58) encoding for public and private keys are required for storing PSBT `PSBT_GLOBAL_XPUB` according to BIP 174. This PR extracts binary encoding from inside `Display` and `FromStr` functions and put this as a standalone methods.
This PR is dependent on #469; to see only changes specific to the current PR pls check commit https://github.com/rust-bitcoin/rust-bitcoin/commit/94c2ddaeffd4277aed50bc88e0684e4d311faeea
> BIP 32 binary encoding functions are extracted from base58

- src/util/psbt/map/input.rs
- src/util/psbt/map/output.rs
- src/util/psbt/mod.rs
Nit, but since we have 100% of other key names matching the BIP names, and this one does not, I think it is nice to have.
This is API breaking change, but still not hard to adopt by downstream dependencies.
PS Based on #512 since otherwise fails to build due to a bug in the master
> PSBT: making input and output field names match spec type names

- src/blockdata/transaction.rs
The fact that `sighash_u32` is `u32` is a bit confusing and inconvenient.
First commit adds some explanation.
Second helps with the convenience.
> Improve `sighash_u32` handling

- src/util/psbt/map/global.rs
- src/util/psbt/map/input.rs
- src/util/psbt/map/output.rs
This does not create any external API changes, but is useful for code readability, internal consistency & future work, preventing from typos-type mistakes etc.
Part of PSBT/BIP32 refactoring epic https://github.com/rust-bitcoin/rust-bitcoin/issues/473
> PSBT types are now constants

- src/consensus/encode.rs
- src/network/message.rs
- src/network/stream_reader.rs
Currently whenever an unrecognized network message is received, it is never flushed from the read buffer, meaning that unless the stream is closed and recreated it will keep returning the same error every time `read_next()` is called.
This commit adds the length of the message to `UnrecognizedNetworkCommand`, so that the `StreamReader` can flush those bytes before returning the error to the caller.
@RCasatta and I encountered this issue while connecting to a Bitcoin Core 0.21-rc2 node using the latest release of `rust-bitcoin`. The specific error we were getting about `sendaddrv2` being unrecognized should already be fixed here in `master`, but still this is probably an issue worth fixing for messages that could be added in the future to the P2P protocol.
> Flush unrecognized network messages from the read buffer

- src/network/message.rs
There is currently not really an easy way to enforce this limit in our implementation.
> Add message::MAX_INV_SIZE constant

- src/network/address.rs
This allows the message to be passed in constructors that take `A: ToSocketAddrs` like `net::TcpStream` etc.
> network: Implement net::ToSocketAddrs for address messages

- src/consensus/encode.rs
- src/network/message.rs
- src/network/message_blockdata.rs
- src/network/message_network.rs
- src/network/stream_reader.rs
Both by added an `Unknown` variant.
Ideally we'd also mark these enums (and a few other enums) as `#[non_exhaustive]`, but that's not supported yet in Rust 1.29.
> Make Inventory and NetworkMessage enums exhaustive

- src/util/psbt/error.rs
- src/util/psbt/map/global.rs
- src/util/psbt/map/input.rs
- src/util/psbt/map/output.rs
- src/util/psbt/mod.rs
- src/util/psbt/raw.rs
This is a companion PR to https://github.com/rust-bitcoin/rust-bitcoin/pull/478 and a part of epic https://github.com/rust-bitcoin/rust-bitcoin/issues/473
This PR is based on previous PRs for BIP 32 binary serialization and versioning from #469  and #470 (which must be merged first) and includes commits from them. Commits specific to this PR starts from https://github.com/rust-bitcoin/rust-bitcoin/pull/471/commits/325f323aebc201903d0839bb969f3cb2dcd325e2
Once #478 will be merged, I will add constant key name for the new hash key types into this PR
> PSBT proprietary key system matching BIP 174

- src/blockdata/transaction.rs
Insert double quotes instead of a combination of single quote
and backtick.
> docs: fix quotes in Transaction#ntxid description

- src/blockdata/transaction.rs
Instead of using a wildcard path for the `hash_types` module,
be explicit about what types we're using by using nested paths.
There are many benefits to this, including not polluting the namespace
and clearly demarcating the types' location.
> refactor(blockdata/transaction): use nested paths

- src/network/address.rs
Building the latest master gives the following warning. 
```
warning: taking a mutable reference to a `const` item
--> src/network/address.rs:317:27
|
317 |                 services: ServiceFlags::NETWORK.add(ServiceFlags::WITNESS),
|                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(const_item_mutation)]` on by default
= note: each usage of a `const` item creates a new temporary
= note: the mutable reference will refer to this temporary, not the original `const` item
note: mutable reference created due to call to this method
--> src/network/constants.rs:161:5
|
161 |     pub fn add(&mut self, other: ServiceFlags) -> ServiceFlags {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: `const` item defined here
--> …
```
> Fix service flags warning

- README.md
The old travis one is defunct due to our CI switch.
> Switch CI badge to GH actions

- Cargo.toml
`rust-secp256k1` version 0.20 was recently released: https://github.com/rust-bitcoin/rust-secp256k1/pull/257
This PR updates `rust-bitcoin` to this latest version.
> Bump to secp256k1 0.20 and don't enable `recovery` of `secp256k1` in the dependency declaration

- src/blockdata/script.rs
- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/hash_types.rs
- src/internal_macros.rs
- src/network/address.rs
- src/network/constants.rs
- src/network/message.rs
- src/network/message_blockdata.rs
- src/network/message_network.rs
- src/util/merkleblock.rs
- src/util/psbt/macros.rs
- src/util/psbt/map/global.rs
- src/util/psbt/map/input.rs
- src/util/psbt/map/mod.rs
- src/util/psbt/map/output.rs
- src/util/psbt/mod.rs
- src/util/psbt/raw.rs
- src/util/uint.rs
This is instead of encode::Errors because the encoders should
not be allowed to return errors that don't originate in the writer
they are writing into.
This is a part of the method definition that has been relied upon for a
while already.
> Change the signature of consensus_encode to return io::Error's 

- src/blockdata/transaction.rs
I noticed we currently don't have an easy way to check the explicit RBF signaling of a tx (see also rust-bitcoin/rust-bitcoincore-rpc#162).
> Add function to check RBF-ness of transactions

- src/blockdata/block.rs
Validating a block's proof-of-work involves computing the block hash. Returning it from `BlockHeader::validate_pow` avoids having callers recompute the block hash if it is needed.
Helpful when validating the chain in https://github.com/rust-bitcoin/rust-lightning/pull/791#discussion_r575705113
> Return BlockHash from BlockHeader::validate_pow

- src/util/amount.rs
I've been working a bit with Amounts and the satoshi notation is really confusing if you're dealing with 1 BTC+ amounts. The `Debug` trait is meant to as easily as possible give the developer an idea of the amount, so adding a decimal point gives strictly more information. Like this it always shows 8 digits.
This should not be considered a breaking change, IMO. The `Debug` trait is not intended to be parseable.
> Change Amount Debug impl to BTC with 8 decimals

- src/util/key.rs
Underlying error types (SECP and Base58) are clonable and equatable; however the key error is neither of them. This PR fixes the issue and opens a way for more detailed clonable error types in rust-miniscript (my current WIP)
> More derives for key::Error

- src/blockdata/transaction.rs
- src/util/bip143.rs
- src/util/psbt/serialize.rs
Right now, any sighash type could be parsed without error, which matches
consensus rules. However most of them would be invalid by standardness,
so it's a bit footgun-y (even more so for pre-signed transactions
protocols for which standardness is critical).
This adds `from_u32_standard()`, which takes care to error if we are
passed an invalid-by-current-policy-rules SIGHASH type.
(Happy to bikeshed the method name)
> SigHashType: add a method to error on non-standard hashtypes

- src/util/bip32.rs
Trivial changes:
1. Support for `_h` format in hardened indexes using alternate format string (`format!("{:#}", ChildNumber::from_hardened_idx(5))` will print `5h` instead of `5'`)
2. Using Display trait allows custom number formatting (for instance `format!("{:#06}", ChildNumber::from_hardened_idx(5))` will print `000005h`)
> Improving bip32 ChildNumber display implementation

- src/util/psbt/map/global.rs
- src/util/psbt/mod.rs
Fix bug introduced in #471
Proprietary keys in PSBT were not deserialized back
first commit introduce a failing test, second commit fix the test
> Include proprietary key in deserialized PSBT

- src/util/amount.rs
This patch fixes the Optional Amount serialization for Amount types and adds tests that ensure that round tripping actually works.
This issue comes up because e.g., `{amt: null}` and `{}` are theoretically equivalent types, but our code did not properly handle the `{amt: null}` serialization output by serde_json.
> Fix Optional Amount Serialization

- src/blockdata/script.rs
This makes it convenient to print/construct the script assembly on byte slices withoout having to clone them to copy them to create a Script struct.
> Make Script::fmt_asm a static method and add Script::str_asm 

- .github/workflows/rust.yml
[CI fails](https://github.com/rust-bitcoin/rust-bitcoin/pull/582/checks?check_run_id=2263509700) in PR #582 although no code changes happened. My theory is that the base image's apt database is outdated and contains old paths to packages. If that's the case this PR should fix it.
> Don't fail CI if base image's apt db is outdated

- src/blockdata/transaction.rs
Small fix to a small issue I noticed
> doc: correct Transaction struct encode_signing_data_to doc comment

- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/util/base58.rs
This implements first part of #555 recommendations for Error types within rust-bitcoin. This PR is (a) non-API breaking & (b) can be applied before similar PRs in other repos. It will be followed by more PRs that are (1) depend on error type derives from downstream repos & (2) will be API-breaking
PS: depends on https://github.com/rust-bitcoin/rust-bitcoinconsensus/pull/22 merge & new version release
> Non-API breaking derives for error & transaction types

- src/blockdata/transaction.rs
My OCD for fixing yellow lines in the build process.
> fix warnings for sighashtype

- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/internal_macros.rs
- src/network/message.rs
- src/util/psbt/map/global.rs
- src/util/psbt/mod.rs
This allows counting the byte read during encoding
> Count bytes read in encoding

- .github/workflows/rust.yml
- src/blockdata/opcodes.rs
- src/blockdata/script.rs
- src/blockdata/transaction.rs
- src/lib.rs
- src/network/address.rs
- src/network/message.rs
- src/util/amount.rs
- src/util/bip32.rs
- src/util/contracthash.rs
- src/util/misc.rs
- src/util/psbt/mod.rs
- src/util/psbt/raw.rs
This fixes documentation intra-links so that are correctly rendered in generated HTML pages and on docs.rs
It also adds `#![deny(broken_intra_doc_links)]` and build docs in CI so that future errors of this kind are seen by the CI
Do we want to use nightly to build the docs since it's the version used on docs.rs?
> Fixes documentation intra-links and enforce it

- src/blockdata/script.rs
- src/blockdata/transaction.rs
In https://github.com/RCasatta/blocks_iterator/blob/verify/examples/verify.rs I would like to verify mainnet and testnet blocks. However, at the moment the verify flag is not exposed in the API so it's not possible (without using bitcoinconsensus directly).
I preserved the original method and added `verify_with_flags` so that it should not be a breaking change.
The flag parameter is taken as `Into<u32>` so that if we introduce a VerifyFlags type/builder in bitcoinconsensus the migration should be more smooth.
> Add verify_with_flags to Script and Transaction

- src/blockdata/script.rs
The dust calculations added were only valid for P2WPKH and P2PKH
outputs, and somehow this fact was missed in review, despite the
upstream Core code being linked to and looked at by two reviewers
and the author (me).
Someday I will grow eyeballs, but that day is not today.
> Fix Script::dust_value()'s calculation for non-P2*PKH script_pubkeys

- src/util/address.rs
Add a method `to_qr_string` for `Address` which is the same as `to_string` given by `Display` but it's uppercased if the address is bech32. Useful to embed the address in QR codes
> Address to optimized QR string

- Cargo.toml
- src/lib.rs
Caused by the latest `bitcoin_hashes` release
> Fixing hashes core dependency and fuzz feature

- src/blockdata/constants.rs
- src/blockdata/script.rs
- src/lib.rs
- src/policy/mod.rs
~~Not sure about the place since all other constants are consensus, but it seemed awkward to have it eg in the `transaction` module while there is a `constants` one :shrug:~~
EDIT: this now introduces a minimal set of policy stuff from `bitcoind` in a new `policy` module.
> Introduce some policy constants from Bitcoin Core

- src/util/bip158.rs
Current example seems to be not formatted correctly in https://docs.rs/bitcoin/0.26.0/bitcoin/util/bip158/index.html:
> Fix bip158 example formatting

- CHANGELOG.md
- Cargo.toml
More than half of the year has passed since the last release and we already have 24 PRs merged, which indicates the clear need to get the new version out.
I have only doubts about https://github.com/rust-bitcoin/rust-bitcoin/pull/572 which is marked as API version breaking change, so if you see this to be critical we will need to mark this release as `0.27` - but pls let's do not postpone this release further.
> Bump version to 0.26.1

- CHANGELOG.md
- Cargo.toml
- src/util/bip32.rs
We broke downstream with 0.26.1, I propose yankign it and releasing 0.26.2. This fixes #608 and closes #609 .
> Fix release 0.26.2

- src/util/address.rs
- src/util/base58.rs
- src/util/bip32.rs
- src/util/ecdsa.rs
- src/util/psbt/error.rs
- src/util/psbt/map/global.rs
- src/util/psbt/map/input.rs
I was having a look at the output of the command:
```
RUSTFLAGS=-Zprint-type-sizes cargo +nightly build --release
```
And I thought some size optimization on error enums are worthy because they are used a lot around in Results and encapsulated in other errors. In the end, I also removed and introduced variants.
The following enums have direct size improvements:
* util::psbt::error::Error from 120 bytes to 40 bytes
* util::base58::Error from 32 bytes to 16 bytes
* util::bip32::Error from 32 bytes to 8 bytes
> Errors enum improvements

- Cargo.toml
- src/util/address.rs
This adds support for Bech32m and fixes test vectors according to BIP-350. All changes non-API breaking, which allow to introduce them in `0.26.1` such that we will be able to parse Taproot addresses before `0.27` and #563
Since we do not want to break API I re-used existing error type in https://github.com/rust-bitcoin/rust-bitcoin/pull/601/files#diff-c55d0186f3d5990b5e223c1a8aa1bbe60988201c452dd13b3324e892bc33119eR447 to mark failed Bech32(m) encoding variant. This should not be a problem since with  #563 it will be solved anyway by `0.27` release
> Bech32m adoption

- .github/workflows/rust.yml
- src/consensus/encode.rs
- src/network/address.rs
- src/util/uint.rs
fixes https://github.com/rust-bitcoin/rust-bitcoin/issues/624
Adds a CI job using cross https://github.com/rust-embedded/cross to run tests on bigendian arch
> “Zero setup” cross compilation and “cross testing” of Rust crates  maintained by the Tools team.
At the moment it is using `s390x-unknown-linux-gnu` which is the arch used by @jlatone in the referenced issue but we can easily extend via matrix if we want to test other arch.
> Bigendian fixes and CI test

- CHANGELOG.md
- Cargo.toml
The minor version increment is due to the breaking changes in #601 and #521
> Bump version to 0.27.0

- Cargo.toml
- fuzz/Cargo.toml
It seems to be unused and when there's a need for it it's better to use
`--cfg fuzzing` as in `rust-secp256k1 ` and `bitcoin_hashes`.
See https://github.com/rust-bitcoin/rust-bitcoin/pull/633#discussion_r678624842 for context
> Removed fuzztarget feature

- src/blockdata/script.rs
close https://github.com/rust-bitcoin/rust-bitcoin/issues/595
At the moment `Script` for serde non-human-readable format is serialized as bytes of the hex format, doubling the space required 
This fix by serializing in bytes if the encoding format is non-human-readable (such as using bincode or serde_cbor)
> Script serialization/deserialization in serde non-human-readable format

- src/blockdata/script.rs
In https://github.com/rust-bitcoin/rust-bitcoin/pull/598 `verify` function signature has left untouched to avoid breaking the API
This address https://github.com/rust-bitcoin/rust-bitcoin/pull/598#discussion_r624438394 but it's a breaking change
> use Amount type in verify

- src/blockdata/constants.rs
- src/util/address.rs
Instead of using magic numbers we can define constants for the address
prefix bytes. This makes it easier for future readers of the code to see
what these values are if they don't know them and/or see that they are
correct if they do know them.
> Use consts for address prefix values

- src/util/taproot.rs
Current docs https://docs.rs/bitcoin/0.26.2/bitcoin/util/taproot/index.html show `[$newtype]` because macro vars aren't expanded in docs
> Fix documentation referencing macro var

- src/blockdata/script.rs
- src/util/address.rs
Reopening as a new PR to #562 (github does not allow to re-open force-pushed branches) since there might be changes during the review at this level unrelated to #563 (which will be in draft mode until this is merged - and rebased after the merge)
> WitnessVersion type

- src/util/bip32.rs
- src/util/psbt/error.rs
- src/util/psbt/map/global.rs
Removes controversial aspects from #560 (all `io::Error`-related changes) and leaves the rest
> Improvements to Error types (part 4)

- src/blockdata/block.rs
- src/blockdata/transaction.rs
I implemented the following methods:
- `block.get_strippedsize()`: gets the "strippedsize" of a block.
- `tx.get_vsize()`: gets the "virtual" size of a transaction.
The test values added for this code match the values comes from Bitcoin Core.
Edit: `block.get_strippedsize()` will call `tx.get_scaled_size()` twice for every transactions in a block, which cannot be prevented without exposing an extra function in `Transaction` which produces the non-segwit data bytes. This will impact the performance, while the exposed API kept simple.
Edit 2: If you prefer performance over smaller API change, let me know. I will modify my PR (will add `tx.get_strippedsize()`).
> Implement `Block.get_strippedsize()` and `Transaction.get_vsize()`

- src/util/amount.rs
Currently iterators of amounts can't be summed. This PR fixes this and also adds a checked variant.
> Implement `Sum` for amount types

- src/util/amount.rs
The latest merge of https://github.com/rust-bitcoin/rust-bitcoin/pull/615 broke the master b/c it didn't run new `no_std` CI. This PR fixes the problem.
> Fixing no_std for Amount sum iterator

- src/network/message.rs
- src/network/message_bloom.rs
- src/network/mod.rs
Adds initial support for parsing the `merkleblock`, `filterload`, `filteradd` and `filterclear` network messages.
https://developer.bitcoin.org/reference/p2p_networking.html#filteradd
https://developer.bitcoin.org/reference/p2p_networking.html#filterclear
> Add Bloom filter network messages

- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/util/bip143.rs
- src/util/mod.rs
- src/util/sighash.rs
Adds https://github.com/bitcoin/bips/blob/master/bip-0341.mediawiki message signature algorithm
The base is taken from `bip143::SigHashCache`, some code results duplicated but I think it's more clear to keep things separated
Would mark some bullet point on https://github.com/rust-bitcoin/rust-bitcoin/issues/503
Test vectors are taken by running https://github.com/bitcoin/bitcoin/blob/d1e4c56309aeb73772e3a9d779a9c157024c9e1e/test/functional/feature_taproot.py with a modified `TaprootSignatureHash` function to print intermediate values that I cannot found in the bip341 [test vector json](https://raw.githubusercontent.com/bitcoin-core/qa-assets/main/unit_test_data/script_assets_test.json)
UPDATE: Latest version includes the suggestion from @sanket1729 to create a unified tool for signature …
> Adds Taproot BIP341 signature message and create a unified sighash cache for legacy, segwit and taproot inputs

- src/blockdata/constants.rs
- src/util/address.rs
Added changes in the p2sh function to return a result (#650), created an error for ExcessiveScriptSize, added a constant for MAX_SCRIPT_ELEMENT_SIZE and added a test where the script size exceeds 520.
> Changes for checking script size and returning Result<Address, Error> for p2sh

- src/blockdata/script.rs
This adds an overflow check in `Script::bytes_to_asm_fmt()` motivated by
`electrs` issue. While it was not tested yet, I'm very confident that
overflow is the cause of panic there and even if not it can cause panic
becuase the public function takes unvalidated byte array and reads
`data_len` from it.
The `electrs` issue: https://github.com/romanz/electrs/issues/490
~~Strangely, this breaks a test case and I can't see why. I'm publishing in case someone wants to help.~~
Edit: One damn character. :D Should be OK now.
> Check for overflow in Script::bytes_to_asm_fmt()

- CHANGELOG.md
- Cargo.toml
- src/blockdata/script.rs
> [backport #658] Check for overflow in Script::bytes_to_asm_fmt()

- .github/workflows/rust.yml
This adds i686 to CI which can help catching pointer-size-related bugs
such as the one addressed by #658.
Opening a new PR seemed more appropriate than adding it to #658 I can change it if you disagree.
> Add i686 to tested architectures

- src/blockdata/opcodes.rs
- src/blockdata/script.rs
- src/util/contracthash.rs
- src/util/misc.rs
Adds support for `CHECKSIGADD` and `OP_SUCCESSxxx`. BIP 342 link for reference https://github.com/bitcoin/bips/blob/master/bip-0342.mediawiki#specification .
Also makes a minor change to add `INVALIDOPCODE` (was previously `OP_RETURN`)
> Add OP_CHECKSIGADD and OP_SUCCESSxxx

- src/util/address.rs
- src/util/misc.rs
Part of Taproot project https://github.com/orgs/rust-bitcoin/projects/3 and epic #503. Depends on #617
> Taproot P2TR address

- fuzz/fuzz_targets/uint128_fuzz.rs
- src/util/uint.rs
This is #578 with review feedback addressed.
> Fix `Uint256::increment` panics

- .github/workflows/fuzz.yml
- fuzz/Cargo.toml
- fuzz/fuzz_targets/script_bytes_to_asm_fmt.rs
- src/blockdata/script.rs
*Because of this change being somewhat large I didn't do it together with #658.
I also don't mind if this is merged after Taproot (feel free to put off review).*
This refactors `Script::bytes_to_asm_fmt`` function to use an iterator
instead of index. Such change makes it easier to reason about overflows
or out-of-bounds accesses. As a result this also fixes three unlikely
overflows and happens to improve formatting to not output space at the
beginning in some weird cases.
To improve robustness even better it also moves `read_uint`
implementation to internal function which returns a more specific error
type which can be exhaustively matched on to guarantee correct error
handling. Probably because of lack of this the code was previously
checking the same condition twice, the second time …
> Refactor Script::bytes_to_asm_fmt to use iterator

- src/util/address.rs
- src/util/schnorr.rs
Addressing issue #687.
Changes:
- New method `Address::dangerous_p2tr` that creates an address given an untweaked internal key and optional merkle root of a script tree. The method utilizes existing hash methods from within the library and key tweaking from the `rust-secp256k1` library.
- Added a test to create a P2TR address from an internal key without a script tree. Test was taken from BIP-86.
Questions:
- Should key tweaking be a seperate function in it self? Since the `secp256k1` key tweaking method does not hash the data, there could be a method that does the tweaking and commitment part of the `Address::dangerous_p2tr` method. 
- What error should `Address::dangerous_p2tr` return if an error occurs while tweaking the internal key?
I would love feedback as this is my first PR to …
> P2TR address from untweaked key

- .github/workflows/rust.yml
- Cargo.toml
- embedded/scripts/env.sh
- embedded/src/main.rs
- cleanup embedded test memory based on comments under https://github.com/rust-bitcoin/rust-bitcoin/pull/603#pullrequestreview-708333388
- pull in `secp256k1/alloc` for no-std use
> no-std cleanup

- src/util/psbt/macros.rs
- src/util/psbt/map/global.rs
- src/util/psbt/map/mod.rs
- src/util/psbt/mod.rs
I took the most non-invasive approach to reduce diff size. Many parts of the code can be improved in style or further refactored (like some functions are not necessary and can be just moved to be part of other functions), but I'd prefer to do that as a separate PR once this will be merged.
My approach with this PR:
1. Remove `Global` struct by moving its fields right into `PartiallySignedTransaction` - but keep the `util/psbt/map/global.rs` file with all its logic
2. Keep existing `Map for Global` implementation in the same file, but just change it to `Map for PartiallySignedTransaction` 
3. With serialization, convert `Global` deserialization into crate-private function and use it from `PartiallySignedTransaction` deserialization
4. Refactor the tests and imports as required to get the …
> Making globals part of PSBT struct. Closes #652

- src/util/address.rs
The new AddressType test shows addresses that are valid but have
no type. If in the future some of those get a type or become
invalid (either voluntarily or due to a regression), this will
highlight it.
> tests: improve coverage for P2tr and AddressType

- src/util/address.rs
- src/util/schnorr.rs
This was my bad for not clearly stating the expected spec #687 . Changed values to references so that we only take ownership where it is required. 
This should simplify the #697
> P2tr fixes

- src/util/taproot.rs
I noticed one cleanup & one bugfix while looking into the huffman algorithm:
1) the cleanup: we can use a u128 to guarantee no overflows, and saturating_add to guarantee reasonable behavior in any case
2) the bug: the binary heap is a max heap so the behavior ends up merging the nodes of the most likely entries repeatedly. a huffman encoder requires merging the least likely elements, so it should be reversed.
> Huffman Bug Fix

- src/blockdata/block.rs
- src/blockdata/script.rs
- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/util/bip143.rs
- src/util/bip158.rs
- src/util/hash.rs
- src/util/merkleblock.rs
- src/util/misc.rs
- src/util/taproot.rs
Calls to `unwrap` outside of tests are generally unfavourable. We currently call `unwrap` in a bunch of places on calls to `consensus_encode` when passing writers that do not fail.
Remove `unwrap` calls on all calls to `consensus_encode` that pass a writer argument for which write functions do not fail. Use `expect` with a descriptive string instead.
Fixes: #714
> Use expect instead of unwrap for calls to consensus_encode

- src/util/address.rs
- src/util/schnorr.rs
Quick follow up PR to #691 using a method from #677.
- Updated `UntweakedPublicKey::tap_tweak(...)` to use `TapTweakHash::from_key_and_tweak(...)`
> Use TapTweakHash::from_key_and_tweak() method in computing tweak for UntweakedPublicKey

- Cargo.toml
Latest merges has broken builds since they have introduced `alloc` feature in `secp256k1` which appeared only in `0.20.3` version, while `Cargo.toml` here still required `0.20.2`
This was not caught by CI since it always runs with `cargo update`
> Hotfix for secp256k1 alloc feature

- src/blockdata/script.rs
`Instructions` guarantee to return `None` from empty iterator so we
should signal this in type system so that the code can be optimized
better. This also adds a test to make sure this property holds.
> Super-trivial: Implement `FusedIterator` for `Instructions`

- src/util/taproot.rs
This builds on https://github.com/rust-bitcoin/rust-bitcoin/pull/699 but is the more bikesheddable part since it changes the API.
> u32 of weight should be enough for any branch.
-- Bill Gates
> Decrease Huffman Weights to u32

- src/util/schnorr.rs
Extraction of a portion from #696 which can be done without changes in `rust-secp256k1`
> Improvements to script methods related to Taproot

- src/blockdata/transaction.rs
- src/lib.rs
- src/util/bip143.rs
- src/util/ecdsa.rs
- src/util/psbt/map/input.rs
- src/util/psbt/mod.rs
- src/util/psbt/serialize.rs
- src/util/schnorr.rs
- src/util/sighash.rs
Fixes #670 . Separates `SchnorrSigHashType` and `LegacySigHashType`. Also adds the following new structs:
```rust
pub struct SchnorrSig {
/// The underlying schnorr signature
pub sig: secp256k1::schnorrsig::Signature,
/// The corresponding hash type
pub hash_ty: SchnorrSigHashType,
}
pub struct EcdsaSig {
/// The underlying DER serialized Signature
pub sig: secp256k1::Signature,
/// The corresponding hash type
pub hash_ty: LegacySigHashType,
}
```
This code is currently minimal to aid reviews. We can at a later point implement (Encodeable, psbt::Serialize, FromHex, ToHex) etc in follow-up PRs.
> Separate signature hash types

- src/util/taproot.rs
- test_data/bip341_tests.json
Add tests for taproot. 
- ~Also fixes one bug in #677, namely, I was returning `LeafVersion::default()` instead of given version~
- ~ Fixes a bug in #691 about taking secp context as a reference instead of consuming it. This should have not passed my review, but this is easy to miss. ~
- Makes the display on taproot hashes forward instead of the reverse (because the BIP prints in a forward way, I think we should too and it is more natural. )
> BIP341 test vectors

- src/lib.rs
Using the latest version of rust-bitcoin master on rust-miniscript
errors on bitcoin::SigHashType not found. In the original PR, I only
renamed the export to ECDSASigHashType, but original re-export should
also be there in lib.rs to avoid breaking changes downstream.
Fixup to #702 
Before this PR,
```
|
89 |         required: bitcoin::SigHashType,
|                            ^^^^^^^^^^^ not found in `bitcoin
```
After this PR, 
```
warning: use of deprecated type alias `bitcoin::SigHashType`: Please use [`EcdsaSigHashType`] instead
--> src/psbt/mod.rs:89:28
|
89 |         required: bitcoin::SigHashType,
```
> Re-export SigHashType in lib.rs

- Cargo.toml
This changes `rustc-args`, which doesn't do what we want, to `rustdoc-args`,
which does.
Because of huge value/effort ratio assigning medium priority and 0.28 milestone - would be a real shame to release without this.
> Fixed docs.rs metadata

- src/util/amount.rs
There is no reason to force users to use a particular format or case for `Denomination` strings. Users may wish to write any of the following and all seem reasonable
- 100 sats
- 100 sat
- 100 SAT
The same goes for various other `Denomination`s.
- Patch 1 enables usage of "sats", "sat", "bit", "bits"
- Patch 2 enables usage of various lower/uper case formatting
Fixes: #729
> Improve parsing of `Denomination` string

- src/blockdata/transaction.rs
If they ever hit a discrepancy they must really be doing something dodgy but hey :)
> transactions: add a note about `get_vsize` and standardness rules

- .github/workflows/fuzz.yml
- fuzz/Cargo.toml
- fuzz/fuzz_targets/deserialize_transaction.rs
- fuzz/fuzz_targets/deserialize_witness.rs
- src/blockdata/block.rs
- src/blockdata/constants.rs
- src/blockdata/mod.rs
- src/blockdata/transaction.rs
- src/blockdata/witness.rs
- src/util/bip143.rs
- src/util/psbt/mod.rs
- src/util/sighash.rs
At the moment the Witness struct is  `Vec<Vec<u8>>`, the vec inside a vec cause a lot of allocations, specifically:
- empty witness -> 1 allocation, while an empty vec doesn't allocate, the outer vec is not empty
- witness with n elements -> n+1 allocations
The proposed Witness struct contains the serialized format of the witness. This reduces the allocations to:
- empty witness -> 0 allocations
- witness with n elements -> 1 allocation for most common cases (you don't know how many bytes is long the entire witness beforehand, thus you need to estimate a good value, not too big to avoid wasting space and not too low to avoid vector reallocation, I used 128 since it covers about 80% of cases on mainnet)
The inconvenience is having slightly less comfortable access to the witness, but the …
> New Witness struct to improve ser/de perfomance

- src/internal_macros.rs
- src/util/sighash.rs
Based on #695 . Adds the remaining test vectors to test sighash paths. Will rebase after #695
> Tapsighash test vectors

- src/blockdata/script.rs
- src/blockdata/transaction.rs
- src/consensus/params.rs
- src/internal_macros.rs
- src/network/message.rs
- src/network/message_filter.rs
- src/util/address.rs
- src/util/ecdsa.rs
- src/util/misc.rs
- src/util/psbt/error.rs
- src/util/sighash.rs
- src/util/uint.rs
(Trivial / Very low priority PR)
Rust idiomatic style is to put the rustdoc _above_ any attributes on types, functions, etc.
Audit the codebase and move comments/attributes to the correct place. Add a trailing full stop at times to neaten things up a little extra.
Done after discussion [here](https://github.com/rust-bitcoin/rust-secp256k1/pull/353#discussion_r778393138)
> Put rustdocs above attributes

- src/blockdata/transaction.rs
- src/util/ecdsa.rs
- src/util/psbt/map/input.rs
- src/util/psbt/mod.rs
- src/util/psbt/serialize.rs
Previously signatures were kept in PSBT as raw byte vec, without processing. This adds specific data type, capable of holding & serializing/deserializing partial signature with sighash flag information.
> PSBT: partial sig data type

- src/util/psbt/serialize.rs
- src/util/sighash.rs
- src/util/taproot.rs
The original `LeafVersion` implementation was just a newtype around `u8`. I think that having enum explicitly listing consensus script implementation rules may be more beneficial in terms of both code readibility and future use of multiple script types, where `LeafVersion` may operate as a context object provided to `Script` to specify interpretation rules for particular op codes.
> Converting LeafVersion into an enum

- examples/bip32.rs
- src/util/bip32.rs
- src/util/ecdsa.rs
- src/util/psbt/mod.rs
This is third step required to introduce Schnorr key support according to #588. This PR starts API-breaking changes and is follow-up to non-API breaking #589, which is already merged.
PR rationale: BIP32 does not support uncompressed keys and using type with compression flag was a mistake
> Taproot: BIP32 extended keys using Scep256k1 keys instead of bitcoin ECDSA

- src/util/sighash.rs
- src/util/taproot.rs
Found this minor doc issue while reviewing(learning) previous merged PR.
Close https://github.com/rust-bitcoin/rust-bitcoin/issues/763
> wrap u8 and LeafVersion in backticks and square bracket in doc

- contrib/test.sh
- examples/bip32.rs
This is my understanding of what we want to fix the confusing bip32 example. Apologize in advance if I misunderstand it.
Closes #748
> improve example: take hex-encoded seed instead of WIF in bip32 example

- src/blockdata/script.rs
- src/util/psbt/map/input.rs
- src/util/psbt/map/output.rs
- src/util/psbt/mod.rs
- src/util/psbt/serialize.rs
Fourth step in implementation of Schnorr key support after #588. This PR is a follow-up to non-API breaking #589 and API-breaking #590, which must be reviewed and merged first. ~~(The current PR includes all commits from #589 and #590, which should be reviewed there. The only commit specific to this PR is b8105e95dc8651626b783403ca060f7d32d21144)~~
UPDATE: All related PRs are merged now and this PR is ready for the review
PR description:
While PSBT BIP174 does not specify whether uncompressed keys are supported in BIP32-related fields, from BIP32 it follows that it is impossible to use uncompressed keys within the extended keys.  This PR fixes this situation and is a companion to BIP174 PR clarifying key serialization: https://github.com/bitcoin/bips/pull/1100
> PSBT BIP32 keys using to Secp256k1 keys instead of bitcoin ECDSA

- src/blockdata/script.rs
- src/util/bip32.rs
- src/util/contracthash.rs
- src/util/ecdsa.rs
- src/util/misc.rs
Since we already broke all possible key-related APIs with this release, I think this one is good to have with 0.28.
Closes #532
> Rename inner key field in PrivateKey and PublicKey

- src/blockdata/witness.rs
Rebasing rust-miniscript on rust-bitcoin master. Expect more trivial PRs :)
> Add Witness::new()

- src/util/psbt/map/input.rs
- src/util/psbt/mod.rs
- src/util/psbt/serialize.rs
Doing this would certainly help APIs downstream that operate on &Witness because they would not conversion from &Vec<Vec<u8>> to &Witness.
> Change type of final script witness to Witness from Vec<Vec<u8>>

- .github/workflows/rust.yml
- src/blockdata/script.rs
- src/util/misc.rs
- src/util/schnorr.rs
* Adds taproot-related methods to `Script`
* Fixes API for existing taproot methods
* Generalizes `TapTweak` trait to work with both public keys and key pairs
~~UPD: PR is pending https://github.com/rust-bitcoin/rust-secp256k1/pull/342~~
> Taproot tweaks generalization & KeyPair support

- src/util/psbt/map/input.rs
- src/util/psbt/map/mod.rs
- src/util/psbt/mod.rs
- src/util/psbt/serialize.rs
- src/util/sighash.rs
We cannot really use `Psbt` for taproot because the sighash type is currently EcdsaSigHashType. We could introduce an enum with two options but then deser is not really clear, so I chose the approach in the current PR. Feedback or other ways to do this welcome :) 
This is NOT related to #776
> Introduce PsbtSigHashType

- src/util/amount.rs
Close [741](https://github.com/rust-bitcoin/rust-bitcoin/issues/741)
> add nano and pico BTC to Denomination enum

- src/util/psbt/macros.rs
- src/util/psbt/map/global.rs
- src/util/psbt/map/input.rs
- src/util/psbt/map/mod.rs
- src/util/psbt/map/output.rs
- src/util/psbt/mod.rs
The `Map` method `insert_pair` is never called for `PartiallySignedTransaction`. Separate the method into its own trait (`Insert`) and delete dead code. The dead code contains the alleged bug in #576. 
- Patch 1: Preparatory cleanup
- Patch 2: Preparatory refactor 
- Patch 3 and 4: Improve docs in the module that this PR touches
- Patch 5: Make `Map` trait private to the `psbt` module
- ~Patch 6: Make `concensus_decode_global` method into a function~
- Patch ~7~ 6: Pull `insert_pair` method out of `Map` trait into newly create `Insert` trait 
Resolves: https://github.com/rust-bitcoin/rust-bitcoin/issues/576
(Title of PR is `Make Map trait private` because that is the API break.)
> Make Map trait private

- Cargo.toml
We still have quite a few issues and PRs pending to be addressed/merged before full 0.28 release: see https://github.com/rust-bitcoin/rust-bitcoin/milestone/10
Most important, we have to find a way to address #777; additionally it will be desirable to get #587, #786, #776.
We also have quite of work to write CHANGELOG in #785
Nevertheless I propose to start with a `beta-1` subrelease to unlock ability for `miniscript` release and downstream testing. The Taproot API looks final, and the pending PRs are addresses internal issues/bugs which is perfectly fine for beta releases.
> Release v0.28 RC1

- CONTRIBUTING.md
We recently added `CONTRIBUTING.md` but forgot to add @Kixunil . Also a couple days ago I was added to the repo.
Patch two is trivial cleanup of whitespace.
> Add new maintainers

- src/lib.rs
- src/util/psbt/mod.rs
We currently have the `map` module private but containing a bunch of types that are needed in the public API (specifically in a `PartiallySignedTransaction`).
To give access to them re-export the `util::psbt` module at the root level.
Found while testing `master` with `rust-miniscript`.
> Re-export psbt module from root level

- CONTRIBUTING.md
@sgeisler requested by email to be step down from the position of
maintainer of `rust-bitcoin`. Remove his name from the contributing document's list of maintainers.
Implement @dr-orlovsky's suggested [whitespace policy ](https://github.com/rust-bitcoin/rust-bitcoin/pull/795#discussion_r786513512)while we are at it.
> Remove Sebastian from maintainers list

- src/blockdata/constants.rs
> Subsidy halving interval

- src/util/address.rs
- src/util/psbt/serialize.rs
- src/util/schnorr.rs
- src/util/sighash.rs
- src/util/taproot.rs
Rust convention is to use `to_` for conversion methods that convert from
an owned type to an owned `Copy` type. `into_` is for owned to owned
non-`Copy` types.
Re-name conversion methods that use `into_` for `Copy` types to use
`to_`, no need to deprecate these ones because they are unreleased.
**Note to maintainers**
This is similar in concept to #798 but only touches new code introduced in this release. Has been labelled 'RC fix' for that reason. Please feel free to remove the label if you disagree.
From the docs: https://rust-lang.github.io/api-guidelines/naming.html
<h2><a class="header" href="https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv" id="ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv">Ad-hoc …
> Use fn name to_ instead of into_ 

- src/util/bip32.rs
- src/util/psbt/raw.rs
- src/util/taproot.rs
write() could write only a part of the given buffer, the caller should
check the numbers of byte written (which is what write_all does)
> Use write_all instead of write

- src/util/sighash.rs
I believe this avoids some allocation of creating a vec of TxOut to
create a slice incase the data is already available in psbt/other
methods.
See #834
> Change Prevouts::All(&[TxOut]) to Prevouts::All(&[&TxOut])

- src/util/base58.rs
- src/util/bip32.rs
- src/util/key.rs
Was following #520 and through it was a quick fix that I could do:
- If an uncompressed public key doesn't have prefix 0x04 in `PublicKey::from_slice()`, an error is returned.
<br>
I was wondering if `PublicKey::from_str()` should also enforce the same rules, however I have not incuded this in the PR.
Please let me know if any changes need to be made.
Thanks
> Don't allow uncompressed public keys without prefix 0x04

- .github/workflows/fuzz.yml
I think this might take a while to resolve and we should move ahead with
1.58. Looks like the fresh release of 1.59 added LLVM 13.0 that broke
some things.
> Tempararily pin fuzzer on rust 1.58

- src/util/psbt/map/input.rs
Fixes #838: Add a utility method to psbt to compute find sighash
type of a given input.
For now, I have changed my previous implementation as discussed in #838 to functional style code as suggested by @Kixunil.
> Add a method to psbt to compute find sighash type

- src/util/taproot.rs
- Changes the API from TweakedPublicKey to XonlyPublicKey. I believe we
introduced TweakedPublicKey to guard against creating address API. This
is confusing because when we want to verify control block we have to
call dangerous_assume_tweak.
- This is in true in most cases that the key would be tweaked, but we only
want to guard in while creating a new address. If we want to verify
blocks, we should deal with native X-only-keys regardless of how they
were created
- Also removes the & from a 32 Copy byte as discussed elsewhere.
> Change the parameter for control block verification

- src/util/psbt/map/input.rs
Recently we added two new methods with rustdocs. The rustdocs have a few minor things that can be improved.
- Use 'Returns' section for both success and error path returns
- Use markdown heading for section
- [Subjectively] improve wording of docs
@rish-singhal this PR is minor rustdocs stuff that I have recently been learning myself. I hope this makes your future patches easier to do in regards to the docs. FTR there are `# Returns` sections and `# Examples` sections that one can use, no set rules as far as I can tell. I chose `# Returns` in this case because it seemed to work. Please feel free to NACK the wording changes if you do not agree.
> Improve rustdocs for *_hash_ty methods

- Cargo.toml
- src/util/schnorr.rs
- src/util/taproot.rs
Update our `rust-secp256k1` dependency to the latest released version.
Requires doing:
- Add a new variant to `Error` for the case where parity of the internal key is an invalid value (not 0 or 1).
- Use non-deprecated const
Please check the error change carefully, this error does relate _only_ to the parity of an internal key, right?
> Update secp256k1 dependency

- src/blockdata/script.rs
Improve the docs in the `blockdata::script` module by doing:
- Use full sentences (use capitals and full stops)
- Improve grammar/wording if necessary
- Remove incorrect/unneeded comments
- Fix layout of rustdoc i.e., use brief and description sections
- Use 100 line character width if it makes the comment look better
- Use third person instead of imperative tense
Sorry to be a bore and request review on all these docs fixes, this one is all in a single patch which makes it a bit harder to review. It is very similar in content to all the others that are open right now so I'm going to be a bit rude and leave it like this. Please say if this is even slightly putting too much demand on you review time.
> Improve docs: script module

- src/blockdata/transaction.rs
Do some cleanups to the docs in `blockdata::transaction`. Patch 1 needs the most careful review please. The rest should not be too controversial.
> Cleanup transaction docs

- src/blockdata/block.rs
Do some clean ups to the `blockdata::block` module.
- Patch 1: Change predicate names (API breaking, could be seen as unnecessarily changing the API), can remove if NACK'd
- Patch 2: Refactor to assist code clarity
- Patch 3 and 4: are docs improvements, shouldn't be too controversial
> Cleanup block module

- .github/workflows/rust.yml
- CONTRIBUTING.md
- contrib/test.sh
We currently build the docs as a separate CI job, we can however just do it as part of the `Tests` job using the nightly toolchain.
Conditionally build the docs based on a `DO_DOCS` env var.
Note, uses `--cfg docsrs` so can only be built run with nightly toolchain.
- Patch 1: Fixes the incorrect file naming `ci.sh` -> `test.sh` in `CONTRIBUTING.md`.
- Patch 2 - 4: Do trivial cleanup of `test.sh`.
- Patch 5: Does the fix described above.
Resolves: #850
> Build the docs with test.sh

- src/blockdata/opcodes.rs
Do some clean ups to the `blockdata::opcodes` module. Patch 3 is big but it should be quick to review because I made all the boring 'add full stops' changes in a single commit.
> Cleanup opcodes module

- src/hash_types.rs
Put the calls to `impl_hashencode` in the same order, and with the same
whitespace, as the calls to `hash_newtype`. This makes groking the file
easier because its quick to glance down the types and see which ones
implement hashencode (consensus_encode/decode) and which ones do not.
> Trivial: Order impl_hashencode lines

- src/util/misc.rs
In response to this comment: https://github.com/rust-bitcoin/rust-bitcoin/pull/819#discussion_r801477961
This should be straightforward. Let me know if there are any style issues. I tried to keep things similar to the existing test while cutting out any extra cruft to keep things small.
> test: Add a test for incorrect message signature in `is_signed_by_address`

- src/blockdata/script.rs
Originally this function was public (at least I was using it in downstream dependency in https://github.com/LNP-BP/descriptor-wallet). Now, in RC1, it became private. It is quite useful to detect witness scriptPubkeys.
> Make Script::witness_version public

- src/blockdata/transaction.rs
Fix up the logic that handles correctly returning the special array 1,0,0,...,0 for signature hash when the sighash single bug is exploitable i.e., when signing a transaction with SIGHASH_SINGLE for an input index that does not have a corresponding transaction output of the same index.
- Patch 1 and 2: Clean up
- Patch 3: Implements the fix
- Patch 4: Adds a passing test that fails if moved to before patch 3
Resolves: #817
> Fix signature hash returned for sighash single bug

- src/blockdata/opcodes.rs
Improve the rustdocs on the `ClassifyContext` enum by doing:
- Use link for `OP_RESERVED`
- Use term `OP_SUCCESSx` is done in BIP342 (no code link, does not exist in code).
- Use enum::variant form for both variant mentions
- Direct readers to BIP342 for full list of opcode re-names
> Improve ClassifyContext rustdocs

- src/blockdata/script.rs
- src/internal_macros.rs
- src/util/bip32.rs
This macro is no longer needed since we bumped MSRV to 1.29.
~We can implement `SliceIndex` to get the `Index` implementations.~
We can implement `core::ops::Index` directly since all the inner types implement `Index` already.
Original ~Idea shamelessly stolen from @elichai [in this comment](https://github.com/rust-bitcoin/rust-bitcoin/issues/352#issuecomment-560331856).~
New idea proposed by @Kixunil during review below. Thanks.
> Remove impl_index_newtype macro

- src/blockdata/transaction.rs
- src/internal_macros.rs
- src/util/sighash.rs
Implement Display/FromStr for SchnorrSigHashType
We currently implement `Display` and `FromStr` on `EcdsaSigHashType` and use them in the `serde_string_impl` macro to implement ser/de.
Mirror this logic in `SchnorrSigHashType`.
Patch 1 and 2 are preparatory patches for patch 3.
This PR has some conflicts with https://github.com/rust-bitcoin/rust-bitcoin/pull/898 but is pushing in the same direction, I'm happy to let 898 go in first and rebase on top.
> Improve `SchnorrSigHashType`

- src/blockdata/script.rs
This is the updated version of #874 (which I closed, force pushed, and then was unable to re-open - my bad).
Feature gating enum variants makes code that uses the library brittle while we do not have `non_exhaustive`, we should avoid doing so. Instead we can add a dummy type that is available when the feature is not turned on. Doing so enables the compiler to enforce that we do not create the error type that is feature gated when the feature is not enabled.
Remove the feature gating around `bitcoinconsensus` error enum variants.
Closes: #645
> Remove feature gated enum variants

- src/util/schnorr.rs
- src/util/taproot.rs
I think this is missing -- unless there is a reason not to have it?
> Add Serialize/Deserialize for TaprootSpendInfo

- src/blockdata/transaction.rs
- src/util/ecdsa.rs
- src/util/psbt/map/input.rs
- src/util/psbt/serialize.rs
- src/util/sighash.rs
This PR has evolved into a full blown clean up of the conversion methods for all three sighash types based on the discussion below.
Everything is split up into very small patches to aid review (and bikeshedding, this PR is almost totally just naming things).
EDIT: I'm not convinced this should be an RC-fix, the changes are too wide spread now. It started as just a single method rename. Leaving label as is for others to consider.
> Re-work sighash type conversion methods

- src/blockdata/transaction.rs
Post-merge #796 follow-up. Feel free to add other changes/nits which hadn't get into #796.
> Remove deprecated method use for sighash conversion

- src/util/psbt/map/output.rs
Implemented after @sanket1729 suggestion in https://github.com/rust-bitcoin/rust-bitcoin/issues/895#issuecomment-1074366108
Iterates all scripts present in TapTree in DFS order returning `(depth, script)` pairs.
I propose to have it as an RC fix since this functionality is really lacking and may be required for many wallets working with Taproot PSBT even outside of the scope where I originally needed it (OP_RETURN tweaks for TapTree described in #895)
> TapTree iterator 

- src/util/taproot.rs
Reported by @shesek. Users might find it convenient to manually construct the tree using `NodeInfo` API
```rust
let leaf1 = NodeInfo::from_leaf_with_ver();
let leaf2 = NodeInfo::from_leaf_with_ver();
let root = NodeInfo::combine(leaf1, leaf2);
let spend_info = TaprootSpendInfo::from_node_info(&secp, internal_key, root);
```
> Make NodeInfo API public

- src/blockdata/transaction.rs
- src/util/psbt/map/input.rs
- src/util/sighash.rs
The newly introduced `PsbtSigHashType` uses very different serde formatting from previously used `EcdsaSigHashType`; for instance it does not output human-readable sighash. This is especially obvious when printing out PSBT as JSON/YAML object and is a breaking change from the `0.27`. Serde human-readable implementation requires `Display/FromStr`, which were also absent.
> Make PsbtSigHashType use the same formatting as other *SigHashTypes

- CHANGELOG.md
- Cargo.toml
This does not include a changelog because rc.1 did not have changelog.
> Release 0.28.0-rc.2

- src/util/bip143.rs
We deprecated the `bip143::SigHashCache` in
```
commit 53d0e176d3c79c666cf75952f6f610fa37a105f5
Author: <elided>
Date:   Fri Jul 16 10:44:18 2021 +0200
Deprecate bip143::SigHashCache in favor of sighash::SigHashCache
...
```
This means these changes are unreleased so the deprecated since version
should be the upcoming 0.28 release.
> Fix deprecated since version

- src/util/taproot.rs
I should have done this PR a month ago, my bad. This one is kind of important IMO because we are going to have so many people looking at this part of the code soon as we release.
As has been done in other places in the codebase; improve the docs in the `taproot` module by doing:
- Use full sentences (capital letters + full stops)
- Use back ticks and links for types where appropriate
- Fix grammar
- Fix stale docs
- Use third person for describing functions
- Use 100 character line width
- Use markdown sections (`# Examples`, `# Returns`) where appropriate
- Separate brief heading from extended description when appropriate
- Use `///` for all functions/types (both private and public)
I also did:
- Build the docs and check all the links
- Read all the built docs, check for sanity and …
> Improve docs in taproot module

- src/util/psbt/serialize.rs
- src/util/taproot.rs
There is an inconsistency in depth type: some places uses `u8` (which is reasonable, since the depth can't be >127), others use `usize`. This PR makes API consistent.
I think this should be a RC fix, since it affects newly introduced API in this release and it will be bad to make a breaking changes the next version after its introduction.
> Require taproot tree depth argument always to be u8

- src/util/taproot.rs
See to nits from review of https://github.com/rust-bitcoin/rust-bitcoin/pull/912
Three minor patches to the `taproot` module docs.
CC @dr-orlovsky
> Taproot docs nits

- src/blockdata/script.rs
**Issue** 
I can not use [`XOnlyPublicKey`](https://github.com/rust-bitcoin/rust-secp256k1/blob/ae985dd1911183c22bab9c9a199aca7b154c40f9/src/key.rs#L973) in my Scripts which prevents me from working with Taproot.
**Cause** 
The current version of [`script::Builder`](https://github.com/rust-bitcoin/rust-bitcoin/blob/0a2d45de094c4c0a4861dc19314568684ac4d91c/src/blockdata/script.rs#L121) does not accept `XOnlyPublicKey`s.
**Solution**
So, I created a function `push_xkey(self, key: &XOnlyPublicKey)` based on the existing [`push_key`](https://github.com/rust-bitcoin/rust-bitcoin/blob/0a2d45de094c4c0a4861dc19314568684ac4d91c/src/blockdata/script.rs#L914) function. I also augmented an [existing test](https://github.com/rust-bitcoin/rust-bitcoin/blob/0a2d45de094c4c0a4861dc19314568684ac4d91c/src/bl …
> Push key xonly

- src/blockdata/transaction.rs
- src/hash_types.rs
- src/lib.rs
- src/util/bip143.rs
- src/util/ecdsa.rs
- src/util/psbt/error.rs
- src/util/psbt/map/input.rs
- src/util/psbt/map/mod.rs
- src/util/psbt/mod.rs
- src/util/psbt/serialize.rs
- src/util/schnorr.rs
- src/util/sighash.rs
Our usage of `SigHash` implies that 'sighash' is _two_ words; 'sighash' is a well known word in the Bitcoin ecosystem it should appear in identifiers as `Sighash`.
Change various types, variants, and code comments to use sighash as a single word. 
- Patches 1-8 are code changes `s/SigHash/Sighash/g`
- Patch 9 is code changes `s/sig_hash/sighash/g`
- Patch 11 is docs fixes
Fixes: #911
I've been particularly pedantic with the patch separation because we are so close to release.
Done as separate patches to make review easier if review is to be done by reading the diffs. Perhaps at least one person could verify this PR programmatically by doing
- Reset the last 2 patches (those are easy to do manually)
- Check out master
- Do `s/SigHash/Sighash/g` on all source files (bash function below)
- …
> Rename SigHash to Sighash

- src/util/psbt/map/input.rs
- src/util/psbt/map/output.rs
- src/util/psbt/mod.rs
> Derive Eq for PSBT types

- src/util/psbt/map/input.rs
We have a deprecated function call because of the MSRV, tell clippy to ignore it.
> Allow deprecated function call

- src/util/psbt/map/output.rs
- src/util/psbt/serialize.rs
- src/util/taproot.rs
This PR makes existing taproot script iterator to iterate `LeafScript` values instead of constructed `(u8, &Script)`. First, this is more idiomatic (iterator should not construct value but iterate through real internal representation); second information about merkle path of the scripts is required for me downstream to implement OP_RETURN taproot commitments.
The PR also removes unnecessary iterator type, replacing it with a slice iterator type from the core rust library.
I am asking to include this PR into RC fix scope, since it is required downstream.
> Improvements to taproot script iterator

- CONTRIBUTING.md
- README.md
This warns contributors about possible rebases. Changing CONTRIBUTING
should ensure that GitHub will display special warning. This will be
removed after migration is done.
See also https://github.com/rust-bitcoin/rust-bitcoin/discussions/945
> Add temporary warning about edition change

- src/util/psbt/serialize.rs
Trees should only be serialized if both of the following conditions
hold:
1) Tree is complete binary tree(is_finalized)
2) Tree does not have any hidden nodes
> Fix TapTree derserialization

- src/network/message.rs
- src/network/message_network.rs
[BIP-61 defines `response-to-msg`][bip61] (`Reject::message` in rust-bitcoin; the message that triggered the reject) to be a `var_str`. However, by using the `CommandString` it was (de)serialized as 12 byte string. A test is added that de- and serializes two reject messages received from an older Bitcoin Core peer.
Reject message sending has been removed from Bitcoin Core, I'm still receiving them from older peers from time to time.
[bip61]: https://github.com/bitcoin/bips/blob/master/bip-0061.mediawiki#common-payload
gh-ref: https://github.com/rust-bitcoin/rust-bitcoin/pull/323
> fix: reject message (de)serialization 

- src/blockdata/script.rs
In order to sign a utxo that does a p2wpkh spend we need to create the
script that can be used to create a sighash. In the libbitcoin docs this
is referred to as the 'script code' [0] (also described in BIP143)
The script is the same as a p2pkh script but the pubkey_hash is found in
the scriptPubkey.
Add a `Script` conversion method that checks if `self` is a v0 p2wpkh
script and if so extracts the pubkey_hash and returns the required
script.
Includes a link to BIP143
[0] https://github.com/libbitcoin/libbitcoin-system/wiki/P2WPKH-Transactions#spending-a-p2wpkh-output
> Add Script conversion method p2wpkh_script_code

- src/util/key.rs
We can bring the `Write` trait into scope, no need to underscore it.
Done as part of the MSRV checklist.
> Remove unnecessary `Write as _fmtWrite`

- .github/workflows/rust.yml
- contrib/test.sh
We no longer need to test against Rust 1.29 now that v0.28 is out. In order to allow minor changes to be merged (i.e., not the _big_ MSRV patchset) that rely on MSRV being 1.41.1 update the CI pipeline.
Remove the pinning stuff from `contrib/test.sh` while we are at it.
> Remove 1.29 checks from CI pipeline

- src/util/amount.rs
Currently unmergable because of MSRV but I heard talk about bumping it, so once it's bumped, this is a very much needed change :)
> util::amount: Make from_sat constructor constant

- src/util/psbt/error.rs
- src/util/psbt/mod.rs
The API returns a vector of UTXOs and has return type `Result<Vec<&TxOut>, Error>`
The return statement should be of type `sighash::Prevouts` as pointed in #849
> API to find funding utxos in psbt

- src/blockdata/opcodes.rs
- src/blockdata/transaction.rs
- src/util/psbt/map/input.rs
- src/util/taproot.rs
Now that 0.28 is out we do not need to support Rust 1.29 on `master`.
Remove trivial MSRV `TODO`s from the code. (All these changes only rely on MSRV bumping to 1.31 so are easily within bounds.)
> Remove MSRV todo comments

- Cargo.toml
- src/blockdata/script.rs
- src/internal_macros.rs
With this patch, existing users of the `use-serde` feature will no longer be
compiling with `serde/std` enabled, but this allows dependent projects
to import serde and enable `serde/alloc` as required by some no-std targets.
> Disable Serde's default-features

- src/blockdata/script.rs
This refactors `blockdata::script::Instructions` to use
`::core::slice::Iter<'a, u8>` instead of `&'a [u8]` to better express
the intention and to avoid some slicing mistakes. Similarly to a
previous change this uses a macro to deduplicate the common logic and
the new `read_uint_iter` internal function to automatically advance the
iterator.
Addresses:
https://github.com/rust-bitcoin/rust-bitcoin/pull/662#pullrequestreview-768320603
> Use iterator in `blockdata::script::Instructions`

- src/util/amount.rs
This significatnly refactors the formatting code to make formatting more
configurable. The main addition is the `Display` type which is a
builder that can configure denomination or other things (possibly more
in the future).
Further, this makes all representations of numbers minimal by default,
so should be documented as a possibly-breaking change.
Because of the effort to support all other `fmt::Formatter` options this
required practically complete rewrite of `fmt_satoshi_in`. As a
byproduct I took the opportunity of removing one allocation from there.
Closes #709
> Add `amount::Display` - make formatting configurable

- README.md
These are no longer relevant for MSRV 1.41.1+
> Remove irrelevant notes about version pinning

- .gitignore
- Cargo.toml
- README.md
- src/util/bip32.rs
> [backport] Fix `no_std` MSRV

- src/util/address.rs
Hi, thanks for the amazing work on this crate.
I am trying to upgrade from v0.27 to v0.28, but unable to do so because the `Address::get_payload_bytes` was made private. My use-case is that I have a script hash address and an `Address` and need to compare the two, and in order to do so I need access to the payload bytes of `Address`.
I hope you will consider making this function public again 🙏
> Make Address::get_payload_bytes public

- src/util/ecdsa.rs
- src/util/psbt/map/output.rs
Do a couple of trivial docs fixes, done during other work.
- Patch 1 improves docs on the `EcdsaSig` struct
- Patch 2 clears a clippy warning during docs build - no sure if the solution is the best available though
> Trival docs fixes

- src/util/taproot.rs
Since commit `commit 275adc6c335a4326699cfbd444949e1725864ea1` on `bitcoin_hashes` we have the identical implementation of the macro `sha256t1_hash_newtype` in this crate and in `bitcoin_hashes`.
Remove the `sha256t_hash_newtype` macro from this crate in favour of the one in `bitcoin_hashes`.
> Remove sha256t_hash_newtype macro

- src/util/psbt/error.rs
- src/util/psbt/mod.rs
before
```
print-type-size type: `util::psbt::error::Error`: 120 bytes, alignment: 8 bytes
print-type-size     discriminant: 1 bytes
print-type-size     variant `CombineInconsistentKeySources`: 115 bytes
print-type-size         padding: 3 bytes
print-type-size         field `.0`: 112 bytes, alignment: 4 bytes
print-type-size     variant `InvalidKey`: 39 bytes
print-type-size         padding: 7 bytes
print-type-size         field `.0`: 32 bytes, alignment: 8 bytes
```
after
```
print-type-size type: `util::psbt::error::Error`: 40 bytes, alignment: 8 bytes
print-type-size     discriminant: 1 bytes
print-type-size     variant `InvalidKey`: 39 bytes
print-type-size         padding: 7 bytes
print-type-size         field `.0`: 32 bytes, alignment: 8 bytes
print-type-size     variant …
```
> Box value encoded in a variant to reduce enum stack space

- src/blockdata/block.rs
- src/blockdata/script.rs
- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/network/message.rs
- src/network/mod.rs
- src/util/address.rs
- src/util/amount.rs
- src/util/base58.rs
- src/util/bip158.rs
- src/util/bip32.rs
- src/util/ecdsa.rs
- src/util/key.rs
- src/util/misc.rs
- src/util/mod.rs
- src/util/psbt/error.rs
- src/util/psbt/map/output.rs
- src/util/psbt/mod.rs
- src/util/schnorr.rs
- src/util/sighash.rs
- src/util/taproot.rs
- src/util/uint.rs
Now that we have MSRV of 1.41.1 we should use `source` instead of `cause`. Audit the whole codebase and implement `source` for _every_ error type we have.
The first three patches are preparatory cleanup, patch 3 is particularly shameful (adds parenthesis to make my editor work).
CC @Kixunil because he is championing the error stuff.
> Implement `std::error::Error` for the new MSRV

- src/network/address.rs
Refactor address byte swapping
When encoding a `network::Address` two of the fields are encoded
big-endian instead of little-endian as is done by `consensus_encode`. In
order to achieve this we have a helper function `addr_to_be` that swaps
the bytes. This function is miss-named because it is not converting to a
specific endian-ness (which implies different behaviour on machines with
different endian-ness) but is reversing the byte order irrespective of
the underlying architecture.
- Remove function `addr_to_be`
- Inline the endian-ness code when encoding an address
- Remove TODO and use `to_be_bytes` when encoding port
- Add a function for reading big-endian bytes `read_be_address`
- Use `read_be_address` when decoding `Address` and `Addrv2`
Refactor only, no logic changes. Code path is …
> Refactor address byte swapping

- Cargo.toml
We do not need to pin the `ryu` transitive dependency now that MSRV is not 1.29.
> Do not pin transitive ryu dependency

- src/util/amount.rs
Currently we allow multiple trailing colons when matching within the
`check_format_non_negative` macro. We can be more restrictive with no
loss of usability.
Use `$(;)?` instead of `$(;)*` to match against 0 or 1 semi-colons
instead of 0 or more.
Done as part of the [edition 2018 checklist](https://github.com/rust-bitcoin/rust-bitcoin/issues/510).
> Match against an optional single trailing colon

- src/blockdata/script.rs
- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/internal_macros.rs
- src/network/message.rs
As things are right now, memory exhaustion protection in `Decodable`
is based on checking input-decoded lengths against arbitrary limits,
and ad-hoc wrapping collection deserialization in `Take`.
The problem with that are two-fold:
* Potential consensus bugs due to incorrect limits.
* Performance degradation when decoding nested structured,
due to recursive `Take<Take<..>>` readers.
This change introduces a systematic approach to the problem.
A concept of a "size-limited-reader" is introduced to rely on
the input data to finish at enforced limit and fail deserialization.
Memory exhaustion protection is now achived by capping allocations
to reasonable values, yet allowing the underlying collections
to grow to accomodate rare yet legitmately oversized data (with tiny
performance cost), and …
> Add `consensus_decode_from_finite_reader` optimization

- src/blockdata/block.rs
- src/blockdata/script.rs
- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/network/mod.rs
- src/util/address.rs
- src/util/amount.rs
- src/util/base58.rs
- src/util/bip32.rs
- src/util/ecdsa.rs
- src/util/key.rs
- src/util/misc.rs
- src/util/mod.rs
- src/util/psbt/error.rs
- src/util/psbt/map/output.rs
- src/util/psbt/mod.rs
- src/util/schnorr.rs
- src/util/sighash.rs
- src/util/taproot.rs
Adding an error variant to a public enum is an API breaking change, this means making, what could be, small refactorings or improvements harder. If we use `non_exhaustive` for error types then we mitigate this cost.
There is a tradeoff however, downstream users who explicitly match on our public error types must include a wildcard pattern.
> Add non_exhaustive to all error enums

- src/util/address.rs
Adds a check in `Address::from_script()` that checks if segwit v0 scripts have a valid length.
Fix: #995
> Enforce segwit v0 script validity when creating address.

- Cargo.toml
Now that we have MSRV 1.41.1 we can use the more modern `base64` instead of the compat crate. Requires no changes other than changing the dependency.
> Replace base64-compat dependency

- src/blockdata/constants.rs
- src/internal_macros.rs
The Lightning network defines a type called 'chain hash' that is used to uniquely represent the various Bitcoin networks as a 32 byte hash value. Chain hash is now being used by the DLC folks, as such it is useful to have it implemented in rust-bitcoin.
One method of calculating a chain hash is by hashing the genesis block for the respective network.
Add a `ChainHash` type that can be used to get the unique identifier of each of the 4 Bitcoin networks we support. Add a method that calculates the chain hash for a network using the double sha256 of the genesis block. Do so using hard coded consts and add unit tests (regression/sanity) that show these hard coded byte arrays match the hash of the data we return for the genesis block for the respective network.
The chain hash for the main …
> Add chain hash type using consts

- Cargo.toml
- contrib/test.sh
- src/blockdata/block.rs
- src/blockdata/transaction.rs
- src/lib.rs
- src/serde_utils.rs
- src/util/amount.rs
- src/util/ecdsa.rs
- src/util/psbt/map/input.rs
- src/util/psbt/map/output.rs
- src/util/psbt/mod.rs
- src/util/psbt/raw.rs
- src/util/schnorr.rs
- src/util/taproot.rs
Features activating external crates are supposed to have same name as
those crates. However we depend on same feature in other crates so we
need a separate feature. After MSRV bump it is possible to rename the
crates and features so we can now fix this inconsistency.
Sadly, derive can't see that the crate was renamed so all derives must
be told to use the other one.
Replaces #373
> Feature `use-serde` renamed to `serde`

- src/blockdata/script.rs
- src/blockdata/transaction.rs
- src/consensus/encode.rs
- src/internal_macros.rs
- src/network/mod.rs
- src/util/address.rs
- src/util/base58.rs
- src/util/bip158.rs
- src/util/bip32.rs
- src/util/ecdsa.rs
- src/util/key.rs
- src/util/misc.rs
- src/util/mod.rs
- src/util/psbt/error.rs
- src/util/psbt/mod.rs
- src/util/schnorr.rs
- src/util/sighash.rs
- src/util/taproot.rs
As part of the ongoing error improvement work and as a direct result of [this comment](https://github.com/rust-bitcoin/rust-bitcoin/pull/987#issuecomment-1135563287) improve the `Display` implementations of all our error types so as to not repeat the source error when printing.
The first 5 patches are trivial clean ups around the errors. Patch 6 is the real work.
EDIT: ~CC @Kixunil, have I got the right idea here bro?~ Patch 6 now includes a macro as suggested.
> Improve error `Display` implementations

- src/util/address.rs
Add non_exhaustive compiler directive to AddressType
Currently adding variants to enums is a breaking change. In an effort to
reduce the upgrade burden on users we can use the `non_exhaustive`
compiler directive so that adding a new variant does not cause
downstream code to break.
Add `non_exhaustive` to the `AddressType` since it may be extended in
the future.
> Add non_exhaustive compiler directive to `AddressType`

- src/network/mod.rs
- src/util/mod.rs
The `network::Error` is not used, remove it.
(This description has been changed, the thumbs up emojis were put on the previous PR description.)
> Remove network::Error

- src/blockdata/script.rs
Hehe, reason for party, let's invite apoelstra !
> Avoid allocation in build_scriptint

- src/hash_types.rs
Fix #958
I hope putting it on the most notorious type where people actually notice it is enough. I couldn't find a good way to put it on all other `sha256d` automatically, and copy pasting it seems not worth it.
> Document `Txid` being displayed backwards

- src/blockdata/block.rs
- src/blockdata/script.rs
- src/blockdata/transaction.rs
- src/network/message.rs
- src/network/message_network.rs
- src/network/stream_reader.rs
- src/util/address.rs
- src/util/amount.rs
- src/util/base58.rs
- src/util/bip143.rs
- src/util/bip158.rs
- src/util/key.rs
- src/util/psbt/map/input.rs
- src/util/psbt/mod.rs
- src/util/psbt/serialize.rs
- src/util/sighash.rs
- src/util/taproot.rs
Clear all the clippy warnings (excl. #1042) that are returned by running `cargo clippy --all-targets`. 
I apologize in advance for the review burden :)
> Clear clippy warnings from `--all-targets`

- fuzz/fuzz_targets/deserialize_script.rs
- src/util/address.rs
Modify from_script functions to return result instead of option so that, in case of errors, there is more
information on what went wrong.
Resolves: #1022
> Modify from_script functions in address.rs to return result

- src/util/address.rs
> Fix incorrect argument passed to Error::InvalidSegwitV0ProgramLength and add test

- src/network/stream_reader.rs
Done while clearing clippy warnings, done as a separate PR because its not a simple glance to review like the others.
Remove 2 clippy warnings and remove unnecessary local variable.
> Refactor `serve_tcp` code

- src/blockdata/witness.rs
close https://github.com/rust-bitcoin/rust-bitcoin/issues/1050
I don't think we need to change the `collect` since it use the `size_hint()` lower bound to initially allocate
// with size_hint
// test blockdata::witness::benches::bench_big_witness_to_vec              ... bench:         313 ns/iter (+/- 13)
// test blockdata::witness::benches::bench_witness_to_vec                  ... bench:         204 ns/iter (+/- 11)
// without
// test blockdata::witness::benches::bench_big_witness_to_vec              ... bench:         489 ns/iter (+/- 28)
// test blockdata::witness::benches::bench_witness_to_vec                  ... bench:         221 ns/iter (+/- 102)
The reason why the small witness doesn't get big perf boost is because by default vec allocates 4 slots
> Implement iter::size_hint and ExactSizeIterator for Witness Iter

- src/consensus/encode.rs
- src/internal_macros.rs
- src/util/endian.rs
Add a macro `const_assert` that uses some const declaration trickery to trigger a compile time error if a boolean expression is false.
Replace runtime checks using `debug_assert_eq!` with the newly defined `const_asert!` macro.
This PR is the first patch from a [recently closed PR](https://github.com/rust-bitcoin/rust-bitcoin/pull/953). Props to @elichai for the macro idea in the review of that PR.
> Replace runtime size check with compile time check

- README.md
- contrib/test.sh
- src/lib.rs
The docs lint `broken-intra-doc-links` has been changed but the new name
is not available in our MSRV, this means we get a build warning. We only
build docs with the nightly toolchain so we can move this lint control
to the docs build command in `test.sh` instead of doing it crate wide.
With this patch applied devs risk not noticing docs link issues until
they hit them on CI _if_ they do not build with the test script or
explicitly pass in `-- -D rustdoc::broken-intra-doc-links`, which no one
is going to do. Hence we add a line to the readme with a shell alias
that can be used to check docs, taken directly from `test.sh`.
> Move broken-intra-doc-link lint config to command line

- src/blockdata/opcodes.rs
In general, if a function can be const, it should be, and this one
trivially can be, so it should be.
> Make `opcode::to_u8` a const function

- src/blockdata/script.rs
- src/util/address.rs
- src/util/psbt/map/global.rs
- src/util/psbt/map/input.rs
- src/util/psbt/map/output.rs
- src/util/psbt/raw.rs
- src/util/psbt/serialize.rs
- src/util/schnorr.rs
- src/util/sighash.rs
- src/util/taproot.rs
Audit the whole codebase checking for any method that is of the form `from_foo` where foo is not an interesting identifier (like 'consensus' and 'standard'). Implement `TryFrom` for any such methods, deprecating the original.
Done as separate patches so any can be easily dropped if not liked.
> Implement TryFrom

- src/blockdata/script.rs
- src/blockdata/transaction.rs
- src/blockdata/witness.rs
- src/consensus/encode.rs
- src/hash_types.rs
- src/internal_macros.rs
- src/network/address.rs
- src/network/constants.rs
- src/network/message.rs
- src/network/message_blockdata.rs
- src/network/message_bloom.rs
- src/network/message_network.rs
- src/util/merkleblock.rs
- src/util/psbt/macros.rs
- src/util/psbt/map/global.rs
- src/util/psbt/map/mod.rs
- src/util/psbt/mod.rs
- src/util/psbt/raw.rs
- src/util/sighash.rs
- src/util/uint.rs
Fix #1020 (see more relevant discussion there)
This definitely makes the amount of generics compiler
has to generate by avoding generating the same functions
for `R`, `&mut R`, `&mut &mut R` and so on.
old:
```
> ls -al target/release/deps/bitcoin-07a9dabf1f3e0266
-rwxrwxr-x 1 dpc dpc 9947832 Jun  2 22:42 target/release/deps/bitcoin-07a9dabf1f3e0266
> strip target/release/deps/bitcoin-07a9dabf1f3e0266
> ls -al target/release/deps/bitcoin-07a9dabf1f3e0266
-rwxrwxr-x 1 dpc dpc 4463024 Jun  2 22:46 target/release/deps/bitcoin-07a9dabf1f3e0266
```
new:
```
> ls -al target/release/deps/bitcoin-07a9dabf1f3e0266
-rwxrwxr-x 1 dpc dpc 9866800 Jun  2 22:44 target/release/deps/bitcoin-07a9dabf1f3e0266
> strip target/release/deps/bitcoin-07a9dabf1f3e0266
> ls -al …
```
> Take Writer/Reader by `&mut` in consensus en/decoding

- src/blockdata/script.rs
Last release, before we had access to `non_exhaustive` we added some fancy types to enable conditionally having a `bitcoinconsensus::Error`. 
Now that we have bumped the MSRV and have already added `non_exhaustive` to the `Error` type in question, we can use a compiler attribute to conditionally include the `bitcoinconsensus` error.
Remove `Uninhabited` and its usage.
For more context see the [original attempt ](https://github.com/rust-bitcoin/rust-bitcoin/pull/1025)at using `Infallible` (last comment in discussion thread).
> Remove Uninhabited

- src/blockdata/script.rs
- src/consensus/encode.rs
- src/internal_macros.rs
- src/util/address.rs
- src/util/amount.rs
- src/util/uint.rs
Currently we are using the fragment-specifier `expr` in a bunch of
macros for captures that are only used for literals. If we use `literal`
instead it allows the compiler to give slightly more specific error
messages.
The benefits of this change are minor. Of note, this patch found one
unusual macro call site (removed unnecessary `&`).
The macros changed are all internal macros, this is not a breaking change.
> Use fragment-specifier literal

- src/internal_macros.rs
We somehow have two lifetimes that are unused and causing clippy warnings, remove them.
This fixes the red CI runs on a bunch of other open PRs. FTR I have no idea how these got past clippy onto master.
> Remove unused lifetimes

- src/blockdata/constants.rs
- src/blockdata/script.rs
We have a bunch of calls to `format!("{:x}", foo)` for types that implement `ToHex`. The code is terser with no loss of clarity if we use the trait method and call `to_hex()`.
> Use `to_hex` when available

- src/util/address.rs
Adds a custom error `UnknownAddressType(_)` which is returned in cases where an unknown address type tries to be parsed via
`FromStr`. This provides more context for the error, since it contains the `String` that tried to be parsed.
Closes https://github.com/rust-bitcoin/rust-bitcoin/issues/1064
> Add custom error for invalid parsing of address types

- Cargo.toml
- src/consensus/encode.rs
- src/util/bip32.rs
- src/util/merkleblock.rs
- src/util/schnorr.rs
- src/util/sighash.rs
- src/util/taproot.rs
We recently released a new version of `rust-secp256k1`, upgrade to use it.
> Upgrade to secp256k1 v0.23.0

- src/lib.rs
Now that we have an MSRV of 1.41.1 we no longer need `extern crate core`, remove it.
> Remove extern crate core statement

- src/util/key.rs
Replaces #524 
See previous PR for reasoning.
This solution is a little more straightforward. The name and documentation should be enough to prevent misuse.
We can also impl a to_sort_key for any CompressedKey added later. (or just impl Ord in a BIP67 compliant way)
TODO:
> Add PublicKey::to_sort_key method for use with sorting by key

- Cargo.toml
- src/blockdata/block.rs
- src/blockdata/constants.rs
- src/blockdata/transaction.rs
- src/hash_types.rs
- src/network/message_blockdata.rs
- src/util/address.rs
- src/util/hash.rs
- src/util/merkleblock.rs
- src/util/psbt/serialize.rs
- src/util/sighash.rs
We just released a new version of `bitcoin_hashes`, upgrade the dependency to v0.11.0
> Upgrade `bitcoin_hashes` dependency

- src/util/amount.rs
The `ParseAmountError` does not implement `std::error::Error`, must have been missed when we did the rest.
Implement `std::error::Error` for `ParseAmount`.
> Implement std::error::Error for ParseAmount

- README.md
The READEME claims rust-bitcoin supports PSBT finalization, but really needs rust-miniscript for that. I think we should make this clear in this crate's PSBT examples as well.
> > Understanding scripts and witnesses doesn't scream rust-miniscript to me. Miniscript crate is not the first place I'd look, since it's additional.
> 
> We should probably add it to the README here or something. If I needed to deal with scripts or witnesses in any way beyond reserializing them or hashing scriptpubkeys into addresses, I'd immediately turn to Miniscript. You basically can't work on scripts without it, unless you are doing something very specific.
> 
> >Anywhere there's PSBT code I expect a finalizer, even if it had documented limitations.
> 
> Not to be too glib, but suppose we had a finalizer that …
> Document PSBT roles and limitation

- src/blockdata/transaction.rs
- src/util/ecdsa.rs
- src/util/psbt/map/input.rs
- src/util/psbt/map/output.rs
- src/util/psbt/mod.rs
- src/util/schnorr.rs
In preparation for being able to derive `Hash` on all types in `miniscript`, derive `Hash` on all of the required types.
This PR includes all the changes in https://github.com/rust-bitcoin/rust-bitcoin/pull/933/files and hence supersedes it.
ref: https://github.com/rust-bitcoin/rust-miniscript/issues/226
> Derive Hash on a bunch of types

- Cargo.toml
- README.md
- contrib/test.sh
- src/blockdata/block.rs
- src/blockdata/transaction.rs
- src/blockdata/witness.rs
- src/lib.rs
Currently we are unable to build with all features enabled with a non-nightly toolchain, this is because of the use of
`#![cfg_attr(all(test, feature = "unstable"), feature(test))]`
which causes the following error when building:
error[E0554]: `#![feature]` may not be used on the stable release channel
The "unstable" feature is used to guard bench mark modules, this is widely suggested online but there is a better way.
When running the bench marks use the following incantation:
`RUSTFLAGS='--cfg=bench' cargo bench`
This creates a configuration conditional "bench" that can be used to guard the bench mark modules.
```
#[cfg(bench)]
mod benches {
...
}
```
> Create configuration conditional "bench"

- src/blockdata/constants.rs
- src/blockdata/transaction.rs
- src/lib.rs
- src/util/psbt/mod.rs
#1082
Created a new type for txin sequence field with methods to create sequences with relative time locks from block height or time units.
> Add new type for sequence

- src/blockdata/witness.rs
This is dr-orlovsky's [PR](https://github.com/rust-bitcoin/rust-bitcoin/pull/899) picked up at his permission in the discussion thread.
I went through the review comments and implemented everything except the perf optimisations. Also includes a patch at the front of the PR that adds a unit test that can be run to see the "before and after", not sure if we want it in, perhaps it should be removed before merge.
This PR implicitly fixes 942.
To test this PR works as advertised run `cargo test display_transaction --features=serde -- --nocapture` after creating a unit test as follows: 
```rust
// Used to verify that parts of a transaction pretty print.
// `cargo test display_transaction --features=serde -- --nocapture`
#[cfg(feature = "serde")]
#[test]
fn serde_display_transaction() {
let …
```
> Implement human-readable serde for `Witness`

- README.md
Removed in https://github.com/rust-bitcoin/rust-bitcoin/pull/871
> Remove the Pay-to-Contract reference from README.

- Cargo.toml
- contrib/test.sh
- examples/ecdsa-psbt.rs
Add an example PSBT workflow. The workflow we simulate is that of a setup using a watch-only online wallet (contains only public keys) and a cold-storage wallet (contains the private keys).
We create and update a PSBT using the watch-only wallet then pass the PSBT to the cold-storage wallet to sign.
Partially resolves #892 (more done in #935).
This PR includes a sub-module in `examples/psbt.rs` that implements ECDSA signing. This will hopefully eventually be merged into the main crate by way of https://github.com/rust-bitcoin/rust-bitcoin/pull/957.  We have three PRs that add examples/tests of PSBTs that need to do signing, in order to help us design a good AP in #957 I think it would be beneficial to complete and merge these three PRs.
1. This PR (PSBT ECDSA example)
2. PBST ECDSA …
> Add psbt watch-only/cold-storage example

- examples/bip32.rs
- examples/handshake.rs
- rustfmt.toml
- src/hash_types.rs
- src/internal_macros.rs
- src/lib.rs
- src/policy.rs
- src/serde_utils.rs
Looks like we are getting to a place that rustfmt _might_ be able to be used. In an effort to introduce `rustfmt` without requiring devs to do excessively mundane reviews introduce `rustfmt` in a non-invasive manner. What this means is
- Add a fully fleshed out `rustfmt` config file that explicitly ignores all the source files
- Enable sections of code one by one so review is easier (including preparatory patches before doing each section). 
This PR currently does `examples` and all the source files at the root level of the crate (i.e. excludes all directories in `src/`). The other directories can then be done one at a time. 
Please see discussion on: https://github.com/rust-bitcoin/rust-bitcoin/pull/959 for more context.
> Introduce rustfmt in a non-invasive manner

- README.md
As suggested by the `cargo-crev` project; add a comment to the readme reminding people to use `cargo-crev` to check their dependencies.
Today I explored `cargo-crev`, it was new to me before today. I completed proofs for `bech32`, `rust-bitcoinconsenus`, `bitcoin_hashes`, `rust-secp256k1`, and `rust-bitcoin`. I published the proofs to https://github.com/tcharding/crev-proofs.
If I'm understanding correctly proofs are only useful if the author is connected to a web of trust. So far I only found @dpc within the active rust-bitcoin devs with a `crev-proofs` repo (that includes an ID). Since he wrote `cargo-crev` its not surprising he has one :) Two other devs have `crev-proofs` repos but they are both incomplete (no ID) so I was unable to climb onto their web, so to speak. I am not a …
> Add cargo crev reminder to readme

- Cargo.toml
- src/util/misc.rs
- src/util/sighash.rs
- src/util/taproot.rs
Replaces all instances of `secp256k1::Message::from_slice(_).expect(_)` with `secp256k1::Message::from(_)`. This also implements `ThirtyTwoByteHash` for `TapSighashHash`.
Closes https://github.com/rust-bitcoin/rust-bitcoin/issues/824
> Use infallible conversions: `Hash` -> `secp256k1::Message`

- src/network/stream_reader.rs
During test network simulation we only accept a single connection, we can simplify the code by using `accept`.
Done as a follow up to review suggestion:
https://github.com/rust-bitcoin/rust-bitcoin/pull/1042#discussion_r898013799
> Use `listener.accept()`

- contrib/test.sh
Add a call to `cargo tree --duplicates` in the ci script to ensure that we do not have any duplicated dependencies.
Kudos to Kixunil  for the idea (over in: https://github.com/rust-bitcoin/rust-bitcoin/pull/1104)
> Add ci check for duplicate dependencies

- src/util/taproot.rs
Currently we use a cast to get the `u8` depth, as suggested by the TODO in the code we can now use `TryFrom` since we bumped the MSRV.
Use `u8::try_from.expect("")` since depth (node count) is guarded by `TAPROOT_CONTROL_MAX_NODE_COUNT`.
> Use `u8::try_from`

- src/util/amount.rs
After auditing the code base for 'msrv' the only remaining mention (excl. md files) is on `unsigned_abs`.
Add docs to save the next guy looking up what version of Rust introduced `unsigned_abs`. (I also added an item to the [msrv tracking issue](https://github.com/rust-bitcoin/rust-bitcoin/issues/1060).)
> Add docs re Rust 1.51.1

- src/network/address.rs
Now that MSRV is > 1.32 we can use `u16::to_be_bytes` to ensure network byte order when encoding the port number of a `AddrV2Message`.
Remove the TODO and use `to_be_bytes` as suggested.
> Use `u16::to_be_bytes`

- .github/workflows/rust.yml
- contrib/test.sh
- src/util/amount.rs
- src/util/key.rs
- src/util/misc.rs
- src/util/psbt/mod.rs
Currently we run clippy in CI using a github action. The invocation has a couple of shortcomings
1. it does not lint the tests (this requires `--all-targets`)
2. it does not lint the examples
I could not find a way to lint the examples without explicitly linting each example by name.
**This PR does the following:**
- Fix clippy issues (patch 1-4)
- Move the clippy control to `test.sh`
- Add an env var `DO_LINT` to control it
- Remove the separate CI job
- Run the linter during the `Test` job using the stable toolchain.
- Run clippy with ` --all-features` AND `--all-targets` (only recently made possible).
- Run each example explicitly
Thanks to dunxen for noticing all the errors in my psbt example on review and prompting me to work out why clippy was not running :)
> Run clippy from the test script

- CONTRIBUTING.md
- README.md
We have stale docs referring to the old MSRV. We do not need MSRV docs
in `CONTRIBUTING` because we have them in the README already.
Fix stale docs by doing:
- Remove the MSRV docs from readme in favour of `CONTRIBUTING.md`.
- Add a sentence to the redame pointing readers towards `CONTRIBUTING.md`.
- Point readers towards `RUSTUP_TOOLCHAIN`
> Remove stale MSRV docs

- examples/ecdsa-psbt.rs
- src/blockdata/constants.rs
- src/blockdata/locktime.rs
- src/blockdata/mod.rs
- src/blockdata/transaction.rs
- src/lib.rs
- src/util/bip143.rs
- src/util/bip152.rs
- src/util/psbt/mod.rs
- src/util/sighash.rs
Implement a `LockTime` type that adds support for lock time values based on nLockTime and OP_CHECKLOCKTIMEVERIFY.
For example usage in `rust-miniscript` please see https://github.com/rust-bitcoin/rust-miniscript/pull/408.
I probably should have opened a new PR, this is a total re-write and very different from what is being discussed below, sorry, my bad.
This is just half of the 'timelock' story, its the easier half. The reason I switched terminology from timelock to locktime is that we have to compare two u32s so it does not make sense to call them _both_ timelocks.
If I have missed, or apparently ignored, anything you said reviewers please accept my apology in advance, it was not intentional. The thread of discussion is long and this topic is complex. Please do restate your views …
> Add a `LockTime` type

- Cargo.toml
Recently `rust-bech32` v0.9.0 was released, this release included
updating the MSRV to 1.41.1.
> Upgrade bech32 to version 0.9.0

- src/blockdata/locktime.rs
- src/blockdata/transaction.rs
- src/error.rs
- src/internal_macros.rs
- src/lib.rs
- src/parse.rs
- src/util/address.rs
When debugging parsing errors it's very useful to know some context:
what the input was and what integer type was parsed. `ParseIntError`
from `core` doesn't contain this information.
In this commit a custom `ParseIntError` type is crated that carries the
one from `core` as well as additional information. Its `Display`
implementation displays this additional information as a well-formed
English sentence to aid users with understanding the problem. A helper
function parses any integer type from common string types returning the
new `ParseIntError` type on error.
To clean up the error code a bit some new macros are added and used.
New modules are added to organize the types, functions and macros.
Closes #1113
Depends on #994
> Parse int error

- src/util/bip158.rs
The BIP-158 finalize code was serializing value to `Vec` only to
serialize it to writer right away. Thus the intermediary `Vec` was not
needed.
Even more, the code used `write` which, while correct in case of `Vec`,
could trigger code analysis tools or reviewers.
> Remove needless allocation from BIP-158 encoding

- src/util/psbt/map/output.rs
- src/util/psbt/serialize.rs
- src/util/taproot.rs
Found while reviewing https://github.com/rust-bitcoin/rust-miniscript/pull/450/ . There is also a BUG fix in the second commit that would have let users spendinfo from incomplete trees. 
The bug was introduced in #936 which I am responsible for ACKing
> Update finalize API

- src/blockdata/locktime.rs
- src/blockdata/script.rs
- src/blockdata/transaction.rs
- src/internal_macros.rs
- src/util/bip32.rs
- src/util/ecdsa.rs
- src/util/key.rs
- src/util/misc.rs
- src/util/psbt/error.rs
- src/util/schnorr.rs
- src/util/taproot.rs
- src/util/uint.rs
[Turns out](https://github.com/rust-lang/rust-clippy/issues/9248) by default clippy does not lint certain parts of the public API. 
Specifically, by setting `avoid-breaking-exported-api = false` we can get clippy to lint the public API for various things including
`wrong_self_convention`.
This means the saga of to/into/as continues ... we have used the wrong from for many of our `to_*` methods, they should consme `self`. Patch 1 fixes them. Patch 2 adds an `allow`. Patch 3 fixes a few error enum variant identifiers (removes `Error` suffix).
> Fix public API clippy warnings

- Cargo.toml
We recently released a couple of new versions of
`rust-bitcoinconsensus`, the first was mainly to move to git subtree,
included in this release was a bump of the patch version of bitcoin
core. The next release updated bitcoin core major version to 0.20.2
Update our bitcoinconsensus dependency to `0.20.2-0.5.0`.
> Update bitcoinconsensus dependency

- src/blockdata/constants.rs
- src/blockdata/transaction.rs
This is follow up work to the recent addition of the `Sequence` type. We
do not need to keep a public integer const for `MAX_SEQUENCE` because we
offer the `Sequenc::MAX` associated type.
Use the all-bits-set u64 directly in the associated type `Sequence::MAX`.
cc nlanson
> Remove `MAX_SEQUENCE` constant

- CHANGELOG.md
- Cargo.toml
Add changelog notes and bump the version number to v0.29.0.
I attempted to go through all the PRs since last release, please sing out if you had a PR merged that is not mentioned and you would like it mentioned.
The changelog notes can be changed or improved, please do not take me writing them to imply I know exactly what goes on round here - I just made an effort to save others having to do it.
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1131 
- #1137 
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1129
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1151
- https://github.com/rust-bitcoin/rust-bitcoin/pull/1165 (add release notes still)
> Release tracking PR - v0.29.0

- src/util/bip158.rs
In attempt to resolve #1147 clean up the `bip158` module.
I was unable to resolve the `"confusing method names read and write that look like those from std:i:o::{trait}"`
I find the `bip158` data types and abstractions kind a funky but was unable to come up with any improvements.
Open question: Are all the public data types really meant to be public? Perhaps we should have an issue to write an example module that uses the bip158 module?
> Clean up bip158 module

- src/util/bip143.rs
- src/util/merkleblock.rs
- src/util/sighash.rs
I'm not sure what the exact policy we decided on for deprecating is but we have code deprecated since v0.24.0 and v.026.2, both of these seem reasonable safe to remove.
Removal of `SighashCompontents` uncovered the fact that we never moved the BIP 143 test vector code over to the new `SighashCache`.
- Patch 1: Trivial preparatory cleanup
- Patch 2: Re-write bip143 test vectors using `sighash::SighashCache`
- Patch 3: Trivial, use `SighashCache` instead of `SigHashCache`
- Patch 4: Remove `SighashComponents` struct deprecated in 0.24.0
- Patch 5: Remove `MerkleBlock` methods deprecated in 0.26.2
> Remove old deprecated code

- src/blockdata/script.rs
- src/blockdata/transaction.rs
- src/util/bip152.rs
- src/util/psbt/raw.rs
- src/util/sighash.rs
We have a bunch of clippy warnings on master, at least one of them is from a patch dated from March, before we ran clippy on CI.
Fix clippy warnings
- warning: accessing first element with `self.0.get(0)`
- warning: deref on an immutable reference
- warning: you are deriving `PartialEq` and can implement `Eq`
All one patch because clippy has to run cleanly for each patch on CI now.
Please note the `Eq` change, adding this derive is an API change.
> Fix clippy warnings

- examples/bip32.rs
- examples/ecdsa-psbt.rs
- fuzz/fuzz_targets/deserialize_address.rs
- fuzz/fuzz_targets/deserialize_script.rs
- src/address.rs
- src/blockdata/script.rs
- src/error.rs
- src/lib.rs
- src/parse.rs
- src/serde_utils.rs
- src/util/key.rs
- src/util/misc.rs
- src/util/mod.rs
The identifier 'util' does not convey any real information. We have a whole bunch of modules inside the `util` module.
As part of work to reduce the amount of arbitrary things in the `util` module move the `address` module to the crate root level.
- Patch 1: fixes rustfmt issues currently on master, this patch is in heaps of my open PRs at the moment
- Patch 2: Does the module move
- Patch 3: Runs the formatter, done separately so reviewers can run `rustfmt +nightly fmt` and check the diff
> Move `address` out of `util`

- src/blockdata/transaction.rs
- src/util/bip152.rs
- src/util/bip158.rs
- src/util/merkleblock.rs
Do error cleanups, and add a script to help find missing `non_exhaustive` on error types
- Patch 1: Audit the codebase and put `non_exhaustive` on all  error types. 
- Patch 2: Implement `std::error::Error::source` for `bip152::Error`
- Patch 3: Implement `Display` and `std::error::Error::source` for `MerkleBlockError`
- Patch 4: Move rustdocs to above attributes on one error type
- ~Patch 5: Add a python script to `contrib` that checks the codebase for missing non exhaustive on the line above the results of regex `pub enum .*Error`~
I removed the Python script patch, I can't be bothered working on this for now but the clean ups and `non_exhaustive` additions are useful IMO.
- I added 'API break', I think the `non_exhaustive` addition requires major bump but not sure?
- release notes …
> Do error cleanups

- src/blockdata/transaction.rs
- src/blockdata/witness.rs
- src/lib.rs
- src/util/bip143.rs
- src/util/ecdsa.rs
- src/util/psbt/map/input.rs
- src/util/psbt/mod.rs
- src/util/sighash.rs
This is non-urgent work, something I've wanted to do for months now, please only review at your leisure :)
Currently we have a bunch of sighash types defined in the `transaction` module and we have a newer `sighash` module that defines a bunch of related types. This is an artifact of the development process as we added the new types. If we put things that are related together it makes it easier for devs to find their way around the library and grok the code.
Move all the sighash types from the `blockdata::transaction` module to the `sighash` module.
The first two patches are preparatory cleanup.
I added "API break" because I move the types without adding a re-export from the original place. I believe this is correct because we are, hopefully, aiming to de-couple the public API from the …
> Move sighash types to the sighash module

- src/blockdata/locktime.rs
Recently we introduced SPDX license ids but there was some confusion
about the use, form, and purpose of lines before (library name, author).
It was pointed out to me by Andrew that if/when folks cut'n'paste our
code they often will keep the whole blurb. Design it with that in
mind. FTR, Andrew also indicated that he did not mind his name being
removed in favour of "The rust-bitcoin developers".
At first I thought the term "The rust-bitcoin developers" was a bit
wishy-washy but yesterday I realised that I am proud to be part of that
crew, striving to deliver code to the highest possible standard.
Introduce a canonical format for the licences blurb.
- Use the name of the library
- Use "The rust-bitcoin developers"
- Use the SPDX ID
> Introduce new canonical license blurb

- src/blockdata/block.rs
- src/blockdata/locktime.rs
- src/blockdata/transaction.rs
- src/lib.rs
- src/util/bip143.rs
- src/util/sighash.rs
In an effort to make the library more ergonomic to use re-export modules from `blockdata` at the crate root level. This helps to decouple the internal code layout with the public API.
> Re-export blockdata modules

- src/blockdata/opcodes.rs
- src/blockdata/script.rs
- src/internal_macros.rs
- src/util/uint.rs
Related to issue : [1201](https://github.com/rust-bitcoin/rust-bitcoin/issues/1201)
> Replaced macro **impl_display_from_debug** with **impl_debug_from_display**
> Added implementation of Display trait where needed.
> [update] macro to implement Debug from Display and add Display implementation where needed

- .github/workflows/fuzz.yml
Honggfuzz is broken, I have no idea why but no PRs can merge while its broken.
(I tried a bunch of other things but could not debug this issue.)
> Temporarily disable fuzzing in CI

- src/consensus/params.rs
fixes: https://github.com/rust-bitcoin/rust-bitcoin/issues/1213
> consensus::Params should be non_exhaustive

- examples/ecdsa-psbt.rs
- src/blockdata/constants.rs
- src/blockdata/locktime/absolute.rs
- src/blockdata/locktime/mod.rs
- src/blockdata/locktime/relative.rs
- src/blockdata/transaction.rs
- src/lib.rs
- src/util/bip143.rs
- src/util/bip152.rs
- src/util/psbt/mod.rs
- src/util/sighash.rs
Patches 1 and 2 are preparation. Patch 3 adds a new `relative::LockTime` type.
Please see https://github.com/rust-bitcoin/rust-miniscript/pull/455 for demo of use of the new API in miniscript.
- https://medium.com/summa-technology/bitcoins-time-locks-27e0c362d7a1
- https://github.com/bitcoin/bips/blob/master/bip-0068.mediawiki
- https://github.com/bitcoin/bips/blob/master/bip-0112.mediawiki
> Add relative lock time type

- src/blockdata/script.rs
With the latest release of `rust-bitcoinconsensus` the
`bicoinconsensus::Error` now implements `std::error::Error`.
Correctly handle `bicoinconsensus::Error` by returning `Some(e)` and
using `write_err` as is standard across the code base.
> Correctly handle bicoinconsensus::Error

- src/bip158.rs
- src/lib.rs
- src/util/mod.rs
We are attempting to flatten the `util` module.
Move the `bip158` module to the crate root out of `util`.
Currently `src/util/` is ignored by the formatter so this move requires `bip158` module to be formatted. Formatting is done as a separate patch so reviewers can run `cargo +nightly fmt` and compare the diffs if so desired.
> Move bip158 module to crate root

- src/bip158.rs
Recently we moved the `bip158` module but I missed one of the import statements in rustdoc - if only I could work out how to lint rustdocs.
> Use correct path for bip158 in rustdoc

- src/blockdata/block.rs
- src/blockdata/constants.rs
- src/lib.rs
- src/util/bip152.rs
Added new type `BlockVersion` for block header version field with inspiration from [Kixunil 's comment on #1215.](https://github.com/rust-bitcoin/rust-bitcoin/issues/1215#issue-1352273532)
I previously knew very little about the upgrading process so it was fun learning about it in writing this PR, however that also means it's probably not perfect yet, especially around BIP-9 signalling (fingers crossed it's all correct).
API for the type is kept simple but happy to change it up to add more functionality.
> Add new type for block version

- src/blockdata/block.rs
- src/blockdata/script.rs
See: https://github.com/bitcoin/bips/blob/master/bip-0034.mediawiki
The BIP was updated with commit: https://github.com/bitcoin/bips/commit/08844fd6eff55e756c453c6d2e16de40e8f80e73
Found while reviewing #1240 
Also cleanly deals with negative heights as errors.
> BIP 34: Check last minimal encoding accoriding of heights

- examples/ecdsa-psbt.rs
- src/internal_macros.rs
A few trivial formatting errors have snuck into the codebase.
Run `cargo +nightly fmt`
FTR we have an open PR to run formatter in CI: https://github.com/rust-bitcoin/rust-bitcoin/pull/1111
> Run cargo fmt

- src/consensus/encode.rs
The error variants `UnexpectedNetworkMagic` and `UnknownNetworkMagic` were not only duplicated but also completely unused. This removes both of them.
> Remove unused consensus encoding error variants

- src/network/message.rs
- src/util/sighash.rs
- src/util/uint.rs
There was a bunch of manual implemntations that can be converted to
macro call. This commit replaces them except for enums because those are
currently not supported by the macro and we want to protect against
forgetting to handle newly added variants.
Depends on #1129 and is **not** urgent for the next release.
> Impl std error using macro

- src/util/key.rs
Part of #1245.
Do we also want a method on `PubkeyHash` or is the `From` impl sufficient?
> implement `From<PublicKey>` for `PubkeyHash`

- src/util/key.rs
There were a bunch of `if self.serialized` expressions repeated in the code. This change simplifies it by putting the `if` in a function that calls a closure with a slice containing the serialized bytes.
> Simplify `PublicKey` serialization code

- src/internal_macros.rs
The formatter removes an empty line that is clearly better to have. Add a rustdoc comment to at least delineate the line a bit.
> Add a comment to delineate test_macros re-export

- src/bip158.rs
- src/lib.rs
Currently the generic iterators in `bip158` return items of type slice reference. We can make the code cleaner (no explicit lifetimes) and more general if the generic iterator argument iterates over `Borrow<[u8]>`
> Use `Borrow` trait bound for bip158 `Iterator::Item`

- internals/Cargo.toml
- internals/src/hex/buf_encoder.rs
- internals/src/hex/display.rs
- internals/src/hex/mod.rs
- internals/src/lib.rs
There's a `hex` module in `bitcoin_hashes` which is a bit out of place and not very fast - it passes each *digit* through dynamic dispatch not only adding overhead but also not allowing `String` to make better allocations.
This change adds basic support for hex encoding using a stack-allocated buffer which minimizes the overhead of dynamic dispatch. It also provides a new `DisplayHex` trait designed to replace `ToHex` found in `bitcoin_hashes`.
> Implement basic support for fast hex encoding

- CONTRIBUTING.md
We have introduced `rustfmt` but forgot to update the docs section about
it. Since a large portion of the codebase is currently ignored by our
`rustfmt` configuration, point out that `rusntfmt` is work in progress.
> Update docs on rustfmt

- internals/src/hex/buf_encoder.rs
- internals/src/hex/display.rs
- internals/src/lib.rs
Not being able to create an owned `BufEncoder` prevented returning it from functions which need to allocate the buffer on stack. Such is the case in WIP serde via consensus serialzation.
This change refactors `OutBytes` to be unsized, adds an `AsOutBytes` trait and uses that one instead of `Into` to perform the conversion.
Closes #1270 
This is meant as potentially mergeable demonstration. Interestingly, it was easier than I expected.
> Redesign `hex::BufEncoder` to accept owned arrays

- bitcoin/src/blockdata/constants.rs
`ChainHash::using_genesis_block` can't be made `const` because it uses a `match` expression, which is only valid in Rust 1.46. Add individual constants as a workaround so that `ChainHash` can be used in `const` contexts.
> Add constants to `ChainHash` for each `Network`

- bitcoin/src/address.rs
- bitcoin/src/blockdata/opcodes.rs
- bitcoin/src/network/constants.rs
- bitcoin/src/network/message.rs
- bitcoin/src/util/amount.rs
- bitcoin/src/util/psbt/map/output.rs
- bitcoin/src/util/psbt/raw.rs
- bitcoin/src/util/schnorr.rs
- bitcoin/src/util/sighash.rs
- bitcoin/src/util/taproot.rs
We give one release cycle for deprecating old code so as to make the upgrade path easier for downstream users.
Remove code deprecated during the last release (v0.29.0).
(Check out my diff stats - all red ;)
> Remove code deprecated last release

- bitcoin/src/blockdata/constants.rs
ChainHash::using_genesis_block can't be `const` if it uses a `match` expression prior to Rust 1.46. Use an array mapping to work around this limitation.
Follow-up suggested in [#1283](https://github.com/rust-bitcoin/rust-bitcoin/pull/1283#issuecomment-1249418809).
> Make `ChainHash::using_genesis_block` constant

- .github/workflows/fuzz.yml
- fuzz/Cargo.toml
- fuzz/fuzz_targets/deserialize_prefilled_transaction.rs
Add a simple deserialization fuzz test for `PrefilledTransaction`.
Fixes: #460 (I think, I'm not sure if any of the other types need fuzzing?)
> Add fuzz test for PrefilledTransaction

- bitcoin/src/blockdata/locktime/absolute.rs
- bitcoin/src/blockdata/locktime/relative.rs
Patch 1 is a docs improvement.
Patch 2 commit log:
When implementing the absolute lock time API we decided on _not_
supporting checking lock satisfaction with another lock, instead we
provided a pattern in the docs for doing so. Fast forward a months and
I, the primary author, then forgot to use the correct pattern when using
the API in `rust-miniscript` - this is a sure sign that the API is too
hard to use. In this time we worked on the relative lock API and came up
with a `is_satisfied_by_lock` method - this is identical to the required
use case in the absolute lock time module.
Add a method on `absolute::LockTime` for checking a lock against another
lock, add rustdoc comment explaining the methods function in filtering
prospective lock time values (how we use it in `rust-miniscript`).
> Add API method `absolute::LockTime::is_satisfied_by_lock`

- bitcoin/examples/ecdsa-psbt.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/lib.rs
- bitcoin/src/util/psbt/mod.rs
- bitcoin/src/util/schnorr.rs
- bitcoin/src/util/sighash.rs
Recently we moved a few types from `transaction` to `sighash`, while doing so I erroneously annotated code with the `deprecated` attribute hoping it would give downstream users a gentle upgrade experience. It turns out `deprecated` only works on functions.
During that same work, we re-exported from the crate root a bunch of types from the `sighash` module that probably should not have been re-exported. We are currently trying to create a nice clean API surface, in an effort to move in the right direction we should remove the re-exports and just re-export the `sighash` module.
Try to clean up the sighash export mess by doing:
- Remove the re-exports from the `transaction` module
- Remove crate level re-exports of `sighash` module types
- Re-export `sighash` module
Note, this patch is a …
> Try to fix up sighash export mess

- bitcoin/src/lib.rs
- bitcoin/src/sign_message.rs
- bitcoin/src/util/mod.rs
Done as part of [flattening util](https://github.com/rust-bitcoin/rust-bitcoin/issues/639).
Move some code out of `misc` then re-name the module to `signature` and move it to the crate root.
- Patch 1: Move a single public function, needs review that destination module is ok. I did consider re-naming the function to remove `script_` prefix but decided to leave it as is.
- Patch 2: Re-names `misc` -> `signature` and puts it in the crate root
- Patch 3: Runs the formatter on `signature` module
All changes include deprecated re-exports.
> Move/re-name the `util::misc` module

- bitcoin/src/network/constants.rs
Follow up to https://github.com/rust-bitcoin/rust-bitcoin/pull/1288#discussion_r982152738
Implemented `AsMut<[u8]>` and `AsMut<[u8;4]>` for `Magic`.
> `AsMut` impls for `Magic`

- bitcoin/src/blockdata/script.rs
Add a convenience function to `Script` to create a new builder, so that `Builder` doesn't need to be imported. This is a pretty common pattern in Rust for types which have associated builders.
> Add `Script::builder` convenience function

- bitcoin/Cargo.toml
I noted our released crate `0.29.1` was bigger than expected and noted with `cargo package --list` that even with our exclude the `test_data` dir was included. I am also going to backport this.
As specified in the doc:
`foo/` matches any directory with the name `foo` anywhere in the package.
> Fix `test_data` dir exclusion

- bitcoin/examples/ecdsa-psbt.rs
- bitcoin/src/util/psbt/mod.rs
Add an API for signing inputs to the `PSBT` struct. This is work based on code in `rust-miniscript` and the API design suggestions below from @sanket1729 and @Kixunil.
Please note, this adds an `unimplemented!` call for taproot inputs. ECDSA signing is complete.
Includes a patch adding the psbt example from https://github.com/rust-bitcoin/rust-bitcoin/pull/940 updated to use this new api. Run `cargo run --example psbt --features=bitcoinconsensus` to test it out.
> Add API to PSBT to enable signing inputs

- bitcoin/src/blockdata/script.rs
This rewords the doc to have a reasonable summary, adds a little background explaining the opcode behavior and the effect of the function when called multiple times.
Closes #1154
> Improve doc of `Script::push_verify`

- bitcoin/src/address.rs
- bitcoin/src/blockdata/constants.rs
- bitcoin/src/blockdata/opcodes.rs
- bitcoin/src/blockdata/script.rs
We have all of the opcodes defined in a submodule called `all`, this allows wildcard imports without bringing in the other types in the `opcodes` module.
Use wildcard import `use crate::blockdata::opcodes::all::*` instead of fully qualifying the path to opcodes.
The `all` module adds no value, we can remove it without loss of meaning or clarity, doing so makes the code less verbose.
EDIT: After review, now includes importing with wildcard and removing the `opcodes::` path from any type starting with `OP_`.
Idea stolen from: https://github.com/rust-bitcoin/rust-bitcoin/pull/525 (patch 7)
> Remove usage of `opcodes::all`

- bitcoin/src/util/psbt/error.rs
- bitcoin/src/util/psbt/mod.rs
to calculate fee if previous outputs are available.
Closes https://github.com/rust-bitcoin/rust-bitcoin/issues/1220
> Implement PartiallySignedTransaction::fee

- bitcoin/contrib/test.sh
The MSRV break in serde is fixed now, remove the serde version pinning.
Fix: #1256
> ci: Remove serde version pinning

- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/blockdata/witness.rs
- bitcoin/src/lib.rs
- bitcoin/src/sighash.rs
- bitcoin/src/util/ecdsa.rs
- bitcoin/src/util/mod.rs
- bitcoin/src/util/psbt/map/input.rs
- bitcoin/src/util/psbt/mod.rs
Done as part of the effort to flatten the `util` module.
The `sighash` module can stand alone in the crate root, it provides a discreet set of functionality - the `SighashCache` and associated types.
Marking as high priority because this is part of flattening `util` which is a required step before we start crate smashing.
> Move sighash module to crate root

- bitcoin/Cargo.toml
- bitcoin/contrib/test.sh
- bitcoin/examples/taproot-psbt.rs
Will address #893.
Currently includes a BIP86 example (no spendable script path)
Working on script path and key path spending when both are possible spending paths.
> examples: Add taproot PSBT example workflow

- bitcoin/src/lib.rs
`base64` used to be exported until commit 23ee0930c75c3c028572c521e0906fd4f95b6b92 which removed the `pub extern crate` declaration.
> Re-export base64 when enabled

- bitcoin/src/blockdata/witness.rs
It is considered idiomatic for types that have `iter()` method to also implement `IntoIterator` for their references. `Witness` was missing this so it is added here.
> Add `impl IntoIterator for &'_ Witness`

- CHANGELOG.md
I'm not actually sure if we want this - we don't seem to (consistently) add entries for point releases, but figured I'd put it up in case we want it.
> Add a CHANGELOG entry for 0.28.2

- bitcoin/src/bip152.rs
- bitcoin/src/bip32.rs
- bitcoin/src/blockdata/script.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/blockdata/witness.rs
- bitcoin/src/consensus/encode.rs
- bitcoin/src/pow.rs
- bitcoin/src/sign_message.rs
Clippy has been updated and new warnings are being triggered in our codebase. This PR does all warnings using nightly since they all looked like reasonable things to fix.
Needed for CI to pass in other open PRs.
> Do clippy improvements

- bitcoin/src/blockdata/block.rs
- bitcoin/src/lib.rs
- bitcoin/src/merkle_tree.rs
- bitcoin/src/util/merkleblock.rs
- bitcoin/src/util/mod.rs
Done as part of flattening `util`.
The `util::hash` module only provides two functions, both to calculate the merkle root of a list of hashes.
1. Rename `util::hash` -> `crate::merkle_root`
2. Change function names to `calculate[_inline]` so usage becomes `merkle_root::calculate`
Done as two separate patches so we can bikeshed the names, can squash if needed.
> Rename `hash` module to `merkle_root`

- bitcoin/src/amount.rs
- bitcoin/src/lib.rs
- bitcoin/src/util/mod.rs
- fuzz/fuzz_targets/deserialize_amount.rs
Done as part of flattening the `util` module. Simply move the `amount` module out of the `util` module and to the crate root. Justified by the fact that the `Amount` type is more-or-less a "primitive" bitcoin type.
> Move amount module out of util

- bitcoin/Cargo.toml
- bitcoin/src/blockdata/script.rs
- bitcoin/src/lib.rs
`default-features = false` was missing previously but blindly adding it would lead to subtle risk of breaking when a crate not needing `std` depends on `bitcoinconsensus` and simultaneously another crate not needing `bitcoinconsensus` depends on `std` and another crate depends on them both.
This change fixes it by introducing `bitcoinconsensus-std` feature flag and provides a fallback if the flag is off. Unfortunately the fallback has to use a bit of reasonable `unsafe` due to limitations of upcasting.
The only safe alternatives are not do it and provide worse experience for crates that are affected by the problem above or break the API, which couldn't be backported and would be more annoying to use.
Closes #1343
This is considered PoC PR as I realized the possibility of the hack (and …
> Fix `no_std` when `bitcoinconsensus` is enabled

- bitcoin/src/lib.rs
`hashbrown` used to be exported until commit 23ee0930c75c3c028572c521e0906fd4f95b6b92 which removed the `pub extern crate` declaration.
Found thanks to afilini (#1342)!
> Re-export hashbrown when enabled

- internals/src/macros.rs
All the types that we define with `impl_array_newtype` are `Copy` so the correct conversion method to get the underlying byte array is `to_bytes`. We currently provide `into_bytes` as well as `to_bytes`, with one of them calling `clone` - this is unnecessary and against convention.
Remove `into_bytes` and for `to_bytes` just return the inner field. Add code comment to remind devs of correct usage of the macro in regards to deriving `Copy` and `Clone`.
> Remove `into_bytes` from `impl_array_newtype`

- bitcoin/src/blockdata/opcodes.rs
Improve documentation on the `all` module by doing:
- Document guarantee that `all` will only ever contain opcode constants
- Fix stale/incorrect code comment
Done as follow up to #1295
> Improve documentation on the `all` module

- bitcoin/src/bip152.rs
- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/constants.rs
- bitcoin/src/blockdata/script.rs
- bitcoin/src/lib.rs
- bitcoin/src/network/message.rs
- bitcoin/src/pow.rs
- bitcoin/src/sighash.rs
- bitcoin/src/util/merkleblock.rs
- bitcoin/src/util/taproot.rs
After initial attempt and review this PR has been re-written.
- Patch 1: Make types in `block` more terse, this is preparatory clean up based on suggestion below.
- Patch 2: Make inner value of `Version` private to hide the i32/u32 discrepancy 
This is a follow up to #1240
> Improve block version

- bitcoin/src/blockdata/witness.rs
Ref: https://github.com/rust-bitcoin/rust-bitcoin/pull/672#issuecomment-980636502
[Add Index<usize> and nth(index) to Witness](https://github.com/rust-bitcoin/rust-bitcoin/pull/1323/commits/4226d602057529885cf95f935370f6e5bf68bfd2) 
[4226d60](https://github.com/rust-bitcoin/rust-bitcoin/pull/1323/commits/4226d602057529885cf95f935370f6e5bf68bfd2)
Arbitrary indexing into Witness fixes the API of last and second_to_last to be more flexible.
This patch started off as an addition of third_to_last, but ended up evolving
into arbitrary indexing to allow for future use cases.
A list of the indices of the start byte for each witness element is stored as an ordered
contiguous group of u32s represented as 4 bytes each in the Vec<u8> contents.
The bytes are stored using to_ne_bytes for performance …
> [blockdata::Witness] New Features: Index<usize>, nth(index), and get_tapscript

- bitcoin/examples/bip32.rs
- bitcoin/examples/ecdsa-psbt.rs
- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/bip32.rs
- bitcoin/src/util/mod.rs
- bitcoin/src/util/psbt/error.rs
- bitcoin/src/util/psbt/map/global.rs
- bitcoin/src/util/psbt/map/input.rs
- bitcoin/src/util/psbt/map/output.rs
- bitcoin/src/util/psbt/mod.rs
- bitcoin/src/util/psbt/serialize.rs
Recently we added a bunch of deprecated re-exports while moving things out of the util module. Turns out while the code reads like it works, `deprecated` actually only works for functions, not types or modules etc.
Remove the non-functional deprecated lines and elect to _not_ re-export things we moved. Release 0.30 is going to break a lot of code but there is no real nice way to resolve that. We will need good release notes and a public apology probably :)
Fix import statements that still rely on `util::bip32` - these should have been fixed when we moved the `bip32` module.
> Remove deprecated re-exports

- bitcoin/src/address.rs
- bitcoin/src/bip32.rs
- bitcoin/src/util/base58.rs
- bitcoin/src/util/key.rs
Do some clean up work to the `base58` module in preparation for splitting it out into its own crate. 
- Patches 1-6: Basic clean up.
- Patch 7: Re-names the public API functions.
- Patch 8: Fixes rustdoc comment as suggested during review.
- Patch 9: Improves documentation on checksum, also as suggested during review.
> Clean up the `base58` module

- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/blockdata/witness.rs
- bitcoin/src/util/psbt/mod.rs
Cleanup PR to improve the `Witness` API by:
- Adding `Witness::from_slice()` and depreciating `Witness::from_vec()` methods (#1371).
- Making `Witness::push()` not generic and take in `&[u8]` instead of `AsRef<[u8]>` (#1372).
Note: `Witness::from_vec()` has been marked for depreciation from `0.30.0`. Let me know if this should be different.
> `Witness` API improvements

- bitcoin/src/lib.rs
- bitcoin/src/merkle_tree/block.rs
- bitcoin/src/merkle_tree/mod.rs
- bitcoin/src/network/message.rs
- bitcoin/src/util/mod.rs
Re-done after review comments below. This is now PR 1 in the `merkle_tree::block` series :)
Move the `merkleblock` module into the `merkle_tree` module in a submodule called `block`. In order to do the minimum amount of changes in this patch DO NOT rename types to improved naming and reduce stutter.
Note:
- block module is private
- the three types are re-exported from `merkle_block`
- the `MerkleBlock` re-export from the crate root is left in place.
This patch purposefully does the minimum amount of changes because there a whole bunch of improvements to the old "merkleblock" module that are coming next in a separate PR.
> Move `merkleblock` into `merkle_tree`

- bitcoin/src/blockdata/witness.rs
#1385
Implemented:
- `From<Vec<Vec<u8>>>`
- `From<&[&[u8]]>`
- `From<&[Vec<u8>]>`
- `From<Vec<&[u8]>>`
> `Witness` conversion trait implementations

- bitcoin/src/merkle_tree/block.rs
- bitcoin/src/merkle_tree/mod.rs
Run `cargo +nightly fmt` and commit the changes to the `merkle_tree` module. No manual changes, only those introduced by `rustfmt`.
> Format the `merkle_tree` module

- bitcoin/src/blockdata/constants.rs
Amount of coins available stay in the same across Bitcoin network: signet, testnet, mainet. From my understanding this is a leftover from some potential multi-chain support.
For more context: https://github.com/lightningdevkit/rust-lightning/pull/1839#discussion_r1019753069
If there is already an existent PR, it can be closed, however didn't find one.
> Drop Network arg from max_money()

- bitcoin/contrib/test.sh
- bitcoin/src/amount.rs
- bitcoin/src/blockdata/witness.rs
- bitcoin/src/psbt/map/input.rs
Currently we do not fail the CI script if the docs build throws warnings, since we are a group of super anal, easily triggered, code cleanliness obsessed devs this causes a mild rash to develop on the lower back [0]. We can easily fix this by checking for build warnings in CI.
[0] - Amusingly my rash has been playing up since Friday but I thought I'd fixed the warnings in an open PR someplace so I was ignoring it, seeing Kixunil's [issue](https://github.com/rust-bitcoin/rust-bitcoin/issues/1403) this morning prompted me to fix it :)
Fix #1403
> Check for rustdocs build warnings in CI

- bitcoin/src/network/constants.rs
closes: #1207
Adds converting `Network` to its `bitcoind` equivalent.
The arguments for -chain can be found in the documentation and is one of the following:
main, test, signet, regtest
> Add Network::to_core_arg() method

- hashes/src/sha512.rs
Saw the typo and since this typo also exists in crates.io, I thought it'd be good to quickly change it.
Though maybe this should be replaced altogether with the `hash_type` macro since every other hash function implementation is using that.
> Fix typo in the SHA512 documentation

- bitcoin/src/address.rs
It's confusing trying to follow the documentation [here](https://docs.rs/bitcoin/latest/bitcoin/util/address/index.html) unless you know to enable the `rand` feature flag.  This PR updates the docs so people know to enable the flag.
```
22:35 < control> hello, how can i generate a simple wallet address using rust bitcoin? cant find working example
22:45 < andytoshi> control: do you have a private key?
22:45 < andytoshi> what kind of address do you want to generate?
22:46 < andytoshi> my guess would be that you want to use bdk rather than rust-bitcoin directl
22:48 < control> P2PKH address and generate private key. just as simple as bit library in python does
22:52 < control> im trying to run this example
22:52 < control> https://docs.rs/bitcoin/latest/bitcoin/util/address/index.html
22:52 …
```
> Add rand feature flag to the example documentation

- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/address.rs
- bitcoin/src/blockdata/script.rs
- bitcoin/src/blockdata/witness.rs
- bitcoin/src/consensus/encode.rs
- bitcoin/src/crypto/schnorr.rs
- bitcoin/src/lib.rs
- bitcoin/src/psbt/map/input.rs
- bitcoin/src/psbt/map/output.rs
- bitcoin/src/psbt/serialize.rs
- bitcoin/src/sighash.rs
- bitcoin/src/taproot.rs
- bitcoin/src/util/mod.rs
We are trying to flatten the `util` module. The `taproot` module can live in the crate root. If/when we create a `crypto` module/crate we may wish to pull some stuff out of this module but for now moving it gets us closer to removing `util` without making the directory structure any worse.
CC sanket1729, I did this after reviewing the `taproot` module during work on https://github.com/rust-bitcoin/rust-bitcoin/pull/1260 and your review comment.
> Move the taproot module to crate root

- bitcoin/src/address.rs
- bitcoin/src/base58.rs
- bitcoin/src/bip32.rs
- bitcoin/src/crypto/key.rs
- bitcoin/src/lib.rs
- bitcoin/src/util/mod.rs
Move `base58` module to the carte root, direct `rustfmt` to not format the digits array. Run formatter as a separate patch.
> Move `base58` to the crate root

- bitcoin/src/network/constants.rs
`no_run` is not needed since we already mark this up as `bash` which rustc doesn't run when running examples.
While the keyword `bash` is not currently supported it may well be in the future and since only the `rust` keyword causes code to run any other string is effectively a wildcard, `no_run` is therefore meaningful only as a convention. Lets keep `bash` in case support is added later on.
cc sr-gi
> Remove no_run

- bitcoin/src/blockdata/constants.rs
The value is statically known which is better expressed as a constant. Also allows usage in const context.
> Change `max_money` to a constant.

- bitcoin/Cargo.toml
- bitcoin/build.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/consensus/mod.rs
- bitcoin/src/consensus/serde.rs
- bitcoin/src/lib.rs
- internals/src/hex/buf_encoder.rs
In some protocols it is preferred to serialize consensus-encodable types
using consensus encoding. E.g. serialize `Transaction` as hex-encoded
string in Json in Bitcoin Core RPC protocol. This change provides
adapter to make this easier.
The adapter allows providing custom byte-to-string encoder for more
exotic cases and provides a hex implementation which should be useful in
majority of the cases.
Should help with #765
Based on #1252 
Required by #1234
> Consensus encoding based serialization

- bitcoin/src/internal_macros.rs
- bitcoin/src/sighash.rs
Manual parsing Json is tedious and error-prone. It contained a bunch of
`unwrap`s and was hard to read.
This replaces manual Json parsing with serde_derive implementation.
Closes https://github.com/rust-bitcoin/rust-bitcoin/issues/1231
> Serde derive in tests

- bitcoin/src/network/constants.rs
Comming from https://github.com/rust-bitcoin/rust-bitcoincore-rpc/pull/247
`Network::from_str` only considers `rust-bitcoin` string as possible inputs to create a `Network` instance. This PR adds a new method to `Network`, `from_core_arg`, which is complementary to the existing `Network::to_core_arg`. This method allows the conversion between `bitcoind -network` string and `Network` variants.
This also links `Network::from_str` to `Network::from_core_arg` so the default case on the former calls the latter, and an error is only returned if none of the cases match.
> Adds Network::from_core_arg and links it to Network::from_str

- bitcoin/src/amount.rs
- bitcoin/src/blockdata/locktime/absolute.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/lib.rs
- bitcoin/src/parse.rs
- bitcoin/src/pow.rs
- bitcoin/src/string.rs
Closes: #1112 
- Adds new trait `FromStrHex` with 2 methods: `from_hex_str` and `from_hex_str_no_prefix`
-  Impl new trait on each tuple struct with single u32 member. eg `Time(u32)`
As stated in the issue, grep through codebase with `\(u32\)` and `\(pub u32\)` to see all implementations and verify none were missed. 
NonStandardSighashType is an error type and should never be constructed from a hex string. Therefore, it has been omitted from this change.
Tests are somewhat redundant, but cover 4 cases each. 2 happy paths, 1 for each function. 1 case for malformed/invalid hex input, and 1 for calling no_prefix without a prefix
> Add trait `FromStrHex` for tuple structs with single `u32` member

- bitcoin/embedded/Cargo.toml
- hashes/src/util.rs
Currently we implement `Deref` for hashes. From the docs [0]
> Deref should only be implemented for smart pointers to avoid confusion
Furthermore because we implement `Deref` as well as implement `internals::hex::display::DisplayHex` for slices hashes get coerced into slices and `to_lower_hex_string` can be called on them, this is incorrect because `DisplayHex` does not account for hashes that display backwards so we end up with the wrong string.
This is an API breaking change, and I have not built any other crates in our stack to check if anything breaks. 
[0] https://doc.rust-lang.org/std/ops/trait.Deref.html
> hashes: Do not implement `Deref`

- bitcoin/Cargo.toml
- bitcoin/examples/ecdsa-psbt.rs
- bitcoin/examples/taproot-psbt.rs
- bitcoin/fuzz/fuzz_targets/deserialize_script.rs
- bitcoin/fuzz/fuzz_targets/script_bytes_to_asm_fmt.rs
- bitcoin/src/address.rs
- bitcoin/src/bip152.rs
- bitcoin/src/bip158.rs
- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/script.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/internal_macros.rs
- bitcoin/src/lib.rs
- bitcoin/src/network/message.rs
- bitcoin/src/psbt/map/input.rs
- bitcoin/src/psbt/map/output.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/src/psbt/serialize.rs
- bitcoin/src/sighash.rs
- bitcoin/src/taproot.rs
- bitcoin/tests/psbt.rs
- bitcoin/tests/serde.rs
This renames `Script` to `ScriptBuf` and adds unsized `Script` modeled
after `PathBuf`/`Path`. The change cleans up the API a bit, especially
all functions that previously accepted `&Script` now accept truly
borrowed version. Some functions that perviously accepted `&[u8]` can
now accept `&Script` because constructing it is no loger costly.
This is a more idiomatic alternative to #884 with two unavoidable lines of `unsafe` copied from `std`.
Closes #522 
Closes #949 
(For 949, we allow users to use whichever they like but still use `ScriptBuf` in `Transaction`.)
> Implemented unsized `Script`

- hashes/contrib/test.sh
- hashes/src/ripemd160.rs
- hashes/src/sha1.rs
- hashes/src/sha256.rs
- hashes/src/sha256d.rs
- hashes/src/sha512.rs
Currently we only run the linter in `bitcoin/contrib/test.sh`, we should do the same in the `hashes` ci script.
- Patch 1: Fix current clippy issues in `hashes` crate
- Patch 2: Run clippy in CI for `hashes` crate
> Run clippy in ci for `hashes`

- bitcoin/CHANGELOG.md
- bitcoin/src/blockdata/locktime/absolute.rs
- bitcoin/src/blockdata/transaction.rs
Updates the CHANGELOG and also the doccomment on `Transaction`.
> add some documentation clarifying the locktime ordering shenanigans in #1330

- bitcoin/src/blockdata/witness.rs
It seems useful to document that this check is also provided.
> Mention Script::is_v1_p2tr above Witness::tapscript

- .github/workflows/rust.yml
- Cargo.toml
- bitcoin/embedded/Cargo.toml
- bitcoin/fuzz/Cargo.toml
- bitcoin/src/address.rs
- bitcoin/src/hash_types.rs
- bitcoin/src/network/message.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/src/sighash.rs
- bitcoin/src/taproot.rs
This patches `bitcoin_hashes` to use the version in the repository and fixes the code after removal of `Deref`.
> Patch hashes and update the code

- bitcoin/examples/taproot-psbt.rs
- bitcoin/src/blockdata/script.rs
Adds convenience method to `Script` for computing leaf hash of tapscript. Closes #1482.
The little test case is taken from `bip341_tests.json`.
> Add `tapscript_leaf_hash()` to `Script`

- bitcoin/src/blockdata/script.rs
This is useful when one already has bytes allocated in a vec that can be reused.
The change also documents that the mirror method `into_bytes()` doesn't allocate.
> Add `from_bytes(Vec<u8>)` to `ScriptBuf`

- README.md
- bitcoin/Cargo.toml
- bitcoin/src/pow.rs
Introduce mutation testing by way of mutagen [0] (see #1484 for context).
- Conditionally add the dev-dependency `mutagen` (using `do_mutate` flag)
This flag is not very well named but `mutagen` and `mutate` are already taken?
- Mutate all methods of the `U256` struct that do not require additional unit tests.
Uses `cfg(all(test, do_mutate), mutate)` - I cannot workout why we need to check on `test` as well i.e., I don't understand why we cannot use `cfg(do_mutate, mutate)`?
With this applied test can be run as usual with a stable toolchain. To run mutagen we use `RUSTFLAGS='--cfg=do_mutate' cargo +nightly mutagen` (doing so runs 29 mutants).
[0] https://github.com/llogiq/mutagen
> Introduce mutation testing

- bitcoin/src/blockdata/script.rs
`ScriptBuf::extend` contained an optimization for short scripts that was
supposed to preallocate the buffer and then fill it. By mistake it
attempted to fill it from already-exhausted iterator instead of the
temporary array it drained the items into. This obviously produced
garbage (empty) values.
This was not caught by tests because the optimization is only active for
scripts with known maximum length and the test used `Instructions` which
doesn't know the maximum length.
> Fix bug in `ScriptBuf::extend` for short iterators 

- bitcoin/src/blockdata/witness.rs
Since there is unsized `Script` now, this method can return it.
> Make `Witness::tapscript()` return `Script` instead of raw bytes

- .github/workflows/rust.yml
`cross` currently fails to install, this has been reported already
https://github.com/cross-rs/cross/issues/1177
The workaround is to use `cargo install --locked`.
> Use cargo install cross `--locked`

- .github/workflows/rust.yml
Done on top of #1508
Currently we use the `actions-rs` GitHub action to run our tests. It seems the project is now unmaintained [0].
Well known Rust developer dtonlnay maintains a GitHub action that can be used instead.
Replace all uses of `actions-rs/toolchain` with `dtonlnay/rust-toolchain`. Note that with the new action there is no way to configure the toolchain, instead a different `uses` statement is required - this means we have to split our jobs up by toolchain. This is arguably cleaner anyways.
Note that with this patch applied the "no-std" tests are now _not_ run for MSRV since we explicitly support "no-std" only for the 1.47 and above toolchains - strange that this was working?
[0] https://github.com/actions-rs/toolchain/issues/216
> Use dtonlnay instead of actions-rs

- bitcoin/src/lib.rs
- hashes/src/lib.rs
Littering the codebase with `#[cfg(not(fuzzing))]` is a bit messy just to quieten the linter during fuzzing. Instead just globally allow.
Done while debugging #1409
> Allow dead_code/unused_imports when fuzzing

- .github/workflows/kani.yml
- README.md
Running kani takes ages, instead of running it on every pull request we can just run it daily.
> Run kani daily on a schedule

- hashes/contrib/test.sh
Currently we are using the `--all` flag in `cargo` commands in the `hashes` CI script. This flag (the deprecated version of `--workspace`) causes cargo to run the command for the whole workspace, this is not what we want because we run test individually for each crate using a ci script per crate.
The effect of this patch is to reduce re-runs of tests i.e., reduce machine usage during CI runs with no reduction of coverage - PROFIT!
> hashes: ci: Remove --all

- README.md
Recently we started using various test frameworks; add documentation to the readme for running the various tests we now support (mutagen, kani, etc.)
This was on a different PR originally, pushing it up on its own.
> Document test frameworks

- bitcoin/src/blockdata/locktime/absolute.rs
- bitcoin/src/blockdata/locktime/relative.rs
Add mutation testing to the `locktime` module and add unit tests to cover all mutants and ensure they are killed.
> Add mutation testing to the `locktime` module

- bitcoin/src/bip32.rs
- bitcoin/src/internal_macros.rs
- bitcoin/src/psbt/map/global.rs
- bitcoin/src/psbt/serialize.rs
- internals/src/macros.rs
This fixes several API bugs:
* Use `TryFrom` instead of `From` for fallible conversions
* Move byte conversion methods from `impl_array_newtype` to `impl_bytes_newtype`
* Add missing trait impls like `AsRef`, `Borrow`, their mutable versions and infallible conversions from arrays
Closes #1336
Notably this change is much less bad than even I expected and some places actually get cleaner than before.
> Fix wrong newtype APIs

- bitcoin/Cargo.toml
- bitcoin/contrib/test.sh
- bitcoin/src/address.rs
- bitcoin/src/consensus/encode.rs
- bitcoin/src/merkle_tree/block.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/src/sign_message.rs
This PR uncovered incorrect feature gating in `secp256k1`, fixed in https://github.com/rust-bitcoin/rust-secp256k1/pull/519
Currently we enable "secp256k1/rand-std" in the "rand" feature, this is incorrect because it means "rand" implies "std" which it does not.
Add a "rand-std" feature that turns on "seck256k1/rand-std" and make the "rand" feature turn on "seck256k1/rand".
Fix: #1384
> Add rand-std feature

- hashes/Cargo.toml
- hashes/src/internal_macros.rs
- hashes/src/sha256.rs
- hashes/src/util.rs
- internals/src/hex/buf_encoder.rs
- internals/src/hex/display.rs
`bitcoin-internals` contains a more performant implementation of hex encoding than what `bitcoin_hashes` uses internally. This switches the implementations for formatting trait implementations as a step towards moving over completely.
The public macros are also changed to delegate to inner type which is technically a breaking change but we will break the API anyway and the consuers should only call the macro on the actual hash newtypes where the inner types already have the appropriate implementations.
Apart from removing reliance on internal hex from public API this reduces duplicated code generated and compiled. E.g. if you created 10 hash newtypes of SHA256 the formatting implementation would be instantiated 11 times despite being the same.
To do all this some other changes were …
> Use hex from internals rather than hashes

- hashes/fuzz/Cargo.toml
- hashes/fuzz/fuzz_targets/sha512_256.rs
- hashes/src/lib.rs
- hashes/src/sha512.rs
- hashes/src/sha512_256.rs
Adds a new file named `sha512_256.rs` that implements the `sha512/256` hash. This was needed as a part of https://github.com/rust-bitcoin/rust-bitcoin/discussions/1318 to drop the `sha2` dependency.
All the actual hashing code is exactly the same as `sha512.rs`, minus the initial constants and the use of `hash_type!` macro. Some unit tests were added from wikipedia (for the "" input) and the rest were from the Go standard library's tests for sha512_256.
Benchmarks on my Ryzen 3600 machine show that it is faster than sha256.
```
test sha256::benches::sha256_10                   ... bench:          37 ns/iter (+/- 0) = 270 MB/s
test sha256::benches::sha256_1k                   ... bench:       3,338 ns/iter (+/- 24) = 306 MB/s
test sha256::benches::sha256_64k                  ... bench: …
```
> Add sha512_256 to bitcoin_hashes

- bitcoin/src/blockdata/locktime/absolute.rs
- bitcoin/src/blockdata/locktime/relative.rs
The additional `use` items were added to improve the style of documentation. Because they were only used for doc they were `cfg`ed. But because this is independent from being built by `docs.rs` the `cfg` should've been `doc` not `docsrs`.
IOW `docsrs` means roughly `all(doc, nightly)` and the added items are unrelated to `nightly`.
Do we want CI for this kind of thing? It feels a bit too much to me but if someone sends a PR I probably won't reject it.
> Change `#[cfg(docsrs)]` to `#[cfg(doc)]` on `use`

- bitcoin/examples/ecdsa-psbt.rs
- bitcoin/examples/taproot-psbt.rs
- bitcoin/fuzz/fuzz_targets/deserialize_psbt.rs
- bitcoin/src/psbt/macros.rs
- bitcoin/src/psbt/map/global.rs
- bitcoin/src/psbt/map/input.rs
- bitcoin/src/psbt/map/mod.rs
- bitcoin/src/psbt/map/output.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/src/psbt/raw.rs
- bitcoin/src/psbt/serialize.rs
- bitcoin/tests/psbt.rs
fix https://github.com/rust-bitcoin/rust-bitcoin/issues/934
Instead of using consensus {de,en}code, serialize high-level structures (PartiallySignedTransaciton, Output, Input) borrow the signature from `Serialize`, `Deserialize` traits and implement them on Psbt:
```rs
impl Psbt {
/// Serialize a value as raw data.
fn serialize(&self) -> Vec<u8>;
/// Deserialize a value from raw data.
fn deserialize(bytes: &[u8]) -> Result<Self, encode::Error>;
}
```
> Replace consensus `Encodable`/`Decodable` Psbt Serialization

- bitcoin/src/amount.rs
I didn't add tests for parsing with no space, but wanted to get a PR up to show the approach.
Fixes #1519.
> Make space optional in amount with denomination

- bitcoin/src/address.rs
- bitcoin/src/blockdata/constants.rs
- bitcoin/src/blockdata/script.rs
- bitcoin/src/blockdata/witness.rs
- bitcoin/src/consensus/encode.rs
- bitcoin/src/crypto/ecdsa.rs
- bitcoin/src/crypto/key.rs
- bitcoin/src/internal_macros.rs
- bitcoin/src/merkle_tree/block.rs
- bitcoin/src/pow.rs
- bitcoin/src/psbt/raw.rs
- bitcoin/src/psbt/serialize.rs
- bitcoin/src/serde_utils.rs
- bitcoin/src/sighash.rs
- bitcoin/src/sign_message.rs
- bitcoin/src/taproot.rs
- hashes/Cargo.toml
- hashes/embedded/src/main.rs
- hashes/src/hash160.rs
- hashes/src/hex.rs
- hashes/src/ripemd160.rs
- hashes/src/sha1.rs
- hashes/src/sha256.rs
- hashes/src/sha256d.rs
- hashes/src/sha256t.rs
- hashes/src/sha512.rs
- hashes/src/sha512_256.rs
- internals/src/hex/display.rs
The `ToHex` trait was replaced by either simple `Display`/`LowerHex` where appropriate or `DisplayHex` from `bitcoin_internals` which is faster.
This change replaces the usages and removes the trait.
> Remove `ToHex`

- bitcoin/src/address.rs
- bitcoin/src/blockdata/script.rs
- bitcoin/src/crypto/schnorr.rs
- bitcoin/src/psbt/map/input.rs
- bitcoin/src/psbt/serialize.rs
- bitcoin/src/sighash.rs
- bitcoin/src/taproot.rs
This does not completely fix #1393 but is a simple starter. Unfortunately, we still need hash_new_type for `TapNodeHash` because is exported as the Merkle root in taproot psbt. This requires serialization and display/from_str methods.
This also adds a method 1) `TapNodeHash::from_script` to deal with single leaf case cleanly. As a nice side effect, this removes the ugly uses of `sha256::Hash` that I had used to represent both `TapLeafHash` and `TapBranchHash`
Does not fix
1) Exporting `TapTweakHash`. This requires some changes to macros we use.
2) Safer usage of `TapNodeHash` by not making it `hash_new_type` and having guarded constructors. As mentioned above, this is required for psbts and sharing Merkle roots. Perhaps, we might need a new type while constructing trees that is not …
> Unify `TapLeafHash` and `TapBranchHash` into `TapNodeHash` while tree construction

- bitcoin/examples/ecdsa-psbt.rs
- bitcoin/examples/taproot-psbt.rs
- bitcoin/fuzz/fuzz_targets/deserialize_address.rs
- bitcoin/src/address.rs
- bitcoin/src/serde_utils.rs
- bitcoin/src/taproot.rs
Adds marker type `NetworkValidation` to `Address` to help compiler enforce network validation. Inspired by Martin's suggestion. Closes #1460.
Open questions:
1. Compilation fails with serde, which uses `Address:from_str` via macro `serde_string_impl!(Address, "a Bitcoin address");`. I don't think there is much we can do, so unless somebody has a better idea how to combine serde and network validation, I would just demacroed the macro for `Address` and add `unsafe_mark_network_valid` into it.
2. Would someone prefer wrapping the validation types by `mod validation`? As they are now, they live in `address` namespace so I don't think mod is necessary.
3. Almost all methods that used to be on `Address` are now on `Address<NetworkValid>` except one (`address_type`) that needs to be called on …
> Use marker type to enforce validation of `Address`'s network

- bitcoin/src/pow.rs
Add more mutation testing to the `pow` module.
The first two patches are preparatory clean up.
All functions/methods that are non-trivial are tested excluding:
- `to_compact_lossy`
- `from_compact`
- `fmt_decimal`
I think its ok to not test `fmt_decimal`. The compact format ones require a bit of work to do but should be done at some stage.
> Add more mutation testing to the `pow` module

- bitcoin/src/amount.rs
Add a rustdoc test to the `Denomination` type to show basic usage.
> Add a rustdoc test to Denomination

- bitcoin/src/blockdata/script.rs
- bitcoin/src/blockdata/witness.rs
- bitcoin/src/consensus/encode.rs
- bitcoin/src/crypto/ecdsa.rs
- bitcoin/src/lib.rs
- bitcoin/src/merkle_tree/block.rs
- bitcoin/src/psbt/raw.rs
- bitcoin/src/psbt/serialize.rs
- bitcoin/src/sighash.rs
- bitcoin/src/taproot.rs
We use `internals::hex::display::DisplayHex` in many places, we can improve ergonomics of the `internals` crate by re-exporting it from the `prelude` module.
> Export the DisplayHex trait from within prelude

- .github/workflows/rust.yml
- hashes/contrib/test.sh
When we merged `hashes` into `rust-bitcoin` we ran the test script a couple of times using `./hashes/contrib/test.sh` this causes the `cargo` commands in the CI script to be run from the crate root which is not what we want.
This showed up recently because `cargo test` was getting run in `bitcoin` after building with address/memory sanitazation configured into the build.
While we are at it run `cargo clean` after the last sanitizer build just to future proof the CI script in case we later accidentally re-use the same build with plain old `cargo` (without `-Zbuild-std etc.`).
> Fix ASAN in CI

- bitcoin/Cargo.toml
- bitcoin/src/bip158.rs
- bitcoin/src/lib.rs
The `bip158` module uses a `HashSet` and in order to do so requires the `hashbrown` dependency for "no-std" builds.
We can replace the usage of `HashSet` with a `BTreeSet` in `bip158` and remove the `hashbrown` dependency entirely.
This patch makes no claims about performance cost or benefit of this change. The patch also makes no claims about the validity of the current `HashSet` usage.
The `hashbrown` dependency and `HashSet` usage can be trivially added back in if someone comes up with perf data to back it up.
> bip158: Replace usage of HashSet with BTreeSet

- bitcoin/src/address.rs
Previously `Debug` was implemented for both `Address<NetworkChecked>` and `Address<NetworkUnchecked>`, but not for cases when the `NetworkValidation` parameter was generic. This change adds this ability. Based on Kixunil's tip.
With previous implementation, the `test_address_debug()` resulted in error:
The added `Debug` on `NetworkChecked` and `NetworkUnchecked` are required by compiler.
---
While dealing with derives and impls, I also attempted to turn all the derives on `Address` into manual impls (see Kixunil's suggestion in https://github.com/rust-bitcoin/rust-bitcoin/pull/1489#discussion_r1052448057). The motivation behind this was the possibility to remove derives on `NetworkChecked` and `NetworkUnchecked`, too. However, even with manual impls, all the traits on `NetworkChecked` and …
> Implement `Debug` for generic `Address<V: NetworkValidation>`

- bitcoin/src/address.rs
- bitcoin/src/blockdata/script.rs
- bitcoin/src/psbt/mod.rs
Fixes #1561. 
Highlights:
- Segwitv0 programs with lengths apart from 20 or 32 are invalid `Address` struct. Such Addresses are useless and we should not parse/create them.
- Renamed `is_standard` to `is_spend_standard`.
> Address validity invariant cleanups

- bitcoin/src/consensus/encode.rs
- bitcoin/src/consensus/serde.rs
- bitcoin/src/psbt/error.rs
- bitcoin/src/psbt/macros.rs
- bitcoin/src/psbt/map/global.rs
- bitcoin/src/psbt/map/input.rs
- bitcoin/src/psbt/map/output.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/src/psbt/raw.rs
- bitcoin/src/psbt/serialize.rs
This initial work attempts to fix #837's first 2 points
> - The current psbt::serialize::Deserialize has an error type of consensus::encode::Error. I think we should cleanly separate consensus encoding errors from application-level encoding errors like psbt.
> - There is a recursive dependence between encode::Error and psbt::Error which would need to be cleanly dissected and separated so that there is no dependence or only one-way dependence.
arturomf94 how compatible do your #1310 changes look to address #837's third point with this design?
> - There are a lot ParseError(String) messages that could use a better type to downflow the information.
I think your prior art would completely address this issue now.
`encode::Error` has an `Io` variant. now that `Psbt::deserialize` returns …
> Improve Psbt error handling

- bitcoin/src/hash_types.rs
- bitcoin/src/sighash.rs
From BIP143:
> If sighash type is SINGLE and the input index is smaller than the number of outputs, hashOutputs is the double SHA256 of the output amount with scriptPubKey of the same index as the input;
Currently we are using a `Sighash` which wraps double sha256 so while technically correct this means we are relying on `Sighash` to implement `Encodable`. We can remove this requirement by directly using the `sha256d::Hash` type to hash the outputs data.
Fix: #1549
> Use `sha256d::Hash` type for sighash encoding

- bitcoin/src/crypto/key.rs
We can make the API more ergonomic by taking a generic argument that implements `Into<secp256k1::PublicKey>` in the `bitcoin::PublicKey` constructors.
The only thing than this is useful for is passing in `KeyPair` and the `From` implementation already exists. Add a unit test to verify.
Fix: #1453
As per the discussion in #1453 I checked secp and bitcoin for all keys that can be converted using `From` and it turns out its only `KeyPair` which already has `From` impls - good rust-bitcoin devs :)
> Take `Into<secp256k1::PublicKey>` in PublicKey constructors

- bitcoin/src/blockdata/script.rs
Currently the derived implementation of `Debug` for `ScriptBuf` prints the inner vector of u8s as integers, this is ugly and hard to read. The `Script` implementation of `Debug` prints the script opcodes and data as hex, we can just delegate to it.
With this applied we get debug output of form:
Script(OP_DUP OP_HASH160 OP_PUSHBYTES_20 3bde42dbee7e4dbe6a21b2d50ce2f0167faa8159 OP_EQUALVERIFY OP_CHECKSIG)
Fix: #1516
> Delegate debug for ScriptBuf to Script

- bitcoin/src/blockdata/transaction.rs
The term "final" is an archaic Bitcoin term however it is well used, it exists in Bitcoin Core code as well as in various bips. To help folks new to Bitcoin add documentation to the `is_final` method including historical notes.
Note, this does _not_ deprecate `is_final` - while writing the notes I found the term "final" in enough official places that I think its fair game to keep the term, some things people just have to learn, we can definitely help with that learning though.
Fix: #1198
> Add documentation to `Sequence::is_final`

- bitcoin/src/bip158.rs
Clippy emits:
warning: the following explicit lifetimes could be elided: 'a
As suggested, remove the unnecessary lifetime.
> Remove unnecessary lifetime

- bitcoin/src/blockdata/locktime/absolute.rs
- bitcoin/src/blockdata/locktime/relative.rs
- bitcoin/src/blockdata/transaction.rs
Some of the lock time structs (`Height`, `Time` ect.) are missing standard constants for min, max ect.
Add standard constants taking into consideration the various locktime corner cases.
Add `max_value` and `min_value` to be consistent with Rust 1.41.1 (incl. `Sequence`).
Fix: #1451
This PR is not complex in itself but **locktimes are notoriously complex, please wait for 3 acks before merging** - and ack'ing makes no guarantee that reviewer got all corner cases :)
There is no rush on this one, apoelstra, Kixunil, sanket1729 please just review when your brain is fresh.
> Add standard constants to lock times

- bitcoin/src/bip32.rs
- bitcoin/src/crypto/key.rs
Recently we used an error type that holds only one expected hex string length when parsing but for `PublicKey`s we have two (66 and 130). Add a new error variant to express the error. Requires adding a variant to `bip32` for the same thing.
Fix: #1281
> Add new hex parse error variant

- bitcoin/src/amount.rs
- bitcoin/src/blockdata/locktime/absolute.rs
- bitcoin/src/blockdata/locktime/relative.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/pow.rs
The `max_value` and `min_value` functions only exist to be compatible/uniform with Rust 1.41.1 they will never change and they just return a constant value. They can therefore be made const functions.
> Make max/min_value functions const

- bitcoin/src/blockdata/script.rs
We can improve ergonomics of the `script` module by implementing the `fmt` traits on `ScriptBuf`, trivial because we can call through to the `Script` implementations.
Fix: #1585
> Implement fmt traits for ScriptBuf

- bitcoin/src/crypto/schnorr.rs
It is trivially possible to get `TweakedPublicKey` from a `TweakedKeyPair`, add conversion methods for doing so.
Patch 1 is preparatory cleanup. Please note `From` is not implemented because the conversion returns the `Parity` also.
Fix: #1452
> Add conversions for `TweakedKeyPair` -> `TweakedPublicKey`

- bitcoin/src/psbt/error.rs
- bitcoin/src/psbt/mod.rs
- bitcoin/src/psbt/serialize.rs
- patch 1 fix #1590 
- patch 2 addresses [this related comment](https://github.com/rust-bitcoin/rust-bitcoin/pull/1532/files#r1067812911) about associated `encode::Error` 
EDIT (by Tobin): fix #1548
I believe this closes out PSBT refactoring and makes way for PSBTv2 in the epic 😎
patch 1 uses match to check the error type in tests. If msrv were 1.42 we could use assert!(matches!(...)); one liners instead.
> Associate io, encode errors with psbt::Error

- bitcoin/src/taproot.rs
Docs created with the `sha256t_hash_newtype` macro are missing a newline between the doc heading and doc main section.
Note that the strings used span multiple lines and therefor the subsequent lines must be aligned with the start of the line (not indented).
Fix: #1540
> Add newline in rustdoc

- bitcoin/src/bip152.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/lib.rs
- bitcoin/src/sighash.rs
Currently we use a wildcard to export all the hash types in `hash_types`. We are moving to a world were we only export normal/standard types from the crate root.
Remove the reexport of the following hash types:
- `FilterHash`
- `FilterHeader`
- `TxMerkleNode`
- `WitnessCommitment`
- `WitnessMerkleNode`
- `XpubIdentifier`
Fix: #1541
> Do not export unusual hash types at crate root

- bitcoin/src/crypto/schnorr.rs
Recently, and bizarrely, a PR merged that broke `cargo test --doc`.
Add an import for `KeyPair` to the `schnorr` rustdoc example.
> Add KeyPair import to rustdoc example

- bitcoin/src/taproot.rs
The `TaprootMerkleBranch` contains a vector of `TapNodeHash`s, as such it can trivially be constructed from an array of the same type.
Implement `From` for all array sizes 1 - 128 inclusive.
Fix: #1469
>  Implement from arrays for `TaprootMerkleBranch`

- bitcoin/src/psbt/mod.rs
- bitcoin/src/sighash.rs
This changes the bound from `Deref<Target = Transaction>` to `Borrow<Transaction>` (with respective `mut` changes) and adds accessors.
Closes #1423 (PSBT stuff will be separate issue).
> Improve `SighashCache` API

- bitcoin/src/sighash.rs
"Sighash" is a technical term that newbies in Bitcoin may not know and could get lost when trying to find how to sign a transaction. This change attempts to make it more obvious that this module is needed for signing.
Closes #1463
> Improve `sighash` module documentation

- bitcoin/src/bip158.rs
Recently we merged `commit 53d4fe66b57c255086def2b5e47afaddee776b75` to fix CI even though a better approach is to use `'_` because it assists reading the code (shows that the bit stream writer is not writing from a reference since its writing a `Copy` type `n`).
Add back in the `'_` (I forget what its called).
> Add '_ back into the BitStreamWriter

- bitcoin/embedded/README.md
The embedded test crate requires usage of the nightly toolchain, fix the docs to show this.
> Instruct devs to use nightly for embedded

- bitcoin/src/psbt/serialize.rs
- bitcoin/src/taproot.rs
- bitcoin/tests/serde.rs
The `TaprootMerkleBranch` and `ControlBlock` both have methods on them called `from_slice` but these methods do more that just basic copy from a slice. `decode` is a more descriptive name.
Deprecate the `from_slice` methods and implement `decode`, on other changes to the logic.
cc sanket1729
> Rename `from_slice` methods to `decode`

- bitcoin/fuzz/fuzz_targets/deserialize_transaction.rs
- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/fee_rate.rs
- bitcoin/src/blockdata/mod.rs
- bitcoin/src/blockdata/transaction.rs
- bitcoin/src/blockdata/weight.rs
- bitcoin/src/parse.rs
Use of general-purpose integers is often error-prone and annoying. We're working towards improving it by introducing newtypes.
This adds newtypes for weight and fee rate to make fee computation easier and more readable. Note however that this dosn't change the type for individual parts of the transaction since computing the total weight is not as simple as summing them up and we want to avoid such confusion.
Part of #630
Replaces #1607 (I want to get this in quickly and don't want to be blocked on DanGould's availability.)
> Add `Weight` and `FeeRate` newtypes

- bitcoin/src/blockdata/script/builder.rs
Lock times are `u32` and can require encoding using 5 bytes. 
Add methods `push_lock_time` and `push_sequence` for pushing absolute lock times and sequence numbers. We do not push relative locktimes because they are only 16 bits from the original sequence number.
> Add methods for pushing locktimes

- bitcoin/src/blockdata/script/builder.rs
- bitcoin/src/blockdata/script/mod.rs
Patch one does the deprecation, the rest of the PR is made up of tiny improvements to the code around reading/writing 'scriptint's (conceptually `CScriptNum`s). I did all this while trying to decipher the discussion on #1547. 
There are many more changes in the pipeline for all this read/write "script int" stuff. This PR was done ages ago and I believe it stall adds value.
I re-did the whole PR manually because of the recent `script` module changes. I hope no one else has to do that - if you do please feel free to holla and I'll "rebase" your PR for you.
> Deprecate `script::read_uint`

- .github/workflows/rust.yml
- bitcoin/contrib/test.sh
- hashes/contrib/test.sh
- hashes/src/sha512_256.rs
Currently the docs build commands in `hashes` and `bitcoin` differ, they should be the same.
Add a command `cargo doc` to improve coverage e.g., recently we botched the feature guarding but since CI only runs `cargo rustdoc` with custom compiler conditional set we didn't catch it.
Done after seeing: https://github.com/rust-bitcoin/rust-bitcoin/pull/1504 and CI should fail on this PR until 1504 is in.
> Improve test coverage for docs build

- bitcoin/src/address.rs
Add an implementation of `From<Address> for ScriptBuf` that calls through to `address.script_pubkey` (which calls
`address.payload.script_pubkey()`).
Fix: #1457
> Add `From<Address>` for `ScriptBuf`

- bitcoin/src/address.rs
Currently we have an attempted tag ```compile_fail that seems to be aiming at allowing code that does not build to exist in rustdoc. This is causing an error when running tests.
No clue how this made it through CI.
Use ```ignore to prevent rustdoc code from being built.
> Use ignore to stop rustdoc code from being built

- bitcoin/src/bip158.rs
When we introduced the SPDX license blurb in [0] we incorrectly gave attribution to Andrew when the original file author had the attribution as "the rust-bitcoin developers". The original author [1] was Tamas Blummer and he copied this code from code he wrote and explicitly re-licenses it. In order to make the re-licensing comment a little clearer and fix the mis-attribution use Tamas' name in the attribution.
[0] commit: `91ff2f628ce7db732d234a812e29fa8508f501a1 Introduce SPDX license identifiers`
[1] commit: `c93a70487f81a93c7d479ae046c75590d9fb7733 Add client side block filter (BIP158) (#281)`
> Fix license on bip158 module

- hashes/Cargo.toml
- hashes/src/hash160.rs
- hashes/src/hex.rs
- hashes/src/hmac.rs
- hashes/src/lib.rs
- hashes/src/ripemd160.rs
- hashes/src/sha1.rs
- hashes/src/sha256.rs
- hashes/src/sha256d.rs
- hashes/src/sha256t.rs
- hashes/src/sha512.rs
- hashes/src/sha512_256.rs
Currently we have a few things mixed up in the feature gating of `hashes`.
Observe that:
- `io::Write` and `io::Read` is not related to allocation but rather provided by `core2`
- "std" should be able to enable "alloc".
Improve feature gating by doing:
- Enable "alloc" from "std" and simplify `cfg` codebase wide.
- Enable "internals/alloc" from "alloc".
- Fix feature gating to use the minimal requirement i.e., "alloc".
Please note one anomaly, `internals` does not set "std" as the default feature but `hashes` does.
> hashes: Improve feature gating

- bitcoin/src/blockdata/script/mod.rs
`FromStr` impls should roundtrip with `Display` imlps but currently our `ScriptBuf` displays using instructions but parses hex.
Looks like this slipped back in during a recent rebase fail by me.
> Remove FromStr impl from ScriptBuf

- bitcoin/src/lib.rs
- hashes/src/lib.rs
- internals/src/lib.rs
Closes #1551 
Signed-off-by: Harshil Jani <harshiljani2002@gmail.com>
> Move deny lint checks to script

- bitcoin/src/psbt/mod.rs
Remove an unused error variant for PSBT code (API breaking because the error type is public).
Woops, somehow I managed to get what was patch 1 of this series merged yesterday, I thought I left it out. Anyways, this is just the remove unused error variant now. No changes to that patch from previous versions of the PR.
> `psbt` cleanup

- bitcoin/src/blockdata/locktime/absolute.rs
An absolute lock time of 100 is nonsensical because we are well past block 100. This value was used because it makes sense for _relative_ locktimes but for absolute lock times it makes the examples and tests slightly confusing.
> Fix absolute lock time examples and tests

- bitcoin/src/address.rs
- bitcoin/src/network/message.rs
- bitcoin/src/psbt/serialize.rs
- hashes/src/internal_macros.rs
- hashes/src/util.rs
Implement `AsRef<[u8; X]>` for hash types including wrapped hash types. Doing so means at times the compiler can no longer infer the type because we have `AsRef<[u8]` implemented also but we can use `into_inner` and `as_inner` to get the inner array if needed.
Fix: #1462
This touches code that will likely be changed by #1577 and when we do #1491 but I believe its a step forward.
> hashes: Implement AsRef for fixed size arrays

- hashes/contrib/test.sh
Recently while trying to fix CI I (Tobin) added a call to `cargo clean` and a code comment justifying it. This was merged because while not incorrect it is redundant since calling `cargo` with different `RUSTFLAGS` triggers a rebuild.
> ci: Remove incorrect code comment and cargo clean

- rustfmt.toml
The `rustfmt` config option `required_version` causes grief in CI because everytime `rustfmt` is update our `nightly` job fails. Since we require nightly anyways to run `rustfmt` the config option is basically redundant.
> Remove the rustfmt required_version config option

- bitcoin/Cargo.toml
- bitcoin/fuzz/fuzz_targets/deserialize_script.rs
- bitcoin/src/address.rs
- bitcoin/src/blockdata/block.rs
- bitcoin/src/blockdata/constants.rs
- bitcoin/src/blockdata/script/borrowed.rs
- bitcoin/src/blockdata/script/builder.rs
- bitcoin/src/blockdata/script/instruction.rs
- bitcoin/src/blockdata/script/mod.rs
- bitcoin/src/blockdata/script/owned.rs
- bitcoin/src/blockdata/script/push_bytes.rs
- bitcoin/src/blockdata/script/tests.rs
- bitcoin/src/crypto/ecdsa.rs
- bitcoin/src/hash_types.rs
- bitcoin/src/sighash.rs
- bitcoin/tests/psbt.rs
The code previously contained undocumented panic when trying to push
slice. This is now solved by making a newtype that guarantees limited
length.
Closes #1186
Closes #1189 
This is done on top of unsized script change. I only request light review of the design for now. I'd like to improve it to use a macro for all unsized types.
> Added a newtype for script-pushable slice 

- bitcoin/src/blockdata/script/push_bytes.rs
It may not be obvious why the condition in `push_bytes` module checks for negation of 16 and 32 bit architectures rather than 64 bit. This adds a comment about it being conservative.
Addresses https://github.com/rust-bitcoin/rust-bitcoin/pull/1190#discussion_r1111342671
> Clarify the intention of strange condition

- bitcoin/examples/bip32.rs
- bitcoin/examples/ecdsa-psbt.rs
- bitcoin/src/bip32.rs
`P: AsRef<[ChildNumber]>` means that path can be borrowed as a reference to a slice of `ChildNumber`.
While it does work with `Vec`, the documentation and examples mislead the user into thinking that he/she has to use a vec, which is not true. A simple reference to a slice of `ChildNumber` also works and does not consume heap
> Changing docs and examples to use correct function signature

- bitcoin/src/blockdata/transaction.rs
To make it more clear what the cache is show the cache construction line in rustdoc.
> Show cache construction in rustdoc
